// Capture cohere's pinned prose classes as native numeric range data.
package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"strconv"
)

func main() {
	source := flag.String("source", "cohere/internal/format/markdown/classes_generated.go", "pinned Go classes")
	output := flag.String("output", "stage1/cohere/markdownblocks/textClasses.ts", "native data")
	formatter := flag.String("formatter", "/tmp/cssstrings-cohere", "cohere formatter executable")
	check := flag.Bool("check", false, "compare generated bytes")
	flag.Parse()
	raw, e := os.ReadFile(*source)
	must(e)
	tree, e := parser.ParseFile(token.NewFileSet(), *source, raw, 0)
	must(e)
	var b bytes.Buffer
	fmt.Fprintf(&b, "// Pinned cohere prose classes, source SHA256 %x.\n// Regenerate: go run ./stage1/cohere/markdownblocks/tools/generate_classes\n", sha256.Sum256(raw))
	count := 0
	ast.Inspect(tree, func(n ast.Node) bool {
		v, ok := n.(*ast.ValueSpec)
		if !ok {
			return true
		}
		if len(v.Names) != 1 || len(v.Values) != 1 {
			panic("unexpected class declaration")
		}
		name := v.Names[0].Name
		value, ok := v.Values[0].(*ast.CompositeLit)
		if !ok {
			panic("expected literal ranges")
		}
		count++
		fmt.Fprintf(&b, "export const %s: readonly number[] = [\n", name)
		for _, element := range value.Elts {
			pair := element.(*ast.CompositeLit)
			if len(pair.Elts) != 2 {
				panic("expected range pair")
			}
			for _, point := range pair.Elts {
				value, e := strconv.ParseInt(point.(*ast.BasicLit).Value, 0, 32)
				must(e)
				fmt.Fprintf(&b, "    %d,\n", value)
			}
		}
		fmt.Fprintln(&b, "];")
		return false
	})
	if count != 5 {
		panic("expected five classes")
	}
	tmp, e := os.CreateTemp("", "adamic-text-classes-*.ts")
	must(e)
	defer os.Remove(tmp.Name())
	_, e = tmp.Write(b.Bytes())
	must(e)
	must(tmp.Close())
	out, e := exec.Command(*formatter, "--no-cache", "--fix", tmp.Name()).CombinedOutput()
	if e != nil {
		panic(fmt.Sprintf("cohere: %v %s", e, out))
	}
	result, e := os.ReadFile(tmp.Name())
	must(e)
	if *check {
		actual, e := os.ReadFile(*output)
		must(e)
		if !bytes.Equal(actual, result) {
			panic("generated classes changed")
		}
	} else {
		must(os.WriteFile(*output, result, 0644))
	}
}
func must(e error) {
	if e != nil {
		panic(e)
	}
}
