import pathlib,json,subprocess,re
out=pathlib.Path('review/compiler/optional-presence-next');changes=json.loads((out/'counts-rows.json').read_text());obs={r['path']:r for r in json.loads((out/'counts-parent-observations.json').read_text())}
def values(row):return None if row is None else [int(s) for s in re.findall(r'\d+', ' | '.join(row.split(' | ')[1:]))]
def nums(row):return 'new row' if row is None else ', '.join(map(str,values(row)))
lines=['# Count row attribution','','The full table was regenerated once with `go test -buildvcs=false ./internal/oracle -run \'^TestCountsAreRecorded$\' -count=1 -parallel 4 -timeout 10m -v -args -update-counts` (outer limit 650 seconds). It passed in 283.723 seconds. The runtime table has 1,320 fixture rows; predicate-direction counts are preserved by the same writer.','','The pre-regeneration merge carried 16 added chain rows and four changed callback-search rows. Regeneration changed ten more numeric rows. For every one of those ten, a counted CLI observation on 897d0e79 reproduces the new measurement, while 50654a40 reproduces the old table. These ten are stale counts inherited from optional-presence-chain, not new merge behavior. counts-parent-observations.json and per-parent logs contain all twenty observations; no second table regeneration was performed.','','Numbers below are allocations, frees, retains, releases, peak live, and in regions. Complete parent and measured rows are in counts-rows.json.','','| Fixture | 897d0e79 recorded | Merged measured | Attribution |','| --- | --- | --- | --- |']
for r in changes:
 if r['merged']!=r['measured']:
  assert [int(s) for s in re.findall(r'\d+',obs[r['path']]['base']['counts'])]==values(r['measured'])
  assert [int(s) for s in re.findall(r'\d+',obs[r['path']]['chain']['counts'])]==values(r['merged'])
  if r['path'].startswith('docs/'):
   reason='897d0e79 already measures this retain increase. Shared copy_fields introduced by b215cedb retains reserved reference slots including NULL; heap.c counts calls before its NULL check. For method.a, generated C is identical to base.'
  else:reason='897d0e79 already measures this reduction; 50654a40 reproduces the recorded row. Inherited optional-presence copy/enumeration paths, not the eep guard or merge. Allocations equal frees.'
 elif r['base'] is None:
  commit=subprocess.check_output(['git','log','50654a40','--format=%h %s','-1','-S',r['measured'],'--','internal/oracle/counts.md'],text=True,timeout=30).strip();reason='Inherited chain fixture row: '+commit
 else:reason='Inherited chain callback-search correction f130c846 (Audit search shrink callback counts on the lowering chain); measured values equal the chain row.'
 lines.append('| '+r['path']+' | '+nums(r['base'])+' | '+nums(r['measured'])+' | '+reason+' |')
lines+=['','Observed versus inferred: parent measurements establish attribution to optional-presence-chain for all ten regeneration movements. The runtime explanation for the method retain increases follows copy_fields and heap.c. The class-private and for-in decreases are attributed to the parent copy/enumeration implementation; no isolated runtime-hunk experiment is claimed for those two.','','Order-only changes retain identical numbers. The merge moved 4ddd17f_weak_single_narrowed.a, d96d304_try_stack.a, and backend_stop_catches.a with chain registration order. The canonical writer moved optional_field_checked_view_required_string.a before its string controls, moved optional_indexing_array.a, optional_indexing_string.a and optional_indexing_string_gap.a after the optional-field block, and placed taste_optional_join.a after stage3/fixtures/taste/17_binder_flow.a. These follow fixture init/registration ordering after the merges. No measured row was discarded to preserve a parent table.','']
(out/'counts-attribution.md').write_text('\n'.join(lines));print('Attributed',len(changes),'added/changed numeric rows and order-only movements')
