from pathlib import Path
import json,subprocess,shlex,shutil,difflib
p=Path('/tmp/defend-scanner/evidence');runs=json.loads((p/'defense-runs.json').read_text());plan=json.loads((p/'defense-plan.json').read_text());base='76c59c81e8617cea1892a01841494895927a712c';pkg='stage1/typescript/scanner';rows=[]
for name,prior,ids in [('TestGapStandsWhereGapsMdSays','TestBigintGapStandsWhereGapsMdSays',['D1']),('TestBigintGapStandsWhereGapsMdSays','TestGapStandsWhereGapsMdSays',['D2']),('TestProfileSnapshotsAgree','TestScannerAgreesWithTypescriptGo family',['D3','D4','D5'])]:
 attempts=[];win=None
 for id in ids:
  x=next(x for x in plan if x['id']==id);r=next(r for r in runs if r['id']==id);attempts.append(dict(mutant=id,file_line=x['file']+':'+str(x['line']),change=(x['old']+' -> '+(x['new'] or '[statement dropped]')),rows_failed=r['failed']))
  if r['unique_target']:win=(x,r)
 r=win[1] if win else next(r for r in runs if r['id']=='D4');env=' '.join(k+'='+shlex.quote(v) for k,v in r['environment'].items() if k!='ADAMIC_TOOLS');command=env+' '+shlex.join(r['command'])+' > '+r['id']+'.log 2>&1';line=next((s for s in r['failing_lines'] if ('gaps_test.go' in s if win else 'profile_test.go' in s)),None)
 row=dict(test=name,package=pkg,prior_verdict='subsumed',subsumed_by=[prior],defense='defended' if win else 'not defended',unique_mutant=win[0]['id']+' '+win[0]['file']+':'+str(win[0]['line']) if win else None,attempts=attempts,evidence=command+'; '+str(line))
 if win:row['rows_passed']=sorted(win[1]['passed'])
 if name== 'TestProfileSnapshotsAgree':row['name_assertion_finding']='No mismatch: the row asserts complete answer bytes against TypeScript-Go for release, profiled and Node runs. It does not compare the counted artifact.'
 rows.append(row)
(p/'rows.json').write_text(json.dumps(rows,indent=2));(p/'matrix.json').write_text(json.dumps([dict(mutant=r['id'],rows_failed=r['failed'],rows_passed=r['passed'],unique_target=r['unique_target']) for r in runs],indent=2));summary=['Defender scanner unit at origin/main '+base+': all 29 audit tests still exist, no new top-level tests.','Two gap rows defended by package-unique D1/D2; profile row not defended after three valid attempts.','Evidence: test-defend/stage1-typescript-scanner under review/test-defend/stage1-typescript-scanner/.'];text='\n'.join(summary)+'\n\n```json\n'+json.dumps(rows,indent=2)+'\n```\n\n'
text+='CODE UNDER TEST AND ORACLES\n\nPush gap: Adamic lowering of a two-argument array push. Node runs the unchanged fixture and supplies ab; the exact NotYet category/What diagnostic is a self-written expectation. Bigint gap: Adamic lowering of a bigint literal representation. Node supplies the unchanged bigint result; NotYet and its exact What are self-written. Profile snapshots: the port executed in native release and separately compiled profiling products, plus Node, including Adamic native allocator/runtime and compiler options; pinned TypeScript-Go supplies the complete expected protocol. No oracle, test, harness, dispatch, corpus or copied-file list was mutated.\n\n'
text+='Coverage\n\nPer-row go test -coverprofile runs use -coverpkg=github.com/system-inc/adamic/internal/lower for both gap rows and -coverpkg=github.com/system-inc/adamic/internal/native for snapshots and all sixteen agreement members. Exact commands and passes are in coverage-runs.json. Push has 489 exclusive covered blocks versus bigint; bigint has 13 versus push. These are blocks, not an invented statement-line count. push-exclusive.txt and bigint-exclusive.txt give source ranges, including object.go:1266 and expression.go:40 respectively.\n\n'
text+='Snapshots has no exclusive Go covered block versus the agreement family (one package-initialization block versus 1154 covered blocks). Go coverage cannot instrument already built C/Node subprocesses, so that comparison does not establish that the semantic executions are redundant. The visible build recipes establish a real difference: agreement uses sanitized native products while snapshots also executes release/profiling products. heap.c sets SLABS=0 under ASan by default and SLABS=1 in release; take is bypassed in the sanitized allocation path. D3/D4 target that release-only behavior, and D5 changes only the non-sanitized branch of native.Flags. Count-only TestPerformance also uses a release product, which explains its observed catches of both allocator corruptions.\n\n'
text+='| Mutant | Origin file:line | Intent | Failed tests |\n|---|---|---|---|\n'
for x in plan:
 r=next(r for r in runs if r['id']==x['id']);text+='| '+x['id']+' | '+x['file']+':'+str(x['line'])+' | '+x['reason']+' | '+(', '.join(r['failed']) or 'none')+' |\n'
text+='\nD1 and D2 each have exactly one observed failing top-level test. All other 28 passed; their exact names are in rows.json and defense-runs.json, including all sixteen agreement members, all seven product wrappers, coverage, performance, profile construction/snapshots and the other gap row. Every valid matrix ran all 29 tests with all profile/benchmark opt-ins enabled and fresh mutant cache/profile paths. No skips, cooking or unobserved cells occurred. Runtime crashes happened in child binaries and did not abort the Go test process.\n\n'
text+='D3 drops the entire free-list advance assignment, causing reuse of the allocated slot. D4 advances fresh slots one byte less than their size. Both produce segmentation faults caught by snapshots and performance. D5 adds -funsafe-math-optimizations only to release options; all 29 tests pass it. A separate unchanged-source rounding program with runtime input 1e20 prints 0 in normal native and Node, but 1 with D5. Its source, exact CLI build/run commands, and outputs are saved as D5-witness-*; this is a witnessed survivor, not a defense of snapshots. The three valid profile attempts are D3/D4/D5.\n\n'
text+='Instruction ambiguities and costs\n\nThe audit report was split across REPORT.md, rows.json, REPLAY.md and inventory.md; all were read before test/source inspection. Copies are retained under audit-source. Its starting commit was cf735d9f; this defense starts at fetched main 76c59c81. All 29 names match, so there were no added tests to omit from the matrix. Families affect row uniqueness; here D1/D2 each fail a single top-level test even before grouping, so the uniqueness result does not depend on that grouping.\n\n'
text+='Go coverage profiles are required, but they do not cover native C or Node. I report that limitation and use the actual release-versus-sanitized execution difference rather than pretending zero Go coverage proves the port was untouched. This is the main coverage limitation; no exclusive native C line count is claimed.\n\n'
text+='The repository corpus collector refuses dirty tracked inputs. Runtime C mutants were committed as temporary variants and followed by restoration commits, so the collector stayed intact. There was no history rewrite. I paused the first runner before the runtime attempts to add this requirement. Every final diff applies independently to the starting origin/main, and the final source tree matches it. Artifacts were freshly rebuilt per mutant; original baseline snapshots were not reused to judge a mutated compiler.\n\n'
text+='The first D5 candidate used -ffast-math. Go vet passed, but actual native runtime compilation failed under -Werror,-Wnan-infinity-disabled. Those failures are invalid and not kills. The rejected candidate and log are labeled D5-fastmath-invalid; invalid-runs.json records it separately. The corrected D5 keeps NaN/Infinity support and successfully builds every product. Both forms change production compiler options, not the clang harness or warning policy.\n\n'
text+='The standalone rounding witness initially passed a number to console.log, which Adamic types reject. Its final unchanged source interpolates a string, then builds successfully in both compiler variants. This witness does not run another package test or change a test oracle. Its Node comparison is a direct external execution.\n\n'
text+='The bias-to-keep requirement and not-defended verdict are compatible: not defended means these three targeted mutations establish no unique catch, not that the row is useless or may be deleted. No test was deleted, rewritten or weakened. For the undefended row, the name promises snapshots agreeing and the assertion checks complete answer bytes against TypeScript-Go. There is no missing threshold promised by that name. The counted binary is built by Artifacts but omitted from snapshots comparison. The two defended gap names mention where a gap stands, but their assertions check the fixture result and diagnostic What/category rather than asserting diagnostic Where or reading GAPS.md.\n\n'
text+='Warm tools were used, with no setup script; npm ci ran in stage3/api. The baseline took 39.026 binary seconds. Coverage commands took '+str(round(sum(x['seconds'] for x in json.loads((p/'coverage-runs.json').read_text())),3))+' wall seconds. Valid matrix commands including validation took '+str(round(sum(x['seconds'] for x in runs),3))+' wall seconds; per-run durations are in defense-runs.json. No binary run exceeded 90 seconds; the longest valid mutant binary was 40.335 seconds. nproc=5. Total session approximately 16 minutes. Other package tests and repository-wide uniqueness were not covered.\n'
(p/'REPORT.md').write_text(text)
for f in ['coverage.py','mutate.py','survivor.py','report.py']:shutil.copy('/tmp/defend-scanner/'+f,p/f)
a=p/'audit-source';a.mkdir(exist_ok=True)
for name in ['REPORT.md','rows.json','REPLAY.md','inventory.md','function-inventory.txt']:(a/name).write_bytes(subprocess.check_output(['git','show','origin/test-audit/stage1-typescript-scanner:review/test-audit/stage1-typescript-scanner/'+name]))
print([(r['test'],r['defense']) for r in rows])
