import pathlib,json,gzip,shutil,subprocess,shlex
p=pathlib.Path('/tmp/defend-mdast');start=subprocess.check_output(['git','rev-parse','origin/main'],text=True).strip();d=pathlib.Path('review/test-defend/stage1-cohere-markdownblocks-mdast_errors/session-'+start[:8]);d.mkdir(parents=True,exist_ok=True)
plan=json.loads(p.joinpath('plan.json').read_text());matrix={};attempts={}
for m in plan:
 mid=m['id'];suffix='-expanded' if mid in ['D1','D4'] else '';es=[json.loads(s) for s in p.joinpath(mid+suffix+'.log').read_text().splitlines() if s.startswith('{')];run=json.loads(p.joinpath(mid+suffix+'-run.json').read_text());rows=sorted(set(e['Test'] for e in es if e.get('Action')=='run' and e.get('Test') and '/' not in e['Test']));failed=sorted(e['Test'] for e in es if e.get('Action')=='fail' and e.get('Test') and '/' not in e['Test']);passed=sorted(e['Test'] for e in es if e.get('Action')=='pass' and e.get('Test') and '/' not in e['Test']);unknown=sorted(set(rows)-set(failed)-set(passed));assert not unknown,(mid,unknown)
 outputs={r:[e['Output'].strip() for e in es if e.get('Test')==r and e.get('OutputType') in ['error','error-continue']] for r in failed};seconds=next(e['Elapsed'] for e in es if not e.get('Test') and e.get('Action')=='fail')
 command='ADAMIC_BUILD_CACHE_DIR='+run['cache']+' '+shlex.join(run['command'])+' > '+mid+suffix+'.log 2>&1'
 matrix[mid]=dict(command=command,rows=rows,rows_failed=failed,rows_passed=passed,unknown=unknown,failure_output=outputs,binary_seconds=seconds,wall_seconds=run['wall'],cache=run['cache'])
 attempts[mid]=dict(mutant=mid,file_line=m['file']+':'+str(m['line']),change=m['before']+' -> '+m['after'],rows_failed=failed)
reports=[]
for target,ids,prior,defense,proof in [('TestMdastIdentifierWitnesses',['D2','D3','D4'],'TestNativeMdastConstruction','not defended','D4'),('TestNativeMdastConstruction',['D1'],'TestMdastIdentifierWitnesses','defended','D1')]:
 evidence=matrix[proof]['command']+'; '+' '.join(matrix[proof]['failure_output'][target])
 reports.append(dict(test=target,package='stage1/cohere/markdownblocks',prior_verdict='subsumed',subsumed_by=[prior],defense=defense,unique_mutant=attempts['D1']['file_line']+' (D1)' if defense=='defended' else None,attempts=[attempts[mid] for mid in ids],evidence=evidence,bounded=True,matrix_rows=matrix[proof]['rows'],rows_passed=matrix[proof]['rows_passed'] if defense=='defended' else [],code_under_test='Native/source/backend execution of the TypeScript mdast construction port: MdastCompiler, MdastArena.attachFrontMatter and the identifier normalization tables.',oracle='Actual Go cohere mdast and pinned Node fork. Identifier also checks retained Go/fork snapshot bytes and verifies their disagreement; all port executors must match Go. The Node execution of the port is another product executor, not the expected-answer oracle.'))
(d/'rows.json').write_text(json.dumps(reports,indent=2));(d/'matrix.json').write_text(json.dumps(matrix,indent=2));(d/'plan.json').write_text(json.dumps(plan,indent=2));(d/'scope.json').write_text(json.dumps(matrix['D1']['rows'],indent=2));(d/'origin.txt').write_text(start+'\n')
for f in p.iterdir():
 if not f.is_file():continue
 if f.suffix=='.log':
  with f.open('rb') as src,gzip.open(d/(f.name+'.gz'),'wb') as dst:shutil.copyfileobj(src,dst)
 elif f.suffix in ['.diff','.cover','.py'] or f.name in ['scope-changes.json','go-exclusive-coverage.json','port-line-coverage.json','port-transforms.json','port-executed-sources.json','port-sources.json'] or f.name.endswith('-run.json') or f.name.endswith('-port-v8.json.gz'):shutil.copy2(f,d/f.name)
for f in ['REPORT.md','rows.json','mutants.md']:
 text=subprocess.check_output(['git','show','origin/test-audit/stage1-cohere-markdownblocks-mdast_errors:review/test-audit/stage1-cohere-markdownblocks-mdast_errors/'+f],text=True);(d/('audit-'+f)).write_text(text)
(d/'validation.json').write_text(json.dumps(dict(origin=start,standalone_apply_check=['D1','D2','D3','D4'],native_compilation='All four variants compiled and executed under the existing native sanitized build flags; observed failures are output differences, not build errors.',restoration='All production source changes reversed before evidence commit.'),indent=2))
(d/'REPORT.md').write_text('''TestNativeMdastConstruction is defended by D1: it alone catches a wrong front-matter end column.
TestMdastIdentifierWitnesses is not uniquely defended after three aimed attempts; its two original-only casing catches are now shared with the exhaustive scalar neighbor.
All four variants completed the same bounded fifteen-function current-consumer matrix with no skips or unknown results. Evidence preserves every pass and failure.

Starting origin/main: '''+start+'''. Audit start: ce1c5a2fd91e40b05160e587ea5d88ed5bdfedb2. Both target names remain in their original files. Comparing the audit commit's static declarations with the current go test -list found no added or removed names. The scalar row already existed outside the audit slice. The audit's mutual subsumption was based only on its broad root-node M1.

Code under test and oracle: the production TypeScript mdast port, including MdastCompiler, MdastArena, token serialization, identifier normalization and front-matter attachment. Actual Go cohere supplies full expected canonical trees and event transport. The pinned Node fork independently agrees for construction inputs; the identifier witnesses retain a known Go/fork disagreement and snapshots. Native, source Node and generated JavaScript must all hold Go's answer. Neither target is a Node/Native twin: each executes all three products over its own distinct corpus and has different additional assertions. No expected-answer oracle, harness, test or fixture was mutated.

Clean baseline: whole package timed out at 90.042 binary seconds without observed individual assertion failures. The ten mdast compiler consumers then passed in 35.547 seconds. Adding the identifier scalar consumer and its products produced a fifteen-function clean baseline in 32.188 seconds. These consumer sets were found by tracing imports: mdastCompile.ts is used only by testdata/mdast_probe.ts; identifier.ts also feeds testdata/identifier_probe.ts. The frontmatter probe uses a different implementation, frontmatter.ts, not parseFrontMatter.ts. Full package and repository-wide uniqueness remain unknown. Every final matrix includes every current top-level declaration reaching either probe, including compile-only product rows and malformed-event shards.

Coverage: isolated -count=1 profiles use -coverpkg=./internal/lower,./internal/native and the two exact test names. Identifier has no exclusive covered Go block; construction has native.go:106.2,106.29, a release-build path. Those profiles measure Go compilation/build work, not the TypeScript runtime. Separate NODE_V8_COVERAGE runs record the port's source execution. In MdastArena.attachFrontMatter, the positive front-matter body has count27 in construction and count0 in the identifier witnesses. Source input inspection confirms all three witness documents lack front matter. This semantic difference leads to D1 at origin mdastArena.ts:28. The raw filtered V8 profiles, transformed sources, source maps, matching scripts and mapped projections are saved. The projection reports V8 block counts; it is not exact C statement coverage and is not used as uniqueness evidence. Mapping required aligning the exact no-source-map transform with the mapped transform, which preserves comments.

D1 changes front-matter end column from last-line length+1 to length+2. Construction fails at mdast_test.go:128 on generated/block/--- a: b --- at byte216: end position 3,5,12 instead of 3,4,12. All fourteen other selected functions pass, including the identifier witnesses and scalar row. The complete list is matrix.json D1.rows_passed.

D2 changes U+0130's normalization table value 105 to304. Identifier witnesses fail at byte813; exhaustive scalar normalization fails at byte1130; construction and all other selected functions pass. This demonstrates a difference from the old subsumer, but not package uniqueness.

D3 changes uppercase Sigma's table value 963 to962, final sigma. Identifier witnesses fail at byte1387; scalar normalization fails at byte3645; construction and all other selected functions pass. The multi-character final-sigma case remains meaningful, but this particular break is also exposed by a single-scalar test.

D4 changes default shortcut-reference classification to collapsed. Identifier witnesses fail at byte459. Construction also fails on generated/leaves/edge references. The scalar row and other selected functions pass. This is an integration fault beyond normalization alone.

No single other row catches all three identifier attempts: the scalar row catches D2/D3 and passes D4; construction catches D4 and passes D2/D3. The enlarged evidence supports overlap, not the original one-row subsumption hint. This does not prove a unique identifier kill, and it does not recommend deletion.

Name findings: TestMdastIdentifierWitnesses actually checks three retained casing disagreements, snapshots and native/source/backend Go-held trees. Its name and comment accurately describe those assertions. TestNativeMdastConstruction checks full native trees, including coordinates, and is independently defended. Its throughput logging is not a performance threshold, and its name does not promise one.

Validation and restoration: each standalone diff applies to the starting origin/main. Every variant was lowered, compiled natively under the existing clang flags and executed; none was counted on a build failure. Every variant uses a distinct ADAMIC_BUILD_CACHE_DIR. D1/D4 were first run over ten direct mdast consumers and then rerun over the common fifteen-function set to resolve comparison against the scalar row; both cache directories are distinct and both logs are retained. Production files are restored byte-for-byte. No test was deleted, rewritten or weakened. No main push or PR.

Friction and limits: Go coverage cannot profile TypeScript port statements, so Go profiles were supplemented with filtered source-Node V8 observations. Source-map transforms preserve comments that the actual runner removes; direct offset mapping was rejected and alignment corrected before reporting. V8's reported blocks can overestimate individual line execution, so the mapped line projections remain supplemental. An initial large audit read was truncated and was followed by focused narrative and row reads. The whole-package timeout required a caller-bounded baseline and matrix. The generic brief does not prescribe a common matrix when mutants reach different entries; the final common fifteen-function set removes that ambiguity. The scalar neighbor was absent from the old audit slice, despite already existing in the package. The old one-mutant subsumption hint therefore needed broader attempts. Native clang rebuild times are not separately instrumented by these tests; binary/command times include rebuilding and execution. Neither source Node product comparisons nor existing built-in mutant subcases were treated as expected-answer oracles to mutate.

Warm toolchain setup reused env.sh, setup.sh not run; nproc5. npm ci reran before baseline, with its log retained; npm and fetch were not separately timed. Coverage binaries took 5.416 and31.571 seconds. Final D1-D4 matrix binary seconds are '''+str([matrix[mid]['binary_seconds'] for mid in ['D1','D2','D3','D4']])+'''; exact commands, wall times and initial narrower runs are retained. No final matrix approached the90-second limit. Not covered: nonconsumer package tests after the cooked baseline, repository-wide replay, compiler-specific mutant defenses, all possible Unicode histories or Markdown corpora, and exact native C coverage.
''')
print('evidence',d);print('final seconds',[matrix[mid]['binary_seconds'] for mid in ['D1','D2','D3','D4']])
