"""Render the stock-checker location ledger; no textual source matching."""
from collections import Counter
import json
from pathlib import Path

HERE = Path(__file__).resolve().parent
c = json.loads((HERE / 'census.json').read_text())
lines = ['# TypeScript 6.0.3 NodeArray ledger', '',
         'Generated by `python3 report.py` from `census.json`. Counts are source sites, not runtime allocations. Locations are one-based and refer to pristine upstream commit `050880ce59e30b356b686bd3144efe24f875ebc8`. Full expressions, spans, receiver types and resolved declarations are in the JSON ledger.', '']

def cell(value):
    return str(value).replace('|', '\\|').replace('\r', '').replace('\n', ' ')

def table(title, headers, rows):
    lines.extend(['## ' + title, '', '| ' + ' | '.join(headers) + ' |', '| ' + ' | '.join(['---'] * len(headers)) + ' |'])
    lines.extend('| ' + ' | '.join(cell(x) for x in row) + ' |' for row in rows)
    lines.append('')

def loc(row):
    return row['file'] + ':' + str(row['line']) + ':' + str(row['column'])

def decl(row):
    return ', '.join(loc(d) for d in row.get('declarations', [])) or '(no declaration in base layout)'

table('Declared layouts', ['Interface', 'Field', 'Type', 'Optional', 'Declaration'],
      [(l['name'], f['name'], f['type'], f['optional'], decl(f)) for l in c['layouts'] for f in l['fields']])
fields = sorted(c['summary']['access_fields'])
table('Direct metadata accesses by field', ['Field', 'Reads', 'Writes', 'Total'],
      [(f, sum(a['field'] == f and a['mode'] == 'read' for a in c['accesses']), sum(a['field'] == f and a['mode'] == 'write' for a in c['accesses']), c['summary']['access_fields'][f]) for f in fields])
files = sorted({r['file'] for key in ['accesses', 'creations', 'other_returning_calls', 'range_calls', 'reflection'] for r in c[key]})
table('Counts by file', ['File', 'Metadata reads', 'Metadata writes', 'Creation/range/slice sites', 'Range calls', 'Other returning calls', 'Reflection'],
      [(f, sum(a['file'] == f and a['mode'] == 'read' for a in c['accesses']), sum(a['file'] == f and a['mode'] == 'write' for a in c['accesses']), sum(a['file'] == f for a in c['creations']), sum(a['file'] == f for a in c['range_calls']), sum(a['file'] == f for a in c['other_returning_calls']), sum(a['file'] == f for a in c['reflection'])) for f in files])
table('Creation forms', ['Form', 'Sites'], c['summary']['creation_forms'].items())
lines.extend(['The three assertion promotions include the two real array promotions in the factory and the debug prototype created by `Object.create(Array.prototype)`. That prototype is not an actual array. A slice result is an ordinary array until a factory initializes it. Factory calls can reuse existing arrays. Nested categories overlap and must not be added to obtain allocations.', ''])
table('Every direct metadata read/write', ['Location', 'Field', 'Mode', 'Expression', 'Resolved declaration', 'Written value type'],
      [(loc(a), a['field'], a['mode'], '`' + a['expression'] + '`', decl(a), a.get('value_type', '')) for a in c['accesses']])
table('Presence queries and descriptor writes', ['Location', 'Field', 'Mode', 'Receiver'],
      [(loc(a), a['field'], a['mode'], a['receiver']) for a in c['reflection']])
table('Shared TextRange helper accesses', ['Location', 'Function', 'Field', 'Mode', 'Expression', 'Resolved declaration'],
      [(loc(a), a['function'], a['field'], a['mode'], a['expression'], decl(a)) for a in c['range_helpers']])
lines.extend(['These four helper accesses are typed `TextRange`, so they are separate from the 97 direct NodeArray accesses. Their 56 array-target call sites contain 46 array providers. Each provider reads pos/end through `setTextRange`; each target writes the range through the selected helper. This is a call-site ledger, not another allocation count.', ''])
table('Every range call with an array argument', ['Location', 'Resolved helper', 'Array arguments and roles'],
      [(loc(a), a['callee'], '; '.join(str(x['argument']) + ': ' + x['role'] + ' (' + x['type'] + ')' for x in a['arrays'])) for a in c['range_calls']])
table('Every creation/range/slice site', ['Location', 'Form', 'Expression'],
      [(loc(a), a['category'], '`' + a['expression'] + '`') for a in c['creations']])
table('Other NodeArray-returning calls', ['Location', 'Callee', 'Result type'],
      [(loc(a), a.get('callee', ''), a['result_type']) for a in c['other_returning_calls']])
lines.extend(['These 593 calls can return, update or forward an existing array. They are included to expose indirect creation paths without claiming they all allocate.', ''])
table('Computed accesses', ['Location', 'Mode', 'Key type', 'Expression'],
      [(loc(a), a['mode'], a['key_type'], a['expression']) for a in c['dynamic_accesses']])
lines.extend(['All 82 computed accesses have numeric keys. They are element reads/writes, not unresolved named metadata accesses.', ''])
(HERE / 'LEDGER.md').write_text('\n'.join(lines))
