import pathlib,json,re,statistics
p=pathlib.Path('review/test-audit/stage1-cohere-lint-registry'); menu=json.loads((p/'menu.json').read_text()); commands=json.loads((p/'commands.json').read_text()); ids=[x['id'] for x in menu if x['id'].startswith('M')]
def events(name):return [json.loads(x) for x in (p/(name+'.log')).read_text().splitlines() if x.startswith('{')]
kills={mid:[x['Test'] for x in events(mid) if x['Action']=='fail' and 'Test'in x and '/'not in x['Test']] for mid in ids+['P1','P2']}
rows=['TestDeterministicRegeneration','TestDescriptorRejections','TestDuplicateOracleAdapter','TestAdamicRuleModule']; oracles=['Generated bytes compared with Render from the same implementation, plus unchanged file modification times. Empty Render passes; M8 and M9 also pass, exposing shared-output defects.','Handwritten error substrings for ten malformed descriptor subcases. Requires an error and matching text; does not compare a complete diagnostic or execute upstream cohere.','Handwritten duplicate oracle adapter error substring. The oracle.go fixture is parsed as registry input; its rule behavior is not executed.','Handwritten .a import substring and ambiguous-module error substring. Checks registration and rejection, not execution of the rendered dispatch.']; result=[]
for row,oracle,line in zip(rows,oracles,[39,77,124,150]):
 times=[]
 for i in range(1,4):
  out=''.join(x.get('Output','') for x in events(row+'-'+str(i))); times.append(float(re.search(r'\bok\s+\S+\s+(\d+\.\d+)s',out).group(1)))
 caught=[mid for mid in ids if row in kills[mid]]; last=caught[-1]; failures=[x.get('Output','').strip() for x in events(last) if x.get('Test','').split('/')[0]==row and 'registry_test.go:'in x.get('Output','') and 'mutant rejected:'not in x['Output']]; failing=failures[0]; command=next(x['command'] for x in commands if x['id']==last)
 item=dict(test=row,package='stage1/cohere/lint/registry',file='stage1/cohere/lint/registry/registry_test.go:'+str(line),seconds=statistics.median(times),oracle=oracle,oracle_kind='self',kills=caught,unique_kills=[mid for mid in caught if len(kills[mid])==1],last_proven_fail=last+' '+failing,verdict='sacred',subsumed_by=[],mutants_in_matrix=12,probe_kills=[mid for mid in ['P1','P2'] if row in kills[mid]],subsumer_seconds=None,vacuous=False,bounded=False,matrix_rows=rows,evidence=command+' > '+str(p/(last+'.log'))+' 2>&1; '+failing,timing_samples=times)
 if row in [rows[0],rows[3]]:item['entry_probe_results']={'Generate':'fail','Render':'fail' if row in kills['P2'] else 'pass'}
 if row==rows[0]:item['vacuous_subcases']=['Entire direct Render byte comparison passes empty Render; Generate entry probe still fails.']
 result.append(item)
(p/'rows.json').write_text(json.dumps(result,indent=2)); (p/'matrix.json').write_text(json.dumps(kills,indent=2))
table='| ID | Origin registry.go line | Change | Failing rows |\n|---|---:|---|---|\n'
for m in menu:
 change=m['menu'] if m['id'].startswith('P') else m['old']+' => '+m['new']
 table+='| '+m['id']+' | '+str(m['line'])+' | `'+change.replace('|','\\|')+'` | '+', '.join(kills[m['id']])+' |\n'
(p/'mutants.md').write_text(table)
wall=sum(x['wall'] for x in commands); vet=sum(x['seconds'] for x in json.loads((p/'validation.json').read_text()))
report='''Unit u119: all four current top-level tests audited, no families or skips.
Base ce1c5a2fd91e40b05160e587ea5d88ed5bdfedb2, nproc 5, warm toolchain, setup skipped.
Clean baseline passed: own binary 0.580s, shell build-and-run 1.074s.
Twelve production mutants: nine caught, two changed-output survivors, one equivalent candidate.
Four sacred rows within this package; repo-wide uniqueness awaits central replay.

'''+json.dumps(result,indent=2)+'\n\n'+table+'''
Survivors:
M8: clean first rule no-debugger/order1; mutant first rule adamic/no-type-predicate/order0. See witness-M8.diff and complete ordering logs.
M9: clean this.rule0.visit(index, parent); mutant this.rule0.visit(index, index). See witness-M9.diff.
M12: equivalent candidate. Clean and mutant Witnesses output identical; filepath.WalkDir already visits lexically. No unguarded-behavior claim.
Witness command: ADAMIC_MUTANT=<clean|M8|M9|M12> go run /tmp/u119/witness.go, stdout/stderr saved witness-<id>.log. Driver retained witness.go.txt.

Brief ambiguities and time costs:
- Package lives under stage1/cohere but tests reach the Go registry generator, not a native port. Thus mutation of registry.go is mutation of the code under test; mutating rule.ts or upstream oracle.go would audit a different component. No native rebuild is applicable.
- Names such as DescriptorRejections and DuplicateOracleAdapter contain built-in malformed inputs, but these directly test production validation. They do not witness a separate agreement comparison. Classified as ordinary validator tests, not harness witnesses.
- The generic admonition not to edit a dispatch or registry applies to adding lint rules. User-authorized scratch mutations of the generator were restored and only audit evidence is committed.
- Scope came from current go test -list: four functions, no wrappers/families, no missing or skipped tests. No row list was supplied for this whole-package unit.
- One boolean vacuous field cannot describe two entries. All Generate probes fail, hence overall false; entry_probe_results records the direct Render pass for DeterministicRegeneration and failure for AdamicRuleModule. Negative descriptor rows do not directly call Render on successful inputs, so their passing P2 runs do not imply vacuity.
- DeterministicRegeneration uses the implementation as its expected byte oracle. M8 and M9 survival and P2 passing are measured weaknesses; modification-time check still uniquely catches M11. Sacred here does not imply that every behavior is guarded.
- Rejection diagnostics use substrings, not full text. This audit proves only the named rejection checks; a different error carrying the same substring could satisfy them.
- A literal unconditional probe return leaves unreachable code flagged by go vet. Final switch-free P1/P2 diffs replace the whole body, retain their empty-entry behavior, and pass vet. Original failed probe-vet logs were replaced by the successful repeated validation; validation-output.log and validation.json are authoritative.
- Witness sorting removal is not labeled unguarded solely because tests pass: observed identical output and WalkDir lexical traversal support only an equivalent candidate.
- Twelve mutations were selected before observing failures, spread across module selection, descriptor parsing/validation, ordering, rendering, witness enumeration and file writing. Other validation gates, filesystem-error paths, rendered runtime semantics and concurrent atomic-generation stress remain unsampled.
- No external authority was claimed or checked: expectations are self-written. npm ci in stage3/api was required by the brief though this package does not load node_modules. No other Node dependency directory is reached.
- Package finished far below 90s; no narrowing, panic reruns, or bounded uniqueness claims were needed. Every production diff and both probes apply to the starting commit and pass go vet. The switch and logs are evidence only; production source restored.

Timing:
Setup 0s (warm env); npm installation was not timed separately. Baseline build/run shell 1.074s; binary 0.580s.
'''+f'Three isolated runs per row plus fourteen matrix/probe runs: {wall:.3f}s combined shell build/run wall, individual commands and walls in commands.json. Standalone go vet rebuild/check total {vet:.3f}s, each in validation.json. No native rebuilds.\n'+'''Audit start was about 12:31 UTC; evidence prepared within the 20-minute budget. Four isolated medians and samples appear in rows.json. No other Adamic packages run. No PR or main push.
'''
(p/'REPORT.md').write_text(report); print(json.dumps(result,indent=2)); print(table)
