const fs=require('fs'),path=require('path'),ts=require('/tmp/lane5-c-original/lib/typescript.js');
const home=path.resolve(__dirname,'../..'),members=require('../../original-members.json').members,c=require('/tmp/lane5-c-carrier-declarations.json');
const ranks=[386,1130,1283,1301,1424,2060,2456,2555,2564,2618],rows=[];
const parse=s=>ts.createSourceFile('declaration.a',s,ts.ScriptTarget.Latest,true);
for(const rank of ranks){const m=members.find(x=>x.rank===rank),defs=new Map();
function visit(t){if(ts.isTypeReferenceNode(t)){const n=t.typeName.getText(),d=c[n];if(!d)throw Error('unknown carrier '+n);if(!defs.has(n)){if(d.kind==='TypeAliasDeclaration'){const a=parse(d.text).statements[0];if(a.typeParameters?.length)throw Error('generic alias '+n);defs.set(n,d.text);visit(a.type);}else if(d.kind==='EnumDeclaration')defs.set(n,'const enum '+n+' {'+Object.entries(d.values).map(([n,v])=>n+'='+v).join(',')+'}');else if(d.kind==='InterfaceDeclaration')defs.set(n,'interface '+n+' {readonly value:number;'+(d.kindValue===undefined?'':'readonly kind:'+d.kindValue+';')+'}');else throw Error('carrier '+n);}return;}ts.forEachChild(t,n=>{if(ts.isTypeNode(n))visit(n);});}
function concrete(t){if(ts.isParenthesizedTypeNode(t))return concrete(t.type);if(ts.isUnionTypeNode(t))return concrete(t.types.find(x=>x.kind!==ts.SyntaxKind.UndefinedKeyword));if(ts.isTypeReferenceNode(t)&&c[t.typeName.getText()]?.kind==='TypeAliasDeclaration')return concrete(parse(c[t.typeName.getText()].text).statements[0].type);return t.getText();}
function value(t){if(ts.isParenthesizedTypeNode(t))return value(t.type);if(ts.isUnionTypeNode(t))return value(t.types.find(x=>x.kind!==ts.SyntaxKind.UndefinedKeyword));if(ts.isTypeReferenceNode(t)){const d=c[t.typeName.getText()];if(d.kind==='TypeAliasDeclaration')return value(parse(d.text).statements[0].type);if(d.kind==='EnumDeclaration')return t.typeName.getText()+'.'+Object.keys(d.values)[0];return '{value:1'+(d.kindValue===undefined?'':',kind:'+d.kindValue)+'}';}throw Error('value '+t.getText());}
try{const element=parse('type Element='+m.type+';').statements[0].type.elementType;visit(element);const good=value(element),bad='"bad"';const parts=m.read.replace(/!/g,'').split('.');parts.pop();let owner='(value as Target).items';for(let i=parts.length-1;i>0;i--)owner='{'+parts[i]+':'+owner+'}';const prefix='// Original Array.pop receiver and declaration; adjacent payload carriers reduced.\n'+[...defs.values()].join('\n')+'\ninterface OriginalMember<T> {'+m.declarations[0].text+'}\ninterface Base {readonly items:unknown;}\ninterface Target {readonly items:'+m.type+';}\nfunction probe(value:Base):void {const '+parts[0]+'='+owner+';'+m.read+'();console.log("completed");}\n';const dir=path.join(home,'families','rank-'+rank);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'good.a'),(prefix+'const seed:'+concrete(element)+'='+good+';probe({items:[seed]});\n').replace(/\r\n/g,'\n'));fs.writeFileSync(path.join(dir,'wrong-element.a'),(prefix+'probe({items:['+bad+']});\n').replace(/\r\n/g,'\n'));rows.push({rank,reads:m.reads,type:m.type,read:m.read,declaration:m.declarations[0].text,diagnostic:'UNPINNED'});}catch(err){console.log(rank+': '+err.message);}}
fs.writeFileSync(path.join(__dirname,'pop-candidates.json'),JSON.stringify(rows,null,2)+'\n');console.log('Prepared '+rows.length+' original pop families.');
