// Generated by adamic from functions.a. Do not edit.

#include "adamic.h"

#include <math.h>
#include <stdbool.h>

static adamic_string adamic_string_0 = ADAMIC_STRING("");
static adamic_string adamic_string_1 = ADAMIC_STRING("hi ");
static adamic_string adamic_string_2 = ADAMIC_STRING("!");
static adamic_string adamic_string_3 = ADAMIC_STRING(" ");
static adamic_string adamic_string_4 = ADAMIC_STRING(" the second");
static adamic_string adamic_string_5 = ADAMIC_STRING("Kirk");
static adamic_string adamic_string_6 = ADAMIC_STRING("Ahra");
static adamic_string adamic_string_7 = ADAMIC_STRING("Ken");
static adamic_string adamic_string_8 = ADAMIC_STRING(" / ");

static adamic_string * adamic_global_0_original = &adamic_string_empty;
static bool adamic_ready_0 = false;

static double adamic_function_0_factorial(double adamic_local_1_value);
static double adamic_function_1_fibonacci(double adamic_local_2_index);
static adamic_string * adamic_function_2_greet(adamic_string * adamic_local_3_name, double adamic_local_4_times);
static adamic_string * adamic_function_3_rename(adamic_string * adamic_local_5_name);

static double adamic_function_0_factorial(double adamic_local_1_value) {
	ADAMIC_CHECK_STACK();
	if (adamic_local_1_value <= (0x1p+00)) {
		{
			double adamic_temporary_1 = (0x1p+00);
			return adamic_temporary_1;
		}
	}
	double adamic_temporary_2 = adamic_function_0_factorial((adamic_local_1_value - (0x1p+00)));
	double adamic_temporary_3 = (adamic_local_1_value * adamic_temporary_2);
	return adamic_temporary_3;
	adamic_unreachable();
}

static double adamic_function_1_fibonacci(double adamic_local_2_index) {
	ADAMIC_CHECK_STACK();
	double adamic_temporary_6;
	if (adamic_local_2_index < (0x1p+01)) {
		adamic_temporary_6 = adamic_local_2_index;
	} else {
		double adamic_temporary_4 = adamic_function_1_fibonacci((adamic_local_2_index - (0x1p+00)));
		double adamic_temporary_5 = adamic_function_1_fibonacci((adamic_local_2_index - (0x1p+01)));
		adamic_temporary_6 = (adamic_temporary_4 + adamic_temporary_5);
	}
	double adamic_temporary_7 = adamic_temporary_6;
	return adamic_temporary_7;
	adamic_unreachable();
}

static adamic_string * adamic_function_2_greet(adamic_string * adamic_local_3_name, double adamic_local_4_times) {
	ADAMIC_CHECK_STACK();
	adamic_string * adamic_local_6_result = adamic_retain(&adamic_string_0);
	{
		double adamic_local_7_count = (0x0p+00);
		for (;;) {
			if (!(adamic_local_7_count < adamic_local_4_times)) {
				break;
			}
			{
				{
					adamic_string * adamic_temporary_10 = adamic_string_concat(2, (adamic_string *const[]){&adamic_string_1, adamic_local_3_name});
					adamic_string * adamic_local_8_piece = adamic_temporary_10;
					if (adamic_local_7_count == (0x1p+01)) {
						{
							adamic_string * adamic_temporary_11 = adamic_string_concat(2, (adamic_string *const[]){adamic_local_6_result, adamic_local_8_piece});
							adamic_string * adamic_temporary_12 = adamic_string_concat(2, (adamic_string *const[]){adamic_temporary_11, &adamic_string_2});
							adamic_string * adamic_temporary_13 = adamic_temporary_12;
							adamic_release(adamic_temporary_11);
							adamic_release(adamic_local_8_piece);
							adamic_release(adamic_local_6_result);
							return adamic_temporary_13;
						}
					}
					adamic_string * adamic_temporary_14 = adamic_string_concat(2, (adamic_string *const[]){adamic_local_6_result, adamic_local_8_piece});
					adamic_string * adamic_temporary_15 = adamic_string_concat(2, (adamic_string *const[]){adamic_temporary_14, &adamic_string_3});
					adamic_string * adamic_temporary_16 = adamic_local_6_result;
					adamic_local_6_result = adamic_temporary_15;
					adamic_release(adamic_temporary_16);
					adamic_release(adamic_temporary_14);
					adamic_release(adamic_local_8_piece);
				}
			}
			adamic_local_7_count = (adamic_local_7_count + (0x1p+00));
		}
	}
	adamic_string * adamic_temporary_17 = adamic_retain(adamic_local_6_result);
	adamic_release(adamic_local_6_result);
	return adamic_temporary_17;
	adamic_unreachable();
}

static adamic_string * adamic_function_3_rename(adamic_string * adamic_local_5_name) {
	ADAMIC_CHECK_STACK();
	adamic_retain(adamic_local_5_name);
	adamic_local_5_name = adamic_string_append(adamic_local_5_name, 1, (adamic_string *const[]){&adamic_string_4});
	adamic_string * adamic_temporary_18 = adamic_retain(adamic_local_5_name);
	adamic_release(adamic_local_5_name);
	return adamic_temporary_18;
	adamic_unreachable();
}

int main(int argc, char **argv) {
	adamic_start(argc, argv);
	double adamic_temporary_19 = adamic_function_0_factorial((0x1.4p+03));
	adamic_string * adamic_temporary_20 = adamic_string_from_number(adamic_temporary_19);
	double adamic_temporary_21 = adamic_function_0_factorial((0x1.4p+04));
	adamic_string * adamic_temporary_22 = adamic_string_from_number(adamic_temporary_21);
	double adamic_temporary_23 = adamic_function_0_factorial((0x1.56p+07));
	adamic_string * adamic_temporary_24 = adamic_string_from_number(adamic_temporary_23);
	double adamic_temporary_25 = adamic_function_1_fibonacci((0x1.4p+04));
	adamic_string * adamic_temporary_26 = adamic_string_from_number(adamic_temporary_25);
	adamic_string * adamic_temporary_27 = adamic_string_concat(7, (adamic_string *const[]){adamic_temporary_20, &adamic_string_3, adamic_temporary_22, &adamic_string_3, adamic_temporary_24, &adamic_string_3, adamic_temporary_26});
	adamic_write_line(adamic_stdout, adamic_temporary_27);
	adamic_release(adamic_temporary_27);
	adamic_release(adamic_temporary_26);
	adamic_release(adamic_temporary_24);
	adamic_release(adamic_temporary_22);
	adamic_release(adamic_temporary_20);
	adamic_string * adamic_temporary_28 = adamic_function_2_greet(&adamic_string_5, (0x1p+00));
	adamic_write_line(adamic_stdout, adamic_temporary_28);
	adamic_release(adamic_temporary_28);
	adamic_string * adamic_temporary_29 = adamic_function_2_greet(&adamic_string_6, (0x1.4p+02));
	adamic_write_line(adamic_stdout, adamic_temporary_29);
	adamic_release(adamic_temporary_29);
	adamic_string * adamic_temporary_30 = adamic_global_0_original;
	adamic_global_0_original = adamic_retain(&adamic_string_7);
	adamic_release(adamic_temporary_30);
	adamic_ready_0 = true;
	adamic_string * adamic_temporary_31 = adamic_retain(adamic_global_0_original);
	adamic_string * adamic_temporary_32 = adamic_function_3_rename(adamic_temporary_31);
	adamic_string * adamic_temporary_33 = adamic_retain(adamic_global_0_original);
	adamic_string * adamic_temporary_34 = adamic_string_concat(3, (adamic_string *const[]){adamic_temporary_32, &adamic_string_8, adamic_temporary_33});
	adamic_write_line(adamic_stdout, adamic_temporary_34);
	adamic_release(adamic_temporary_34);
	adamic_release(adamic_temporary_33);
	adamic_release(adamic_temporary_32);
	adamic_release(adamic_temporary_31);
	adamic_release(adamic_global_0_original);
	adamic_global_0_original = NULL;
	return 0;
}
