import pathlib,json,difflib,subprocess,os,time
root=pathlib.Path('/workspace/adamic');ev=pathlib.Path('/tmp/u131/evidence');file='stage1/cohere/markdowninline/inline_products_shards_test.go';base=(root/file).read_text();old='i >= n {';new='i > n {';assert base.count(old)==1;changed=base.replace(old,new,1)
(ev/'S2B.diff').write_text(''.join(difflib.unified_diff(base.splitlines(True),changed.splitlines(True),fromfile='a/'+file,tofile='b/'+file)));target=ev/'S2B.go.txt';target.write_text(changed);overlay=ev/'S2B.overlay.json';overlay.write_text(json.dumps({'Replace':{str(root/file):str(target)}}));names=json.loads((ev/'matrix-test-names.json').read_text());c=['timeout','120','go','test','-json','-count=1','-timeout','90s','-overlay='+str(overlay),'./stage1/cohere/markdowninline/','-run','^('+'|'.join(names)+')$'];start=time.monotonic()
with (ev/'S2B.log').open('w') as f:p=subprocess.run(c,cwd=root,env={**os.environ,'ADAMIC_MARKDOWNINLINE_LIBRARY':'/tmp/u131/prettier/node_modules/prettier'},stdout=f,stderr=subprocess.STDOUT)
assert p.returncode!=0;runs=json.loads((ev/'runs.json').read_text());runs.append({'id':'S2B','command':c,'environment':{'ADAMIC_MARKDOWNINLINE_LIBRARY':'/tmp/u131/prettier/node_modules/prettier'},'exit':p.returncode,'wall':time.monotonic()-start});(ev/'runs.json').write_text(json.dumps(runs,indent=2));cat=json.loads((ev/'catalog.json').read_text());cat.append({'id':'S2B','file':file,'line':base[:base.index(old)].count('\n')+1,'before':old,'after':new,'kind':'construction'});(ev/'catalog.json').write_text(json.dumps(cat,indent=2))
with (ev/'S2B-vet.log').open('w') as f:p=subprocess.run(['go','vet','-overlay='+str(overlay),'./stage1/cohere/markdowninline/'],cwd=root,stdout=f,stderr=subprocess.STDOUT)
assert p.returncode==0
# S2 equivalence witness: n=0 is already rejected for every integer index by i<0 or i>=n.
pairs=[(i,n) for i in range(-5,6) for n in range(-5,6)];assert all((n<1 or i<0 or i>=n)==(n<0 or i<0 or i>=n) for i,n in pairs);(ev/'S2-equivalence.txt').write_text('Candidate equivalent: changing n < 1 to n < 0 cannot admit n=0, because every integer i satisfies i<0 or i>=0. The two predicates agreed on all 121 pairs i,n in [-5,5]. No changed output witness was found; S2 is not unguarded behavior. S2B independently changes the upper index bound and the selector test rejects it.\n')
