// Generated by lint-registry. Do not commit or edit.
import type { RuleContext } from '../context.ts';
import { create as create0, type Rule as Rule0 } from '../rules/no-debugger/rule.ts';
import { create as create1, type Rule as Rule1 } from '../rules/no-empty/rule.ts';
import { create as create2, type Rule as Rule2 } from '../rules/eqeqeq/rule.ts';
import { create as create3, type Rule as Rule3 } from '../rules/no-var/rule.a';
import { create as create4, type Rule as Rule4 } from '../rules/no-duplicate-case/rule.ts';
import { create as create5, type Rule as Rule5 } from '../rules/no-octal-escape/rule.ts';
import { create as create6, type Rule as Rule6 } from '../rules/no-unexpected-multiline/rule.ts';
import { create as create7, type Rule as Rule7 } from '../rules/no-unused-private-class-members/rule.ts';
import { create as create8, type Rule as Rule8 } from '../rules/no-useless-constructor/rule.ts';
import { create as create9, type Rule as Rule9 } from '../rules/prefer-template/rule.ts';
import { create as create10, type Rule as Rule10 } from '../rules/react-forward-ref-uses-ref/rule.ts';
import { create as create11, type Rule as Rule11 } from '../rules/react-jsx-no-comment-textnodes/rule.ts';
import { create as create12, type Rule as Rule12 } from '../rules/react-no-find-dom-node/rule.ts';
import { create as create13, type Rule as Rule13 } from '../rules/react-no-is-mounted/rule.ts';
import { create as create14, type Rule as Rule14 } from '../rules/react-no-redundant-should-component-update/rule.ts';
import { create as create15, type Rule as Rule15 } from '../rules/typescript-adjacent-overload-signatures/rule.a';
import { create as create16, type Rule as Rule16 } from '../rules/typescript-init-declarations/rule.a';
import { create as create17, type Rule as Rule17 } from '../rules/typescript-method-signature-style/rule.ts';
import { create as create18, type Rule as Rule18 } from '../rules/typescript-no-this-alias/rule.a';
import { create as create19, type Rule as Rule19 } from '../rules/typescript-no-wrapper-object-types/rule.ts';
import { create as create20, type Rule as Rule20 } from '../rules/typescript-prefer-literal-enum-member/rule.ts';
import { create as create21, type Rule as Rule21 } from '../rules/adamic-no-type-predicate/rule.ts';
import { create as create22, type Rule as Rule22 } from '../rules/base-boundary-no-global-container/rule.a';
import { create as create23, type Rule as Rule23 } from '../rules/base-consistency-no-console/rule.ts';
import { create as create24, type Rule as Rule24 } from '../rules/base-consistency-no-hand-built-declared-error/rule.a';
import { create as create25, type Rule as Rule25 } from '../rules/base-consistency-require-pagination-argument-name/rule.a';
import { create as create26, type Rule as Rule26 } from '../rules/max-classes-per-file/rule.a';
import { create as create27, type Rule as Rule27 } from '../rules/max-depth/rule.a';
import { create as create28, type Rule as Rule28 } from '../rules/max-nested-callbacks/rule.a';
import { create as create29, type Rule as Rule29 } from '../rules/nexus-consistency-no-abbreviated-identifier/rule.a';
import { create as create30, type Rule as Rule30 } from '../rules/nexus-consistency-no-ambiguous-identifier/rule.a';
import { create as create31, type Rule as Rule31 } from '../rules/nexus-consistency-no-enum/rule.ts';
import { create as create32, type Rule as Rule32 } from '../rules/nexus-consistency-no-for-in/rule.a';
import { create as create33, type Rule as Rule33 } from '../rules/nexus-consistency-no-long-line-comment/rule.a';
import { create as create34, type Rule as Rule34 } from '../rules/nexus-consistency-no-multiline-arrow-function/rule.a';
import { create as create35, type Rule as Rule35 } from '../rules/nexus-consistency-no-shouting/rule.a';
import { create as create36, type Rule as Rule36 } from '../rules/nexus-consistency-no-single-line-jsdoc/rule.a';
import { create as create37, type Rule as Rule37 } from '../rules/nexus-consistency-no-stuttering-name/rule.a';
import { create as create38, type Rule as Rule38 } from '../rules/nexus-consistency-require-type-suffix/rule.ts';
import { create as create39, type Rule as Rule39 } from '../rules/no-await-in-loop/rule.ts';
import { create as create40, type Rule as Rule40 } from '../rules/no-bitwise/rule.ts';
import { create as create41, type Rule as Rule41 } from '../rules/no-caller/rule.a';
import { create as create42, type Rule as Rule42 } from '../rules/no-continue/rule.ts';
import { create as create43, type Rule as Rule43 } from '../rules/no-div-regex/rule.ts';
import { create as create44, type Rule as Rule44 } from '../rules/no-empty-character-class/rule.a';
import { create as create45, type Rule as Rule45 } from '../rules/no-empty-pattern/rule.a';
import { create as create46, type Rule as Rule46 } from '../rules/no-empty-static-block/rule.a';
import { create as create47, type Rule as Rule47 } from '../rules/no-ex-assign/rule.a';
import { create as create48, type Rule as Rule48 } from '../rules/no-iterator/rule.a';
import { create as create49, type Rule as Rule49 } from '../rules/no-labels/rule.ts';
import { create as create50, type Rule as Rule50 } from '../rules/no-multi-assign/rule.a';
import { create as create51, type Rule as Rule51 } from '../rules/no-negated-condition/rule.ts';
import { create as create52, type Rule as Rule52 } from '../rules/no-new/rule.ts';
import { create as create53, type Rule as Rule53 } from '../rules/no-plusplus/rule.ts';
import { create as create54, type Rule as Rule54 } from '../rules/no-proto/rule.a';
import { create as create55, type Rule as Rule55 } from '../rules/no-return-assign/rule.ts';
import { create as create56, type Rule as Rule56 } from '../rules/no-script-url/rule.a';
import { create as create57, type Rule as Rule57 } from '../rules/no-self-compare/rule.a';
import { create as create58, type Rule as Rule58 } from '../rules/no-sequences/rule.ts';
import { create as create59, type Rule as Rule59 } from '../rules/no-sparse-arrays/rule.ts';
import { create as create60, type Rule as Rule60 } from '../rules/no-template-curly-in-string/rule.ts';
import { create as create61, type Rule as Rule61 } from '../rules/no-underscore-dangle/rule.a';
import { create as create62, type Rule as Rule62 } from '../rules/no-unneeded-ternary/rule.ts';
import { create as create63, type Rule as Rule63 } from '../rules/no-unsafe-finally/rule.a';
import { create as create64, type Rule as Rule64 } from '../rules/no-unsafe-negation/rule.a';
import { create as create65, type Rule as Rule65 } from '../rules/no-unsafe-optional-chaining/rule.a';
import { create as create66, type Rule as Rule66 } from '../rules/no-useless-catch/rule.a';
import { create as create67, type Rule as Rule67 } from '../rules/no-useless-concat/rule.a';
import { create as create68, type Rule as Rule68 } from '../rules/no-warning-comments/rule.ts';
import { create as create69, type Rule as Rule69 } from '../rules/no-with/rule.ts';
import { create as create70, type Rule as Rule70 } from '../rules/prefer-destructuring/rule.a';
import { create as create71, type Rule as Rule71 } from '../rules/require-yield/rule.ts';
import { create as create72, type Rule as Rule72 } from '../rules/unicode-bom/rule.ts';
import { create as create73, type Rule as Rule73 } from '../rules/vars-on-top/rule.ts';
export class RuleSet {
    readonly context: RuleContext;
    readonly rule0: Rule0;
    readonly rule1: Rule1;
    readonly rule2: Rule2;
    readonly rule3: Rule3;
    readonly rule4: Rule4;
    readonly rule5: Rule5;
    readonly rule6: Rule6;
    readonly rule7: Rule7;
    readonly rule8: Rule8;
    readonly rule9: Rule9;
    readonly rule10: Rule10;
    readonly rule11: Rule11;
    readonly rule12: Rule12;
    readonly rule13: Rule13;
    readonly rule14: Rule14;
    readonly rule15: Rule15;
    readonly rule16: Rule16;
    readonly rule17: Rule17;
    readonly rule18: Rule18;
    readonly rule19: Rule19;
    readonly rule20: Rule20;
    readonly rule21: Rule21;
    readonly rule22: Rule22;
    readonly rule23: Rule23;
    readonly rule24: Rule24;
    readonly rule25: Rule25;
    readonly rule26: Rule26;
    readonly rule27: Rule27;
    readonly rule28: Rule28;
    readonly rule29: Rule29;
    readonly rule30: Rule30;
    readonly rule31: Rule31;
    readonly rule32: Rule32;
    readonly rule33: Rule33;
    readonly rule34: Rule34;
    readonly rule35: Rule35;
    readonly rule36: Rule36;
    readonly rule37: Rule37;
    readonly rule38: Rule38;
    readonly rule39: Rule39;
    readonly rule40: Rule40;
    readonly rule41: Rule41;
    readonly rule42: Rule42;
    readonly rule43: Rule43;
    readonly rule44: Rule44;
    readonly rule45: Rule45;
    readonly rule46: Rule46;
    readonly rule47: Rule47;
    readonly rule48: Rule48;
    readonly rule49: Rule49;
    readonly rule50: Rule50;
    readonly rule51: Rule51;
    readonly rule52: Rule52;
    readonly rule53: Rule53;
    readonly rule54: Rule54;
    readonly rule55: Rule55;
    readonly rule56: Rule56;
    readonly rule57: Rule57;
    readonly rule58: Rule58;
    readonly rule59: Rule59;
    readonly rule60: Rule60;
    readonly rule61: Rule61;
    readonly rule62: Rule62;
    readonly rule63: Rule63;
    readonly rule64: Rule64;
    readonly rule65: Rule65;
    readonly rule66: Rule66;
    readonly rule67: Rule67;
    readonly rule68: Rule68;
    readonly rule69: Rule69;
    readonly rule70: Rule70;
    readonly rule71: Rule71;
    readonly rule72: Rule72;
    readonly rule73: Rule73;
    readonly selected0: boolean;
    readonly selected1: boolean;
    readonly selected2: boolean;
    readonly selected3: boolean;
    readonly selected4: boolean;
    readonly selected5: boolean;
    readonly selected6: boolean;
    readonly selected7: boolean;
    readonly selected8: boolean;
    readonly selected9: boolean;
    readonly selected10: boolean;
    readonly selected11: boolean;
    readonly selected12: boolean;
    readonly selected13: boolean;
    readonly selected14: boolean;
    readonly selected15: boolean;
    readonly selected16: boolean;
    readonly selected17: boolean;
    readonly selected18: boolean;
    readonly selected19: boolean;
    readonly selected20: boolean;
    readonly selected21: boolean;
    readonly selected22: boolean;
    readonly selected23: boolean;
    readonly selected24: boolean;
    readonly selected25: boolean;
    readonly selected26: boolean;
    readonly selected27: boolean;
    readonly selected28: boolean;
    readonly selected29: boolean;
    readonly selected30: boolean;
    readonly selected31: boolean;
    readonly selected32: boolean;
    readonly selected33: boolean;
    readonly selected34: boolean;
    readonly selected35: boolean;
    readonly selected36: boolean;
    readonly selected37: boolean;
    readonly selected38: boolean;
    readonly selected39: boolean;
    readonly selected40: boolean;
    readonly selected41: boolean;
    readonly selected42: boolean;
    readonly selected43: boolean;
    readonly selected44: boolean;
    readonly selected45: boolean;
    readonly selected46: boolean;
    readonly selected47: boolean;
    readonly selected48: boolean;
    readonly selected49: boolean;
    readonly selected50: boolean;
    readonly selected51: boolean;
    readonly selected52: boolean;
    readonly selected53: boolean;
    readonly selected54: boolean;
    readonly selected55: boolean;
    readonly selected56: boolean;
    readonly selected57: boolean;
    readonly selected58: boolean;
    readonly selected59: boolean;
    readonly selected60: boolean;
    readonly selected61: boolean;
    readonly selected62: boolean;
    readonly selected63: boolean;
    readonly selected64: boolean;
    readonly selected65: boolean;
    readonly selected66: boolean;
    readonly selected67: boolean;
    readonly selected68: boolean;
    readonly selected69: boolean;
    readonly selected70: boolean;
    readonly selected71: boolean;
    readonly selected72: boolean;
    readonly selected73: boolean;
    constructor(context: RuleContext, rule0: Rule0, rule1: Rule1, rule2: Rule2, rule3: Rule3, rule4: Rule4, rule5: Rule5, rule6: Rule6, rule7: Rule7, rule8: Rule8, rule9: Rule9, rule10: Rule10, rule11: Rule11, rule12: Rule12, rule13: Rule13, rule14: Rule14, rule15: Rule15, rule16: Rule16, rule17: Rule17, rule18: Rule18, rule19: Rule19, rule20: Rule20, rule21: Rule21, rule22: Rule22, rule23: Rule23, rule24: Rule24, rule25: Rule25, rule26: Rule26, rule27: Rule27, rule28: Rule28, rule29: Rule29, rule30: Rule30, rule31: Rule31, rule32: Rule32, rule33: Rule33, rule34: Rule34, rule35: Rule35, rule36: Rule36, rule37: Rule37, rule38: Rule38, rule39: Rule39, rule40: Rule40, rule41: Rule41, rule42: Rule42, rule43: Rule43, rule44: Rule44, rule45: Rule45, rule46: Rule46, rule47: Rule47, rule48: Rule48, rule49: Rule49, rule50: Rule50, rule51: Rule51, rule52: Rule52, rule53: Rule53, rule54: Rule54, rule55: Rule55, rule56: Rule56, rule57: Rule57, rule58: Rule58, rule59: Rule59, rule60: Rule60, rule61: Rule61, rule62: Rule62, rule63: Rule63, rule64: Rule64, rule65: Rule65, rule66: Rule66, rule67: Rule67, rule68: Rule68, rule69: Rule69, rule70: Rule70, rule71: Rule71, rule72: Rule72, rule73: Rule73) {
        this.context = context;
        this.rule0 = rule0;
        this.rule1 = rule1;
        this.rule2 = rule2;
        this.rule3 = rule3;
        this.rule4 = rule4;
        this.rule5 = rule5;
        this.rule6 = rule6;
        this.rule7 = rule7;
        this.rule8 = rule8;
        this.rule9 = rule9;
        this.rule10 = rule10;
        this.rule11 = rule11;
        this.rule12 = rule12;
        this.rule13 = rule13;
        this.rule14 = rule14;
        this.rule15 = rule15;
        this.rule16 = rule16;
        this.rule17 = rule17;
        this.rule18 = rule18;
        this.rule19 = rule19;
        this.rule20 = rule20;
        this.rule21 = rule21;
        this.rule22 = rule22;
        this.rule23 = rule23;
        this.rule24 = rule24;
        this.rule25 = rule25;
        this.rule26 = rule26;
        this.rule27 = rule27;
        this.rule28 = rule28;
        this.rule29 = rule29;
        this.rule30 = rule30;
        this.rule31 = rule31;
        this.rule32 = rule32;
        this.rule33 = rule33;
        this.rule34 = rule34;
        this.rule35 = rule35;
        this.rule36 = rule36;
        this.rule37 = rule37;
        this.rule38 = rule38;
        this.rule39 = rule39;
        this.rule40 = rule40;
        this.rule41 = rule41;
        this.rule42 = rule42;
        this.rule43 = rule43;
        this.rule44 = rule44;
        this.rule45 = rule45;
        this.rule46 = rule46;
        this.rule47 = rule47;
        this.rule48 = rule48;
        this.rule49 = rule49;
        this.rule50 = rule50;
        this.rule51 = rule51;
        this.rule52 = rule52;
        this.rule53 = rule53;
        this.rule54 = rule54;
        this.rule55 = rule55;
        this.rule56 = rule56;
        this.rule57 = rule57;
        this.rule58 = rule58;
        this.rule59 = rule59;
        this.rule60 = rule60;
        this.rule61 = rule61;
        this.rule62 = rule62;
        this.rule63 = rule63;
        this.rule64 = rule64;
        this.rule65 = rule65;
        this.rule66 = rule66;
        this.rule67 = rule67;
        this.rule68 = rule68;
        this.rule69 = rule69;
        this.rule70 = rule70;
        this.rule71 = rule71;
        this.rule72 = rule72;
        this.rule73 = rule73;
        this.selected0 = context.enabled('no-debugger');
        this.selected1 = context.enabled('no-empty');
        this.selected2 = context.enabled('eqeqeq');
        this.selected3 = context.enabled('no-var');
        this.selected4 = context.enabled('no-duplicate-case');
        this.selected5 = context.enabled('no-octal-escape');
        this.selected6 = context.enabled('no-unexpected-multiline');
        this.selected7 = context.enabled('no-unused-private-class-members');
        this.selected8 = context.enabled('no-useless-constructor');
        this.selected9 = context.enabled('prefer-template');
        this.selected10 = context.enabled('react/forward-ref-uses-ref');
        this.selected11 = context.enabled('react/jsx-no-comment-textnodes');
        this.selected12 = context.enabled('react/no-find-dom-node');
        this.selected13 = context.enabled('react/no-is-mounted');
        this.selected14 = context.enabled('react/no-redundant-should-component-update');
        this.selected15 = context.enabled('@typescript-eslint/adjacent-overload-signatures');
        this.selected16 = context.enabled('@typescript-eslint/init-declarations');
        this.selected17 = context.enabled('@typescript-eslint/method-signature-style');
        this.selected18 = context.enabled('@typescript-eslint/no-this-alias');
        this.selected19 = context.enabled('@typescript-eslint/no-wrapper-object-types');
        this.selected20 = context.enabled('@typescript-eslint/prefer-literal-enum-member');
        this.selected21 = context.enabled('adamic/no-type-predicate');
        this.selected22 = context.enabled('base/boundary-no-global-container');
        this.selected23 = context.enabled('base/consistency-no-console');
        this.selected24 = context.enabled('base/consistency-no-hand-built-declared-error');
        this.selected25 = context.enabled('base/consistency-require-pagination-argument-name');
        this.selected26 = context.enabled('max-classes-per-file');
        this.selected27 = context.enabled('max-depth');
        this.selected28 = context.enabled('max-nested-callbacks');
        this.selected29 = context.enabled('nexus/consistency-no-abbreviated-identifier');
        this.selected30 = context.enabled('nexus/consistency-no-ambiguous-identifier');
        this.selected31 = context.enabled('nexus/consistency-no-enum');
        this.selected32 = context.enabled('nexus/consistency-no-for-in');
        this.selected33 = context.enabled('nexus/consistency-no-long-line-comment');
        this.selected34 = context.enabled('nexus/consistency-no-multiline-arrow-function');
        this.selected35 = context.enabled('nexus/consistency-no-shouting');
        this.selected36 = context.enabled('nexus/consistency-no-single-line-jsdoc');
        this.selected37 = context.enabled('nexus/consistency-no-stuttering-name');
        this.selected38 = context.enabled('nexus/consistency-require-type-suffix');
        this.selected39 = context.enabled('no-await-in-loop');
        this.selected40 = context.enabled('no-bitwise');
        this.selected41 = context.enabled('no-caller');
        this.selected42 = context.enabled('no-continue');
        this.selected43 = context.enabled('no-div-regex');
        this.selected44 = context.enabled('no-empty-character-class');
        this.selected45 = context.enabled('no-empty-pattern');
        this.selected46 = context.enabled('no-empty-static-block');
        this.selected47 = context.enabled('no-ex-assign');
        this.selected48 = context.enabled('no-iterator');
        this.selected49 = context.enabled('no-labels');
        this.selected50 = context.enabled('no-multi-assign');
        this.selected51 = context.enabled('no-negated-condition');
        this.selected52 = context.enabled('no-new');
        this.selected53 = context.enabled('no-plusplus');
        this.selected54 = context.enabled('no-proto');
        this.selected55 = context.enabled('no-return-assign');
        this.selected56 = context.enabled('no-script-url');
        this.selected57 = context.enabled('no-self-compare');
        this.selected58 = context.enabled('no-sequences');
        this.selected59 = context.enabled('no-sparse-arrays');
        this.selected60 = context.enabled('no-template-curly-in-string');
        this.selected61 = context.enabled('no-underscore-dangle');
        this.selected62 = context.enabled('no-unneeded-ternary');
        this.selected63 = context.enabled('no-unsafe-finally');
        this.selected64 = context.enabled('no-unsafe-negation');
        this.selected65 = context.enabled('no-unsafe-optional-chaining');
        this.selected66 = context.enabled('no-useless-catch');
        this.selected67 = context.enabled('no-useless-concat');
        this.selected68 = context.enabled('no-warning-comments');
        this.selected69 = context.enabled('no-with');
        this.selected70 = context.enabled('prefer-destructuring');
        this.selected71 = context.enabled('require-yield');
        this.selected72 = context.enabled('unicode-bom');
        this.selected73 = context.enabled('vars-on-top');
    }
    prepare(root: number): void {
    if(this.selected19) { this.rule19.prepare(root); }
}
    finish(root: number): void {
    if(this.selected26) { this.rule26.finish(root); }
}
    visit(index: number, parent: number): void {
        const node = this.context.node(index);
        switch(node.kind) {
        case 'ArrayBindingPattern':
            if(this.selected45) { this.rule45.visit(node, index, parent); }
            break;
        case 'ArrayLiteralExpression':
            if(this.selected59) { this.rule59.visit(node, index); }
            break;
        case 'ArrowFunction':
            if(this.selected28) { this.rule28.visit(node, index); }
            if(this.selected34) { this.rule34.visit(node, index); }
            if(this.selected61) { this.rule61.visit(node, index); }
            break;
        case 'AwaitExpression':
            if(this.selected39) { this.rule39.visit(node, index, parent); }
            break;
        case 'BigIntLiteral':
            if(this.selected9) { this.rule9.visit(index); }
            break;
        case 'BinaryExpression':
            if(this.selected2) { this.rule2.visit(index); }
            if(this.selected6) { this.rule6.visit(index); }
            if(this.selected18) { this.rule18.visit(node, index); }
            if(this.selected40) { this.rule40.visit(node, index); }
            if(this.selected50) { this.rule50.visit(node, index); }
            if(this.selected55) { this.rule55.visit(node, index); }
            if(this.selected57) { this.rule57.visit(node, index); }
            if(this.selected58) { this.rule58.visit(node, index, parent); }
            if(this.selected64) { this.rule64.visit(node, index); }
            if(this.selected65) { this.rule65.visit(node, index); }
            if(this.selected67) { this.rule67.visit(node, index); }
            if(this.selected70) { this.rule70.visit(node, index); }
            break;
        case 'BindingElement':
            if(this.selected65) { this.rule65.visit(node, index); }
            break;
        case 'Block':
            if(this.selected1) { this.rule1.visit(index, parent); }
            if(this.selected15) { this.rule15.visit(node, index); }
            break;
        case 'BreakStatement':
            if(this.selected63) { this.rule63.visit(node, index); }
            break;
        case 'CallExpression':
            if(this.selected6) { this.rule6.visit(index); }
            if(this.selected10) { this.rule10.visit(index); }
            if(this.selected12) { this.rule12.visit(index); }
            if(this.selected13) { this.rule13.visit(index); }
            if(this.selected34) { this.rule34.visit(node, index); }
            if(this.selected65) { this.rule65.visit(node, index); }
            break;
        case 'CatchClause':
            if(this.selected47) { this.rule47.visit(node, index); }
            if(this.selected66) { this.rule66.visit(node, index); }
            break;
        case 'ClassDeclaration':
            if(this.selected7) { this.rule7.visit(index); }
            if(this.selected14) { this.rule14.visit(index); }
            if(this.selected15) { this.rule15.visit(node, index); }
            if(this.selected26) { this.rule26.visit(node, index, parent); }
            if(this.selected65) { this.rule65.visit(node, index); }
            break;
        case 'ClassExpression':
            if(this.selected7) { this.rule7.visit(index); }
            if(this.selected14) { this.rule14.visit(index); }
            if(this.selected15) { this.rule15.visit(node, index); }
            if(this.selected26) { this.rule26.visit(node, index, parent); }
            if(this.selected65) { this.rule65.visit(node, index); }
            break;
        case 'ClassStaticBlockDeclaration':
            if(this.selected46) { this.rule46.visit(node, index); }
            break;
        case 'ConditionalExpression':
            if(this.selected51) { this.rule51.visit(node, index); }
            if(this.selected62) { this.rule62.visit(node, index); }
            break;
        case 'Constructor':
            if(this.selected8) { this.rule8.visit(index); }
            break;
        case 'ContinueStatement':
            if(this.selected42) { this.rule42.visit(node, index); }
            if(this.selected63) { this.rule63.visit(node, index); }
            break;
        case 'DebuggerStatement':
            if(this.selected0) { this.rule0.visit(index, parent); }
            break;
        case 'Decorator':
            if(this.selected25) { this.rule25.visit(node, index); }
            break;
        case 'DoStatement':
            if(this.selected27) { this.rule27.visit(node, index); }
            break;
        case 'ElementAccessExpression':
            if(this.selected6) { this.rule6.visit(index); }
            if(this.selected23) { this.rule23.visit(node, index); }
            if(this.selected48) { this.rule48.visit(node, index); }
            if(this.selected54) { this.rule54.visit(node, index); }
            if(this.selected65) { this.rule65.visit(node, index); }
            break;
        case 'EnumDeclaration':
            if(this.selected31) { this.rule31.visit(node, index); }
            break;
        case 'EnumMember':
            if(this.selected20) { this.rule20.visit(node, index); }
            break;
        case 'ExpressionStatement':
            if(this.selected52) { this.rule52.visit(node, index); }
            break;
        case 'FalseKeyword':
            if(this.selected9) { this.rule9.visit(index); }
            break;
        case 'ForInStatement':
            if(this.selected3) { this.rule3.visit(index, parent); }
            if(this.selected27) { this.rule27.visit(node, index); }
            if(this.selected32) { this.rule32.visit(node, index); }
            break;
        case 'ForOfStatement':
            if(this.selected3) { this.rule3.visit(index, parent); }
            if(this.selected27) { this.rule27.visit(node, index); }
            if(this.selected39) { this.rule39.visit(node, index, parent); }
            if(this.selected65) { this.rule65.visit(node, index); }
            break;
        case 'ForStatement':
            if(this.selected3) { this.rule3.visit(index, parent); }
            if(this.selected27) { this.rule27.visit(node, index); }
            break;
        case 'FunctionDeclaration':
            if(this.selected61) { this.rule61.visit(node, index); }
            if(this.selected71) { this.rule71.visit(node, index); }
            break;
        case 'FunctionExpression':
            if(this.selected28) { this.rule28.visit(node, index); }
            if(this.selected61) { this.rule61.visit(node, index); }
            if(this.selected71) { this.rule71.visit(node, index); }
            break;
        case 'Identifier':
            if(this.selected22) { this.rule22.visit(node, index); }
            if(this.selected29) { this.rule29.visit(node, index); }
            if(this.selected30) { this.rule30.visit(node, index); }
            break;
        case 'IfStatement':
            if(this.selected27) { this.rule27.visit(node, index); }
            if(this.selected51) { this.rule51.visit(node, index); }
            break;
        case 'InterfaceDeclaration':
            if(this.selected15) { this.rule15.visit(node, index); }
            if(this.selected38) { this.rule38.visit(node, index); }
            break;
        case 'JsxText':
            if(this.selected11) { this.rule11.visit(index); }
            break;
        case 'MethodDeclaration':
            if(this.selected8) { this.rule8.visit(index); }
            if(this.selected61) { this.rule61.visit(node, index); }
            if(this.selected71) { this.rule71.visit(node, index); }
            break;
        case 'MethodSignature':
            if(this.selected17) { this.rule17.visit(node, index); }
            break;
        case 'ModuleBlock':
            if(this.selected15) { this.rule15.visit(node, index); }
            break;
        case 'NewExpression':
            if(this.selected24) { this.rule24.visit(node, index); }
            if(this.selected65) { this.rule65.visit(node, index); }
            break;
        case 'NoSubstitutionTemplateLiteral':
            if(this.selected9) { this.rule9.visit(index); }
            if(this.selected56) { this.rule56.visit(node, index, parent); }
            break;
        case 'NullKeyword':
            if(this.selected9) { this.rule9.visit(index); }
            break;
        case 'NumericLiteral':
            if(this.selected9) { this.rule9.visit(index); }
            break;
        case 'ObjectBindingPattern':
            if(this.selected45) { this.rule45.visit(node, index, parent); }
            break;
        case 'Parameter':
            if(this.selected65) { this.rule65.visit(node, index); }
            break;
        case 'PostfixUnaryExpression':
            if(this.selected53) { this.rule53.visit(node, index); }
            break;
        case 'PrefixUnaryExpression':
            if(this.selected40) { this.rule40.visit(node, index); }
            if(this.selected53) { this.rule53.visit(node, index); }
            if(this.selected65) { this.rule65.visit(node, index); }
            break;
        case 'PropertyAccessExpression':
            if(this.selected23) { this.rule23.visit(node, index); }
            if(this.selected37) { this.rule37.visit(node, index); }
            if(this.selected41) { this.rule41.visit(node, index); }
            if(this.selected48) { this.rule48.visit(node, index); }
            if(this.selected54) { this.rule54.visit(node, index); }
            if(this.selected61) { this.rule61.visit(node, index); }
            if(this.selected65) { this.rule65.visit(node, index); }
            break;
        case 'PropertyDeclaration':
            if(this.selected61) { this.rule61.visit(node, index); }
            break;
        case 'PropertySignature':
            if(this.selected17) { this.rule17.visit(node, index); }
            break;
        case 'RegularExpressionLiteral':
            if(this.selected9) { this.rule9.visit(index); }
            if(this.selected43) { this.rule43.visit(node, index); }
            if(this.selected44) { this.rule44.visit(node, index); }
            break;
        case 'ReturnStatement':
            if(this.selected63) { this.rule63.visit(node, index); }
            break;
        case 'SourceFile':
            if(this.selected15) { this.rule15.visit(node, index); }
            if(this.selected33) { this.rule33.visit(node, index); }
            if(this.selected35) { this.rule35.visit(node, index); }
            if(this.selected36) { this.rule36.visit(node, index); }
            if(this.selected49) { this.rule49.visit(node, index); }
            if(this.selected68) { this.rule68.visit(node, index); }
            if(this.selected72) { this.rule72.visit(node, index); }
            break;
        case 'SpreadElement':
            if(this.selected65) { this.rule65.visit(node, index); }
            break;
        case 'StringLiteral':
            if(this.selected5) { this.rule5.visit(index); }
            if(this.selected9) { this.rule9.visit(index); }
            if(this.selected56) { this.rule56.visit(node, index, parent); }
            if(this.selected60) { this.rule60.visit(node, index); }
            break;
        case 'SwitchStatement':
            if(this.selected1) { this.rule1.visit(index, parent); }
            if(this.selected4) { this.rule4.visit(index); }
            if(this.selected27) { this.rule27.visit(node, index); }
            break;
        case 'TaggedTemplateExpression':
            if(this.selected6) { this.rule6.visit(index); }
            if(this.selected65) { this.rule65.visit(node, index); }
            break;
        case 'TemplateExpression':
            if(this.selected9) { this.rule9.visit(index); }
            break;
        case 'ThrowStatement':
            if(this.selected63) { this.rule63.visit(node, index); }
            break;
        case 'TrueKeyword':
            if(this.selected9) { this.rule9.visit(index); }
            break;
        case 'TryStatement':
            if(this.selected27) { this.rule27.visit(node, index); }
            break;
        case 'TypeAliasDeclaration':
            if(this.selected38) { this.rule38.visit(node, index); }
            break;
        case 'TypeLiteral':
            if(this.selected15) { this.rule15.visit(node, index); }
            break;
        case 'TypePredicate':
            if(this.selected21) { this.rule21.visit(node, index); }
            break;
        case 'TypeReference':
            if(this.selected19) { this.rule19.visit(node, index); }
            break;
        case 'VariableDeclaration':
            if(this.selected18) { this.rule18.visit(node, index); }
            if(this.selected38) { this.rule38.visit(node, index); }
            if(this.selected61) { this.rule61.visit(node, index); }
            if(this.selected65) { this.rule65.visit(node, index); }
            if(this.selected70) { this.rule70.visit(node, index); }
            break;
        case 'VariableDeclarationList':
            if(this.selected16) { this.rule16.visit(node, index); }
            if(this.selected39) { this.rule39.visit(node, index, parent); }
            if(this.selected73) { this.rule73.visit(node, index, parent); }
            break;
        case 'VariableStatement':
            if(this.selected3) { this.rule3.visit(index, parent); }
            break;
        case 'WhileStatement':
            if(this.selected27) { this.rule27.visit(node, index); }
            break;
        case 'WithStatement':
            if(this.selected27) { this.rule27.visit(node, index); }
            if(this.selected65) { this.rule65.visit(node, index); }
            if(this.selected69) { this.rule69.visit(node, index); }
            break;
        default:
            break;
    }
    }
}
export function createRuleSet(context: RuleContext): RuleSet {
    const rule0 = create0(context);
    const rule1 = create1(context);
    const rule2 = create2(context);
    const rule3 = create3(context);
    const rule4 = create4(context);
    const rule5 = create5(context);
    const rule6 = create6(context);
    const rule7 = create7(context);
    const rule8 = create8(context);
    const rule9 = create9(context);
    const rule10 = create10(context);
    const rule11 = create11(context);
    const rule12 = create12(context);
    const rule13 = create13(context);
    const rule14 = create14(context);
    const rule15 = create15(context);
    const rule16 = create16(context);
    const rule17 = create17(context);
    const rule18 = create18(context);
    const rule19 = create19(context);
    const rule20 = create20(context);
    const rule21 = create21(context);
    const rule22 = create22(context);
    const rule23 = create23(context);
    const rule24 = create24(context);
    const rule25 = create25(context);
    const rule26 = create26(context);
    const rule27 = create27(context);
    const rule28 = create28(context);
    const rule29 = create29(context);
    const rule30 = create30(context);
    const rule31 = create31(context);
    const rule32 = create32(context);
    const rule33 = create33(context);
    const rule34 = create34(context);
    const rule35 = create35(context);
    const rule36 = create36(context);
    const rule37 = create37(context);
    const rule38 = create38(context);
    const rule39 = create39(context);
    const rule40 = create40(context);
    const rule41 = create41(context);
    const rule42 = create42(context);
    const rule43 = create43(context);
    const rule44 = create44(context);
    const rule45 = create45(context);
    const rule46 = create46(context);
    const rule47 = create47(context);
    const rule48 = create48(context);
    const rule49 = create49(context);
    const rule50 = create50(context);
    const rule51 = create51(context);
    const rule52 = create52(context);
    const rule53 = create53(context);
    const rule54 = create54(context);
    const rule55 = create55(context);
    const rule56 = create56(context);
    const rule57 = create57(context);
    const rule58 = create58(context);
    const rule59 = create59(context);
    const rule60 = create60(context);
    const rule61 = create61(context);
    const rule62 = create62(context);
    const rule63 = create63(context);
    const rule64 = create64(context);
    const rule65 = create65(context);
    const rule66 = create66(context);
    const rule67 = create67(context);
    const rule68 = create68(context);
    const rule69 = create69(context);
    const rule70 = create70(context);
    const rule71 = create71(context);
    const rule72 = create72(context);
    const rule73 = create73(context);
    return new RuleSet(context, rule0, rule1, rule2, rule3, rule4, rule5, rule6, rule7, rule8, rule9, rule10, rule11, rule12, rule13, rule14, rule15, rule16, rule17, rule18, rule19, rule20, rule21, rule22, rule23, rule24, rule25, rule26, rule27, rule28, rule29, rule30, rule31, rule32, rule33, rule34, rule35, rule36, rule37, rule38, rule39, rule40, rule41, rule42, rule43, rule44, rule45, rule46, rule47, rule48, rule49, rule50, rule51, rule52, rule53, rule54, rule55, rule56, rule57, rule58, rule59, rule60, rule61, rule62, rule63, rule64, rule65, rule66, rule67, rule68, rule69, rule70, rule71, rule72, rule73);
}
