
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"reflect"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/system-inc/adamic/internal/oracle"


)

var tests = []testing.InternalTest{

	{"TestArgumentsLengthTypeScriptSource", _test.TestArgumentsLengthTypeScriptSource},

	{"TestArgumentsLengthWrongSlotMutant", _test.TestArgumentsLengthWrongSlotMutant},

	{"TestGateCacheGeneratedC", _test.TestGateCacheGeneratedC},

	{"TestGateCacheToolchains", _test.TestGateCacheToolchains},

	{"TestGateCacheNodeInputs", _test.TestGateCacheNodeInputs},

	{"TestGateCacheAtomicEvidence", _test.TestGateCacheAtomicEvidence},

	{"TestGateCacheUncached", _test.TestGateCacheUncached},

	{"TestCheckedCastFlushesOutput", _test.TestCheckedCastFlushesOutput},

	{"TestUncheckableCastAdmission", _test.TestUncheckableCastAdmission},

	{"TestCheckedCastRunsNoCatchOrFinally", _test.TestCheckedCastRunsNoCatchOrFinally},

	{"TestCheckedCastFailureContract", _test.TestCheckedCastFailureContract},

	{"TestCheckedCastMutants", _test.TestCheckedCastMutants},

	{"TestCensusAppendResultProof", _test.TestCensusAppendResultProof},

	{"TestCensusOverloadResultStop", _test.TestCensusOverloadResultStop},

	{"TestCensusSmallStoppedSourceOnNode", _test.TestCensusSmallStoppedSourceOnNode},

	{"TestCheckedViewFlagDowncast", _test.TestCheckedViewFlagDowncast},

	{"TestCheckedViewInterfaces", _test.TestCheckedViewInterfaces},

	{"TestCheckedViewObjects", _test.TestCheckedViewObjects},

	{"TestCheckedViewOptionalReadBoundary", _test.TestCheckedViewOptionalReadBoundary},

	{"TestCheckedViewV2ReadsAfterWrites", _test.TestCheckedViewV2ReadsAfterWrites},

	{"TestCheckedViewV2ArrayArmBoundary", _test.TestCheckedViewV2ArrayArmBoundary},

	{"TestCheckedViewV2WrongFamilyMutant", _test.TestCheckedViewV2WrongFamilyMutant},

	{"TestCheckedViewV2RepresentationMutants", _test.TestCheckedViewV2RepresentationMutants},

	{"TestCheckedViewV2MembershipMutant", _test.TestCheckedViewV2MembershipMutant},

	{"TestCheckedViewV2TupleIdentityMutant", _test.TestCheckedViewV2TupleIdentityMutant},

	{"TestCheckedViewV2CallableProducerMutant", _test.TestCheckedViewV2CallableProducerMutant},

	{"TestCheckedViewV2MovedStage3Results", _test.TestCheckedViewV2MovedStage3Results},

	{"TestCheckedViewObjectPrimitiveSource", _test.TestCheckedViewObjectPrimitiveSource},

	{"TestCheckedViewUntaggedSourceDispatch", _test.TestCheckedViewUntaggedSourceDispatch},

	{"TestCheckedViewUntaggedCallableUnion", _test.TestCheckedViewUntaggedCallableUnion},

	{"TestCheckedViewUntaggedOptionalCallableControl", _test.TestCheckedViewUntaggedOptionalCallableControl},

	{"TestCheckedViewUntaggedSourceFlows", _test.TestCheckedViewUntaggedSourceFlows},

	{"TestCheckedViewUntaggedOwnClassData", _test.TestCheckedViewUntaggedOwnClassData},

	{"TestCheckedViewUntaggedRecursive", _test.TestCheckedViewUntaggedRecursive},

	{"TestCheckedViewUntaggedArrayPending", _test.TestCheckedViewUntaggedArrayPending},

	{"TestClassWrongOutput103", _test.TestClassWrongOutput103},

	{"TestClassWrongOutput107", _test.TestClassWrongOutput107},

	{"TestClassWrongOutput108", _test.TestClassWrongOutput108},

	{"TestClassWrongOutput106", _test.TestClassWrongOutput106},

	{"TestClockGenericReturnsT01Mutant", _test.TestClockGenericReturnsT01Mutant},

	{"TestClosureMergeRefusals", _test.TestClosureMergeRefusals},

	{"TestTypeScriptConditionsAgreeWithNode", _test.TestTypeScriptConditionsAgreeWithNode},

	{"TestConditionNaNMutant", _test.TestConditionNaNMutant},

	{"TestConditionLedgerMissingSiteMutant", _test.TestConditionLedgerMissingSiteMutant},

	{"TestConditionLedgerNullMutant", _test.TestConditionLedgerNullMutant},

	{"TestLoopCountersAgreeWithNode", _test.TestLoopCountersAgreeWithNode},

	{"TestCountsAreRecorded", _test.TestCountsAreRecorded},

	{"TestDebuggerNativeEmitsNothing", _test.TestDebuggerNativeEmitsNothing},

	{"TestElementAccessCompilerAreaBoundaries", _test.TestElementAccessCompilerAreaBoundaries},

	{"TestEntriesAcceptance", _test.TestEntriesAcceptance},

	{"TestEntriesProvenance", _test.TestEntriesProvenance},

	{"TestEntriesRuntimeReadiness", _test.TestEntriesRuntimeReadiness},

	{"TestEnumInitializationNode", _test.TestEnumInitializationNode},

	{"TestEnumInitializationUnknownPinned", _test.TestEnumInitializationUnknownPinned},

	{"TestNumericEnumNeverPathsPinned", _test.TestNumericEnumNeverPathsPinned},

	{"TestNumericEnumNeverPinned", _test.TestNumericEnumNeverPinned},

	{"TestStage3EnumBoundaries", _test.TestStage3EnumBoundaries},

	{"TestStage3EnumSparseArrayBoundary", _test.TestStage3EnumSparseArrayBoundary},

	{"TestEnumNameEnumerationMutant", _test.TestEnumNameEnumerationMutant},

	{"TestEnumSemanticMutants", _test.TestEnumSemanticMutants},

	{"TestEnumCleanupMutant", _test.TestEnumCleanupMutant},

	{"TestFallthroughMutants", _test.TestFallthroughMutants},

	{"TestFieldReadinessRepresentation", _test.TestFieldReadinessRepresentation},

	{"TestFreshWriteProbesStayRefused", _test.TestFreshWriteProbesStayRefused},

	{"TestFunctionValueBoundaryBoxing", _test.TestFunctionValueBoundaryBoxing},

	{"TestImportCycleRuntimeCalls", _test.TestImportCycleRuntimeCalls},

	{"TestImportCycleLoadTimeReads", _test.TestImportCycleLoadTimeReads},

	{"TestImportedNonliteralConstCaseIsNotYet", _test.TestImportedNonliteralConstCaseIsNotYet},

	{"TestInputAgreesWithNode", _test.TestInputAgreesWithNode},

	{"TestInterfaceCastOracle", _test.TestInterfaceCastOracle},

	{"TestInterfaceCastChecksMalformedRead", _test.TestInterfaceCastChecksMalformedRead},

	{"TestInterfaceCastRuntimeMutants", _test.TestInterfaceCastRuntimeMutants},

	{"TestInterfaceCastImportedConstruction", _test.TestInterfaceCastImportedConstruction},

	{"TestInterfaceCastScalarTags", _test.TestInterfaceCastScalarTags},

	{"TestArrayFamilyMutants", _test.TestArrayFamilyMutants},

	{"TestArrayWithBoundsMutant", _test.TestArrayWithBoundsMutant},

	{"TestJSONStringifyRefusals", _test.TestJSONStringifyRefusals},

	{"TestJSONStringifyResultMayBeUndefined", _test.TestJSONStringifyResultMayBeUndefined},

	{"TestJSONStringifyOracleCatchesKeyOrder", _test.TestJSONStringifyOracleCatchesKeyOrder},

	{"TestLibraryMapSetIteratorCopiesRefused", _test.TestLibraryMapSetIteratorCopiesRefused},

	{"TestLibraryMapSetMutants", _test.TestLibraryMapSetMutants},

	{"TestMathNumberOracleCatchesMutants", _test.TestMathNumberOracleCatchesMutants},

	{"TestLibraryStringMutants", _test.TestLibraryStringMutants},

	{"TestLiteralOptionalOracleCatchesMutant", _test.TestLiteralOptionalOracleCatchesMutant},

	{"TestLiteralUndefinedOracleCatchesMutant", _test.TestLiteralUndefinedOracleCatchesMutant},

	{"TestLibraryMethodValueMutants", _test.TestLibraryMethodValueMutants},

	{"TestLibraryMethodOwnLoadMutants", _test.TestLibraryMethodOwnLoadMutants},

	{"TestLibraryMethodCaptureMutants", _test.TestLibraryMethodCaptureMutants},

	{"TestLibraryMethodAliasReadMutant", _test.TestLibraryMethodAliasReadMutant},

	{"TestModuleNamespaceReadsMatchNode", _test.TestModuleNamespaceReadsMatchNode},

	{"TestModuleNamespaceReadinessMutants", _test.TestModuleNamespaceReadinessMutants},

	{"TestModuleNamespaceLiveBindingMutant", _test.TestModuleNamespaceLiveBindingMutant},

	{"TestNamespaceLiveExportBoundary", _test.TestNamespaceLiveExportBoundary},

	{"TestNamespaceRuledMutants", _test.TestNamespaceRuledMutants},

	{"TestNamespaceSemanticMutants", _test.TestNamespaceSemanticMutants},

	{"TestNamespaceStateMutants", _test.TestNamespaceStateMutants},

	{"TestNarrowedUnionMemberCheck", _test.TestNarrowedUnionMemberCheck},

	{"TestNarrowedUnionObjectTagRefusal", _test.TestNarrowedUnionObjectTagRefusal},

	{"TestNestedSiblingCycleMutantIsCaught", _test.TestNestedSiblingCycleMutantIsCaught},

	{"TestNestedCycleRefusal", _test.TestNestedCycleRefusal},

	{"TestNestedRebindingCheckerRefusal", _test.TestNestedRebindingCheckerRefusal},

	{"TestNestedCallbackCarrierMutantIsCaught", _test.TestNestedCallbackCarrierMutantIsCaught},

	{"TestNewExpressionUint16RemainsNotYet", _test.TestNewExpressionUint16RemainsNotYet},

	{"TestNewExpressionCacheCaptureRemainsNotYet", _test.TestNewExpressionCacheCaptureRemainsNotYet},

	{"TestNodeFSFileAgreesWithNode", _test.TestNodeFSFileAgreesWithNode},

	{"TestNodeFSFileMutants", _test.TestNodeFSFileMutants},

	{"TestCheckedNonNullTypeScript", _test.TestCheckedNonNullTypeScript},

	{"TestCheckedNonNullAdamicRefusal", _test.TestCheckedNonNullAdamicRefusal},

	{"TestCheckedNonNullCounts", _test.TestCheckedNonNullCounts},

	{"TestImpossibleNonNullFixturesAreRefused", _test.TestImpossibleNonNullFixturesAreRefused},

	{"TestPossibleNonNullAdamicAssertionsAreRefused", _test.TestPossibleNonNullAdamicAssertionsAreRefused},

	{"TestMigratedNonNullFixturesRemainCovered", _test.TestMigratedNonNullFixturesRemainCovered},

	{"TestNonNullLiteralUnionInitializers", _test.TestNonNullLiteralUnionInitializers},

	{"TestParserNonNullSourceExtension", _test.TestParserNonNullSourceExtension},

	{"TestNonNullAdamicRefusal", _test.TestNonNullAdamicRefusal},

	{"TestNotYetLibraryObjectEntriesConstMutant", _test.TestNotYetLibraryObjectEntriesConstMutant},

	{"TestNotYetLibraryRegexCallbackMutants", _test.TestNotYetLibraryRegexCallbackMutants},

	{"TestNotYetLibraryRegexOffsetMutants", _test.TestNotYetLibraryRegexOffsetMutants},

	{"TestNotYetLibraryStringBoundsMutants", _test.TestNotYetLibraryStringBoundsMutants},

	{"TestOct6InheritanceMutants", _test.TestOct6InheritanceMutants},

	{"TestOct6ReleaseMutant", _test.TestOct6ReleaseMutant},

	{"TestOmittedArgumentZeroMutantIsCaught", _test.TestOmittedArgumentZeroMutantIsCaught},

	{"TestOmittedOriginalProbePolicy", _test.TestOmittedOriginalProbePolicy},

	{"TestOmittedReaderZeroMutantIsCaught", _test.TestOmittedReaderZeroMutantIsCaught},

	{"TestNativeAgreesWithNode", _test.TestNativeAgreesWithNode},

	{"TestTheOracleCatchesOneByte", _test.TestTheOracleCatchesOneByte},

	{"TestOneFileHoldsNodesOrder", _test.TestOneFileHoldsNodesOrder},

	{"TestClosedStdoutEndsAsOnNode", _test.TestClosedStdoutEndsAsOnNode},

	{"TestFileWritesLandInNodesOrder", _test.TestFileWritesLandInNodesOrder},

	{"TestAPromptComesBeforeTheRead", _test.TestAPromptComesBeforeTheRead},

	{"TestASignalLeavesWhatWasPrinted", _test.TestASignalLeavesWhatWasPrinted},

	{"TestOverloadContractRulings", _test.TestOverloadContractRulings},

	{"TestParameterPropertyMutants", _test.TestParameterPropertyMutants},

	{"TestParameterPropertyOwnershipMutant", _test.TestParameterPropertyOwnershipMutant},

	{"TestParserNamespaceReceiver", _test.TestParserNamespaceReceiver},

	{"TestParserNamespaceClass", _test.TestParserNamespaceClass},

	{"TestParserCallableNamespace", _test.TestParserCallableNamespace},

	{"TestParserCallableNamespaceMutant", _test.TestParserCallableNamespaceMutant},

	{"TestParserNamespaceClassRegistrationMutant", _test.TestParserNamespaceClassRegistrationMutant},

	{"TestParserNamespaceReceiverMutant", _test.TestParserNamespaceReceiverMutant},

	{"TestPredicateDirectionCountsAreRecorded", _test.TestPredicateDirectionCountsAreRecorded},

	{"TestPredicateMiscompileRefusals", _test.TestPredicateMiscompileRefusals},

	{"TestInUnionNarrowingIsRefused", _test.TestInUnionNarrowingIsRefused},

	{"TestPrivateGenericMethodOwnerMutant", _test.TestPrivateGenericMethodOwnerMutant},

	{"TestReadinessMutants", _test.TestReadinessMutants},

	{"TestUninitializedIsNotNullishMutant", _test.TestUninitializedIsNotNullishMutant},

	{"TestNonNullWeakFreedNamesExpression", _test.TestNonNullWeakFreedNamesExpression},

	{"TestLazyInitializerIsNotEagerMutant", _test.TestLazyInitializerIsNotEagerMutant},

	{"TestClosedNestedConstituentMutant", _test.TestClosedNestedConstituentMutant},

	{"TestRegexCycleFixtureHasItsNativeDependency", _test.TestRegexCycleFixtureHasItsNativeDependency},

	{"TestRegExpReplacementNodeMutants", _test.TestRegExpReplacementNodeMutants},

	{"TestRegExpReplacementTypeGuardMutants", _test.TestRegExpReplacementTypeGuardMutants},

	{"TestRepresentationClockSourceMutant", _test.TestRepresentationClockSourceMutant},

	{"TestRuntimeLastIndexOfMatchesNode", _test.TestRuntimeLastIndexOfMatchesNode},

	{"TestScannerNestedOverloadImplementationMutantIsCaught", _test.TestScannerNestedOverloadImplementationMutantIsCaught},

	{"TestScannerNestedReferenceMutants", _test.TestScannerNestedReferenceMutants},

	{"TestScannerNestedReferences", _test.TestScannerNestedReferences},

	{"TestNestedReferenceIdentityMutant", _test.TestNestedReferenceIdentityMutant},

	{"TestLongArgumentsLeaveTheStackItsLimit", _test.TestLongArgumentsLeaveTheStackItsLimit},

	{"TestSmallStacksStillPanic", _test.TestSmallStacksStillPanic},

	{"TestStage3EnumFallthrough", _test.TestStage3EnumFallthrough},

	{"TestStage3FixtureHook", _test.TestStage3FixtureHook},

	{"TestStatementsSmallRulings", _test.TestStatementsSmallRulings},

	{"TestStatementsSmallTypeScriptIncrement", _test.TestStatementsSmallTypeScriptIncrement},

	{"TestSwitchCaseDeadZoneStop", _test.TestSwitchCaseDeadZoneStop},

	{"TestSwitchCaseDeclarationMutants", _test.TestSwitchCaseDeclarationMutants},

	{"TestSwitchCaseOverloadIsNotYet", _test.TestSwitchCaseOverloadIsNotYet},

	{"TestSwitchTrailingEmptyMutant", _test.TestSwitchTrailingEmptyMutant},

	{"TestSyntaxModuleDeclarationMutants", _test.TestSyntaxModuleDeclarationMutants},

	{"TestSyntaxSubstrMutants", _test.TestSyntaxSubstrMutants},

	{"TestTypedArrayWriteStopIsPinned", _test.TestTypedArrayWriteStopIsPinned},

	{"TestTypedArrayWorkersStatsMatchesPlatforms", _test.TestTypedArrayWorkersStatsMatchesPlatforms},

	{"TestTypeOfConstructorMutant", _test.TestTypeOfConstructorMutant},

	{"TestTypeOfStringLiteralMutant", _test.TestTypeOfStringLiteralMutant},

	{"TestTypeOfNullMutant", _test.TestTypeOfNullMutant},

	{"TestTypeOfNullSlotPresenceMutant", _test.TestTypeOfNullSlotPresenceMutant},

	{"TestUnknownNarrowingMutants", _test.TestUnknownNarrowingMutants},

	{"TestRequiredViewFieldPrimitive", _test.TestRequiredViewFieldPrimitive},

	{"TestRequiredViewFieldOperandOnce", _test.TestRequiredViewFieldOperandOnce},

	{"TestNarrowedFieldUsesSharedReadiness", _test.TestNarrowedFieldUsesSharedReadiness},

	{"TestViewFieldInheritedStaticReadiness", _test.TestViewFieldInheritedStaticReadiness},

	{"TestDefaultTaggedSourceViews", _test.TestDefaultTaggedSourceViews},

	{"TestWASIShardUnion", _test.TestWASIShardUnion},

	{"TestWASIShardPlantedDisagreement", _test.TestWASIShardPlantedDisagreement},

	{"TestWASIShardPlantedFixture", _test.TestWASIShardPlantedFixture},

	{"TestWASIAgreesWithNode", _test.TestWASIAgreesWithNode},

	{"TestWASIOracleCatchesMutants", _test.TestWASIOracleCatchesMutants},

	{"TestWASIRunnerCatchesMutants", _test.TestWASIRunnerCatchesMutants},

	{"TestWASIEmission", _test.TestWASIEmission},

	{"TestWeakReadsUndefinedOnceFreed", _test.TestWeakReadsUndefinedOnceFreed},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/system-inc/adamic"
	testdeps.ImportPath = "github.com/system-inc/adamic/internal/oracle"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	_test.TestMain(m)
	os.Exit(int(reflect.ValueOf(m).Elem().FieldByName("exitCode").Int()))

}

