// Generated by adamic from main.a. Do not edit.

import { fileStatus, panic, programArguments, readDirectory, readTextFile, utf8At, utf8Length, writeTextFile } from 'adamic';

class AdamicClosure {
	constructor(code, cells) {
		this.code = code;
		this.cells = cells;
	}
}
const adamicTypeOf = (value) => value instanceof AdamicClosure ? 'function' : typeof value;
const adamicCollectionIterator = (collection, part) => { const iterator = collection[part](); return { next: new AdamicClosure(() => iterator.next(), []) }; };
const adamicJSONValue = (value) => {
 if (value instanceof AdamicClosure) return () => undefined;
 if (Array.isArray(value)) return value.map(adamicJSONValue);
 if (value !== null && typeof value === 'object' && !(value instanceof Map) && !(value instanceof Set)) {
  const copy = {};
  for (const key of Object.keys(value)) copy[key] = adamicJSONValue(value[key]);
  return copy;
 }
 return value;
};
const adamicJSONStringify = (value, replacer, space) => JSON.stringify(adamicJSONValue(value), replacer, space);
const adamicCall = (closure, values) => closure.code(closure, values);
const adamicCallee = (object, name) => Object.hasOwn(object, name) ? object[name] : { code: (closure, values) => object[name](object, ...values) };
const adamicOptionalCall = (object, name, values) => object === undefined ? undefined : adamicCall(adamicCallee(object, name), values());
const adamicVisit = (array, method, callback) => array[method]((element, index, all) => adamicCall(callback, [element, index, all]));
const adamicMap = (array, callback) => {
	const count = array.length;
	const mapped = [];
	for (let index = 0; index < count; index++) {
		if (index >= array.length) panic('map: the array shrank while it was being mapped');
		mapped.push(adamicCall(callback, [array[index], index, array]));
	}
	return mapped;
};
const adamicFind = (array, method, callback) => {
	const count = array.length;
	const last = method === 'findLast' || method === 'findLastIndex';
	const valueResult = method === 'find' || method === 'findLast';
	for (let step = 0; step < count; step++) {
		const index = last ? count - 1 - step : step;
		if (index >= array.length) panic(`${method}: the array shrank while it was being searched`);
		const element = array[index];
		if (adamicCall(callback, [element, index, array])) return valueResult ? element : index;
	}
	return valueResult ? undefined : -1;
};
const adamicCollectionVisit = (collection, callback) => collection.forEach((value, key, all) => adamicCall(callback, [value, key, all]));
const adamicFrom = (length, callback) => Array.from({ length }, (element, index) => adamicCall(callback, [element, index]));
const adamicDefinedNull = (value, message) => value === null ? panic(message) : value;
const adamicDefined = (value, message) => value === undefined ? panic(message) : value;
const adamicSort = (array, callback) => array.sort((left, right) => adamicCall(callback, [left, right]));
const adamicReduce =(array, callback, initial) => array.reduce((carried, element, index, all) => adamicCall(callback, [carried, element, index, all]), initial);
const adamicSetIndex = (array, index, value) => {
	if (!(Number.isInteger(index) && index >= 0 && index < array.length)) panic(`index ${index} is outside an array of length ${array.length}`);
	array[index] = value;
};
const adamicCast = (object, field, allowed, message) => allowed.includes(object[field]) ? object : panic(message);
const adamicUnready = (name) => { throw new ReferenceError(`Cannot access '${name}' before initialization`); };

let local_0_ruleName;
let ready_0 = false;
let local_1_syntaxKinds;
let ready_1 = false;
let local_2_ruleName;
let ready_2 = false;
let local_3_syntaxKinds;
let ready_3 = false;
let local_4_ruleName;
let ready_4 = false;
let local_5_syntaxKinds;
let ready_5 = false;
let local_6_ruleName;
let ready_6 = false;
let local_7_syntaxKinds;
let ready_7 = false;
let local_8_ruleName;
let ready_8 = false;
let local_9_syntaxKinds;
let ready_9 = false;
let local_10_ruleName;
let ready_10 = false;
let local_11_syntaxKinds;
let ready_11 = false;

local_0_ruleName = "@typescript-eslint/non-nullable-type-assertion-style";
ready_0 = true;
local_1_syntaxKinds = ["AsExpression", "TypeAssertionExpression"];
ready_1 = true;
local_2_ruleName = "no-invalid-regexp";
ready_2 = true;
local_3_syntaxKinds = ["CallExpression", "NewExpression"];
ready_3 = true;
local_4_ruleName = "no-label-var";
ready_4 = true;
local_5_syntaxKinds = ["LabeledStatement"];
ready_5 = true;
local_6_ruleName = "no-misleading-character-class";
ready_6 = true;
local_7_syntaxKinds = ["RegularExpressionLiteral", "SourceFile"];
ready_7 = true;
local_8_ruleName = "prefer-const";
ready_8 = true;
local_9_syntaxKinds = ["VariableDeclarationList"];
ready_9 = true;
local_10_ruleName = "radix";
ready_10 = true;
local_11_syntaxKinds = ["CallExpression"];
ready_11 = true;
console.log(((local_0_ruleName + "\u0009") + local_1_syntaxKinds.join(",")));
console.log(((local_2_ruleName + "\u0009") + local_3_syntaxKinds.join(",")));
console.log(((local_4_ruleName + "\u0009") + local_5_syntaxKinds.join(",")));
console.log(((local_6_ruleName + "\u0009") + local_7_syntaxKinds.join(",")));
console.log(((local_8_ruleName + "\u0009") + local_9_syntaxKinds.join(",")));
console.log(((local_10_ruleName + "\u0009") + local_11_syntaxKinds.join(",")));
