#!/usr/bin/env python3
from pathlib import Path
import json
root=Path(__file__).resolve().parents[2]
core=[('ABI','abi','bridgeABI'),('InputLength','input-length','bridgeInputLength'),('UnlinkedBuild','unlinked-build','bridgeUnlinkedBuild'),('UnlinkedC','unlinked-c','bridgeUnlinkedC'),('UnlinkedJavaScript','unlinked-js','bridgeUnlinkedJavaScript'),('OutputLength','output-length','bridgeOutputLength'),('StaleHandle','stale-handle','bridgeStale'),('Linkage','linkage','bridgeLinkage'),('OutputFree','output-free','bridgeOutputFree'),('Region','region','bridgeRegion'),('RegionOwnership','region-ownership','bridgeRegionOwnership')]
rows=[dict(name='TestBridge'+name,piece=piece,file='',round=0,helper=helper) for name,piece,helper in core]
for label,file in [('Sample','sample.ts'),('Checker','checker.ts'),('Parser','parser.ts'),('Types','types.ts'),('Utilities','utilities.ts')]:
 for name,piece,helper,round in [('Oracle','oracle','bridgeOracle',0),('TimingRound1','timing-1','bridgeTiming',1),('TimingRound2','timing-2','bridgeTiming',2),('TimingRound3','timing-3','bridgeTiming',3),('WrongPosition','wrong-position','bridgeWrongPosition',0)]:
  rows.append(dict(name='TestBridge'+name+label,piece=piece,file=file,round=round,helper=helper))
text='// Code generated by review/test-split-bridge/generate.py; DO NOT EDIT.\npackage tsgo_test\n\nimport "testing"\n\nvar bridgeCases = []bridgeCase{\n'
for r in rows:text+=' {'+','.join(json.dumps(r[k]) for k in ['name','piece','file'])+','+str(r['round'])+','+r['helper']+'},\n'
text+='}\n\nvar bridgeBindings = []func(*testing.T){\n'+''.join(' '+r['name']+',\n' for r in rows)+'}\n\n'
for index,r in enumerate(rows):text+='func '+r['name']+'(t *testing.T) { runBridgeCase(t,'+str(index)+') }\n'
(root/'bridge/tsgo/registered_units_test.go').write_text(text)
(root/'review/test-split-bridge/units.json').write_text(json.dumps(rows,indent=2)+'\n')
