import pathlib,json,re,difflib
root=pathlib.Path('/workspace/adamic');ev=root/'review/test-audit/stage1-cohere-markdownblocks-mdast_errors';base='stage1/cohere/markdownblocks/';seeds=['testdata/mdast_probe.ts','testdata/path_probe.ts','testdata/prefix_probe.ts','testdata/list_probe.ts','gaps/6_uninitialized_optional_string.ts'];visited=set(); pending=[root/(base+x)for x in seeds];inventory=[]
while pending:
 p=pending.pop()
 if p in visited or not p.exists():continue
 visited.add(p); text=p.read_text()
 for i,line in enumerate(text.splitlines(),1):
  if re.match(r'(?:export )?function\s+\w+\(',line.strip())or re.match(r'^    (?:private )?\w+\([^;]*$',line):inventory.append(str(p.relative_to(root))+':'+str(i)+' '+line.strip())
 for imp in re.findall(r"from ['\"]([^'\"]+)['\"]",text):
  if imp.startswith('.'):pending.append((p.parent/imp).resolve())
(ev/'function-inventory.txt').write_text('Conservative transitive source inventory from the five entries named by these tests. Includes methods not dynamically verified as reached; no mutant is drawn from an unverified method. Direct mutation sites are compile root construction, AstPath root observation, preprocess NUL mapping, printQuote marker, and entry probes. Go preflight has no Adamic entry. Construction/check functions are listed separately in menu.json.\n'+'\n'.join(sorted(inventory))+'\n');(ev/'source-files.json').write_text(json.dumps(sorted(str(p.relative_to(root))for p in visited),indent=2))
def item(mid,file,old,new,kind,members):
 p=root/(base+file);s=p.read_text();assert s.count(old)==1,(mid,s.count(old));return dict(id=mid,file=str(p.relative_to(root)),line=s[:s.index(old)].count('\n')+1,old=old,new=new,kind=kind,members=members)
mdast=['TestMdastMalformedEvents_Setup','TestMdastIdentifierWitnesses','TestNativeMdastConstruction'];quote=['TestMarkdownQuoteLayoutNative','TestMarkdownQuoteLayout_Setup','TestMarkdownQuoteLayoutUnion']+['TestMarkdownQuoteLayout_%03d'%i for i in range(12)];preflight=['TestWholeDocumentOraclePreflightUnion']+['TestWholeDocumentOraclePreflight_%03d'%i for i in range(4)]
menu=[item('M1','mdastCompile.ts',"const root = this.arena.add('root', true, false);","const root = this.arena.add('root', false, false);",'change constant',mdast),item('M2','astPath.ts','return this.stack.length === 1;','return this.stack.length === 0;','change constant',['TestMarkdownAstPath']),item('M3','preprocess.ts','code: 65533','code: 65534','change constant',['TestMarkdownParserPrefixes']),item('M4','quotes.ts',"arena.text('> ')","arena.text('# ')",'change constant',quote)]
menu += [item('P1','mdastCompile.ts','compile(): MdastArena {','compile(): MdastArena {\n        return this.arena;','empty entry',mdast),item('P2','pathObserve.ts','export function observePath(path: AstPath): string {',"export function observePath(path: AstPath): string {\n    return '';",'empty entry',['TestMarkdownAstPath']),item('P3','preprocess.ts','export function preprocess(value: string): ChunkInterface[] {','export function preprocess(value: string): ChunkInterface[] {\n    return [];','empty entry',['TestMarkdownParserPrefixes']),item('P4','quotes.ts','export function printQuote(arena: DocumentArena, children: readonly ListBlockInterface[]): number {','export function printQuote(arena: DocumentArena, children: readonly ListBlockInterface[]): number {\n    return 0;','empty entry',quote)]
menu += [item('W1','preflight_shards_test.go','if !bytes.Equal([]byte(actual.Off), []byte(expected.Off)) {','if false {','weaken witnessed comparison',preflight),item('W2','preflight_shards_test.go','if actual.Off != nodeAnswers[index].Off {','if false {','weaken witnessed comparison',['TestWholeDocumentOraclePreflightMutants']),item('W3','quote_layout_shards_test.go','return bytes.Equal(actual, expected)','return true','weaken witnessed comparison',quote),item('G2','quote_layout_shards_test.go','products.sanitized = filepath.Join(dir, "port")','products.sanitized = ""','drop constructed product value',['TestMarkdownQuoteLayoutNative','TestMarkdownQuoteLayout_Setup'])]
# Two append occurrences require scoped generated-loop statement edit rather than a generic anchor.
menu.append(item('G3','sample_test.go','if included[gatesample.GeneratedKey(index)] {','if included[gatesample.GeneratedKey(index)] && false {','drop generated input condition',['TestSampleRetainsFixedMarkdownInputs','TestGeneratedLayoutSelection']))
menu.append(item('G1','malformed_events_independent_test.go','"-overlay="+overlayPath, "-o", filepath.Join(dir, "go-errors")','"-overlay="+overlayPath, "-invalid-output-flag", filepath.Join(dir, "go-errors")','change construction build option',['TestMdastMalformedEvents_Setup']))
originals={m['file']:(root/m['file']).read_text()for m in menu};(ev/'originals.json').write_text(json.dumps(originals));(ev/'menu.json').write_text(json.dumps(menu,indent=2))
for m in menu:
 s=originals[m['file']];changed=s.replace(m['old'],m['new']);(ev/(m['id']+'.diff')).write_text(''.join(difflib.unified_diff(s.splitlines(True),changed.splitlines(True),fromfile='a/'+m['file'],tofile='b/'+m['file'])))
print('Menu fixed',len(menu))
