import pathlib,json,subprocess
p=pathlib.Path('/workspace/adamic/review/test-defend/internal-native-radix');results=json.loads((p/'results.json').read_text());plan=json.loads((p/'plan.json').read_text());matrix=json.loads((p/'matrix.json').read_text());coverage=json.loads((p/'coverage-runs.json').read_text());base=subprocess.check_output(['git','rev-parse','HEAD']).decode().strip()
assert len([x for x in matrix if x['id']=='R3'])>0
assert subprocess.check_output(['git','diff','--name-only','--','internal']).decode()==''
for m in plan:subprocess.run(['git','apply','--check',str(p/'diffs'/(m['id']+'.diff'))],check=True)
assert all(x['exit']==0 for x in coverage)
for m in plan:assert all(x['exit']==0 for x in json.loads((p/(m['id']+'-validation.json')).read_text()))
issues=['Whole-package clean baseline cooked at 90.054 seconds without an assertion failure. The bounded 65-row clean control subsequently passed. Wider compiler/runtime fixtures remain outside this matrix; kills there are unknown.', 'Cold instrumented Go compilation exceeded the 120-second outer timeout before tests started. A warm retry produced four green profiles. Go coverage alone measures compiler/build code, so LLVM C instrumentation was needed to inspect runtime behavior.', 'LLVM emitted one-function mismatched-profile warnings for combined sanitized/release builds. Exports and raw profiles are retained. Segment coverage supplies leads, not independent uniqueness proof; covered ranges can include comments or braces.', 'The first bounded clean control failed on text file busy in a built-in witness. No mutant had run. Sources remained unchanged, temporaries moved from workspace storage to /tmp, and the complete control then passed in 61.858 seconds.', 'Two package tests were added since the audit: TestRegExpNativeStepLimitBoundary and TestRuntimeKeyKeepsBoundaries. Both are included in every matrix. No audited name vanished.', 'The brief truncates both prior evidence commands and abbreviates mutant IDs. Full audit reports and matrix were fetched and preserved; all final defense evidence comes from this session.', 'B2 exceeded 90 wall seconds including compilation, but its binary took 87.050 seconds. The initial commentary called it cooked; that was corrected. Only binary timeout or outer timeout is treated as incomplete.', 'The record benchmark shares much semantic work with RecordsAgainstNode, including a million-key workload. Its release allocator differs from sanitized record controls, but the chunk-sharing and slab probe rows also catch the allocator mutant.', 'B2 leaks map bucket storage and the benchmark passes. Sanitized record/map rows catch it. The benchmark name fits observational timing, but there is no speed threshold or unsanitized leak assertion, as its comment explicitly states.', 'RuntimeReleasePaths accurately checks release behavior: immediate live accounting, shared ownership, deep child cleanup, release and sanitized modes. R1 is a production accounting regression, not a proof that actual objects leaked. The runtime-count implementation is code under test; expected live values and sanitizer checks stay unchanged.', 'Production-mutant failures of built-in witness controls are recorded separately from the witnesses\' own quality. No witness/harness source was changed, and those failures are not the sole competing catch for either subject.', 'The session exceeded the approximate 20-minute budget because of cold coverage compilation, recovery of the executable filesystem failure and six matrices near a minute. All completed binary timings and command walls are recorded. No other package tests, test deletion, rewrite, PR or main push was performed.']
text='Neither row gained a unique catch in these six aimed mutants.\nTests remain unchanged; all standalone diffs compile and apply to starting origin/main.\nSources restored at '+base+'; complete bounded results follow.\n\n'+json.dumps(results,indent=2)+'\n\nCode and oracle: see method.md. RecordBenchmark compares native C record operations against live Node checksums and validates five timing fields. RuntimeReleasePaths compares production live counters with self-written values and uses ASan/UBSan plus fixed stdout. No oracle is mutated.\n\nMutants (origin/main sites):\n\n| ID | Site | Change |\n|---|---|---|\n'
for m in plan:text+='| '+m['id']+' | '+m['file']+':'+str(m['line'])+' | '+(m['old']+' -> '+m['new']).replace('\n',' ').replace('|','\\|')+' |\n'
text+='\nCoverage: Benchmark has zero Go blocks beyond StringEquality and 386 C segment lines beyond it. ReleasePaths has 21 Go blocks and 264 C segment lines beyond IteratorResultShape. The latter includes counted release and slab allocation; benchmarks include maps, records and bulk allocator reuse. Exact lists and raw Go/C profiles are preserved.\n\nPlaces the brief was unclear or cost time, and owner findings:\n\n'+'\n'.join('- '+s for s in issues)+'\n\nTiming: warm setup 0 seconds; npm reports 418 milliseconds; nproc 5. Completed coverage command walls '+str(round(sum(x['wall'] for x in coverage),3))+' seconds, plus the failed cold 120-second outer compilation. Bounded matrix/control command walls '+str(round(sum(x['wall'] for x in matrix),3))+' seconds. Binary timings are in matrix.json; cold runtime rebuilds are included, not separately phase-timed. Whole-package baseline 90.054 seconds. Session approximately 25 minutes.\n'
(p/'REPORT.md').write_text(text);(p/'validation.json').write_text(json.dumps(dict(starting_commit=base,source_restored=True,tests_changed=False,apply_checks=[x['id'] for x in plan],release_and_sanitized_clang_validation=[x['id'] for x in plan]),indent=2));print([(r['test'],r['defense']) for r in results])
