package native

import (
	"fmt"
	"github.com/system-inc/adamic/internal/ir"
	"strings"
)

// asyncC emits the closed primitive state graph. All locals live in the counted frame, so no
// synchronous borrow/reuse/region proof is used across suspension.
func asyncC(program *ir.Program) string {
	var out strings.Builder
	fmt.Fprintf(&out, "// Generated by adamic from %s.\n#include \"async.h\"\n#include \"library_errors.h\"\n#include <string.h>\n#include <math.h>\n", program.Source)
	for index, value := range program.Strings {
		if len(value) <= longestLiteral {
			fmt.Fprintf(&out, "static adamic_string adamic_string_%d = ADAMIC_STRING(%s);\n", index, cString(value))
		} else {
			fmt.Fprintf(&out, "static const char adamic_bytes_%d[%d] = {%s};\n", index, len(value), cBytes(value))
			fmt.Fprintf(&out, "static adamic_string adamic_string_%d = ADAMIC_STRING_BYTES(adamic_bytes_%d, %d);\n", index, index, len(value))
		}
	}
	for index, fn := range program.Async.Functions {
		fmt.Fprintf(&out, "typedef struct { adamic_async_frame base;\n")
		for _, local := range fn.Locals {
			if program.Locals[local].Type != 0 {
				fmt.Fprintf(&out, "%s local_%d;\n", cType(program.Locals[local].Type), local)
			}
		}
		fmt.Fprintf(&out, "} adamic_generated_frame_%d;\n", index)
		fmt.Fprintf(&out, "static adamic_async_promise *adamic_async_start_%d(%s);\n", index, asyncParameters(program, fn))
	}
	for index, fn := range program.Async.Functions {
		fmt.Fprintf(&out, "static void adamic_async_children_%d(adamic_async_frame *base, void (*drop)(void *)) {\n adamic_generated_frame_%d *frame = (void *)base; (void)frame; (void)drop;\n", index, index)
		for _, local := range fn.Locals {
			if program.Locals[local].Type.IsReference() {
				fmt.Fprintf(&out, "drop(frame->local_%d);\n", local)
			}
		}
		out.WriteString("}\n")
		e := &emitter{program: program, indent: 1, reuse: &reusePlan{}, regions: &regionPlan{}, scopes: [][]string{nil}}
		for _, local := range fn.Locals {
			fmt.Fprintf(&out, "#define %s (frame->local_%d)\n", e.localName(local), local)
		}
		fmt.Fprintf(&out, "static void adamic_async_resume_%d(adamic_async_frame *base, adamic_value resumed, bool rejected) {\n adamic_generated_frame_%d *frame = (void *)base; (void)frame; (void)resumed;\n if (rejected) { adamic_async_settle(base->output, resumed, true, true); return; }\n switch (base->state) {\n", index, index)
		for stateIndex, state := range fn.States {
			e.line("case %d: {", stateIndex)
			if stateIndex > 0 {
				prev := fn.States[stateIndex-1]
				if prev.Await != nil && prev.Target >= 0 && prev.Await.Of != 0 {
					local := prev.Target
					value := fmt.Sprintf("resumed.%s", member(prev.Await.Of))
					if prev.Await.Of.IsReference() {
						value = fmt.Sprintf("(%s)adamic_retain(%s)", cType(prev.Await.Of), value)
					}
					e.line("%s = %s;", e.localName(local), value)
				}
			}
			for _, statement := range state.Body {
				switch statement := statement.(type) {
				case ir.Declare:
					value := e.value(statement.Value)
					if statement.Value.Type().IsReference() {
						value = e.kept(value)
					}
					e.line("%s = %s;", e.localName(statement.Local), value)
					e.end()
				case ir.WriteLine:
					e.statement(statement)
				default:
					panic("native async: unknown lowered statement")
				}
			}
			if state.Await != nil {
				p := e.temporary()
				wait := state.Await
				if wait.Function >= 0 {
					args := []string{}
					for _, arg := range wait.Arguments {
						args = append(args, e.value(arg))
					}
					e.line("adamic_async_promise *%s = adamic_async_start_%d(%s);", p, wait.Function, strings.Join(args, ", "))
				} else {
					value := "(adamic_value){.number = 0}"
					if wait.Value != nil {
						value = fmt.Sprintf("(adamic_value){.%s = %s}", member(wait.Of), e.value(wait.Value))
					}
					e.line("adamic_async_promise *%s = adamic_async_new();", p)
					e.line("adamic_async_settle(%s, %s, %t, false);", p, value, wait.Of.IsReference())
				}
				e.line("base->state = %d;", stateIndex+1)
				e.line("adamic_async_await(base, %s);", p)
				e.line("adamic_release(%s);", p)
				e.end()
				e.line("return;")
			} else {
				value := "(adamic_value){.number = 0}"
				refs := false
				reject := state.Throw != nil
				expr := state.Result
				if reject {
					expr = state.Throw
				}
				if expr != nil {
					value = fmt.Sprintf("(adamic_value){.%s = %s}", member(expr.Type()), e.value(expr))
					refs = expr.Type().IsReference()
				}
				e.line("adamic_async_settle(base->output, %s, %t, %t);", value, refs, reject)
				e.end()
				e.line("base->state = %d; return;", len(fn.States))
			}
			e.line("}")
		}
		e.line("default: adamic_unreachable();")
		out.WriteString(e.out.String())
		out.WriteString("}\n}\n")
		for _, local := range fn.Locals {
			fmt.Fprintf(&out, "#undef %s\n", e.localName(local))
		}
		fmt.Fprintf(&out, "static adamic_async_promise *adamic_async_start_%d(%s) {\n ADAMIC_CHECK_STACK();\n adamic_generated_frame_%d *frame = adamic_allocate(sizeof *frame, adamic_kind_async_frame);\n memset((char *)frame + sizeof(adamic_heap), 0, sizeof *frame - sizeof(adamic_heap));\n adamic_async_promise *output = adamic_async_new();\n frame->base.output = adamic_retain(output);\n frame->base.resume = adamic_async_resume_%d; frame->base.children = adamic_async_children_%d;\n", index, asyncParameters(program, fn), index, index, index)
		for position, local := range fn.Parameters {
			value := fmt.Sprintf("argument_%d", position)
			if program.Locals[local].Type.IsReference() {
				value = "adamic_retain(" + value + ")"
			}
			fmt.Fprintf(&out, "frame->local_%d = %s;\n", local, value)
		}
		fmt.Fprintf(&out, "adamic_async_resume_%d(&frame->base, (adamic_value){.number = 0}, false);\n adamic_release(frame); return output;\n}\n", index)
	}
	fmt.Fprintf(&out, "int main(int argc, char **argv) {\n adamic_start(argc, argv);\n adamic_async_promise *root = adamic_async_start_%d();\n adamic_async_run();\n if (root->rejected) {\n adamic_string *reason = root->value.reference;\n if (reason->length == 0) adamic_panic(\"Error\", 5);\n static adamic_string prefix = ADAMIC_STRING(\"Error: \");\n adamic_string *message = adamic_string_concat(2, (adamic_string *[]){&prefix, root->value.reference});\n adamic_panic(message->bytes, message->length);\n }\n adamic_release(root); return 0;\n}\n", program.Async.Entry)
	return out.String()
}
func asyncParameters(program *ir.Program, fn ir.AsyncFunction) string {
	parts := []string{}
	for index, local := range fn.Parameters {
		parts = append(parts, fmt.Sprintf("%s argument_%d", cType(program.Locals[local].Type), index))
	}
	if len(parts) == 0 {
		return "void"
	}
	return strings.Join(parts, ", ")
}
