package native

import (
	"fmt"
	"github.com/system-inc/adamic/internal/ir"
	"strings"
)

// C is a program as one C translation unit, to be compiled with the runtime.
//
// Expressions are evaluated in JavaScript's order. Each one yields a C expression that stays valid
// to the end of its statement: a constant, a local nothing can change mid-statement, or a temporary.
// A global is copied before anything after it runs, since a call may change it. &&, || and ?: become
// real branches whenever their later operands have work to do, so what JavaScript doesn't evaluate,
// Adamic doesn't either.
//
// Every string reference is released exactly once. A string made mid-statement lives in a temporary
// released when the statement ends; a variable takes its own reference (retain) and gives it back
// when reassigned or when its scope ends, by break, continue or return included. Stage 0 pays a
// retain and a release on every assignment for that simplicity; removing them where they cancel is
// the memory model's work, measured against this.
func C(program *ir.Program) string {
	if program.Async != nil {
		return asyncC(program)
	}
	return cProgram(program, -1)
}

func cProgram(program *ir.Program, handler int) string {
	// Borrowed elements first: reuse must see the variables they mark Borrowed.
	elementBorrows, lending := planElementBorrows(program)
	emitter := &emitter{program: program, reuse: planReuse(program, lending), regions: planRegions(program), elementBorrows: elementBorrows}
	var builder strings.Builder
	fmt.Fprintf(&builder, "// Generated by adamic from %s. Do not edit.\n\n#include \"adamic.h\"\n\n#include <math.h>\n#include <stdbool.h>\n\n", program.Source)
	for index, value := range program.Strings {
		if len(value) <= longestLiteral {
			fmt.Fprintf(&builder, "static adamic_string adamic_string_%d = ADAMIC_STRING(%s);\n", index, cLiteral(value))
			continue
		}
		// Longer than a C string literal may be under -pedantic: its bytes as an array instead.
		fmt.Fprintf(&builder, "static const char adamic_bytes_%d[%d] = {%s};\n", index, len(value), cBytes(value))
		fmt.Fprintf(&builder, "static adamic_string adamic_string_%d = ADAMIC_STRING_BYTES(adamic_bytes_%d, %d);\n", index, index, len(value))
	}
	if len(program.Strings) > 0 {
		builder.WriteString("\n")
	}

	for _, regex := range program.Regexps {
		builder.WriteString(regex.Declarations)
	}
	globals := false
	for index, local := range program.Locals {
		if !local.Global {
			continue
		}
		globals = true
		fmt.Fprintf(&builder, "static %s %s = %s;\n", cType(local.Type), emitter.localName(index), zero(local.Type))
		fmt.Fprintf(&builder, "static bool %s = false;\n", readyName(index))
	}
	if globals {
		builder.WriteString("\n")
	}

	// Bodies first: the shapes and field caches they use are found while they're emitted.
	bodies := strings.Builder{}
	for index, function := range program.Functions {
		for _, inRegion := range emitter.regionVariants(index) {
			emitter.inRegion = inRegion
			fmt.Fprintf(&bodies, "static %s {\n", emitter.signature(index))
			emitter.indent = 1
			emitter.functionIndex = index
			emitter.functionBody(function)
			bodies.WriteString(emitter.out.String())
			emitter.out.Reset()
			bodies.WriteString("}\n\n")
		}
	}
	emitter.inRegion = false
	bodies.WriteString("int main(int argc, char **argv) {\n")
	bodies.WriteString("\tadamic_start(argc, argv);\n")
	emitter.indent = 1
	emitter.block(program.Main, nil)
	if handler < 0 {
		emitter.releaseGlobals()
	}
	bodies.WriteString(emitter.out.String())
	bodies.WriteString("\treturn 0;\n}\n")
	if handler >= 0 {
		bodies.WriteString(emitter.requestABI(handler))
	}

	for index := range program.Functions {
		for _, inRegion := range emitter.regionVariants(index) {
			emitter.inRegion = inRegion
			fmt.Fprintf(&builder, "static %s;\n", emitter.signature(index))
		}
	}
	emitter.inRegion = false
	if len(program.Functions) > 0 {
		builder.WriteString("\n")
	}
	emitter.prepareClassShapes()
	// After the prototypes: a sort's comparator adapter calls one of the program's functions.
	for _, declaration := range emitter.declarations {
		builder.WriteString(declaration)
		builder.WriteString("\n")
	}
	if len(emitter.declarations) > 0 {
		builder.WriteString("\n")
	}
	emitter.classDeclarations(&builder)
	builder.WriteString(bodies.String())
	return builder.String()
}

// longestLiteral is the longest string literal C11 promises to compile (5.2.4.1: 4,095 characters),
// which clang holds a program to under -pedantic. A longer string is written as bytes (cBytes).
const longestLiteral = 4095

// cBytes is a string's bytes as an array initializer, as many as it has, with no terminator.
func cBytes(value string) string {
	var builder strings.Builder
	for index := 0; index < len(value); index++ {
		if index > 0 {
			builder.WriteString(",")
			if index%32 == 0 {
				builder.WriteString("\n\t")
			}
		}
		fmt.Fprintf(&builder, "%d", value[index])
	}
	return builder.String()
}

type emitter struct {
	program *ir.Program
	out     strings.Builder
	indent  int

	// reuse is where objects are reused in place (reuse.go), at names the statement being emitted,
	// where it stands in its slice, and taking is the spread whose replaced fields are being
	// evaluated, if any.
	reuse  *reusePlan
	at     *ir.Statement
	taking *taking

	// regions is where values are allocated in a statement's region (region.go). functionIndex is
	// the function being emitted, inRegion whether it's the version of a fresh function that makes
	// its result in a region, regionValues the C names of values known to be in one, statementRegion the C name of the region of the statement being
	// emitted, if it has one, regionCallDepth and regionCallArgument the depth of the call a parent
	// hands a region and that region, and regionLiteralDepth the depth of the object literal a fresh
	// function's return allocates in its region.
	regions            *regionPlan
	elementBorrows     map[*ir.Statement]bool
	mostlyNull         map[string]bool
	functionIndex      int
	inRegion           bool
	regionValues       map[string]bool
	statementRegion    string
	regionCallDepth    int
	regionCallArgument string
	regionLiteralDepth int

	// depth is how deep value is in the expression being emitted, lendAt the depth whose reads a
	// consumer lends without a count, lendable whether the expression being evaluated is one of
	// them, self whether its own value was lent, and lent whether one of the current expression's
	// operands was (borrow.go).
	depth    int
	lendAt   int
	lendable bool
	self     bool
	lent     bool

	// temporaries counts the C temporaries made so far, for unique names.
	temporaries int

	// owned is the string temporaries the statement being emitted releases when it ends.
	owned []string

	// scopes holds, innermost last, the references (C names) each open scope releases when it ends.
	scopes [][]string

	// loops holds, innermost last, each open loop's scope depth and continue label, and whether
	// anything jumps to that label.
	loops []*loop

	// breakables holds, innermost last, each open loop or switch and its cleanup depth.
	breakables []*breakable

	// declarations are file-scope lines the bodies need: object shapes and field caches.
	declarations []string

	// shapes names each object layout already declared, by its fields.
	shapes map[string]string
	// thunks are the methods whose adamic_method is declared (methodThunk).
	thunks map[int]bool

	// fieldOffsets proves uniform named slots across the program (fields.go).
	fieldOffsets map[string]int

	// initialized is every global main declares, in the order their declarations run: modules in
	// ECMAScript's order, and each module's from the top.
	initialized []int

	// handlers are the tries open in the function being emitted, innermost last, and outerOwned what
	// the statement owned outside each aside being emitted (exceptions.go).
	handlers   []*handler
	outerOwned [][]string

	// function is the function being emitted, and functionDepth the scope depth its body starts at.
	function      *ir.Function
	functionDepth int
}

func (e *emitter) line(format string, arguments ...any) {
	e.out.WriteString(strings.Repeat("\t", e.indent))
	fmt.Fprintf(&e.out, format, arguments...)
	e.out.WriteString("\n")
}

func (e *emitter) temporary() string {
	e.temporaries++
	return fmt.Sprintf("adamic_temporary_%d", e.temporaries)
}
