package native

import (
	"fmt"
	"github.com/system-inc/adamic/internal/ir"
	"sort"
	"strings"
)

// C is a program as one C translation unit, to be compiled with the runtime.
//
// Expressions are evaluated in JavaScript's order. Each one yields a C expression that stays valid
// to the end of its statement: a constant, a local nothing can change mid-statement, or a temporary.
// A global is copied before anything after it runs, since a call may change it. &&, || and ?: become
// real branches whenever their later operands have work to do, so what JavaScript doesn't evaluate,
// Adamic doesn't either.
//
// Every string reference is released exactly once. A string made mid-statement lives in a temporary
// released when the statement ends; a variable takes its own reference (retain) and gives it back
// when reassigned or when its scope ends, by break, continue or return included. Stage 0 pays a
// retain and a release on every assignment for that simplicity; removing them where they cancel is
// the memory model's work, measured against this.
func C(program *ir.Program) string {
	return cProgram(program, -1)
}

func cProgram(program *ir.Program, handler int) string {
	emitter := &emitter{program: program}
	if program.HasPromises() {
		// Suspension ownership is conservative until the shared analyses prove it.
		emitter.reuse = &reusePlan{}
		emitter.regions = &regionPlan{program: program}
	} else {
		elementBorrows, lending := planElementBorrows(program)
		emitter.elementBorrows = elementBorrows
		emitter.reuse = planReuse(program, lending)
		emitter.regions = planRegions(program)
	}
	var builder strings.Builder
	fmt.Fprintf(&builder, "// Generated by adamic from %s. Do not edit.\n\n#include \"adamic.h\"\n\n#include <math.h>\n#include <stdbool.h>\n\n", program.Source)
	if program.HasPromises() {
		builder.WriteString("#include \"async.h\"\n#include <string.h>\n")
	}
	seenStrings := map[string]bool{}
	for _, value := range program.Strings {
		if seenStrings[value] {
			continue
		}
		seenStrings[value] = true
		if len(value) <= longestLiteral {
			fmt.Fprintf(&builder, "static adamic_string %s = ADAMIC_STRING(%s);\n", stringName(value), cLiteral(value))
			continue
		}
		// Longer than a C string literal may be under -pedantic: its bytes as an array instead.
		fmt.Fprintf(&builder, "static const char %s_bytes[%d] = {%s};\n", stringName(value), len(value), cBytes(value))
		fmt.Fprintf(&builder, "static adamic_string %s = ADAMIC_STRING_BYTES(%s_bytes, %d);\n", stringName(value), stringName(value), len(value))
	}
	if len(program.Strings) > 0 {
		builder.WriteString("\n")
	}

	seenRegexps := map[string]bool{}
	for index := range program.Regexps {
		name := emitter.regexName(index)
		if !seenRegexps[name] {
			builder.WriteString(emitter.regexDeclarations(index))
			seenRegexps[name] = true
		}
	}
	globals := false
	for index, local := range program.Locals {
		if !local.Global {
			continue
		}
		globals = true
		fmt.Fprintf(&builder, "static %s %s = %s;\n", cType(local.Type), emitter.localName(index), zero(local.Type))
		fmt.Fprintf(&builder, "static bool %s = false;\n", emitter.readyName(index))
	}
	if globals {
		builder.WriteString("\n")
	}

	// Bodies first: the shapes and field caches they use are found while they're emitted.
	bodies := strings.Builder{}
	emittedBodies := map[string]string{}
	for index, function := range program.Functions {
		if function.Async {
			bodies.WriteString(emitter.asyncFunction(index))
			continue
		}
		for _, inRegion := range emitter.regionVariants(index) {
			emitter.inRegion = inRegion
			emitter.resetCounters()
			signature := emitter.signature(index)
			emitter.indent = 1
			emitter.functionIndex = index
			emitter.functionBody(function)
			body := emitter.out.String()
			emitter.out.Reset()
			name := emitter.functionName(index)
			if inRegion {
				name = emitter.regionFunctionName(index)
			}
			definition := "static " + signature + " {\n" + body + "}\n\n"
			if previous, found := emittedBodies[name]; found {
				if previous != definition {
					panic("native: conflicting definitions for stable symbol " + name)
				}
			} else {
				emittedBodies[name] = definition
				fmt.Fprintf(&bodies, "// adamic-module %q\n", function.Source.Module)
				bodies.WriteString(definition)
			}
		}
	}
	emitter.inRegion = false
	emitter.resetCounters()
	emitter.indent = 1
	emitter.asyncMain()
	// The async scheduler and its root stay in main, outside initializer chunks.
	prefix := emitter.out.String()
	emitter.out.Reset()
	bodies.WriteString(emitter.moduleMain())
	bodies.WriteString("int main(int argc, char **argv) {\n\tadamic_start(argc, argv);\n")
	bodies.WriteString(prefix)
	if program.HasPromises() && program.AsyncEntry == 0 {
		emitter.line("adamic_async_run();")
	}
	if handler < 0 {
		emitter.releaseGlobals()
	}

	bodies.WriteString(emitter.out.String())
	bodies.WriteString("\treturn 0;\n}\n")
	if handler >= 0 {
		bodies.WriteString(emitter.requestABI(handler))
	}

	prototypes := map[string]bool{}
	for index := range program.Functions {
		for _, inRegion := range emitter.regionVariants(index) {
			emitter.inRegion = inRegion
			signature := emitter.signature(index)
			if !prototypes[signature] {
				fmt.Fprintf(&builder, "static %s;\n", signature)
				prototypes[signature] = true
			}
		}
	}
	emitter.inRegion = false
	if len(program.Functions) > 0 {
		builder.WriteString("\n")
	}
	emitter.prepareClassShapes()
	// After the prototypes: a sort's comparator adapter calls one of the program's functions.
	for _, declaration := range emitter.declarations {
		builder.WriteString(declaration)
		builder.WriteString("\n")
	}
	if len(emitter.declarations) > 0 {
		builder.WriteString("\n")
	}
	emitter.classDeclarations(&builder)
	// Validate every emitted layout, including public class shapes that need no allocation.
	checks := strings.Builder{}
	checks.WriteString("#ifdef ADAMIC_COUNT\n")
	shapeNames := make([]string, 0, len(emitter.shapes))
	for _, name := range emitter.shapes {
		shapeNames = append(shapeNames, name)
	}
	sort.Strings(shapeNames)
	for _, name := range shapeNames {
		fmt.Fprintf(&checks, "\tadamic_shape_check(&%s);\n", name)
	}
	checks.WriteString("#endif\n")
	builder.WriteString(strings.Replace(bodies.String(), "\tadamic_start(argc, argv);\n", "\tadamic_start(argc, argv);\n"+checks.String(), 1))
	return builder.String()
}

// longestLiteral is the longest string literal C11 promises to compile (5.2.4.1: 4,095 characters),
// which clang holds a program to under -pedantic. A longer string is written as bytes (cBytes).
const longestLiteral = 4095

// cBytes is a string's bytes as an array initializer, as many as it has, with no terminator.
func cBytes(value string) string {
	var builder strings.Builder
	for index := 0; index < len(value); index++ {
		if index > 0 {
			builder.WriteString(",")
			if index%32 == 0 {
				builder.WriteString("\n\t")
			}
		}
		fmt.Fprintf(&builder, "%d", value[index])
	}
	return builder.String()
}

type emitter struct {
	program           *ir.Program
	counterModes      map[int]bool
	doubleCounterPath bool
	out               strings.Builder
	indent            int

	// reuse is where objects are reused in place (reuse.go), at names the statement being emitted,
	// where it stands in its slice, and taking is the spread whose replaced fields are being
	// evaluated, if any.
	reuse  *reusePlan
	at     *ir.Statement
	taking *taking

	// regions is where values are allocated in a statement's region (region.go). functionIndex is
	// the function being emitted, inRegion whether it's the version of a fresh function that makes
	// its result in a region, regionValues the C names of values known to be in one, statementRegion the C name of the region of the statement being
	// emitted, if it has one, regionCallDepth and regionCallArgument the depth of the call a parent
	// hands a region and that region, and regionLiteralDepth the depth of the object literal a fresh
	// function's return allocates in its region.
	regions            *regionPlan
	elementBorrows     map[*ir.Statement]bool
	mostlyNull         map[string]bool
	functionIndex      int
	inRegion           bool
	regionValues       map[string]bool
	statementRegion    string
	regionCallDepth    int
	regionCallArgument string
	regionLiteralDepth int

	// depth is how deep value is in the expression being emitted, lendAt the depth whose reads a
	// consumer lends without a count, lendable whether the expression being evaluated is one of
	// them, self whether its own value was lent, and lent whether one of the current expression's
	// operands was (borrow.go).
	depth    int
	lendAt   int
	lendable bool
	self     bool
	lent     bool

	// temporaries and caches count names within the body being emitted.
	temporaries int
	caches      int
	mainModule  string

	// owned is the string temporaries the statement being emitted releases when it ends.
	owned []string

	// scopes holds, innermost last, the references (C names) each open scope releases when it ends.
	scopes [][]string

	// loops holds, innermost last, each open loop's scope depth and continue label, and whether
	// anything jumps to that label.
	loops []*loop

	// breakables holds, innermost last, each open loop or switch and its cleanup depth.
	breakables []*breakable

	// declarations are file-scope lines the bodies need: object shapes and field caches.
	declarations          []string
	generatedDeclarations map[string]bool
	functionNames         map[int]string
	localNames            map[int]string

	// shapes names each object layout already declared, by its fields.
	shapes map[string]string
	// thunks are the methods whose adamic_method is declared (methodThunk).
	thunks map[string]bool

	// fieldOffsets proves uniform named slots across the program (fields.go).
	fieldOffsets map[string]int

	// initialized is every global main declares, in the order their declarations run: modules in
	// ECMAScript's order, and each module's from the top.
	initialized []int

	// handlers are the tries open in the function being emitted, innermost last, and outerOwned what
	// the statement owned outside each aside being emitted (exceptions.go).
	handlers   []*handler
	outerOwned [][]string

	// function is the function being emitted, and functionDepth the scope depth its body starts at.
	asyncSlots    map[int]int
	asyncHandler  string
	function      *ir.Function
	functionDepth int
}

func (e *emitter) line(format string, arguments ...any) {
	e.out.WriteString(strings.Repeat("\t", e.indent))
	fmt.Fprintf(&e.out, format, arguments...)
	e.out.WriteString("\n")
}

func (e *emitter) temporary() string {
	e.temporaries++
	if e.mainModule != "" {
		return fmt.Sprintf("adamic_temporary_%s_%d", e.mainModule, e.temporaries)
	}
	return fmt.Sprintf("adamic_temporary_%d", e.temporaries)
}

// resetCounters starts a function body (each region variant has its own counters).
func (e *emitter) resetCounters() {
	e.temporaries = 0
	e.caches = 0
	// Region facts use C temporary names, whose lifetime now ends with this body.
	e.regionValues = map[string]bool{}
}
