package native

import (
	"os"
	"os/exec"
	"path/filepath"
	"testing"
)

func TestSplitBuildPolicy(t *testing.T) {
	for _, override := range []string{"", "0", "1"} {
		t.Run("override="+override, func(t *testing.T) {
			t.Setenv("ADAMIC_NATIVE_SPLIT", override)
			for _, options := range []Options{{Release: true}, {Release: true, Split: true}, {Target: "wasm32-wasi", Sanitize: true, Split: true}} {
				if useSplit(options) {
					t.Fatalf("single-unit policy changed: %+v", options)
				}
			}
			for _, options := range []Options{{Sanitize: true}, {Count: true}, {Release: true, Count: true}, {Release: true, Sanitize: true}} {
				if useSplit(options) != (override != "0") {
					t.Fatalf("instrumented policy: %+v", options)
				}
			}
			if !useSplit(Options{Split: true}) {
				t.Fatal("explicit split ignored")
			}
			if useSplit(Options{}) != (override == "1") {
				t.Fatal("ordinary uninstrumented policy changed")
			}
		})
	}
}

func TestSplitJobsPolicy(t *testing.T) {
	t.Setenv("ADAMIC_NATIVE_JOBS", "")
	if jobs, err := splitJobs(Options{}); err != nil || jobs != 1 {
		t.Fatalf("go-test default: %d %v", jobs, err)
	}
	t.Setenv("ADAMIC_NATIVE_JOBS", "2")
	if jobs, err := splitJobs(Options{}); err != nil || jobs != 2 {
		t.Fatalf("environment jobs: %d %v", jobs, err)
	}
	t.Setenv("ADAMIC_NATIVE_JOBS", "invalid")
	if jobs, err := splitJobs(Options{Jobs: 3}); err != nil || jobs != 3 {
		t.Fatalf("explicit jobs: %d %v", jobs, err)
	}
	for _, invalid := range []string{"invalid", "-1"} {
		t.Setenv("ADAMIC_NATIVE_JOBS", invalid)
		if _, err := splitJobs(Options{}); err == nil {
			t.Fatalf("accepted jobs %q", invalid)
		}
	}
}

func TestSplitFrameTypedefPreservesState(t *testing.T) {
	t.Setenv("ADAMIC_NATIVE_SPLIT", "")
	source := `// Generated by adamic from split-default-frame. Do not edit.
#include "adamic.h"
#include <stdio.h>
typedef struct { int values[2]; int (*next)(void); } adamic_generated_frame;
static int state = 0;
static int next(void) { return ++state; }
static adamic_generated_frame frame = {{0, 0}, next};
int main(void) { frame.values[0] = frame.next(); frame.values[1] = frame.next(); printf("%d %d %d\n", frame.values[0], frame.values[1], state); return 0; }
`
	binary := filepath.Join(t.TempDir(), "probe")
	if err := Build(source, binary, Options{Sanitize: true}); err != nil {
		t.Fatal(err)
	}
	if output, err := exec.Command(binary).CombinedOutput(); err != nil || string(output) != "1 2 2\n" {
		t.Fatalf("shared frame state: %v %s", err, output)
	}
}

func TestParallelRuntimeKeepsArchiveOrderAndState(t *testing.T) {
	compiler, err := exec.LookPath("clang")
	if err != nil {
		t.Fatal(err)
	}
	version, err := exec.Command(compiler, "--version").Output()
	if err != nil {
		t.Fatal(err)
	}
	files := []runtimeFile{
		{"a.c", []byte("static int state; int next(void) { return ++state; }\n")},
		{"b.c", []byte("int next(void); int pair(void) { int first = next(); int second = next(); return first * 10 + second; }\n")},
	}
	flags := Flags(Options{Sanitize: true})
	directory := t.TempDir()
	library, err := cachedRuntime(files, flags, compiler, string(version), filepath.Join(directory, "cache"), 5)
	if err != nil {
		t.Fatal(err)
	}
	if output, err := exec.Command(archiverName(compiler), "t", library).CombinedOutput(); err != nil || string(output) != "a.o\nb.o\n" {
		t.Fatalf("archive order: %v %s", err, output)
	}
	again, err := cachedRuntime(files, flags, compiler, string(version), filepath.Join(directory, "cache"), 1)
	if err != nil || again != library {
		t.Fatalf("scheduling changed cache identity: %s %v", again, err)
	}
	main := filepath.Join(directory, "main.c")
	if err := os.WriteFile(main, []byte("#include <stdio.h>\nint pair(void); int main(void) { int first = pair(); int second = pair(); printf(\"%d %d\\n\", first, second); return 0; }\n"), 0600); err != nil {
		t.Fatal(err)
	}
	binary := filepath.Join(directory, "probe")
	if output, err := exec.Command(compiler, append(flags, main, library, "-o", binary)...).CombinedOutput(); err != nil {
		t.Fatalf("link: %v %s", err, output)
	}
	if output, err := exec.Command(binary).CombinedOutput(); err != nil || string(output) != "12 34\n" {
		t.Fatalf("runtime state: %v %s", err, output)
	}
}

func TestSplitSourcePolicy(t *testing.T) {
	t.Setenv("ADAMIC_NATIVE_SPLIT", "")
	generated := "// Generated by adamic from fixture.a. Do not edit.\nint main(void) { return 0; }\n"
	for _, options := range []Options{{Sanitize: true}, {Count: true}} {
		if !useSplitSource(generated, options) || !useSplitSource("#include \"tsgo_runtime.h\"\n"+generated, options) {
			t.Fatal("emitted native program did not split")
		}
		if useSplitSource("#define main original_main\n"+generated, options) {
			t.Fatal("handwritten harness sent to emitter-only splitter")
		}
	}
	if !useSplitSource("int main(void) { return 0; }", Options{Split: true}) {
		t.Fatal("explicit splitter prototype request ignored")
	}
}
