// Generate finite emoji matcher instructions from cohere's pinned width data.
package main

import (
	"bytes"
	"crypto/sha256"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"regexp/syntax"
	"sort"
	"strconv"
	"strings"
)

func main() {
	source := flag.String("source", "cohere/internal/format/doc/string_width_generated.go", "pinned Go tables")
	output := flag.String("output", "stage1/cohere/markdownblocks/widthTables.ts", "native tables")
	formatter := flag.String("formatter", "/tmp/cssstrings-cohere", "cohere executable for generated source formatting")
	check := flag.Bool("check", false, "verify generated bytes")
	flag.Parse()
	raw, err := os.ReadFile(*source)
	must(err)
	tree, err := parser.ParseFile(token.NewFileSet(), *source, raw, 0)
	must(err)
	constants := map[string]string{}
	var ranges [][2]int
	ast.Inspect(tree, func(n ast.Node) bool {
		v, ok := n.(*ast.ValueSpec)
		if !ok || len(v.Names) != 1 {
			return true
		}
		name := v.Names[0].Name
		if name == "wideRanges" {
			for _, e := range v.Values[0].(*ast.CompositeLit).Elts {
				pair := e.(*ast.CompositeLit)
				var r [2]int
				for i, x := range pair.Elts {
					value, e := strconv.ParseInt(x.(*ast.BasicLit).Value, 0, 32)
					must(e)
					r[i] = int(value)
				}
				ranges = append(ranges, r)
			}
		} else if name == "emojiPatternSource" || name == "narrowEmojiPatternSource" {
			value, e := strconv.Unquote(v.Values[0].(*ast.BasicLit).Value)
			must(e)
			constants[name] = value
		}
		return true
	})
	if len(ranges) == 0 || len(constants) != 2 {
		panic("missing pinned tables")
	}
	var b bytes.Buffer
	var runeData bytes.Buffer
	var names []string
	fmt.Fprintf(&b, "// Generated from cohere StringWidth data, SHA256 %x.\n// emoji-regex 10.6.0; get-east-asian-width 1.6.0; narrow-emojis 0.0.3.\n// Regenerate: go run ./stage1/cohere/markdownblocks/tools/generate_width\nexport interface WidthInstructionInterface {\n    readonly kind: string;\n    readonly out: number;\n    readonly alternate: number;\n    readonly assertion: number;\n    readonly ranges: readonly number[];\n}\n", sha256.Sum256(raw))
	emitRanges := func(name string, pairs [][2]int) {
		fmt.Fprintf(&b, "export const %s: readonly number[] = [\n", name)
		for _, r := range pairs {
			fmt.Fprintf(&b, "    %d, %d,\n", r[0], r[1])
		}
		fmt.Fprintln(&b, "];")
	}
	emitRanges("wideRanges", ranges)
	for _, item := range []struct{ name, constant string }{{"emoji", "emojiPatternSource"}, {"narrow", "narrowEmojiPatternSource"}} {
		re, e := syntax.Parse(constants[item.constant], syntax.Perl)
		must(e)
		p, e := syntax.Compile(re.Simplify())
		must(e)
		fmt.Fprintf(&b, "export const %sStart = %d;\nexport const %sInstructions: readonly WidthInstructionInterface[] = [\n", item.name, p.Start, item.name)
		for _, i := range p.Inst {
			kind := ""
			rs := []rune{}
			switch i.Op {
			case syntax.InstAlt:
				kind = "a"
			case syntax.InstRune, syntax.InstRune1:
				if i.Arg != 0 {
					panic("fold case not supported")
				}
				kind = "r"
				rs = i.Rune
				if len(rs) == 1 {
					rs = []rune{rs[0], rs[0]}
				}
			case syntax.InstNop:
				kind = "n"
			case syntax.InstMatch:
				kind = "m"
			case syntax.InstFail:
				kind = "f"
			case syntax.InstEmptyWidth:
				if syntax.EmptyOp(i.Arg) & ^(syntax.EmptyBeginText|syntax.EmptyEndText) != 0 {
					panic("unsupported assertion")
				}
				kind = "e"
			default:
				panic(fmt.Sprintf("unsupported %s", i.Op))
			}
			fmt.Fprintf(&b, "    { kind: '%s', out: %d, alternate: %d, assertion: %d, ranges: ", kind, i.Out, i.Arg, i.Arg)
			target := &b
			if len(rs) > 10 {
				name := fmt.Sprintf("widthRunes%d", len(names))
				names = append(names, name)
				fmt.Fprintf(&b, "%s },\n", name)
				fmt.Fprintf(&runeData, "export const %s: readonly number[] = ", name)
				target = &runeData
			}
			target.WriteString("[")
			for j, r := range rs {
				if j > 0 {
					target.WriteString(", ")
				}
				fmt.Fprint(target, int(r))
			}
			if target == &b {
				target.WriteString("] },\n")
			} else {
				target.WriteString("];\n")
			}

		}
		fmt.Fprintln(&b, "];")
		if item.name == "emoji" {
			var starters [][2]int
			seen := map[uint32]bool{}
			var walk func(uint32)
			walk = func(id uint32) {
				if seen[id] {
					return
				}
				seen[id] = true
				i := p.Inst[id]
				switch i.Op {
				case syntax.InstAlt:
					walk(i.Out)
					walk(i.Arg)
				case syntax.InstNop, syntax.InstEmptyWidth:
					walk(i.Out)
				case syntax.InstRune, syntax.InstRune1:
					if len(i.Rune) == 1 {
						starters = append(starters, [2]int{int(i.Rune[0]), int(i.Rune[0])})
					} else {
						for j := 0; j < len(i.Rune); j += 2 {
							starters = append(starters, [2]int{int(i.Rune[j]), int(i.Rune[j+1])})
						}
					}
				case syntax.InstFail:
				default:
					panic("emoji must not match empty")
				}
			}
			walk(uint32(p.Start))
			sort.Slice(starters, func(i, j int) bool { return starters[i][0] < starters[j][0] })
			var merged [][2]int
			for _, r := range starters {
				if len(merged) > 0 && r[0] <= merged[len(merged)-1][1]+1 {
					if r[1] > merged[len(merged)-1][1] {
						merged[len(merged)-1][1] = r[1]
					}
				} else {
					merged = append(merged, r)
				}
			}
			emitRanges("emojiStarts", merged)
		}
	}
	table := []byte("import { " + strings.Join(names, ", ") + " } from './widthRuneRanges.ts';\n" + b.String())
	for _, item := range []struct {
		path string
		data []byte
	}{{*output, table}, {filepath.Join(filepath.Dir(*output), "widthRuneRanges.ts"), []byte("// Generated rune classes used by the finite emoji matchers.\n" + runeData.String())}} {
		tmp, err := os.CreateTemp("", "adamic-width-*.ts")
		must(err)
		defer os.Remove(tmp.Name())
		_, err = tmp.Write(item.data)
		must(err)
		must(tmp.Close())
		formatted, err := exec.Command(*formatter, "--no-cache", "--fix", tmp.Name()).CombinedOutput()
		if err != nil {
			panic(fmt.Sprintf("formatter: %v %s", err, formatted))
		}
		result, err := os.ReadFile(tmp.Name())
		must(err)
		if *check {
			actual, err := os.ReadFile(item.path)
			must(err)
			if !bytes.Equal(actual, result) {
				panic("generated tables changed")
			}
		} else {
			must(os.WriteFile(item.path, result, 0644))
		}
	}
}
func must(err error) {
	if err != nil {
		panic(err)
	}
}
