// Expose the original private directory-entry declaration without changing its members.
const fs = require('node:fs');
const path = require('node:path');
const cp = require('node:child_process');
const crypto = require('node:crypto');
const ts = require('../../../api/node_modules/typescript');
const [root, out] = process.argv.slice(2).map(p => path.resolve(p));
cp.execFileSync(process.execPath, [path.join(__dirname, '../original22/prepare.cjs'), root, out], {stdio: 'inherit'});
const file = path.join(root, 'src/compiler/watchUtilities.ts');
const options = {target: ts.ScriptTarget.ES2024, module: ts.ModuleKind.ESNext, moduleResolution: ts.ModuleResolutionKind.Bundler, declaration: true, emitDeclarationOnly: true, noEmitOnError: false, strict: true, types: [], rootDir: path.join(root, 'src'), outDir: out};
const host = ts.createCompilerHost(options);
const originalGet = host.getSourceFile.bind(host);
host.getSourceFile = (name, language, error, fresh) => name === file ? ts.createSourceFile(name, fs.readFileSync(name, 'utf8') + '\nexport type { SortedAndCanonicalizedMutableFileSystemEntries };\n', language) : originalGet(name, language, error, fresh);
const program = ts.createProgram([file], options, host);
const checker = program.getTypeChecker();
const source = program.getSourceFile(file);
const declaration = source.statements.find(n => ts.isInterfaceDeclaration(n) && n.name.text === 'SortedAndCanonicalizedMutableFileSystemEntries');
const type = checker.getTypeAtLocation(declaration.name);
const fields = checker.getPropertiesOfType(type).map(p => p.name).sort();
if (fields.join(',') !== 'directories,files,sortedAndCanonicalizedDirectories,sortedAndCanonicalizedFiles') throw Error('private declaration drift');
const queue = JSON.parse(fs.readFileSync(path.join(__dirname, '../lazy-array-priority.json'))).candidate_queue;
const pair = queue.find(p => p.type === 'SortedAndCanonicalizedMutableFileSystemEntries' && p.field === 'files');
const member = checker.getPropertyOfType(type, 'files');
if (pair.read_count !== 3 || checker.typeToString(checker.getTypeOfSymbolAtLocation(member, member.valueDeclaration)) !== pair.declared_type) throw Error('directory array census drift');
for (const site of pair.sites) if (fs.readFileSync(path.join(root,site.file),'utf8').slice(site.start,site.end) !== site.text) throw Error('original callback witness drift');
const emitted = {};
const result = program.emit(undefined,(name,text) => {fs.mkdirSync(path.dirname(name),{recursive:true});fs.writeFileSync(name,text);emitted[path.relative(out,name)] = crypto.createHash('sha256').update(text).digest('hex');});
if (result.emitSkipped || result.diagnostics.length) throw Error('private declaration emission failed');
const text = fs.readFileSync(path.join(out,'compiler/watchUtilities.d.ts'),'utf8');
if (!text.includes('interface SortedAndCanonicalizedMutableFileSystemEntries') || !text.includes('readonly files: string[]')) throw Error('private declaration absent');
const manifest = JSON.parse(fs.readFileSync(path.join(out,'original-manifest.json')));
manifest.fields = {SortedAndCanonicalizedMutableFileSystemEntries: fields};
manifest.pairs = [pair];
manifest.declarations = emitted;
fs.writeFileSync(path.join(out,'array29-manifest.json'),JSON.stringify(manifest,null,2)+'\n');
console.log('Original private directory-entry declaration exposed; 3 file-array spans retained');
