// Generated by adamic from borrow_element_super_move.a. Do not edit.

#include "adamic.h"

#include <math.h>
#include <stdbool.h>

static adamic_string adamic_string_0 = ADAMIC_STRING("!");
static adamic_string adamic_string_1 = ADAMIC_STRING("a");
static adamic_string adamic_string_2 = ADAMIC_STRING("b");
static adamic_string adamic_string_3 = ADAMIC_STRING("z");
static adamic_string adamic_string_4 = ADAMIC_STRING(" ");

static adamic_object * adamic_function_0_Worker_new(void);
static adamic_object * adamic_function_0_Worker_new_in(adamic_region *region);
static double adamic_function_1_Worker_run(adamic_object * adamic_local_0_this, adamic_array * adamic_local_1_items);
static void adamic_function_2_Worker_new_initialize(adamic_object * adamic_local_2_this);
static adamic_object * adamic_function_3_Mapper_new(void);
static adamic_object * adamic_function_3_Mapper_new_in(adamic_region *region);
static double adamic_function_4_Mapper_run(adamic_object * adamic_local_4_this, adamic_array * adamic_local_5_items);
static adamic_string * adamic_function_5_Mapper_twice(adamic_object * adamic_local_6_this);
static void adamic_function_6_Mapper_new_initialize(adamic_object * adamic_local_7_this);
static adamic_code_function adamic_function_7_closure;

static adamic_method_function adamic_method_1;
static adamic_value adamic_method_1(adamic_object *self, adamic_value *arguments) {
	(void)arguments;
	return (adamic_value){.number = adamic_function_1_Worker_run(self, adamic_retain((adamic_array *)arguments[0].reference))};
}
static const char *const adamic_shape_0_method_names[] = {"run"};
static const adamic_method adamic_shape_0_method_code[] = {adamic_method_1};
static const adamic_methods adamic_shape_0_methods = {1, adamic_shape_0_method_names, adamic_shape_0_method_code};
static const adamic_shape adamic_shape_0 = {0, NULL, NULL, &adamic_shape_0_methods};
static adamic_method_function adamic_method_4;
static adamic_value adamic_method_4(adamic_object *self, adamic_value *arguments) {
	(void)arguments;
	return (adamic_value){.number = adamic_function_4_Mapper_run(self, adamic_retain((adamic_array *)arguments[0].reference))};
}
static adamic_method_function adamic_method_5;
static adamic_value adamic_method_5(adamic_object *self, adamic_value *arguments) {
	(void)arguments;
	return (adamic_value){.reference = adamic_function_5_Mapper_twice(self)};
}
static const char *const adamic_shape_1_method_names[] = {"run", "twice"};
static const adamic_method adamic_shape_1_method_code[] = {adamic_method_4, adamic_method_5};
static const adamic_methods adamic_shape_1_methods = {2, adamic_shape_1_method_names, adamic_shape_1_method_code};
static const adamic_shape adamic_shape_1 = {0, NULL, NULL, &adamic_shape_1_methods};
static const char *const adamic_shape_2_names[] = {"v"};
static const bool adamic_shape_2_references[] = {true};
static const adamic_shape adamic_shape_2 = {1, adamic_shape_2_names, adamic_shape_2_references, NULL};
static const adamic_shape adamic_shape_3 = {0, NULL, NULL, NULL};

static const adamic_class adamic_class_1;
static const adamic_class adamic_class_2;
static const size_t adamic_methods_1[] = {1};
static const adamic_class adamic_class_1 = {NULL, 0, 0, adamic_methods_1, 1, &adamic_shape_3, NULL, 0, false, 0, NULL};
static const size_t adamic_methods_2[] = {4, 5};
static const adamic_class adamic_class_2 = {&adamic_class_1, 0, 0, adamic_methods_2, 2, &adamic_shape_3, NULL, 0, false, 0, NULL};
static adamic_object * adamic_function_0_Worker_new(void) {
	ADAMIC_CHECK_STACK();
	adamic_object * adamic_temporary_1 = adamic_object_new(&adamic_shape_0);
	adamic_temporary_1->class = &adamic_class_1;
	adamic_object * adamic_local_3_this = adamic_temporary_1;
	adamic_function_2_Worker_new_initialize(adamic_local_3_this);
	adamic_object * adamic_temporary_2 = adamic_retain(adamic_local_3_this);
	adamic_release(adamic_local_3_this);
	return adamic_temporary_2;
	adamic_unreachable();
}

static adamic_object * adamic_function_0_Worker_new_in(adamic_region *region) {
	ADAMIC_CHECK_STACK();
	adamic_object *adamic_temporary_3 = adamic_object_new_in(region, &adamic_shape_0);
	adamic_temporary_3->class = &adamic_class_1;
	adamic_object * adamic_local_3_this = adamic_retain(adamic_temporary_3);
	adamic_function_2_Worker_new_initialize(adamic_local_3_this);
	adamic_object * adamic_temporary_4 = adamic_local_3_this;
	adamic_release(adamic_local_3_this);
	return adamic_temporary_4;
	adamic_unreachable();
}

static double adamic_function_1_Worker_run(adamic_object * adamic_local_0_this, adamic_array * adamic_local_1_items) {
	ADAMIC_CHECK_STACK();
	double adamic_temporary_5 = (double)adamic_local_1_items->length;
	double adamic_temporary_6 = adamic_temporary_5;
	adamic_release(adamic_local_1_items);
	return adamic_temporary_6;
	adamic_unreachable();
}

static void adamic_function_2_Worker_new_initialize(adamic_object * adamic_local_2_this) {
	ADAMIC_CHECK_STACK();
}

static adamic_object * adamic_function_3_Mapper_new(void) {
	ADAMIC_CHECK_STACK();
	adamic_object * adamic_temporary_7 = adamic_object_new(&adamic_shape_1);
	adamic_temporary_7->class = &adamic_class_2;
	adamic_object * adamic_local_8_this = adamic_temporary_7;
	adamic_function_6_Mapper_new_initialize(adamic_local_8_this);
	adamic_object * adamic_temporary_8 = adamic_retain(adamic_local_8_this);
	adamic_release(adamic_local_8_this);
	return adamic_temporary_8;
	adamic_unreachable();
}

static adamic_object * adamic_function_3_Mapper_new_in(adamic_region *region) {
	ADAMIC_CHECK_STACK();
	adamic_object *adamic_temporary_9 = adamic_object_new_in(region, &adamic_shape_1);
	adamic_temporary_9->class = &adamic_class_2;
	adamic_object * adamic_local_8_this = adamic_retain(adamic_temporary_9);
	adamic_function_6_Mapper_new_initialize(adamic_local_8_this);
	adamic_object * adamic_temporary_10 = adamic_local_8_this;
	adamic_release(adamic_local_8_this);
	return adamic_temporary_10;
	adamic_unreachable();
}

static double adamic_function_4_Mapper_run(adamic_object * adamic_local_4_this, adamic_array * adamic_local_5_items) {
	ADAMIC_CHECK_STACK();
	bool adamic_temporary_11 = (adamic_local_5_items->heap.references == 1 && !adamic_weak_held(adamic_local_5_items));
	adamic_closure * adamic_temporary_12 = adamic_closure_new(adamic_function_7_closure, 0);
	adamic_array * adamic_temporary_13 = (adamic_temporary_11 ? adamic_retain(adamic_local_5_items) : adamic_array_new(adamic_local_5_items->length, true));
	size_t adamic_temporary_14 = adamic_local_5_items->length;
	for (size_t adamic_temporary_15 = 0; adamic_temporary_15 < adamic_temporary_14; adamic_temporary_15++) {
		if (adamic_temporary_15 >= adamic_local_5_items->length) {
			static const char message[] = "map: the array shrank while it was being mapped";
			adamic_panic(message, sizeof message - 1);
		}
		adamic_value adamic_temporary_16 = adamic_temporary_12->code(adamic_temporary_12, (adamic_value[]){adamic_local_5_items->elements[adamic_temporary_15], {.number = (double)adamic_temporary_15}, {.reference = adamic_local_5_items}});
		if (adamic_temporary_11) {
			adamic_release(adamic_local_5_items->elements[adamic_temporary_15].reference);
			adamic_local_5_items->elements[adamic_temporary_15] = adamic_temporary_16;
		} else {
			adamic_array_push(adamic_temporary_13, adamic_temporary_16);
		}
	}
	adamic_array * adamic_local_9_out = adamic_temporary_13;
	adamic_release(adamic_temporary_12);
	double adamic_temporary_17 = (double)adamic_local_9_out->length;
	double adamic_temporary_18 = adamic_temporary_17;
	adamic_release(adamic_local_9_out);
	adamic_release(adamic_local_5_items);
	return adamic_temporary_18;
	adamic_unreachable();
}

static adamic_string * adamic_function_5_Mapper_twice(adamic_object * adamic_local_6_this) {
	ADAMIC_CHECK_STACK();
	adamic_string * adamic_temporary_19 = adamic_string_from_number((0x1p+00));
	adamic_string * adamic_temporary_20 = adamic_string_concat(2, (adamic_string *const[]){&adamic_string_1, adamic_temporary_19});
	adamic_object * adamic_temporary_21 = adamic_object_new(&adamic_shape_2);
	adamic_temporary_21->slots[0].reference = adamic_temporary_20;
	adamic_string * adamic_temporary_22 = adamic_string_from_number((0x1p+01));
	adamic_string * adamic_temporary_23 = adamic_string_concat(2, (adamic_string *const[]){&adamic_string_2, adamic_temporary_22});
	adamic_object * adamic_temporary_24 = adamic_object_new(&adamic_shape_2);
	adamic_temporary_24->slots[0].reference = adamic_temporary_23;
	adamic_array * adamic_temporary_25 = adamic_array_new(2, true);
	adamic_array_push(adamic_temporary_25, (adamic_value){.reference = adamic_retain(adamic_temporary_21)});
	adamic_array_push(adamic_temporary_25, (adamic_value){.reference = adamic_retain(adamic_temporary_24)});
	adamic_array * adamic_local_11_items = adamic_temporary_25;
	adamic_release(adamic_temporary_24);
	adamic_release(adamic_temporary_22);
	adamic_release(adamic_temporary_21);
	adamic_release(adamic_temporary_19);
	adamic_value *adamic_temporary_26 = adamic_array_at(adamic_local_11_items, (0x0p+00));
	adamic_object * adamic_local_12_first = adamic_temporary_26 == NULL ? NULL : (adamic_object *)adamic_temporary_26->reference;
	adamic_object * adamic_local_12_first_owner = NULL;
	if (adamic_local_12_first == NULL) {
		adamic_string * adamic_temporary_27 = adamic_string_from_number((0x0p+00));
		adamic_string * adamic_temporary_28 = adamic_string_concat(2, (adamic_string *const[]){&adamic_string_3, adamic_temporary_27});
		adamic_object * adamic_temporary_29 = adamic_object_new(&adamic_shape_2);
		adamic_temporary_29->slots[0].reference = adamic_temporary_28;
		adamic_local_12_first_owner = adamic_temporary_29;
		adamic_local_12_first = adamic_local_12_first_owner;
		adamic_release(adamic_temporary_27);
	}
	adamic_array * adamic_temporary_30 = adamic_local_11_items;
	adamic_local_11_items = NULL;
	double adamic_temporary_31 = adamic_function_1_Worker_run(adamic_local_6_this, adamic_temporary_30);
	double adamic_local_13_count = adamic_temporary_31;
	adamic_string * adamic_temporary_32 = ((adamic_string *)(&adamic_local_12_first->slots[0])->reference);
	adamic_string * adamic_temporary_33 = adamic_string_from_number(adamic_local_13_count);
	adamic_string * adamic_temporary_34 = adamic_string_concat(3, (adamic_string *const[]){adamic_temporary_32, &adamic_string_4, adamic_temporary_33});
	adamic_string * adamic_temporary_35 = adamic_temporary_34;
	adamic_release(adamic_temporary_33);
	if (adamic_local_12_first_owner != NULL) {
		adamic_release(adamic_local_12_first_owner);
	}
	adamic_release(adamic_local_11_items);
	return adamic_temporary_35;
	adamic_unreachable();
}

static void adamic_function_6_Mapper_new_initialize(adamic_object * adamic_local_7_this) {
	ADAMIC_CHECK_STACK();
	adamic_function_2_Worker_new_initialize(adamic_local_7_this);
}

static adamic_value adamic_function_7_closure(adamic_closure *self, adamic_value *arguments) {
	ADAMIC_CHECK_STACK();
	(void)self;
	(void)arguments;
	adamic_object * adamic_local_10_box = (adamic_object *)arguments[0].reference;
	adamic_retain(adamic_local_10_box);
	adamic_string * adamic_temporary_36 = ((adamic_string *)(&adamic_local_10_box->slots[0])->reference);
	adamic_string * adamic_temporary_37 = adamic_string_concat(2, (adamic_string *const[]){adamic_temporary_36, &adamic_string_0});
	adamic_object * adamic_temporary_38 = adamic_object_new(&adamic_shape_2);
	adamic_temporary_38->slots[0].reference = adamic_temporary_37;
	adamic_object * adamic_temporary_39 = adamic_temporary_38;
	adamic_release(adamic_local_10_box);
	return (adamic_value){.reference = adamic_temporary_39};
	adamic_unreachable();
}

int main(int argc, char **argv) {
	adamic_start(argc, argv);
	adamic_region adamic_temporary_40 = ADAMIC_REGION;
	adamic_object *adamic_temporary_41 = adamic_function_3_Mapper_new_in(&adamic_temporary_40);
	adamic_string * adamic_temporary_42 = adamic_function_5_Mapper_twice(adamic_temporary_41);
	adamic_write_line(adamic_stdout, adamic_temporary_42);
	adamic_release(adamic_temporary_42);
	adamic_region_end(&adamic_temporary_40);
	return 0;
}
