const fs = require('node:fs');
const path = require('node:path');
const tree = path.resolve(process.argv[2]);
if (!fs.existsSync(path.join(tree, 'slice.json'))) throw new Error('adaptation 80 requires a declaration slice');
const file = path.join(tree, 'src/compiler/debug.ts');
const before = fs.readFileSync(file, 'utf8');
const pattern = /\(Error as any\)\.captureStackTrace/g;
const count = [...before.matchAll(pattern)].length;
if (count !== 0 && count !== 2) throw new Error(`expected two Error capture casts, found ${count}`);
const after = before.replace(pattern, 'Error.captureStackTrace');
if (count) fs.writeFileSync(file, after);
console.log(JSON.stringify({ errorCaptureCasts: count }));
