// Package javascript compiles Adamic's IR to JavaScript: the second backend, and half of the oracle.
//
// It mirrors the native backend's model rather than borrowing JavaScript's: a captured variable is an
// explicit cell, a closure is its code and its cells, a global is checked against the temporal dead
// zone by the same ready flag. That makes it a test of the IR itself. If lowering got a capture, an
// evaluation order or a scope wrong, this program's output differs from Node running the source, with
// nothing of C involved. Counting references has no meaning here, so it's the one thing left out.
//
// It also carries every check the compiler inserts, the same ones native does, which is what lets the
// oracle hold a program whose checks fire: there, Node running the source doesn't have them.
package javascript

import (
	"fmt"
	"regexp"
	"strconv"
	"strings"

	"github.com/system-inc/adamic/internal/ir"
)

// JavaScript is a program as one JavaScript module, importing panic and the functions that read and
// write files from 'adamic'.
func JavaScript(program *ir.Program) string {
	return JavaScriptWith(program, Options{})
}

// Options adds to what JavaScript emits, for tests that watch a program run. The zero value adds
// nothing.
type Options struct {
	// Mark, when set, is called for each point internal/flow's graph has an instruction for: a
	// statement (by its address in its slice) and a part of it, as flow.Instruction.Part numbers them.
	// The JavaScript expression it returns is evaluated each time the program reaches that point,
	// just before the point itself runs.
	Mark func(at *ir.Statement, part int) string

	// Enter and Leave, when set, are JavaScript expressions evaluated as each call of a function
	// starts and as it ends, however it ends short of a panic.
	Enter func(function int) string
	Leave func(function int) string
}

// JavaScriptWith is JavaScript with options.
func JavaScriptWith(program *ir.Program, options Options) string {
	emitter := &emitter{program: program, options: options}
	var builder strings.Builder
	fmt.Fprintf(&builder, "// Generated by adamic from %s. Do not edit.\n\nimport * as adamicNodeFS from 'node:fs';\nimport * as adamicNodePath from 'node:path';\nimport { fileStatus, panic, processExit as adamicProcessExit, processExiting as adamicProcessExiting, programArguments, readDirectory, readTextFile, realPath, utf8At, utf8Length, writeTextFile } from 'adamic';\n\n", program.Source)
	builder.WriteString("import { tmpdir as adamicNodeTmpdir } from 'node:os';\n")
	// A closure is its code and its cells, an instance of its own class so typeof can tell it from an
	// object that happens to have fields of those names.
	builder.WriteString("class AdamicClosure {\n\tconstructor(code, cells, receiver = false) {\n\t\tthis.code = code;\n\t\tthis.cells = cells;\n\t\tthis.receiver = receiver;\n\t}\n}\n")
	builder.WriteString("const adamicTypeOf = (value) => value instanceof AdamicClosure ? 'function' : typeof value;\n")
	builder.WriteString(fieldReadinessRuntime)
	builder.WriteString(viewArraysRuntime)
	builder.WriteString(viewArrayElementsRuntime)
	builder.WriteString(viewArrayOperationsRuntime)
	builder.WriteString(viewCallablesRuntime)
	builder.WriteString("import { createHash as adamicNodeCreateHash } from 'node:crypto';\n")
	builder.WriteString(collectionIteratorRuntime)
	builder.WriteString(jsonStringifyRuntime)
	builder.WriteString("const adamicCall = (closure, values) => closure.code(closure, values);\n")
	// object.name(...) through an interface: the object's own function value, or else its class's
	// method (on the prototype its constructor gave it), called with the object as this.
	builder.WriteString("const adamicCallee = (object, name) => { if (object === performance || object === process.stdout._handle) return {code: (closure, values) => object[name](...values)}; if (!Object.hasOwn(object, name)) return { code: (closure, values) => object[name](object, ...values) }; const callee = object[name]; return callee.receiver ? { code: (closure, values) => adamicCall(callee, [object, ...values]) } : callee; };\n")
	builder.WriteString("const adamicOptionalCall = (object, name, values) => object === undefined ? undefined : adamicCall(adamicCallee(object, name), values());\n")
	// The array and the callback are each evaluated once, in that order, before the first call.
	builder.WriteString("const adamicVisit = (array, method, callback) => array[method]((element, index, all) => adamicCall(callback, [element, index, all]));\n")
	// map reads the length once, as JavaScript's does; an array the callback shrinks would leave a hole,
	// which 0.1 has no way to hold, so it's a panic, the same one native's map has.
	builder.WriteString("const adamicMap = (array, callback) => {\n\tconst count = array.length;\n\tconst mapped = [];\n\tfor (let index = 0; index < count; index++) {\n\t\tif (index >= array.length) panic('map: the array shrank while it was being mapped');\n\t\tmapped.push(adamicCall(callback, [array[index], index, array]));\n\t}\n\treturn mapped;\n};\n")
	// find and findIndex call the callback even at an index the callback took away, with undefined,
	// which the element's type can't hold: a panic there, the same one native has.
	builder.WriteString("const adamicFind = (array, method, callback) => {\n\tconst count = array.length;\n\tconst last = method === 'findLast' || method === 'findLastIndex';\n\tconst valueResult = method === 'find' || method === 'findLast';\n\tfor (let step = 0; step < count; step++) {\n\t\tconst index = last ? count - 1 - step : step;\n\t\tif (index >= array.length) panic(`${method}: the array shrank while it was being searched`);\n\t\tconst element = array[index];\n\t\tif (adamicCall(callback, [element, index, array])) return valueResult ? element : index;\n\t}\n\treturn valueResult ? undefined : -1;\n};\n")
	// A Map's forEach gives value, key and the map; a Set's gives its element twice and the set.
	builder.WriteString("const adamicCollectionVisit = (collection, callback) => collection.forEach((value, key, all) => adamicCall(callback, [value, key, all]));\n")
	builder.WriteString("const adamicFrom = (length, callback) => Array.from({ length }, (element, index) => adamicCall(callback, [element, index]));\n")
	builder.WriteString("const adamicDefinedNull = (value, message) => value === null ? panic(message) : value;\n")
	builder.WriteString("const adamicDefined = (value, message) => value === undefined ? panic(message) : value;\n")
	builder.WriteString("const adamicSort = (array, callback) => array.sort((left, right) => adamicCall(callback, [left, right]));\n")
	builder.WriteString("const adamicReduce =(array, callback, initial) => array.reduce((carried, element, index, all) => adamicCall(callback, [carried, element, index, all]), initial);\n")
	builder.WriteString("const adamicArrayHolesSetIndex = (array, index, value) => { array[index] = value; };\n")
	builder.WriteString("const adamicSetIndex = (array, index, value) => {\n\tif (!(Number.isInteger(index) && index >= 0 && index < array.length)) panic(`index ${index} is outside an array of length ${array.length}`);\n\tarray[index] = value;\n};\n")
	builder.WriteString("const adamicCast = (object, field, allowed, message) => allowed.includes(object[field]) ? object : panic(message);\n")
	builder.WriteString("const adamicUnready = (name) => { throw new ReferenceError(`Cannot access '${name}' before initialization`); };\n\n")
	if len(program.Classes) > 0 {
		builder.WriteString("const adamicClassIdentities = new WeakMap();\nconst adamicClass = (value, id) => { const metadata = adamicClasses[id - 1]; if (metadata.literal) { const result = {}; for (const name of metadata.publicKeys) { const descriptor = metadata.accessors[name]; if (descriptor) Object.defineProperty(result, name, {enumerable: true, get: descriptor.get === undefined ? undefined : () => adamicGetAccessor(result, name), set: descriptor.set === undefined ? undefined : (next) => adamicSetAccessor(result, name, next)}); else result[name] = value[name]; } for (const name of metadata.privateFields) Object.defineProperty(result, name, {value: value[name], enumerable: false}); value = result; } else for (const name of metadata.privateFields) Object.defineProperty(value, name, {enumerable: false}); if (metadata.static) { const storage = value; value = function () {}; if (metadata.parent) Object.setPrototypeOf(value, storage[metadata.parent]); for (const name of metadata.privateFields) Object.defineProperty(value, name, {value: storage[name], writable: true, configurable: true}); } adamicClassIdentities.set(value, id); return value; };\nconst adamicInstanceOf = (value, wanted) => { for (let id = adamicClassIdentities.get(value); id; id = adamicClasses[id - 1].base) { if (id === wanted || (adamicClasses[wanted - 1].definition && adamicClasses[id - 1].definition === adamicClasses[wanted - 1].definition)) return true; } return false; };\nconst adamicVirtual = (value, slot, ...args) => adamicClasses[adamicClassIdentities.get(value) - 1].methods[slot](value, ...args);\n")
		builder.WriteString("const adamicFindAccessor = (value, name) => { for (let id = adamicClassIdentities.get(value); id; id = adamicClasses[id - 1].base) { const found = adamicClasses[id - 1].accessors[name]; if (found) return found; } };\nconst adamicGetAccessor = (value, name) => { const get = adamicFindAccessor(value, name).get; return typeof get === 'string' ? adamicCall(value[get], [value]) : get(value); };\nconst adamicSetAccessor = (value, name, next) => { const set = adamicFindAccessor(value, name).set; return typeof set === 'string' ? adamicCall(value[set], [value, next]) : set(value, next); };\n")
		classes := []string{}
		for _, class := range program.Classes {
			methods := []string{}
			for _, method := range class.Methods {
				methods = append(methods, functionName(program, method))
			}
			hidden := []string{}
			for _, field := range class.Fields {
				if field.Private {
					hidden = append(hidden, quote(field.Name))
				}
			}
			publicKeys := []string{}
			for _, field := range class.PublicFields {
				publicKeys = append(publicKeys, quote(field.Name))
			}
			accessors := []string{}
			for _, accessor := range class.Accessors {
				getter, setter := "undefined", "undefined"
				if accessor.Getter >= 0 {
					getter = functionName(program, accessor.Getter)
					if program.Functions[accessor.Getter].Closure {
						getter = quote(fmt.Sprintf("#accessor:%d", accessor.Getter))
					}
				}
				if accessor.Setter >= 0 {
					setter = functionName(program, accessor.Setter)
					if program.Functions[accessor.Setter].Closure {
						setter = quote(fmt.Sprintf("#accessor:%d", accessor.Setter))
					}
				}
				accessors = append(accessors, fmt.Sprintf("[%s]: {get: %s, set: %s}", quote(accessor.Name), getter, setter))
			}
			parent := ""
			if class.StaticParent != 0 {
				parent = class.Fields[class.StaticParent-1].Name
			}
			classes = append(classes, fmt.Sprintf("{static: %t, parent: %s, base: %d, methods: [%s], definition: %d, privateFields: [%s], literal: %t, publicKeys: [%s], accessors: {%s}}", class.Static, quote(parent), class.Base, strings.Join(methods, ", "), class.Definition, strings.Join(hidden, ", "), class.Literal, strings.Join(publicKeys, ", "), strings.Join(accessors, ", ")))
		}
		fmt.Fprintf(&builder, "const adamicClasses = [%s];\n", strings.Join(classes, ", "))
	}
	for index, local := range program.Locals {
		if local.Global {
			fmt.Fprintf(&builder, "let %s;\nlet %s = false;\n", emitter.name(index), readyName(index))
			if local.Uninitialized {
				fmt.Fprintf(&builder, "let %s_declared = false;\n", readyName(index))
			}
		}
	}
	for index, function := range program.Functions {
		emitter.indent = 1
		emitter.function = &program.Functions[index]
		parameters := []string{}
		if function.Closure {
			parameters = []string{"self", "values"}
		} else {
			for _, parameter := range function.Parameters {
				parameters = append(parameters, emitter.name(parameter))
			}
		}
		fmt.Fprintf(&builder, "\nfunction %s(%s) {\n", functionName(program, index), strings.Join(parameters, ", "))
		if function.Closure {
			for position, parameter := range function.Parameters {
				emitter.line("let %s = values[%d];", emitter.name(parameter), position)
			}
		}
		emitter.allocateEnvironment(function.FrameEnvironment)
		for _, parameter := range function.Parameters {
			if program.Locals[parameter].Uninitialized && !program.Locals[parameter].Captured {
				emitter.line("let %s = true;", readyName(parameter))
			}
			if program.Locals[parameter].EnvironmentCell {
				emitter.line("%s.value = %s;", emitter.cellName(parameter), emitter.name(parameter))
				emitter.line("%s.ready = true;", emitter.cellName(parameter))
			} else if program.Locals[parameter].Captured {
				emitter.line("const %s = { value: %s, ready: true };", emitter.cellName(parameter), emitter.name(parameter))
			}
		}
		if options.Enter != nil {
			emitter.line("%s;", options.Enter(index))
			emitter.line("try {")
			emitter.indent++
		}
		emitter.statements(function.Body)
		if options.Leave != nil {
			emitter.indent--
			emitter.line("} finally {")
			emitter.line("\tif (!adamicProcessExiting()) { %s; }", options.Leave(index))
			emitter.line("}")
		}
		builder.WriteString(emitter.out.String())
		emitter.out.Reset()
		builder.WriteString("}\n")
	}
	emitter.function = nil
	emitter.indent = 0
	builder.WriteString("\n")
	// Each class's methods, the prototype of the objects its constructor makes, declared before the
	// program runs; a class's methods are functions, hoisted, so each is there to name.
	for _, prototype := range emitter.prototypes {
		builder.WriteString(prototype)
	}
	emitter.statements(program.Main)
	builder.WriteString(emitter.out.String())
	code := builder.String()
	if strings.Contains(code, "adamicNodeFSFile.") {
		code = "import * as adamicNodeFSFile from 'node:fs';\n" + code
	}
	return code
}

type emitter struct {
	program  *ir.Program
	options  Options
	function *ir.Function
	out      strings.Builder
	indent   int
	labels   int

	// prototypes declares each class's methods, in the order the constructors that make them are
	// emitted, and prototypeNames names each by its constructor's literal.
	prototypes     []string
	prototypeNames map[string]string

	// continues holds, innermost last, each open loop's continue label.
	continues  []string
	breakables []string
}

func (e *emitter) line(format string, arguments ...any) {
	e.out.WriteString(strings.Repeat("\t", e.indent))
	fmt.Fprintf(&e.out, format, arguments...)
	e.out.WriteString("\n")
}

var identifier = regexp.MustCompile(`[^A-Za-z0-9_]`)

func (e *emitter) name(local int) string {
	return Name(e.program, local)
}

// Name is the JavaScript name of a local that isn't captured (a captured one lives in a cell), for a
// test that reads it through Options.Mark.
func Name(program *ir.Program, local int) string {
	return fmt.Sprintf("local_%d_%s", local, identifier.ReplaceAllString(program.Locals[local].Name, ""))
}

func (e *emitter) cellName(local int) string {
	return e.name(local) + "_cell"
}

func readyName(local int) string {
	return fmt.Sprintf("ready_%d", local)
}

func functionName(program *ir.Program, function int) string {
	return fmt.Sprintf("function_%d_%s", function, identifier.ReplaceAllString(program.Functions[function].Name, ""))
}

// prototype names the object holding a class's methods by name, declaring it the first time.
func (e *emitter) prototype(methods []ir.Method) string {
	entries := []string{}
	for _, method := range methods {
		entries = append(entries, quote(method.Name)+": "+functionName(e.program, method.Function))
	}
	key := strings.Join(entries, ", ")
	if name, isDeclared := e.prototypeNames[key]; isDeclared {
		return name
	}
	if e.prototypeNames == nil {
		e.prototypeNames = map[string]string{}
	}
	name := fmt.Sprintf("methods_%d", len(e.prototypes))
	e.prototypeNames[key] = name
	// Class prototypes inherit Object methods, just as the source classes do.
	e.prototypes = append(e.prototypes, fmt.Sprintf("const %s = { __proto__: Object.prototype, %s };\n", name, key))
	return name
}

// variable is where a local's value is, from the current function: a cell of its environment, a cell
// it declared, or the plain name.
func (e *emitter) variable(local int) string {
	declared := e.program.Locals[local]
	if declared.Captured && !declared.Global {
		if e.function != nil {
			for position, captured := range e.function.Environment {
				if captured == local {
					return fmt.Sprintf("self.cells[%d].value", position)
				}
			}
		}
		return e.cellName(local) + ".value"
	}
	return e.name(local)
}

func (e *emitter) cell(local int) string {
	if e.function != nil {
		for position, captured := range e.function.Environment {
			if captured == local {
				return fmt.Sprintf("self.cells[%d]", position)
			}
		}
	}
	return e.cellName(local)
}

// statements emits each statement where it stands in its slice, the address Options.Mark names it by.
func (e *emitter) statements(statements []ir.Statement) {
	for index := range statements {
		e.statement(&statements[index])
	}
}

// mark is the JavaScript Options.Mark gives for a point, or "" with no Mark.
func (e *emitter) mark(at *ir.Statement, part int) string {
	if e.options.Mark == nil {
		return ""
	}
	return e.options.Mark(at, part)
}

// markLine marks a point with a statement of its own.
func (e *emitter) markLine(at *ir.Statement, part int) {
	if mark := e.mark(at, part); mark != "" {
		e.line("%s;", mark)
	}
}

// marked is an expression that marks a point as it's evaluated, and is value.
func (e *emitter) marked(at *ir.Statement, part int, value string) string {
	if mark := e.mark(at, part); mark != "" {
		return fmt.Sprintf("(%s, %s)", mark, value)
	}
	return value
}

func (e *emitter) nested(statements []ir.Statement) {
	e.indent++
	e.statements(statements)
	e.indent--
}

func (e *emitter) declare(local int, value string) {
	declared := e.program.Locals[local]
	if declared.Captured && declared.Preallocated {
		e.line("%s.value = %s;", e.cell(local), value)
		e.line("%s.ready = true;", e.cell(local))
		return
	}
	if declared.Captured {
		e.line("let %s = { value: %s, ready: true };", e.cellName(local), value)
		return
	}
	e.line("let %s = %s;", e.name(local), value)
}

func (e *emitter) statement(at *ir.Statement) {
	switch (*at).(type) {
	case ir.Block, ir.Loop, ir.ForOf, ir.Switch, ir.Break, ir.Continue, ir.Try:
		// Marked inside, where their parts run, or not at all: a block, a break and a continue run
		// nothing of their own.
	default:
		e.markLine(at, 0)
	}
	switch statement := (*at).(type) {
	case ir.WriteLine:
		stream := "log"
		if statement.Stream == ir.Stderr {
			stream = "error"
		}
		e.line("console.%s(%s);", stream, e.value(statement.Value))
	case ir.AllocateEnvironment:
		// Emitted at function entry before parameter cells are initialized.
	case ir.Declare:
		if statement.Uninitialized && !e.program.Locals[statement.Local].Uninitialized {
			local := e.program.Locals[statement.Local]
			if local.Captured && !local.EnvironmentCell {
				e.line("let %s = { value: undefined, ready: false };", e.cellName(statement.Local))
			}
			return
		}
		if statement.Uninitialized && e.program.Locals[statement.Local].EnvironmentCell {
			e.line("%s = false;", e.localReady(statement.Local))
			return
		}
		value := "undefined"
		if statement.Value != nil {
			value = e.value(statement.Value)
		} else {
			value = zero(e.program.Locals[statement.Local].Type)
		}
		if e.program.Locals[statement.Local].Global {
			e.line("%s = %s;", e.name(statement.Local), value)
			e.line("%s = %t;", readyName(statement.Local), !statement.Uninitialized)
			if e.program.Locals[statement.Local].Uninitialized {
				e.line("%s_declared = true;", readyName(statement.Local))
			}
			return
		}
		e.declare(statement.Local, value)
		if e.program.Locals[statement.Local].Uninitialized {
			if e.program.Locals[statement.Local].Captured {
				e.line("%s = %t;", e.localReady(statement.Local), !statement.Uninitialized)
			} else {
				e.line("let %s = %t;", readyName(statement.Local), !statement.Uninitialized)
			}
		}
	case ir.Assign:
		value := e.value(statement.Value)
		if e.program.Locals[statement.Local].Uninitialized && e.program.Locals[statement.Local].Global && !e.program.Locals[statement.Local].Hoisted {
			temporary := e.temporary()
			e.line("const %s = %s;", temporary, value)
			e.line("if (!%s_declared) adamicUnready(%s);", readyName(statement.Local), quote(e.program.Locals[statement.Local].Name))
			value = temporary
		}
		if statement.Checked {
			// After the value, as JavaScript does: the right side runs, then the write throws.
			temporary := e.temporary()
			e.line("const %s = %s;", temporary, value)
			e.line("if (!%s) adamicUnready(%s);", e.ready(statement.Local), quote(e.program.Locals[statement.Local].Name))
			value = temporary
		}
		e.line("%s = %s;", e.variable(statement.Local), value)
		if e.program.Locals[statement.Local].Uninitialized {
			e.line("%s = %t;", e.localReady(statement.Local), !statement.Uninitialized)
		}
	case ir.Evaluate:
		e.line("%s;", e.value(statement.Value))
	case ir.Panic:
		e.line("panic(%s);", e.value(statement.Message))
	case ir.SetProperty:
		if statement.WriteContract != 0 && e.program.CheckedFields[statement.Name] && !statement.Define && !statement.Uninitialized {
			allowed := []string{}
			for _, id := range ir.ScalarWriteContracts(e.program, statement.WriteContract) {
				allowed = append(allowed, fmt.Sprint(id))
			}
			if statement.WriteProven {
				e.line("adamicWriteField(%s, %s, %s);", e.value(statement.Object), quote(statement.Name), e.value(statement.Value))
				break
			}
			e.line("adamicCheckedWrite(%s, %s, %s, [%s], %s);", e.value(statement.Object), quote(statement.Name), e.value(statement.Value), strings.Join(allowed, ","), quote(statement.WriteWhere))
			break
		}
		if e.program.CheckedFields[statement.Name] && !statement.Define && !statement.Uninitialized {
			e.line("adamicViewWrite(%s, %s, %s, %d);", e.value(statement.Object), quote(statement.Name), e.value(statement.Value), statement.Value.Type())
			break
		}
		if statement.Define || statement.Uninitialized {
			e.line("adamicDefineField(%s, %s, %s, %t, %t, %d);", e.value(statement.Object), quote(statement.Name), e.value(statement.Value), !strings.HasPrefix(statement.Name, "#"), !statement.Uninitialized, statement.Value.Type())
		} else {
			e.line("adamicWriteField(%s, %s, %s);", e.value(statement.Object), quote(statement.Name), e.value(statement.Value))
		}
	case ir.SetIndex:
		if ir.HasArrayViews(e.program) {
			e.line("adamicViewSetIndex(%s, %s, %s, %d, %t);", e.value(statement.Array), e.value(statement.Index), e.value(statement.Value), statement.Element, hasArrayHoles(e.program))
		} else {
			setter := "adamicSetIndex"
			if hasArrayHoles(e.program) {
				setter = "adamicArrayHolesSetIndex"
			}
			e.line(setter+"(%s, %s, %s);", e.value(statement.Array), e.value(statement.Index), e.value(statement.Value))
		}
	case ir.Return:
		if statement.Value == nil {
			e.line("return;")
		} else {
			e.line("return %s;", e.value(statement.Value))
		}
	case ir.If:
		e.line("if (%s) {", e.value(statement.Condition))
		e.nested(statement.Then)
		if len(statement.Else) > 0 {
			e.line("} else {")
			e.nested(statement.Else)
		}
		e.line("}")
	case ir.Block:
		e.line("{")
		e.nested(statement.Body)
		e.line("}")
	case ir.Loop:
		e.loop(at, statement)
	case ir.ForOf:
		e.forOf(at, statement)
	case ir.Switch:
		label := e.temporary()
		e.breakables = append(e.breakables, label)
		e.line("%s: do {", label)
		e.indent++
		value := e.temporary()
		e.markLine(at, 0)
		e.line("const %s = %s;", value, e.value(statement.Value))
		part := 0
		for index, matched := range statement.Cases {
			tests := []string{}
			for _, test := range matched.Tests {
				part++
				tests = append(tests, e.marked(at, part, fmt.Sprintf("%s === %s", value, e.value(test))))
			}
			prefix := "} else if"
			if index == 0 {
				prefix = "if"
			}
			e.line("%s (%s) {", prefix, strings.Join(tests, " || "))
			e.nested(matched.Body)
		}
		if len(statement.Cases) > 0 {
			e.line("} else {")
			e.nested(statement.Default)
			e.line("}")
		} else {
			e.statements(statement.Default)
		}
		e.indent--
		e.line("} while (false);")
		e.breakables = e.breakables[:len(e.breakables)-1]
	case ir.Break:
		e.line("break %s;", e.breakables[len(e.breakables)-1-statement.Depth])
	case ir.Continue:
		e.line("break %s;", e.continues[len(e.continues)-1])
	case ir.Throw:
		e.line("throw %s;", e.value(statement.Value))
	case ir.Try:
		e.line("try {")
		e.nested(statement.Body)
		if statement.HasCatch {
			caught := e.temporary()
			e.line("} catch (%s) {", caught)
			e.indent++
			// An explicit exit is not a source exception and cannot enter a catch.
			e.line("if (adamicProcessExiting()) throw %s;", caught)
			// Part 1 of a try is its catch taking the error (flow.Instruction.Part).
			e.markLine(at, 1)
			if statement.CatchLocal >= 0 {
				e.declare(statement.CatchLocal, caught)
			}
			e.statements(statement.Catch)
			e.indent--
		}
		if statement.HasFinally {
			e.line("} finally {")
			e.indent++
			e.line("if (!adamicProcessExiting()) {")
			e.nested(statement.Finally)
			e.line("}")
			e.indent--
		}
		e.line("}")
	default:
		panic(fmt.Sprintf("javascript: no JavaScript for %T", statement))
	}
}

func (e *emitter) temporary() string {
	e.labels++
	return fmt.Sprintf("temporary_%d", e.labels)
}

// loop emits every loop as the native backend does: for (;;), the condition as an if that breaks,
// the body in a labeled block a continue breaks out of, then the per-iteration copies and the update.
func (e *emitter) loop(at *ir.Statement, statement ir.Loop) {
	e.labels++
	label := fmt.Sprintf("continue_%d", e.labels)
	breakLabel := e.temporary()
	e.breakables = append(e.breakables, breakLabel)
	e.line("%s: for (;;) {", breakLabel)
	e.indent++
	if !statement.CheckAfter {
		e.line("if (!%s) break;", e.marked(at, 0, "("+e.value(statement.Condition)+")"))
	}
	e.continues = append(e.continues, label)
	e.line("%s: {", label)
	e.nested(statement.Body)
	e.line("}")
	e.continues = e.continues[:len(e.continues)-1]
	for _, local := range statement.PerIteration {
		if e.program.Locals[local].Captured {
			e.line("%s = { value: %s.value, ready: %s.ready };", e.cellName(local), e.cellName(local), e.cellName(local))
		}
	}
	e.statements(statement.Update)
	if statement.CheckAfter {
		e.line("if (!%s) break;", e.marked(at, 0, "("+e.value(statement.Condition)+")"))
	}
	e.indent--
	e.line("}")
	e.breakables = e.breakables[:len(e.breakables)-1]
}

func (e *emitter) forOf(at *ir.Statement, statement ir.ForOf) {
	e.labels++
	label := fmt.Sprintf("continue_%d", e.labels)
	held, index := e.temporary(), e.temporary()
	e.line("{")
	e.indent++
	e.markLine(at, 0)
	e.line("const %s = %s;", held, e.value(statement.Iterable))
	breakLabel := e.temporary()
	e.breakables = append(e.breakables, breakLabel)
	e.line("%s:", breakLabel)
	switch {
	case statement.MapPart == "keys" || statement.MapPart == "values":
		e.line("for (const %s of %s.%s()) {", index, held, statement.MapPart)
	case statement.Iterable.Type() == ir.String || statement.MapPart != "" || statement.RegexIterator:
		// A string's code points, or a map's [key, value] entries.
		e.line("for (const %s of %s) {", index, held)
	default:
		e.line("for (let %s_index = 0; %s_index < %s.length; %s_index++) {", index, index, held, index)
		if statement.ViewRead.View != "" {
			e.line("\tconst %s = %s;", index, e.viewArrayElementCheck(statement.ViewRead, held+"["+index+"_index]"))
		} else {
			e.line("\tconst %s = %s[%s_index];", index, held, index)
		}
	}
	e.indent++
	e.continues = append(e.continues, label)
	e.line("%s: {", label)
	e.indent++
	e.markLine(at, 1)
	if statement.Pattern != nil {
		for _, binding := range statement.Pattern {
			e.declare(binding.Local, fmt.Sprintf("%s[%s]", index, quote(binding.Field)))
		}
	} else {
		e.declare(statement.Local, index)
	}
	e.statements(statement.Body)
	e.indent--
	e.line("}")
	e.continues = e.continues[:len(e.continues)-1]
	e.indent--
	e.line("}")
	e.indent--
	e.line("}")
	e.breakables = e.breakables[:len(e.breakables)-1]
}

var operators = map[ir.Operator]string{
	ir.Add: "+", ir.Subtract: "-", ir.Multiply: "*", ir.Divide: "/", ir.Remainder: "%", ir.Power: "**",
	ir.Less: "<", ir.LessOrEqual: "<=", ir.Greater: ">", ir.GreaterOrEqual: ">=",
	ir.Equal: "===", ir.NotEqual: "!==", ir.And: "&&", ir.Or: "||",
	ir.BitAnd: "&", ir.BitOr: "|", ir.BitXor: "^", ir.ShiftLeft: "<<", ir.ShiftRight: ">>", ir.ShiftRightUnsigned: ">>>",
}

// value is a JavaScript expression for a value. JavaScript evaluates left to right and short-circuits
// as the IR means, so nesting expressions keeps every order the native backend makes explicit.
func (e *emitter) valueWithoutViewArrays(expression ir.Expression) string {
	switch expression := expression.(type) {
	case ir.NodeFSFile:
		return e.nodeFSFile(expression)
	case ir.NodeHostCall:
		return e.nodeHostCall(expression)
	case ir.ProcessCall:
		if value, known := e.nodeProcessCall(expression); known {
			return value
		}
		switch expression.Operation {
		case "exitCode":
			return "process.exitCode"
		case "stdoutTTY":
			return "process.stdout.isTTY"
		case "stderrTTY":
			return "process.stderr.isTTY"
		case "env":
			return "process.env[" + e.value(expression.Arguments[0]) + "]"
		case "setExitCode":
			return "(process.exitCode = " + e.value(expression.Arguments[0]) + ")"
		case "exit":
			return "adamicProcessExit(" + e.value(expression.Arguments[0]) + ")"
		}
	case ir.RegExpNew:
		if expression.Arguments != nil {
			return "new RegExp(" + e.values(expression.Arguments) + ")"
		}
		r := e.program.Regexps[expression.Index]
		return "new RegExp(" + quote(r.Pattern) + ", " + quote(r.Flags) + ")"
	case ir.RegExpCall:
		if expression.Method == "iteratorDone" {
			return e.value(expression.Value) + ".done"
		}
		return e.value(expression.Value) + "." + expression.Method + "(" + e.values(expression.Arguments) + ")"
	case ir.RegExpGroup:
		operator := "["
		if expression.Optional {
			operator = "?.["
		}
		return e.value(expression.Object) + operator + quote(expression.Name) + "]"
	case ir.RegExpProperty:
		if expression.Optional {
			return e.value(expression.Array) + "?.[" + quote(expression.Name) + "]"
		}
		return e.value(expression.Array) + "[" + quote(expression.Name) + "]"
	case ir.Null:
		return "null"
	case ir.IsNull:
		if expression.AlwaysFalse {
			return "(" + e.value(expression.Value) + ", false)"
		}
		return "(" + e.value(expression.Value) + " === null)"
	case ir.NumberConstant:
		return number(expression.Value)
	case ir.BooleanConstant:
		return strconv.FormatBool(expression.Value)
	case ir.StringConstant:
		return quote(e.program.Strings[expression.Index])
	case ir.Read:
		if expression.Readiness != "" {
			message := fmt.Sprintf("read before assignment: variable '%s' in %s", e.program.Locals[expression.Local].Name, expression.Readiness)
			return fmt.Sprintf("(%s ? %s : panic(%s))", e.localReady(expression.Local), e.variable(expression.Local), quote(message))
		}
		if expression.Checked {
			return fmt.Sprintf("(%s ? %s : adamicUnready(%s))", e.ready(expression.Local), e.variable(expression.Local), quote(e.program.Locals[expression.Local].Name))
		}
		return e.variable(expression.Local)
	case ir.Unary:
		operator := map[ir.Operator]string{ir.Negate: "-", ir.Plus: "+", ir.Not: "!", ir.BitNot: "~"}[expression.Operator]
		return "(" + operator + e.value(expression.Operand) + ")"
	case ir.Binary:
		return "(" + e.value(expression.Left) + " " + operators[expression.Operator] + " " + e.value(expression.Right) + ")"
	case ir.HasAccessor:
		return "adamicFindAccessor(" + e.value(expression.Object) + ", " + quote(expression.Name) + ") !== undefined"
	case ir.InstanceOf:
		if expression.Exact {
			return fmt.Sprintf("adamicClassIdentities.get(%s) === %d", e.value(expression.Value), expression.Class)
		}
		return fmt.Sprintf("adamicInstanceOf(%s, %d)", e.value(expression.Value), expression.Class)
	case ir.Call:
		if expression.Accessor != "" {
			object := e.value(expression.Arguments[0])
			if expression.Setter {
				return "adamicSetAccessor(" + object + ", " + quote(expression.Accessor) + ", " + e.value(expression.Arguments[1]) + ")"
			}
			return "adamicGetAccessor(" + object + ", " + quote(expression.Accessor) + ")"
		}
		if expression.Virtual != 0 {
			arguments := []string{e.value(expression.Arguments[0]), strconv.Itoa(expression.Virtual - 1)}
			for _, argument := range expression.Arguments[1:] {
				arguments = append(arguments, e.value(argument))
			}
			return "adamicVirtual(" + strings.Join(arguments, ", ") + ")"
		}
		return functionName(e.program, expression.Function) + "(" + e.values(expression.Arguments) + ")"
	case ir.NumberToString:
		return "String(" + e.value(expression.Value) + ")"
	case ir.BooleanToString:
		return "String(" + e.value(expression.Value) + ")"
	case ir.Concat:
		parts := []string{}
		for _, part := range expression.Parts {
			parts = append(parts, e.value(part))
		}
		if len(parts) == 1 {
			return parts[0]
		}
		return "(" + strings.Join(parts, " + ") + ")"
	case ir.Conditional:
		return "(" + e.value(expression.Condition) + " ? " + e.value(expression.WhenTrue) + " : " + e.value(expression.WhenNot) + ")"
	case ir.ObjectLiteral:
		if expression.Tuple {
			elements := []string{}
			for _, field := range expression.Fields {
				elements = append(elements, e.value(field.Value))
			}
			return "[" + strings.Join(elements, ", ") + "]"
		}
		spreadValue := ""
		fields := []string{}
		if len(expression.Methods) > 0 {
			fields = append(fields, "__proto__: "+e.prototype(expression.Methods))
		}
		if expression.Spread != nil {
			spread := e.value(expression.Spread)
			if expression.SpreadReadiness != "" {
				spread = "adamicSpreadFields(" + spread + ", " + quote(expression.SpreadReadiness) + ")"
			}
			if len(e.program.CheckedFields) != 0 {
				spreadValue = spread
				spread = "adamicSpreadSource"
			}
			fields = append(fields, "..."+spread)
		}
		for _, field := range expression.Fields {
			fields = append(fields, quote(field.Name)+": "+e.value(field.Value))
		}
		object := "({" + strings.Join(fields, ", ") + "})"
		if expression.Class != 0 {
			object = fmt.Sprintf("adamicClass(%s, %d)", object, expression.Class)
		}
		unready := []string{}
		for _, field := range expression.Fields {
			if field.Uninitialized {
				unready = append(unready, quote(field.Name))
			}
		}
		if len(unready) > 0 {
			object = "adamicUninitializedFields(" + object + ", [" + strings.Join(unready, ", ") + "])"
		}
		if len(e.program.CheckedFields) != 0 {
			types := []string{}
			for _, field := range expression.Fields {
				types = append(types, quote(field.Name)+": "+fmt.Sprint(field.Value.Type()))
			}
			parentTypes := ""
			if spreadValue != "" {
				parentTypes = "...adamicFieldRepresentations.get(adamicSpreadSource), "
			}
			object = "adamicRecordFieldTypes(" + object + ", {" + parentTypes + strings.Join(types, ", ") + "})"
			contracts := []string{}
			for _, field := range expression.Fields {
				contracts = append(contracts, quote(field.Name)+": "+fmt.Sprint(field.Contract))
			}
			parentContracts := ""
			if spreadValue != "" {
				parentContracts = "...adamicSlotContracts.get(adamicSpreadSource), "
			}
			real := "record"
			if expression.RealType != "" {
				real = expression.RealType
			}
			if expression.Class != 0 {
				real = e.program.Classes[expression.Class-1].Name
			}
			object = "adamicRecordSlotContracts(" + object + ", {" + parentContracts + strings.Join(contracts, ", ") + "}, " + quote(real) + ")"
			if spreadValue != "" {
				object = "((adamicSpreadSource) => " + object + ")(" + spreadValue + ")"
			}
		}
		return object
	case ir.PhantomMember:
		operator := "["
		if expression.Optional {
			operator = "?.["
		}
		return "(" + e.value(expression.Value) + ")" + operator + quote(expression.Name) + "]"
	case ir.Property:
		if expression.View != "" && expression.Of == ir.Union && !expression.Nullish {
			return e.viewObjectPrimitive(expression)
		}
		if expression.View != "" {
			if expression.Nullish {
				return e.nullishViewField(expression)
			}
			if expression.Of == ir.Closure {
				return e.emitViewCallableProperty(expression)
			}
			expected := expression.ViewType
			if expected == "" {
				expected = map[ir.Type]string{ir.Number: "number", ir.Boolean: "boolean", ir.String: "string", ir.Object: "object", ir.Array: "array", ir.Map: "Map"}[expression.Of]
			}
			value := fmt.Sprintf("adamicViewField(%s, %s, %s, %d, %s, [%s], %t, %t)", e.value(expression.Object), quote(expression.Name), quote(expression.View), expression.Of, quote(expected), e.values(expression.ViewAllowed), expression.Absent, expression.Optional)
			return e.viewObjectUnion(expression, value)
		}
		if expression.Readiness != "" {
			return fmt.Sprintf("adamicReadField(%s, %s, %s, %t, %t)", e.value(expression.Object), quote(expression.Name), quote(expression.Readiness), expression.Optional, expression.Absent)
		}
		if expression.Optional {
			return e.value(expression.Object) + "?.[" + quote(expression.Name) + "]"
		}
		return e.value(expression.Object) + "[" + quote(expression.Name) + "]"
	case ir.ArrayLiteral:
		elements := []string{}
		for index, element := range expression.Elements {
			if expression.Spread != nil && expression.Spread[index] {
				elements = append(elements, "..."+e.value(element))
			} else {
				elements = append(elements, e.value(element))
			}
		}
		return "[" + strings.Join(elements, ", ") + "]"
	case ir.Length:
		if expression.Optional {
			return e.value(expression.Array) + "?.length"
		}
		return e.value(expression.Array) + ".length"
	case ir.StringLength:
		if expression.Optional {
			return e.value(expression.Value) + "?.length"
		}
		return e.value(expression.Value) + ".length"
	case ir.JSONStringify:
		value := e.value(expression.Value)
		replacer, space := "undefined", "undefined"
		if expression.Replacer != nil {
			replacer = e.value(expression.Replacer)
		}
		if expression.Space != nil {
			space = e.value(expression.Space)
		}
		return "adamicJSONStringify(" + value + ", " + replacer + ", " + space + ")"
	case ir.JSONNull:
		return "null"
	case ir.MathCall:
		if expression.Spread != nil {
			return "Math." + expression.Function + "(..." + e.value(expression.Spread) + ")"
		}
		return "Math." + expression.Function + "(" + e.values(expression.Arguments) + ")"
	case ir.StringFromCodes:
		codes := e.values(expression.Codes)
		if expression.Spread != nil {
			codes = "..." + e.value(expression.Spread)
		}
		if expression.CodePoints {
			return "String.fromCodePoint(" + codes + ")"
		}
		return "String.fromCharCode(" + codes + ")"
	case ir.NodeBufferCall:
		return e.nodeBufferCall(expression)
	case ir.ObjectCall:
		if expression.Readiness != "" {
			return "adamicObjectReadCall(" + quote(expression.Method) + ", " + quote(expression.Readiness) + ", " + e.values(expression.Arguments) + ")"
		}
		return "Object." + expression.Method + "(" + e.values(expression.Arguments) + ")"
	case ir.NumberCall:
		if expression.Function == "toBoolean" {
			return "Boolean(" + e.values(expression.Arguments) + ")"
		}
		if expression.Function == "prototypeHasOwnProperty" {
			return "Number.prototype.hasOwnProperty(" + e.values(expression.Arguments) + ")"
		}
		if expression.Function == "convert" {
			return "Number(" + e.values(expression.Arguments) + ")"
		}
		return "Number." + expression.Function + "(" + e.values(expression.Arguments) + ")"
	case ir.ToFixed:
		return e.value(expression.Value) + ".toFixed(" + e.value(expression.Digits) + ")"
	case ir.NumberFormat:
		argument := ""
		if expression.Argument != nil {
			argument = e.value(expression.Argument)
		}
		return e.value(expression.Value) + "." + expression.Method + "(" + argument + ")"
	case ir.Undefined:
		return "undefined"
	case ir.IsUndefined:
		return "(" + e.value(expression.Value) + " === undefined)"
	case ir.Unwrap:
		// Checked as native checks it: the checker narrowed undefined away, but a call may have put it back.
		return "adamicDefined(" + e.value(expression.Value) + ", " + quote(narrowedAwayMessage) + ")"
	case ir.Defined:
		if expression.Null {
			return "adamicDefinedNull(" + e.value(expression.Value) + ", " + quote(expression.Message) + ")"
		}
		return "adamicDefined(" + e.value(expression.Value) + ", " + quote(expression.Message) + ")"
	case ir.MaybeOf:
		if expression.Value == nil {
			return "undefined"
		}
		return e.value(expression.Value)
	case ir.Box:
		return e.value(expression.Value)
	case ir.MakeError:
		if expression.Name != nil {
			return "Object.assign(new Error(" + e.value(expression.Message) + "), {name: " + e.value(expression.Name) + "})"
		}
		return "new Error(" + e.value(expression.Message) + ")"
	case ir.WeakOf:
		// A plain reference: Node keeps what it points to as long as anything does, which is what the
		// source on Node does too (docs/memory.md says where native differs).
		return e.value(expression.Value)
	case ir.WeakTarget:
		return e.value(expression.Value)
	case ir.Narrow:
		return fmt.Sprintf("adamicNarrow(%s, %d)", e.value(expression.Value), expression.To)
	case ir.TypeOf:
		return "adamicTypeOf(" + e.value(expression.Value) + ")"
	case ir.UnionToString:
		return "String(" + e.value(expression.Value) + ")"
	case ir.MaybeToString:
		return "String(" + e.value(expression.Value) + ")"
	case ir.Coalesce:
		if expression.Panic != nil {
			return "(" + e.value(expression.Value) + " ?? panic(" + e.value(expression.Panic) + "))"
		}
		return "(" + e.value(expression.Value) + " ?? " + e.value(expression.Fallback) + ")"
	case ir.ArrayPush:
		if ir.HasArrayViews(e.program) {
			return fmt.Sprintf("adamicViewPush(%s, %s, %d)", e.value(expression.Array), e.value(expression.Value), expression.Element)
		}
		return e.value(expression.Array) + ".push(" + e.value(expression.Value) + ")"
	case ir.ArrayJoin:
		if expression.ViewRead.View != "" {
			return "adamicViewJoin(" + e.value(expression.Array) + ", " + e.value(expression.Separator) + ", " + e.viewArrayChecker(expression.ViewRead) + ")"
		}
		return e.value(expression.Array) + ".join(" + e.value(expression.Separator) + ")"
	case ir.CharCodeAt:
		return e.value(expression.Value) + ".charCodeAt(" + e.value(expression.Index) + ")"
	case ir.Trim:
		return e.value(expression.Value) + ".trim()"
	case ir.StringCall:
		return e.value(expression.Value) + "." + expression.Method + "(" + e.values(expression.Arguments) + ")"
	case ir.CodePoints:
		return "[..." + e.value(expression.Value) + "]"
	case ir.ArrayIndex:
		if expression.View != "" {
			return e.emitViewArrayRead(expression)
		}
		if expression.Relative {
			return e.value(expression.Array) + ".at(" + e.value(expression.Index) + ")"
		}
		return e.value(expression.Array) + "[" + e.value(expression.Index) + "]"
	case ir.ArraySearch:
		if expression.ViewRead.View != "" {
			return e.emitViewArraySearch(expression)
		}
		method := ".indexOf("
		if expression.Includes {
			method = ".includes("
		}
		if expression.Last {
			method = ".lastIndexOf("
		}
		arguments := []ir.Expression{expression.Value}
		if expression.From != nil {
			arguments = append(arguments, expression.From)
		}
		return e.value(expression.Array) + method + e.values(arguments) + ")"
	case ir.ArrayFrom:
		return "adamicFrom(" + e.value(expression.Length) + ", " + e.value(expression.Callback) + ")"
	case ir.ArrayReverse:
		return e.value(expression.Array) + ".reverse()"
	case ir.ArrayRangeErrorIs:
		return "(" + e.value(expression.Value) + " instanceof RangeError)"
	case ir.ArraySetLength:
		return "(" + e.value(expression.Array) + ".length = " + e.value(expression.Length) + ")"
	case ir.ArrayHoles:
		return "new Array(" + e.value(expression.Length) + ")"
	case ir.ArrayFill:
		if expression.Array == nil {
			return "new Array(" + e.value(expression.Length) + ").fill(" + e.value(expression.Value) + ")"
		}
		arguments := []ir.Expression{expression.Value}
		if expression.Start != nil {
			arguments = append(arguments, expression.Start)
		}
		if expression.End != nil {
			arguments = append(arguments, expression.End)
		}
		return e.value(expression.Array) + ".fill(" + e.values(arguments) + ")"
	case ir.ArraySplice:
		arguments := []ir.Expression{expression.Start}
		if expression.Count != nil {
			arguments = append(arguments, expression.Count)
			arguments = append(arguments, expression.Items...)
		}
		return e.value(expression.Array) + ".splice(" + e.values(arguments) + ")"
	case ir.ArrayConcat:
		return e.value(expression.Array) + ".concat(" + e.values(expression.Others) + ")"
	case ir.ArrayReduce:
		if expression.ViewRead.View != "" {
			return "adamicViewReduce(" + e.value(expression.Array) + ", " + e.value(expression.Callback) + ", " + e.value(expression.Initial) + ", " + e.viewArrayChecker(expression.ViewRead) + ")"
		}
		return "adamicReduce(" + e.value(expression.Array) + ", " + e.value(expression.Callback) + ", " + e.value(expression.Initial) + ")"
	case ir.StringIndex:
		return e.value(expression.Value) + "[" + e.value(expression.Index) + "]"
	case ir.CheckedCast:
		if expression.CheckedFields {
			return "adamicCheckedViewCast(" + e.value(expression.Value) + ", " + quote(expression.Field) + ", " + fmt.Sprint(expression.FieldType) + ", [" + e.values(expression.Allowed) + "], " + quote(expression.Message) + ")"
		}
		return "adamicCast(" + e.value(expression.Value) + ", " + quote(expression.Field) + ", [" + e.values(expression.Allowed) + "], " + quote(expression.Message) + ")"
	case ir.ArrayPop:
		if expression.ViewRead.View != "" {
			return "adamicViewPop(" + e.value(expression.Array) + ", " + e.viewArrayChecker(expression.ViewRead) + ")"
		}
		return e.value(expression.Array) + ".pop()"
	case ir.ObjectKeys:
		return "Object.keys(" + e.value(expression.Object) + ")"
	case ir.ClosureSelf:
		return "self"
	case ir.LibraryGlobal:
		return expression.Name
	case ir.MakeClosure:
		cells := []string{}
		for _, local := range e.program.Functions[expression.Function].Environment {
			cells = append(cells, e.cell(local))
		}
		return fmt.Sprintf("new AdamicClosure(%s, [%s], %t)", functionName(e.program, expression.Function), strings.Join(cells, ", "), e.program.Functions[expression.Function].Receiver)
	case ir.CallClosure:
		if expression.Direct > 0 {
			return fmt.Sprintf("%s(self, [%s])", functionName(e.program, expression.Direct-1), e.values(expression.Arguments))
		}
		if property, ok := expression.Closure.(ir.Property); ok && property.View != "" {
			return "adamicCall(" + e.emitViewCallableProperty(property) + ", [" + e.values(expression.Arguments) + "])"
		}
		if property, isProperty := expression.Closure.(ir.Property); isProperty && property.Method {
			if property.Optional {
				// object?.name(...): undefined, with nothing looked up or evaluated, where the object is.
				return "adamicOptionalCall(" + e.value(property.Object) + ", " + quote(property.Name) + ", () => [" + e.values(expression.Arguments) + "])"
			}
			return "adamicCall(adamicCallee(" + e.value(property.Object) + ", " + quote(property.Name) + "), [" + e.values(expression.Arguments) + "])"
		}
		return "adamicCall(" + e.value(expression.Closure) + ", [" + e.values(expression.Arguments) + "])"
	case ir.ArrayMap:
		if expression.ViewRead.View != "" {
			return "adamicViewMap(" + e.value(expression.Array) + ", " + e.value(expression.Callback) + ", " + e.viewArrayChecker(expression.ViewRead) + ")"
		}
		if hasArrayHoles(e.program) {
			return "adamicVisit(" + e.value(expression.Array) + ", 'map', " + e.value(expression.Callback) + ")"
		}
		return "adamicMap(" + e.value(expression.Array) + ", " + e.value(expression.Callback) + ")"
	case ir.ArrayVisit:
		if expression.ViewRead.View != "" {
			method := "adamicViewVisit"
			if expression.Method == "find" || expression.Method == "findIndex" {
				method = "adamicViewFind"
			}
			return method + "(" + e.value(expression.Array) + ", " + quote(expression.Method) + ", " + e.value(expression.Callback) + ", " + e.viewArrayChecker(expression.ViewRead) + ")"
		}
		if expression.Method == "find" || expression.Method == "findIndex" || expression.Method == "findLast" || expression.Method == "findLastIndex" {
			return "adamicFind(" + e.value(expression.Array) + ", " + quote(expression.Method) + ", " + e.value(expression.Callback) + ")"
		}
		return "adamicVisit(" + e.value(expression.Array) + ", " + quote(expression.Method) + ", " + e.value(expression.Callback) + ")"
	case ir.CollectionIterator:
		return "adamicCollectionIterator(" + e.value(expression.Collection) + ", " + quote(expression.Part) + ")"
	case ir.MapNew:
		entries := []string{}
		for _, entry := range expression.Entries {
			entries = append(entries, "["+e.value(entry[0])+", "+e.value(entry[1])+"]")
		}
		if expression.Pairs != nil {
			return "new Map(" + e.value(expression.Pairs) + ")"
		}
		return "new Map([" + strings.Join(entries, ", ") + "])"
	case ir.MapKeys:
		return "[..." + e.value(expression.Map) + ".keys()]"
	case ir.MapValues:
		return "[..." + e.value(expression.Map) + ".values()]"
	case ir.MapClear:
		return e.value(expression.Map) + ".clear()"
	case ir.MapForEach:
		return "adamicCollectionVisit(" + e.value(expression.Map) + ", " + e.value(expression.Callback) + ")"
	case ir.MapGet:
		return e.value(expression.Map) + ".get(" + e.value(expression.Key) + ")"
	case ir.MapSet:
		return e.value(expression.Map) + ".set(" + e.value(expression.Key) + ", " + e.value(expression.Value) + ")"
	case ir.SetNew:
		if expression.Values == nil {
			return "new Set()"
		}
		return "new Set(" + e.value(expression.Values) + ")"
	case ir.SetAdd:
		return e.value(expression.Set) + ".add(" + e.value(expression.Value) + ")"
	case ir.SetValues:
		return "[..." + e.value(expression.Set) + "]"
	case ir.MapHas:
		return e.value(expression.Map) + ".has(" + e.value(expression.Key) + ")"
	case ir.MapDelete:
		return e.value(expression.Map) + ".delete(" + e.value(expression.Key) + ")"
	case ir.MapSize:
		return e.value(expression.Map) + ".size"
	case ir.HasOwn:
		return e.value(expression.Object) + ".hasOwnProperty(" + e.value(expression.Key) + ")"
	case ir.ReadTextFile:
		return "readTextFile(" + e.value(expression.Path) + ")"
	case ir.ProgramArguments:
		return "programArguments()"
	case ir.Utf8Length:
		return "utf8Length(" + e.value(expression.Text) + ")"
	case ir.Utf8At:
		return "utf8At(" + e.value(expression.Text) + ", " + e.value(expression.Index) + ")"
	case ir.ReadDirectory:
		return "readDirectory(" + e.value(expression.Path) + ")"
	case ir.RealPath:
		return "realPath(" + e.value(expression.Path) + ")"
	case ir.FileStatus:
		return "fileStatus(" + e.value(expression.Path) + ")"
	case ir.WriteTextFile:
		return "writeTextFile(" + e.value(expression.Path) + ", " + e.value(expression.Text) + ")"
	case ir.MapEntries:
		return "[..." + e.value(expression.Map) + "]"
	case ir.ArraySlice:
		if ir.HasArrayViews(e.program) {
			return "adamicViewSlice(" + e.value(expression.Array) + ", [" + e.values(expression.Arguments) + "])"
		}
		return e.value(expression.Array) + ".slice(" + e.values(expression.Arguments) + ")"
	case ir.ArraySort:
		if expression.Callback != nil {
			return "adamicSort(" + e.value(expression.Array) + ", " + e.value(expression.Callback) + ")"
		}
		return e.value(expression.Array) + ".sort(" + functionName(e.program, expression.Comparator) + ")"
	}
	panic(fmt.Sprintf("javascript: no JavaScript for %T", expression))
}

func (e *emitter) values(expressions []ir.Expression) string {
	values := []string{}
	for _, expression := range expressions {
		values = append(values, e.value(expression))
	}
	return strings.Join(values, ", ")
}

func zero(valueType ir.Type) string {
	switch valueType {
	case ir.Number:
		return "0"
	case ir.Boolean:
		return "false"
	case ir.String:
		return "''"
	}
	return "undefined"
}

// number is a double as a JavaScript literal that reads back as the same bits.
func number(value float64) string {
	switch {
	case value != value:
		return "NaN"
	case value > 1.7976931348623157e308:
		return "Infinity"
	case value < -1.7976931348623157e308:
		return "(-Infinity)"
	case value == 0 && 1/value < 0:
		return "(-0)"
	}
	return "(" + strconv.FormatFloat(value, 'g', -1, 64) + ")"
}

// quote is a JavaScript string literal for a string the checker gave as WTF-8: every code unit
// outside printable ASCII is written as \uXXXX, so a lone surrogate survives as itself.
func quote(text string) string {
	var builder strings.Builder
	builder.WriteByte('"')
	for index := 0; index < len(text); {
		lead := text[index]
		size := 1
		var point rune
		switch {
		case lead < 0x80:
			point = rune(lead)
		case lead < 0xe0:
			size, point = 2, rune(lead&0x1f)<<6|rune(text[index+1]&0x3f)
		case lead < 0xf0:
			size, point = 3, rune(lead&0x0f)<<12|rune(text[index+1]&0x3f)<<6|rune(text[index+2]&0x3f)
		default:
			size, point = 4, rune(lead&0x07)<<18|rune(text[index+1]&0x3f)<<12|rune(text[index+2]&0x3f)<<6|rune(text[index+3]&0x3f)
		}
		index += size
		switch {
		case point == '"' || point == '\\':
			builder.WriteByte('\\')
			builder.WriteRune(point)
		case point >= 0x20 && point < 0x7f:
			builder.WriteRune(point)
		case point > 0xffff:
			point -= 0x10000
			fmt.Fprintf(&builder, "\\u%04x\\u%04x", 0xd800+(point>>10), 0xdc00+(point&0x3ff))
		default:
			fmt.Fprintf(&builder, "\\u%04x", point)
		}
	}
	builder.WriteByte('"')
	return builder.String()
}

// narrowedAwayMessage is native's (internal/native), word for word: the checks are the same on both sides.
const narrowedAwayMessage = "undefined where the checker narrowed it away: a call since the narrowing put it back"

func (e *emitter) ready(local int) string {
	if e.program.Locals[local].Captured && !e.program.Locals[local].Global {
		return e.cell(local) + ".ready"
	}
	return readyName(local)
}

func (e *emitter) allocateEnvironment(cells []int) {
	if len(cells) == 0 {
		return
	}
	environment := e.temporary()
	e.line("const %s = Array.from({length: %d}, () => ({value: undefined, ready: false}));", environment, len(cells))
	for position, local := range cells {
		e.line("const %s = %s[%d];", e.cellName(local), environment, position)
	}
}
