import pathlib,json,statistics,gzip,shutil,hashlib,re
p=pathlib.Path('review/test-audit/stage1-cohere-formatfiles-formatfiles_shards');scope=json.loads((p/'scope.json').read_text());matrix=json.loads((p/'matrix.json').read_text());probe=json.loads((p/'probe-result.json').read_text());harness=json.loads((p/'harness-probes.json').read_text());timings=json.loads((p/'timings.json').read_text());plan=json.loads((p/'mutant-plan.json').read_text());family='TestThePortParsesAsGoCohereDoes family';witness='TestFormatfilesShardPlantedDisagreement';members=scope['tests'][1:];text=pathlib.Path('stage1/cohere/formatfiles/formatfiles_shards_test.go').read_text()
for q in matrix:assert not q['cooked'];assert q['kills'];assert all(t in members for t in q['kills'])
wf=next(e['Output'].strip() for e in harness[0]['events'] if 'caught by []' in e.get('Output',''));last=matrix[-1];failure=next(e['Output'].strip() for e in last['events'] if 'native and Go cohere differ' in e.get('Output',''))
empty_hits=[e for e in probe['events'] if 'caught: line 1: "", Go cohere "tree ' in e.get('Output','')];assert len(empty_hits)==24
seconds={label:statistics.median([q['seconds'] for q in timings if q['label']==label]) for label in ['witness','family']}
report=[dict(test=witness,package='stage1/cohere/formatfiles',file='stage1/cohere/formatfiles/formatfiles_shards_test.go:'+str(text[:text.index('func '+witness+'(')].count('\n')+1),seconds=seconds['witness'],oracle='Self-written expectation that one planted output difference is caught only by its hash-assigned owner. W01 disables firstDifference; the witness then fails.',oracle_kind='self',kills=[],unique_kills=[],last_proven_fail='W01: '+wf,verdict='witness',subsumed_by=[],mutants_in_matrix=4,probe_kills=[],subsumer_seconds=None,vacuous=None,bounded=False,matrix_rows=[],evidence=harness[0]['command']+'; '+wf),dict(test=family,package='stage1/cohere/formatfiles',file='stage1/cohere/formatfiles/formatfiles_shards_test.go:'+str(text[:text.index('func '+members[0]+'(')].count('\n')+1),members=members,seconds=seconds['family'],oracle='Go cohere executes the same fixture trees and emits expected bytes. Native, port-on-Node and JavaScript backend stdout must match; exits/stderr checked. Self-written corpus coverage, embedded mutant-disagreement expectations and zero-leak contract are additional checks. Embedded disagreement checks accept an empty driver under P01.',oracle_kind=['external-run','self'],kills=[q['id'] for q in matrix],unique_kills=[q['id'] for q in matrix],last_proven_fail=last['id']+': '+failure,verdict='sacred',subsumed_by=[],mutants_in_matrix=4,probe_kills=['P01'],subsumer_seconds=None,vacuous=False,vacuous_subcases=['Embedded mutant-disagreement checks for all 12 built-in mutants: 24 native/Node comparisons accept empty output under P01.'],probe_exempt_members=['TestThePortParsesAsGoCohereDoesUnion: construction-only member does not execute the port entry.'],bounded=False,matrix_rows=[],evidence=last['command']+'; /tmp/u092/mutant contains M04; '+failure,union_construction_evidence=harness[1]['command']+'; '+next(e['Output'].strip() for e in harness[1]['events'] if 'invalid leaf declaration' in e.get('Output','')))]
(p/'report.json').write_text(json.dumps(report,indent=2)+'\n')
summary='Unit u092: all 34 requested Test names exist; two grouped rows.\nBase '+scope['base']+'; nproc 5; warm toolchain.\nWhole-package clean baseline passed in 28.427 seconds; no skips.\nFour native-port mutants killed only by the shard family, package-unique after grouping.\nVerdicts: shard family sacred; planted-disagreement row witness.\n'
table='| ID | origin/main location | One-line change | Failed grouped rows | Failed leaves |\n|---|---|---|---|---|\n'
for q,m in zip(plan,matrix):table+=f"| {q['id']} | {q['file']}:{q['line']} | `{q['old']}` to `{q['new']}` | {family} | {len(m['kills'])} |\n"
notes='''Survivors: none among the four production mutants. Every run completed below 90 seconds. No equivalent candidates claimed.

Findings, scope and brief complications:
- The brief cites origin/main 8de93800f4; fetched main was 3a1c8b5792fb66503290d2d494ce96302bc4386d. All 34 named functions still exist in formatfiles_shards_test.go. No moved or vanished names. The introduction says two rows and the end lists 34 functions; grouping gives one witness and one family.
- The Union has distinct construction assertions while the family rule explicitly names numbered shards plus union as a family. Following that explicit shape and the brief's two-row scope, Union is included as a construction member. Its S01 failure is reported separately and never supports the family's sacred verdict. It does not execute the port, so the port-entry probe is not its own entry probe.
- CODE UNDER TEST: formatfiles .ts port, main.ts module entry, imported gitignore path/glob/matcher code. The production declaration inventory is source-function-inventory.json. observed-functions.json plus node-coverage.json.gz record 155 observed V8 function entries across original and built-in-mutant TypeScript module copies, including module bodies and callbacks. These entries are not claimed to be 155 unique source declarations. The witness checks the suite's firstDifference comparison.
- ORACLE: original Go cohere formatfiles operates on the same on-disk trees and emits byte-for-byte expected output. No Go cohere, oracle script, corpus or assertion was mutated for production evidence. Native products were rebuilt for each standalone .ts mutant; all compiled successfully before the switch matrix. All four faults were caught in native output, and also by Node/backend comparisons.
- Whole package has 50 top-level Tests. Each matrix run used -run . with count=1 and a 90-second binary timeout. None cooked or panicked. Only numbered shard leaves failed. Grouping makes each mutant a single-family kill and therefore package-unique. Repo-wide uniqueness is left for central replay; no other Adamic package was tested. The Go cohere child oracle is required by this package's own tests, not a broad repo replay.
- Four fixed menu mutations span enumeration accounting, disk classification, Unicode lowercase mapping and escaped output. The approximate six-mutant target for two rows conflicts with the at-most-four rebuild advice; the witness is not a production row in any event. No inserted production statement supports a verdict.
- Existing built-in port mutation sites must remain present: otherwise the suite fails during preparation rather than on an answer. All four audit edits avoid those exact-match sites. The scratch selector is read from /tmp/u092/mutant by the port. Its helper statements are scaffolding, absent from standalone diffs; the neutral switched whole-package baseline passed before any selected mutation ran.
- The port's entry is top-level module execution, not a named main function. P01 removes the whole executable driver from const casesPath onward, leaving declarations/imports and producing no output with exit zero. Its standalone native build passed. Every execution shard rejects it; Union passes because it checks partition construction rather than executing the entry. Family vacuity is false.
- P01 exposes a narrower weakness: all twelve built-in mutant-disagreement checks accept empty output as a successful difference, 24 comparisons total across native and Node. Example: formatfiles_check_test.go:96: natively, caught: line 1: "", Go cohere "tree cohere 0". The ordinary baseline comparisons reject that output, so this is a vacuous embedded check finding, not a vacuous whole family.
- W01 returns an empty difference from firstDifference, leaving witness planting and ownership assertions intact. The witness fails with caught by [], want only 4. Its failures under production mutations do not count; only this weakened-comparison run establishes witness.
- S01 changes the construction shard count from 32 to 31. Union fails on the existing _031 declaration. This is separately permitted setup evidence and is never counted as a production kill.
- The family combines external-run Go comparisons with self-written coverage and disagreement expectations. Its leak check also relies on success status from LeakSanitizer on Linux. The exact-output oracle distinguishes M04's changed escape spelling while output remains successful; this is not merely a count/exit-code catch.
- No opt-in, skipped row or missing-tool skip occurred in clean, matrix or probe runs. Warm toolchain setup was skipped; npm ci ran before the baseline. Tests use warm product caching but always regenerate the current port IR and source-dependent keys. Port selector values are runtime inputs, so switched products can be reused safely. No compiler code was mutated and no stale native product was used.
- Rebuild measurements are full native-product test command wall times, including lowering and C emission plus Go command overhead, not isolated clang time. The switch baseline includes building all switched products. Matrix runs reuse those unchanged switched products. Distinct standalone validation caches are listed in mutant-plan.json.
- The complete restored-source package passed again. Runtime leak behavior on Darwin, ungenerated seeds, larger corpora and repo-wide replay were not covered. No permission or automatic-review block occurred.

Timing:
'''
notes+='Toolchain setup skipped; nproc 5. npm ci log is preserved. Clean package binary 28.427 s.\n'
for label in ['witness','family']:notes+=label+': samples '+str([q['seconds'] for q in timings if q['label']==label])+', median '+str(seconds[label])+' s.\n'
for q in plan:notes+=q['id']+': standalone native rebuild command wall '+f"{q['validation']['wall_seconds']:.3f}"+' s.\n'
for q in matrix:notes+=q['id']+': matrix command wall '+f"{q['wall_seconds']:.3f}"+' s.\n'
notes+='P01 command wall '+f"{probe['wall_seconds']:.3f}"+' s.\n'
restored=json.loads((p/'restored.json').read_text());notes+='Restored whole-package command wall '+f"{restored['wall_seconds']:.3f}"+' s. Exact binary elapsed and switch build measurements are preserved in their JSON/logs.\n'
(p/'REPORT.txt').write_text(summary+'\n'+json.dumps(report,indent=2)+'\n\n'+table+'\n'+notes)
for f in ['/tmp/u092-measure.py','/tmp/u092-audit.py','/tmp/u092-finish.py','/tmp/u092-report.py']:shutil.copy(f,p/pathlib.Path(f).name)
for f in (p/'logs').glob('*.log'):
 with f.open('rb') as inp,gzip.open(str(f)+'.gz','wb') as out:shutil.copyfileobj(inp,out)
 f.unlink()
(p/'SHA256SUMS').write_text(''.join(hashlib.sha256(f.read_bytes()).hexdigest()+'  '+str(f.relative_to(p))+'\n' for f in sorted(p.rglob('*')) if f.is_file() and f.name!='SHA256SUMS'))
