
// Code generated by 'go test'. DO NOT EDIT.

package main

import (
	"os"

	"testing"
	"testing/internal/testdeps"



	_test "github.com/system-inc/adamic/internal/lower"


)

var tests = []testing.InternalTest{

	{"TestArgumentsLengthRefusals", _test.TestArgumentsLengthRefusals},

	{"TestArgumentsLengthReadNeighbors", _test.TestArgumentsLengthReadNeighbors},

	{"TestArgumentsLengthRefusalFixtures", _test.TestArgumentsLengthRefusalFixtures},

	{"TestArrayPredicatePreservesDeclaredElementContract", _test.TestArrayPredicatePreservesDeclaredElementContract},

	{"TestArrayPredicateCannotInventAnElementContract", _test.TestArrayPredicateCannotInventAnElementContract},

	{"TestArrayPredicateDoesNotMisclassifyNativeTuples", _test.TestArrayPredicateDoesNotMisclassifyNativeTuples},

	{"TestUnknownArrayPredicateRefusesUnrepresentedObservations", _test.TestUnknownArrayPredicateRefusesUnrepresentedObservations},

	{"TestArrayPredicateCoexistsWithUnknownReflection", _test.TestArrayPredicateCoexistsWithUnknownReflection},

	{"TestUncheckableCastsStayRefused", _test.TestUncheckableCastsStayRefused},

	{"TestCheckedCastProofAndElision", _test.TestCheckedCastProofAndElision},

	{"TestCensusMarkerResultIsAssignable", _test.TestCensusMarkerResultIsAssignable},

	{"TestCensusMarkerZeroCallIsNotAssumedSafe", _test.TestCensusMarkerZeroCallIsNotAssumedSafe},

	{"TestOptionalFunctionValueRelation", _test.TestOptionalFunctionValueRelation},

	{"TestOverloadedShorthandFunctionValueStaysNotYet", _test.TestOverloadedShorthandFunctionValueStaysNotYet},

	{"TestCensusOverloadBinderGuards", _test.TestCensusOverloadBinderGuards},

	{"TestCensusOverloadReturnProof", _test.TestCensusOverloadReturnProof},

	{"TestCensusPredicateInteractionBoundary", _test.TestCensusPredicateInteractionBoundary},

	{"TestCensusPredicateInteractionEscapes", _test.TestCensusPredicateInteractionEscapes},

	{"TestCensusPredicateMarkerKeepsProofBoundaries", _test.TestCensusPredicateMarkerKeepsProofBoundaries},

	{"TestCensusPredicateMarkerCallStaysNotYet", _test.TestCensusPredicateMarkerCallStaysNotYet},

	{"TestCensusOverloadRelation", _test.TestCensusOverloadRelation},

	{"TestCensusSmallFiniteKeyRead", _test.TestCensusSmallFiniteKeyRead},

	{"TestCensusRestMutableElements", _test.TestCensusRestMutableElements},

	{"TestCensusBooleanDeadBranch", _test.TestCensusBooleanDeadBranch},

	{"TestCheckPragmasAreRefused", _test.TestCheckPragmasAreRefused},

	{"TestCheckPragmaNeighborsCompile", _test.TestCheckPragmaNeighborsCompile},

	{"TestTsgoHonorsNoCheckInAdamicFiles", _test.TestTsgoHonorsNoCheckInAdamicFiles},

	{"TestClassFeaturesReadonlyChecker", _test.TestClassFeaturesReadonlyChecker},

	{"TestClassFeaturesPrivateChecker", _test.TestClassFeaturesPrivateChecker},

	{"TestClassFeaturesPrivateStorage", _test.TestClassFeaturesPrivateStorage},

	{"TestClassFeaturesAccessorRefusals", _test.TestClassFeaturesAccessorRefusals},

	{"TestClassFeaturesStaticDeclarationsExecute", _test.TestClassFeaturesStaticDeclarationsExecute},

	{"TestClassFeaturesStaticSoundness", _test.TestClassFeaturesStaticSoundness},

	{"TestClassFeaturesAccessorCaptureCycle", _test.TestClassFeaturesAccessorCaptureCycle},

	{"TestClassFeaturesNarrowedAccessor", _test.TestClassFeaturesNarrowedAccessor},

	{"TestClassFeaturesStaticParentCycle", _test.TestClassFeaturesStaticParentCycle},

	{"TestClassFeaturesStaticInterfaceCycle", _test.TestClassFeaturesStaticInterfaceCycle},

	{"TestInheritanceRefusesUnsoundOverrides", _test.TestInheritanceRefusesUnsoundOverrides},

	{"TestInheritanceKeepsCheckerConstructorRules", _test.TestInheritanceKeepsCheckerConstructorRules},

	{"TestInheritanceAllowsSoundOverrides", _test.TestInheritanceAllowsSoundOverrides},

	{"TestInheritanceHasClassIdentity", _test.TestInheritanceHasClassIdentity},

	{"TestInheritanceCycleFinderIncludesInheritedFields", _test.TestInheritanceCycleFinderIncludesInheritedFields},

	{"TestInheritanceRejectsUnsupportedConstructorShapes", _test.TestInheritanceRejectsUnsupportedConstructorShapes},

	{"TestInheritanceRefusesFalseNominalViews", _test.TestInheritanceRefusesFalseNominalViews},

	{"TestInheritanceRefusesThisBeforeSuperReturns", _test.TestInheritanceRefusesThisBeforeSuperReturns},

	{"TestInheritanceKeepsNominalTupleDestructuring", _test.TestInheritanceKeepsNominalTupleDestructuring},

	{"TestInheritanceGenericMonomorphizations", _test.TestInheritanceGenericMonomorphizations},

	{"TestInheritanceRefusesGrowingGenericClasses", _test.TestInheritanceRefusesGrowingGenericClasses},

	{"TestInheritanceGenericSoundness", _test.TestInheritanceGenericSoundness},

	{"TestInheritanceConditionalThisRules", _test.TestInheritanceConditionalThisRules},

	{"TestInheritanceGenericViewsKeepNominalArguments", _test.TestInheritanceGenericViewsKeepNominalArguments},

	{"TestInheritanceGenericNominalConstraints", _test.TestInheritanceGenericNominalConstraints},

	{"TestInheritanceGenericFactoryLayouts", _test.TestInheritanceGenericFactoryLayouts},

	{"TestInheritanceNativeSignatureNeighbors", _test.TestInheritanceNativeSignatureNeighbors},

	{"TestInheritanceNativeSignatureLimits", _test.TestInheritanceNativeSignatureLimits},

	{"TestClassArgumentsUseCheckerIdentity", _test.TestClassArgumentsUseCheckerIdentity},

	{"TestClassWrongOutputIteratorReceiver", _test.TestClassWrongOutputIteratorReceiver},

	{"TestClassWrongOutputKeysRepair", _test.TestClassWrongOutputKeysRepair},

	{"TestClassWrongOutputPrivateRepair", _test.TestClassWrongOutputPrivateRepair},

	{"TestClockGenericReturnsT01Shapes", _test.TestClockGenericReturnsT01Shapes},

	{"TestClockGenericReturnsT01DeclinesBrandedPrimitives", _test.TestClockGenericReturnsT01DeclinesBrandedPrimitives},

	{"TestClockGenericReturnsT01RejectsNullBeforeBody", _test.TestClockGenericReturnsT01RejectsNullBeforeBody},

	{"TestClockGenericReturnsT01RejectsIndexBeforeBody", _test.TestClockGenericReturnsT01RejectsIndexBeforeBody},

	{"TestDefiniteAssignmentUsesReadiness", _test.TestDefiniteAssignmentUsesReadiness},

	{"TestDefiniteAssignmentSoundNeighbors", _test.TestDefiniteAssignmentSoundNeighbors},

	{"TestNestedEmptyArrayElementKinds", _test.TestNestedEmptyArrayElementKinds},

	{"TestEmptyLiteralGenericReturnUsesSamePath", _test.TestEmptyLiteralGenericReturnUsesSamePath},

	{"TestEntriesAllocationProof", _test.TestEntriesAllocationProof},

	{"TestEntriesRecordBoundaries", _test.TestEntriesRecordBoundaries},

	{"TestFlagEnumsOpen", _test.TestFlagEnumsOpen},

	{"TestFlagEnumsDomain", _test.TestFlagEnumsDomain},

	{"TestEnumNeverDefault", _test.TestEnumNeverDefault},

	{"TestFlagEnumLiteralSpellings", _test.TestFlagEnumLiteralSpellings},

	{"TestFlagEnumMemberAliases", _test.TestFlagEnumMemberAliases},

	{"TestEnumNameEnumeration", _test.TestEnumNameEnumeration},

	{"TestFlagEnumInlineIteration", _test.TestFlagEnumInlineIteration},

	{"TestFlagEnumAliasBoundaries", _test.TestFlagEnumAliasBoundaries},

	{"TestEnumInitializationReach", _test.TestEnumInitializationReach},

	{"TestEnumInitializationGraphMemo", _test.TestEnumInitializationGraphMemo},

	{"TestEnumNamespaceSharedCycle", _test.TestEnumNamespaceSharedCycle},

	{"TestNumericEnumsAreOpen", _test.TestNumericEnumsAreOpen},

	{"TestStringEnumsStayClosed", _test.TestStringEnumsStayClosed},

	{"TestNumericEnumNeverProof", _test.TestNumericEnumNeverProof},

	{"TestNumericEnumLiteralPromises", _test.TestNumericEnumLiteralPromises},

	{"TestEnumSlotViews", _test.TestEnumSlotViews},

	{"TestEnumSwitchExhaustiveness", _test.TestEnumSwitchExhaustiveness},

	{"TestEnumLimitsStayLoud", _test.TestEnumLimitsStayLoud},

	{"TestConstEnumErasesRuntimeObject", _test.TestConstEnumErasesRuntimeObject},

	{"TestEnumIdentityAcrossModules", _test.TestEnumIdentityAcrossModules},

	{"TestReadonlyFieldsAreJudgedByTheirConstructorsWrites", _test.TestReadonlyFieldsAreJudgedByTheirConstructorsWrites},

	{"TestFunctionValueUnionViewsStayNotYet", _test.TestFunctionValueUnionViewsStayNotYet},

	{"TestGenericFunctionPolymorphicRecursionIsRefused", _test.TestGenericFunctionPolymorphicRecursionIsRefused},

	{"TestGenericUnionFixtureHasSeparateInstances", _test.TestGenericUnionFixtureHasSeparateInstances},

	{"TestGenericJSONUnionArrayIsNotYet", _test.TestGenericJSONUnionArrayIsNotYet},

	{"TestOriginalCycleLedger", _test.TestOriginalCycleLedger},

	{"TestUndecidedCycleReadsUseReadyChecks", _test.TestUndecidedCycleReadsUseReadyChecks},

	{"TestInputSpreadArgumentsAreNotYet", _test.TestInputSpreadArgumentsAreNotYet},

	{"TestInputSpreadCoverage", _test.TestInputSpreadCoverage},

	{"TestDefaultTaggedInterfaceAdmission", _test.TestDefaultTaggedInterfaceAdmission},

	{"TestDefaultTaggedInterfaceNeedsNoFlag", _test.TestDefaultTaggedInterfaceNeedsNoFlag},

	{"TestIteratorGapsAreExplicit", _test.TestIteratorGapsAreExplicit},

	{"TestIteratorViewsCannotHideReturn", _test.TestIteratorViewsCannotHideReturn},

	{"TestIteratorViewsCannotEraseReceivers", _test.TestIteratorViewsCannotEraseReceivers},

	{"TestIteratorDestructuringDoesNotLieAboutExhaustion", _test.TestIteratorDestructuringDoesNotLieAboutExhaustion},

	{"TestGeneratorsAreRefusedEvenWithoutYield", _test.TestGeneratorsAreRefusedEvenWithoutYield},

	{"TestLiteralMethodCapturesCannotMakeCycles", _test.TestLiteralMethodCapturesCannotMakeCycles},

	{"TestLiteralMethodViewsDoNotLoseThis", _test.TestLiteralMethodViewsDoNotLoseThis},

	{"TestIteratorDescriptorReasons", _test.TestIteratorDescriptorReasons},

	{"TestRepresentedMethodReplacementIsNotYet", _test.TestRepresentedMethodReplacementIsNotYet},

	{"TestDestructuredMethodsCannotLoadOwnSlots", _test.TestDestructuredMethodsCannotLoadOwnSlots},

	{"TestGenericIteratorViewsPreserveNativeArguments", _test.TestGenericIteratorViewsPreserveNativeArguments},

	{"TestIteratorMapperIndexHasNumberRepresentation", _test.TestIteratorMapperIndexHasNumberRepresentation},

	{"TestIteratorSymbolKeysAreNotStringKeys", _test.TestIteratorSymbolKeysAreNotStringKeys},

	{"TestLibraryLanguageBoundaries", _test.TestLibraryLanguageBoundaries},

	{"TestLibraryMapSetGapsStayRefused", _test.TestLibraryMapSetGapsStayRefused},

	{"TestLibraryMapSetIteratorCopyTypesRefused", _test.TestLibraryMapSetIteratorCopyTypesRefused},

	{"TestLibraryMethodValues", _test.TestLibraryMethodValues},

	{"TestLibraryMethodValueBoundaries", _test.TestLibraryMethodValueBoundaries},

	{"TestLibraryMethodValueSafety", _test.TestLibraryMethodValueSafety},

	{"TestNodeBufferRefusals", _test.TestNodeBufferRefusals},

	{"TestNodeFSFileOptionsBorrow", _test.TestNodeFSFileOptionsBorrow},

	{"TestNodeFSFileDoesNotAuthorizeMutableWidening", _test.TestNodeFSFileDoesNotAuthorizeMutableWidening},

	{"TestNodeFSFileRefusesOptionEffects", _test.TestNodeFSFileRefusesOptionEffects},

	{"TestNodeFSFileRefusesVoidValues", _test.TestNodeFSFileRefusesVoidValues},

	{"TestNodeFSFileRefusesPinnedUnsupportedOverloads", _test.TestNodeFSFileRefusesPinnedUnsupportedOverloads},

	{"TestNodeFSFileNamespaceImport", _test.TestNodeFSFileNamespaceImport},

	{"TestNodeFSFileQualifiedErrorType", _test.TestNodeFSFileQualifiedErrorType},

	{"TestNodeFSFileKeepsDetachedMethodRefusal", _test.TestNodeFSFileKeepsDetachedMethodRefusal},

	{"TestNodeFSFileBufferBorrow", _test.TestNodeFSFileBufferBorrow},

	{"TestNodeFSFileScratchOptionsBorrow", _test.TestNodeFSFileScratchOptionsBorrow},

	{"TestNodeFSFileScratchOverloadsAreNamed", _test.TestNodeFSFileScratchOverloadsAreNamed},

	{"TestNodeLibraryNamesUnimplementedMembers", _test.TestNodeLibraryNamesUnimplementedMembers},

	{"TestNodeLibraryDoesNotRefuseTypeOnlyOrUserNames", _test.TestNodeLibraryDoesNotRefuseTypeOnlyOrUserNames},

	{"TestNodeLibraryDistinguishesReceiverOwners", _test.TestNodeLibraryDistinguishesReceiverOwners},

	{"TestNodeLibraryQualifiedTypeAssertion", _test.TestNodeLibraryQualifiedTypeAssertion},

	{"TestObjectRefusalsExplainSoundness", _test.TestObjectRefusalsExplainSoundness},

	{"TestObjectUnprovenShapesStayNotYet", _test.TestObjectUnprovenShapesStayNotYet},

	{"TestLibraryRegexOffsetRequiresNoCaptures", _test.TestLibraryRegexOffsetRequiresNoCaptures},

	{"TestLibraryStringRefusals", _test.TestLibraryStringRefusals},

	{"TestConsoleLowersToWriteLine", _test.TestConsoleLowersToWriteLine},

	{"TestWhatStageZeroCannotLowerIsRefusedWithWhereAndWhat", _test.TestWhatStageZeroCannotLowerIsRefusedWithWhereAndWhat},

	{"TestWhatZeroOneRefusesIsRefusedWithAFix", _test.TestWhatZeroOneRefusesIsRefusedWithAFix},

	{"TestAMutableLocationSeenWiderIsRefused", _test.TestAMutableLocationSeenWiderIsRefused},

	{"TestAViewThatCantWriteIsNotRefused", _test.TestAViewThatCantWriteIsNotRefused},

	{"TestATupleSeenAsAnArrayIsNotYet", _test.TestATupleSeenAsAnArrayIsNotYet},

	{"TestAMethodReadAsAValueIsRefused", _test.TestAMethodReadAsAValueIsRefused},

	{"TestModuleNamespaceLimitsStayLoud", _test.TestModuleNamespaceLimitsStayLoud},

	{"TestModuleNamespaceInitializedReadProof", _test.TestModuleNamespaceInitializedReadProof},

	{"TestCallableNamespaceLimitsStayLoud", _test.TestCallableNamespaceLimitsStayLoud},

	{"TestCallableNamespaceReceiverStaysLoud", _test.TestCallableNamespaceReceiverStaysLoud},

	{"TestNamespaceClassEarlyConstructionStaysLoud", _test.TestNamespaceClassEarlyConstructionStaysLoud},

	{"TestNamespaceReceiverArrowInheritsScope", _test.TestNamespaceReceiverArrowInheritsScope},

	{"TestNamespaceAmbientHostInitialization", _test.TestNamespaceAmbientHostInitialization},

	{"TestNamespaceAmbientContextsDoNotExecute", _test.TestNamespaceAmbientContextsDoNotExecute},

	{"TestNamespaceCallGraphLinearWork", _test.TestNamespaceCallGraphLinearWork},

	{"TestNamespaceCallGraphCycleUnion", _test.TestNamespaceCallGraphCycleUnion},

	{"TestNamespaceEnumInitializationIndependentOfModuleAnalysis", _test.TestNamespaceEnumInitializationIndependentOfModuleAnalysis},

	{"TestParserFactoryBindingHoisting", _test.TestParserFactoryBindingHoisting},

	{"TestMissingBindingSymbolHasStructuredLocation", _test.TestMissingBindingSymbolHasStructuredLocation},

	{"TestTscNamespaceDeclarationShapes", _test.TestTscNamespaceDeclarationShapes},

	{"TestNamespaceLimitsStayLoud", _test.TestNamespaceLimitsStayLoud},

	{"TestNamespaceReceiverRefusal", _test.TestNamespaceReceiverRefusal},

	{"TestNamespaceTypesErase", _test.TestNamespaceTypesErase},

	{"TestTracingNamespaceEscapeStaysNotYet", _test.TestTracingNamespaceEscapeStaysNotYet},

	{"TestDebugNamespaceMergedCapabilities", _test.TestDebugNamespaceMergedCapabilities},

	{"TestNamespaceReturnedAssignmentLimits", _test.TestNamespaceReturnedAssignmentLimits},

	{"TestNamespaceInitializationReachability", _test.TestNamespaceInitializationReachability},

	{"TestNamespaceClosedCallGraphEdges", _test.TestNamespaceClosedCallGraphEdges},

	{"TestEmptyNeverMapCannotGainWritableInhabitants", _test.TestEmptyNeverMapCannotGainWritableInhabitants},

	{"TestNestedFunctionGapsAreLoud", _test.TestNestedFunctionGapsAreLoud},

	{"TestNestedFunctionCycleIsRefused", _test.TestNestedFunctionCycleIsRefused},

	{"TestNestedEnvironmentHasOneAllocationSite", _test.TestNestedEnvironmentHasOneAllocationSite},

	{"TestNestedEnvironmentCycleIncludesDisjointSlots", _test.TestNestedEnvironmentCycleIncludesDisjointSlots},

	{"TestNestedCapturedParametersAreOwned", _test.TestNestedCapturedParametersAreOwned},

	{"TestClosedFrameInputRejectsMutation", _test.TestClosedFrameInputRejectsMutation},

	{"TestNestedRebindingNotYet", _test.TestNestedRebindingNotYet},

	{"TestNestedCallbackCycleIsRefused", _test.TestNestedCallbackCycleIsRefused},

	{"TestNestedBodylessDeclarationsAreLoud", _test.TestNestedBodylessDeclarationsAreLoud},

	{"TestNestedRestIsSupported", _test.TestNestedRestIsSupported},

	{"TestAdamicNullishAssertionsAreRefused", _test.TestAdamicNullishAssertionsAreRefused},

	{"TestNonNullAssertionLowersToNullishPanic", _test.TestNonNullAssertionLowersToNullishPanic},

	{"TestNonNullAssertionOnPresentTypeIsErased", _test.TestNonNullAssertionOnPresentTypeIsErased},

	{"TestOptionalIndexingMapShapeRefused", _test.TestOptionalIndexingMapShapeRefused},

	{"TestOptionalIndexingKeepsIndexSignaturesRefused", _test.TestOptionalIndexingKeepsIndexSignaturesRefused},

	{"TestOptionalIndexingKeepsUnsupportedStorageNotYet", _test.TestOptionalIndexingKeepsUnsupportedStorageNotYet},

	{"TestOptionalWideningCensus", _test.TestOptionalWideningCensus},

	{"TestOptionalWideningRefused", _test.TestOptionalWideningRefused},

	{"TestOptionalWideningAllowed", _test.TestOptionalWideningAllowed},

	{"TestOptionalWideningSpreadOverwrite", _test.TestOptionalWideningSpreadOverwrite},

	{"TestOverloadInferenceWitnesses", _test.TestOverloadInferenceWitnesses},

	{"TestAbfe962OverrideDefaultAddedRefusesNativeSignature", _test.TestAbfe962OverrideDefaultAddedRefusesNativeSignature},

	{"TestOverrideOptionalNumberRefusesNativeSignature", _test.TestOverrideOptionalNumberRefusesNativeSignature},

	{"TestOverrideOptionalRefusesNativeSignature", _test.TestOverrideOptionalRefusesNativeSignature},

	{"TestParameterPropertiesSoundness", _test.TestParameterPropertiesSoundness},

	{"TestParameterPropertyCheckerContracts", _test.TestParameterPropertyCheckerContracts},

	{"TestParameterPropertyCallbackReceiver", _test.TestParameterPropertyCallbackReceiver},

	{"TestPredicateSummaryParameterIndex", _test.TestPredicateSummaryParameterIndex},

	{"TestPredicateOverloadRuntime", _test.TestPredicateOverloadRuntime},

	{"TestIndirectPredicateOverloadIsPending", _test.TestIndirectPredicateOverloadIsPending},

	{"TestPredicateBodyProof", _test.TestPredicateBodyProof},

	{"TestConditionAssertionAdmission", _test.TestConditionAssertionAdmission},

	{"TestPredicateCallbackContracts", _test.TestPredicateCallbackContracts},

	{"TestEveryNeedsCallbackEffects", _test.TestEveryNeedsCallbackEffects},

	{"TestPredicateOverloadCallback", _test.TestPredicateOverloadCallback},

	{"TestPredicateUseRegions", _test.TestPredicateUseRegions},

	{"TestPredicateUsesBelongToEachCall", _test.TestPredicateUsesBelongToEachCall},

	{"TestUnprovenPredicateReturnsAreRefused", _test.TestUnprovenPredicateReturnsAreRefused},

	{"TestPredicateBodiesAreProven", _test.TestPredicateBodiesAreProven},

	{"TestPrimitiveAdmittingSlotsUseBoxes", _test.TestPrimitiveAdmittingSlotsUseBoxes},

	{"TestInheritedLibraryReadsNeverLoadOwnFields", _test.TestInheritedLibraryReadsNeverLoadOwnFields},

	{"TestPrototypeMethodsAreRefusedWithReasons", _test.TestPrototypeMethodsAreRefusedWithReasons},

	{"TestNullishPrototypeReadsAreRejectedByChecker", _test.TestNullishPrototypeReadsAreRejectedByChecker},

	{"TestPrototypeHazardsBehindObjectViewsAreNotYet", _test.TestPrototypeHazardsBehindObjectViewsAreNotYet},

	{"TestUnrepresentedPrototypeCallsAreNotYet", _test.TestUnrepresentedPrototypeCallsAreNotYet},

	{"TestIsPrototypeOfReadsExplainThePrototypeRefusal", _test.TestIsPrototypeOfReadsExplainThePrototypeRefusal},

	{"TestProvenRelationsRefuse", _test.TestProvenRelationsRefuse},

	{"TestProvenRelationsErase", _test.TestProvenRelationsErase},

	{"TestReadinessElisionRequiresDominatingAssignment", _test.TestReadinessElisionRequiresDominatingAssignment},

	{"TestRegExpNativeRefusals", _test.TestRegExpNativeRefusals},

	{"TestRegExpSourceNode", _test.TestRegExpSourceNode},

	{"TestRepresentationClockSourceCheckedTypes", _test.TestRepresentationClockSourceCheckedTypes},

	{"TestSuppressionDirectivesAreRefused", _test.TestSuppressionDirectivesAreRefused},

	{"TestSuppressionDirectiveSoundNeighbors", _test.TestSuppressionDirectiveSoundNeighbors},

	{"TestTasteRepresentationLimitsStayExplicit", _test.TestTasteRepresentationLimitsStayExplicit},

	{"TestTypedArraysLower", _test.TestTypedArraysLower},

	{"TestTypedArrayGaps", _test.TestTypedArrayGaps},

	{"TestTypedArrayViewsCannotChangeRepresentation", _test.TestTypedArrayViewsCannotChangeRepresentation},

	{"TestUnknownReflectionRefusals", _test.TestUnknownReflectionRefusals},

	{"TestViewObjectContractsAreAvailableToEraser", _test.TestViewObjectContractsAreAvailableToEraser},

	{"TestViewObjectWritesNeedSourceCertificate", _test.TestViewObjectWritesNeedSourceCertificate},

	{"TestMixedUnionContractGraph", _test.TestMixedUnionContractGraph},

	{"TestMixedUnionContractFailureDoesNotCertifyRetry", _test.TestMixedUnionContractFailureDoesNotCertifyRetry},

	{"TestMixedUnionContractUnknownMemberFails", _test.TestMixedUnionContractUnknownMemberFails},

	{"TestMixedUnionContractRecursiveMember", _test.TestMixedUnionContractRecursiveMember},

	{"TestMixedUnionContractPhantomBrandUsesPrimitiveBase", _test.TestMixedUnionContractPhantomBrandUsesPrimitiveBase},

	{"TestMixedUnionContractPhantomVoidIsUndefined", _test.TestMixedUnionContractPhantomVoidIsUndefined},

	{"TestUntaggedViewMemberTags", _test.TestUntaggedViewMemberTags},

	{"TestUntaggedViewStructuralFallback", _test.TestUntaggedViewStructuralFallback},

}

var benchmarks = []testing.InternalBenchmark{

}

var fuzzTargets = []testing.InternalFuzzTarget{

}

var examples = []testing.InternalExample{

}

func init() {

	testdeps.ModulePath = "github.com/system-inc/adamic"
	testdeps.ImportPath = "github.com/system-inc/adamic/internal/lower"
}

func main() {
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, fuzzTargets, examples)

	os.Exit(m.Run())

}

