import pathlib,json,re,statistics
p=pathlib.Path('review/test-audit/internal-native-target');runs=json.loads((p/'runs.json').read_text());raw=json.loads((p/'rows.json').read_text());ordinary=[r for r in raw if not r.startswith(('TestWASIUnit','TestSplitTSGoAgrees')) and r!='TestMeasureClangUnits'];med=json.loads((p/'medians.json').read_text());plan=json.loads((p/'plan.json').read_text())
def read(log):
 es=[]
 for line in (p/log).read_text().splitlines():
  try:es.append(json.loads(line))
  except:pass
 return es
def mapped(t):return 'TestWASIUnit family' if t.startswith('TestWASIUnit') else t.split('/')[0]
matrix=[]
for r in runs:
 es=read(r['log']);invalid=r['id']=='M17' and r['wasi'] and not r.get('standalone');failed=sorted({mapped(e['Test']) for e in es if e.get('Action')=='fail' and e.get('Test')});passed=sorted({mapped(e['Test']) for e in es if e.get('Action')=='pass' and e.get('Test')})
 matrix.append(dict(**r,valid=not invalid,failed=failed,passed=passed,binary_seconds=next((e['Elapsed'] for e in reversed(es) if e.get('Action')in ['pass','fail'] and not e.get('Test') and 'Elapsed'in e),None),reason='WASI env={} prevented switch activation' if invalid else None))
(p/'matrix.json').write_text(json.dumps(matrix,indent=2));allkills={id:set(t for m in matrix if m['id']==id and m['valid'] for t in m['failed']) for id in [x['id'] for x in plan]};names=ordinary+['TestMeasureClangUnits','TestSplitTSGoAgreesUnit family','TestWASIUnit family'];records=[]
paths={name:(f,n) for f in pathlib.Path('internal/native').glob('*_test.go') for n,line in enumerate(f.read_text().splitlines(),1) if (m:=re.match(r'^func (Test\w+)\(',line)) for name in [m[1]]}
oracles={ordinary[0]:('self','Self-written required WASI flags and absence of WASI flags for native.'),ordinary[1]:('self','Self-written refusal policy. Most invalid cases require only a non-nil error; the missing-sysroot case checks its diagnostic substring.'),ordinary[2]:(['external-run','self'],'Clang syntax checks plus self-written expectation that missing feature flags must fail; W01 alone proves the witness.'),ordinary[3]:(['external-run','self'],'Node determines normal typed-array output and RangeError cases. Self-written exit-70 and exact index diagnostics; range probes check only exit 70 and a panic prefix and can accept a different panic.'),ordinary[4]:('self','Self-written deterministic split and native output 1 2 2.'),ordinary[5]:(['external-run','self'],'Clang UBSan runs the signed-overflow probe; self-written diagnostic substring requires signed integer overflow.'),ordinary[6]:('self','Self-written literal preservation and rewritten symbol spelling.'),ordinary[7]:(['external-run','self'],'Clang distinguishes system-header and user-header extensions; self-written cached/uncached output 1 and 2 and diagnostic substring.'),ordinary[8]:('self','Self-written exact mixed-union panic diagnostics, exit 70 and empty stdout.'),'TestMeasureClangUnits':('self','Self-written split/header invariants and exactly-one-changed-unit requirement; timing outputs measure the compiler.'),'TestSplitTSGoAgreesUnit family':('self','Whole Adamic checker-archive product is the expected-output snapshot for the split product; no independent Go cohere comparison.'),'TestWASIUnit family':(['external-run','self'],'Node source execution compared with WASI stdout, stderr and exit; request host additionally checks self-written memory/counter and stack-margin invariants.')}
probe_ids={ordinary[0]:['PFlags'],ordinary[1]:['PValidate'],ordinary[2]:['PTSFlags','PFeatureFlags','PFlags'],ordinary[3]:[q['id'] for q in json.loads((p/'probe-plan.json').read_text()) if q['id'].startswith('PT_')],ordinary[4]:['PSplit','PBuild'],ordinary[5]:['PCompile'],ordinary[6]:['PSplit'],ordinary[7]:['PCompile'],ordinary[8]:['PMixed'],'TestWASIUnit family':['PC']}
for name in names:
 kills=[id for id,rows in allkills.items() if name in rows];unique=[id for id in kills if allkills[id]=={name}];verdict='sacred' if unique else 'subsumed' if kills else 'cannot-judge';by=[]
 if name==ordinary[7]:by=[ordinary[5]]
 if name==ordinary[2]:verdict='witness';kills=[];unique=[]
 chosen='W01' if verdict=='witness' else kills[-1] if kills else None;last=None;evidence=None
 if chosen:
  mr=next(m for m in reversed(matrix) if m['id']==chosen and m['valid'] and name in m['failed']);es=read(mr['log']);outputs=[e.get('Output','').strip() for e in es if e.get('Test') and mapped(e['Test'])==name and re.search(r'\.go:\d+:',e.get('Output',''))];last=chosen+': '+(outputs[-1] if outputs else 'observed failure in '+mr['log']);evidence='ADAMIC_BUILD_CACHE_DIR=/tmp/u054/cache/'+chosen+' '+('ADAMIC_MUTANT='+chosen+' ' if not mr.get('standalone') else 'WASI_SYSROOT=/tmp/u054/sdk/share/wasi-sysroot ADAMIC_TEST_WASI=1 PATH=/tmp/u054/sdk/bin:$PATH ')+mr['command']+' > '+mr['log']+' 2>&1; '+last
 probes=probe_ids.get(name,[]);pk=[id for id in probes if any(name in m['failed'] for m in matrix if m['id']==id and m['valid'])];vacuous=any(id not in pk for id in probes) if probes else None
 key=name if name in paths else 'TestWASIUnit00' if name=='TestWASIUnit family' else 'TestSplitTSGoAgreesUnit00';f,n=paths[key];oracle_kind,oracle=oracles[name]
 rec=dict(test=name,package='internal/native',file=str(f)+':'+str(n),seconds=med.get(name),oracle=oracle,oracle_kind=oracle_kind,kills=kills,unique_kills=unique,last_proven_fail=last,verdict=verdict,subsumed_by=by,mutants_in_matrix=17,probe_kills=pk,subsumer_seconds=med[by[0]] if by else None,vacuous=vacuous,bounded=True,matrix_rows=['TestWASIUnit family'] if name=='TestWASIUnit family' else ordinary if probes else [],evidence=evidence)
 if name=='TestWASIUnit family':rec['members']=[r for r in raw if r.startswith('TestWASIUnit')];rec['mutants_in_matrix']=1
 if name=='TestSplitTSGoAgreesUnit family':rec['members']=[r for r in raw if r.startswith('TestSplitTSGoAgrees')]
 if verdict=='cannot-judge':rec.update(reason='Checker archive build exceeded 90 s; no enabled run.' if name.startswith('TestSplitTSGo') else 'Required emitted-C benchmark dataset was absent; no enabled run.',mutants_in_matrix=0,evidence='tsgo-archive-build.log and tsgo-archive-build.json' if name.startswith('TestSplitTSGo') else 'bounded-baseline.log: set ADAMIC_CLANG_MEASURE to emitted C evidence directory')
 if verdict=='subsumed':rec['subsumption_mutants']=len(kills)
 if name==ordinary[3]:rec['vacuous_subcases']=['PT_check_write: release normal-output comparison before invalid-write probes','PT_check_write: sanitized normal-output comparison before invalid-write probes']
 records.append(rec)
(p/'results.json').write_text(json.dumps(records,indent=2));counts={v:sum(r['verdict']==v for r in records) for v in {r['verdict'] for r in records}};start=json.loads((p/'start.json').read_text());summary='\n'.join(['u054 started clean at '+start['commit']+'; all 48 listed functions exist.','Two unit families give 12 audit rows; no requested function moved or vanished.','Whole package timed out at 90.060 s without an individual failure; bounded default and enabled WASI baselines passed.','Verdicts: '+', '.join(str(n)+' '+v for v,n in sorted(counts.items()))+'. All verdicts and uniqueness are bounded.','17 production mutants, one witness weakening and 20 entry probes; all production mutants were killed.'])
table='| ID | origin/main file:line | Change | Failing audit rows |\n|---|---|---|---|\n'
for m in plan:table+='| '+m['id']+' | '+m['file']+':'+str(m['line'])+' | '+m['old'].replace('\n',' ').replace('|','\\|')+' -> '+(m['new'].replace('|','\\|') or '(drop statement)')+' | '+', '.join(sorted(allkills[m['id']]))+' |\n'
issues='''The supplied reference 8de93800f4 differs from the fetched starting commit. All requested tests remain in their named files; source references and diffs use the actual starting commit. The 48 names group into the advertised 12 rows: the two SplitTSGo wrappers are one family, and the 36 WASI wrappers are one family. WASI's common checker also runs the request-host assertions in its last unit; those extra checks are explicitly included in its oracle description.

The whole-package baseline exceeded the binary's 90-second budget, but had no individual test failure. It was narrowed to the named rows. The default bounded baseline passed in 1.480 seconds and measured 35.0% Go statement coverage. The enabled WASI baseline passed in 30.596 seconds. Every enabled row then passed three clean isolated runs. Kills outside the bounded matrix are unknown, including other callers of Flags, splitC and the runtime. Sacred and unique_kills mean uniqueness in the bounded observations, not proven package or repository uniqueness.

The warm environment lacked a WASI SDK. SDK 27 was installed under /tmp/u054/sdk and used only for separate WASI runs; the shared env.sh and default native clang were not changed. The checker archive build reached 90 seconds and was stopped; no archive was produced or used. TestMeasureClangUnits needs an emitted-C benchmark dataset, not just an installable compiler. No matching dataset was present, and I did not invent a replacement benchmark. Those two rows remain cannot-judge, with null costs and vacuity. Initial skips, enabled outcomes and all other whole-package skips are in baseline-summary.json.

WASI's host passes env:{} to its module. This prevents a C getenv-based mutation switch from activating there. The first M17 WASI run is marked invalid, excluded from kills and survivor claims. M17 was rerun as its unconditional standalone diff, without editing the host or oracle. That run failed the weak-parent and two reuse-weak fixtures. It has a separate cache environment and build/run timing. All other runtime mutants and probes use native subprocesses that inherit the selector. PC is a Go emitter probe and activates in the compiler process before the WASI module exists.

The Go matrix covered nine default-enabled rows for every production mutant; M17 additionally ran the WASI family. The WASI harness uses its own fixed clang flags and links unsplit emitted C, so its runtime test does not directly call Flags, ValidateOptions, splitC or compileUnit. The relevant source/caller evidence is retained. C runtime coverage is a conservative source inventory, not measured coverage of native or WASI processes.

TSGoFeatures deliberately checks that removing features makes compilation fail. It is judged as a witness: W01 disabled its compile check and the missing-feature assertion failed. Its production-mutant precondition failures do not count. UnitCacheFlagsHoldSanitizer checks the production cache via a signed-overflow program; M11 removed flags from the key and the runtime sanitizer observation failed. Header provenance is subsumed by that row on one observed mutant only, which is a small-matrix hint rather than a deletion recommendation.

PSplit panicked in the literal-inspection row after returning no units. All nine default rows were rerun individually; their observed results replace the aborted run. Probe failures never count as production kills. Typed-array check_write's empty probe permits the normal-output comparisons and is caught by invalid-write probes; those positive portions are listed in vacuous_subcases. Range-error probes only require exit 70 and a panic prefix, so a different panic could satisfy them. No whole enabled row passed its own entry probe.
'''
setup=json.loads((p/'wasi-sdk-install.json').read_text());archive=json.loads((p/'tsgo-archive-build.json').read_text());timings=json.loads((p/'timings.json').read_text());timingwall=sum(x['wall'] for x in timings);walls=sum(x['wall'] for x in runs);production='; '.join(m['id']+(' WASI standalone' if m.get('standalone') else ' WASI invalid' if not m['valid'] else '')+': '+f"{m['wall']:.3f}s wall/{m['binary_seconds']:.3f}s binary" for m in matrix if m['id'].startswith('M') and not m.get('test'))
issues+=f"\nWarm setup script: 0 seconds; nproc={start['nproc']}. npm ci: {start['npm-ci']['wall']:.3f}s. SDK installation: {setup['seconds']:.3f}s. Checker archive attempt: {archive['seconds']:.3f}s, timeout status {archive['status']}. Whole-package build/run wall: {start['baseline']['wall']:.3f}s. Thirty clean timing invocations totaled {timingwall:.3f}s wall. Matrix, witness and probe invocations totaled {walls:.3f}s wall. Per-diff validation times and exact commands are in validation.json and probe-validation.json. Native C switch products were built once and selected at execution; compiler flag variants rebuilt their needed products. Build-only times were not separately isolated from test overhead. Per-production run totals: {production}.\n\nNo survivors remain among the 17 valid production mutants. Not covered: the timed-out checker archive family, absent real clang benchmark corpus, package-wide or repo-wide uniqueness, and runtime function coverage outside the observed cases. Production and harness sources were restored; no PR or main push.\n"
(p/'report.md').write_text(summary+'\n\n```json\n'+json.dumps(records,indent=2)+'\n```\n\n'+table+'\nSurvivors: none among valid activated production runs.\n\n'+issues)
print(summary);print('probe count',len(json.loads((p/'probe-plan.json').read_text())));print('last',records[-1]['last_proven_fail'])
