// Generated by adamic from namespace_class_registration.a. Do not edit.

import { fileStatus, panic, programArguments, readDirectory, readTextFile, utf8At, utf8Length, writeTextFile } from 'adamic';

class AdamicClosure {
	constructor(code, cells, receiver = false) {
		this.code = code;
		this.cells = cells;
		this.receiver = receiver;
	}
}
const adamicCanonical = (identity, code, cells) => { const values = identity.functions ??= new Map(); if (!values.has(code)) values.set(code, new AdamicClosure(code, cells)); return values.get(code); };
const adamicTypeOf = (value) => value instanceof AdamicClosure ? 'function' : typeof value;
const adamicFieldReadiness = new WeakMap();
const adamicFieldRepresentations = new WeakMap();
const adamicRecordFieldTypes = (object, types) => { adamicFieldRepresentations.set(object, {...adamicFieldRepresentations.get(object), ...types}); return object; };
const adamicViewWrite = (object, name, value, type) => { if (!Object.hasOwn(object, name) || adamicFieldRepresentations.get(object)?.[name] !== type && !(adamicFieldRepresentations.get(object)?.[name] === 13 && ([3,4,5,6,8,10].includes(type))) && !(adamicFieldRepresentations.get(object)?.[name] === 10 && type <= 2) && !(adamicFieldRepresentations.get(object)?.[name] === 7 && type === 1)) adamicViewField(object, name, "<write>." + name, type); adamicWriteField(object, name, value); adamicRecordFieldTypes(object, {[name]: adamicFieldRepresentations.get(object)?.[name] === 10 && type <= 2 ? 10 : type}); };
const adamicUninitializedFields = (object, names) => { adamicFieldReadiness.set(object, new Set(names)); return object; };
const adamicReadField = (object, name, expression, optional = false, allowAbsent = false, fieldView = false) => {
    if (optional && (object === undefined || object === null)) return undefined;
    if (object === undefined || object === null) panic(fieldView ? "field read failed: " + expression + " is not initialized; expected " + fieldView + ", found missing" : "read before assignment: field '" + name + "' in " + expression);
    if (!Object.hasOwn(object, name) && typeof object === 'function' && adamicClassIdentities.has(Object.getPrototypeOf(object))) return adamicReadField(Object.getPrototypeOf(object), name, expression, false, allowAbsent, fieldView);
    if (allowAbsent && !Object.hasOwn(object, name)) return undefined;
    if (!Object.hasOwn(object, name) || adamicFieldReadiness.get(object)?.has(name)) panic(fieldView ? "field read failed: " + expression + " is not initialized; expected " + fieldView + ", found " + (!Object.hasOwn(object, name) ? "missing" : "uninitialized") : "read before assignment: field '" + name + "' in " + expression);
    return object[name];
};
const adamicViewTypeNames = Object.freeze({1: "number", 2: "boolean", 3: "string", 4: "object", 5: "array", 6: "Map"});
const adamicViewField = (object, name, expression, type, expected = adamicViewTypeNames[type], allowed = []) => {
    const value = adamicReadField(object, name, expression, false, false, expected);
    const valid = type === 1 ? typeof value === "number" : type === 2 ? typeof value === "boolean" : type === 3 ? typeof value === "string" : type === 4 ? value !== null && typeof value === "object" && !Array.isArray(value) && !(value instanceof Map) : type === 5 ? Array.isArray(value) : type === 6 ? value instanceof Map : false;
    if (!valid) panic("field read failed: " + expression + " is not a " + expected + "; expected " + expected + ", found " + (value === undefined ? "nullish" : value === null ? "nullish" : Array.isArray(value) ? "array" : value instanceof Map ? "Map" : typeof value));
    if (allowed.length && !allowed.includes(value)) panic("field read failed: " + expression + " expected " + expected + ", found " + typeof value + " " + value);
    return value;
};
const adamicCheckedViewCast = (object, field, type, allowed, message) => allowed.includes(adamicViewField(object, field, field, type)) ? object : panic(message);
const adamicDefineField = (object, name, value, enumerable, ready, type) => { if (type !== undefined) adamicRecordFieldTypes(object, {[name]: type}); Object.defineProperty(object, name, {value, writable: true, enumerable, configurable: true}); if (ready) adamicFieldReadiness.get(object)?.delete(name); else { let fields = adamicFieldReadiness.get(object); if (!fields) adamicFieldReadiness.set(object, fields = new Set()); fields.add(name); } };
const adamicSpreadFields = (object, expression) => { const result = {}; if (object !== undefined && object !== null) for (const name of Object.keys(object)) Object.defineProperty(result, name, {value: adamicReadField(object, name, expression), enumerable: true, writable: true, configurable: true}); return adamicRecordFieldTypes(result, adamicFieldRepresentations.get(object) || {}); };
const adamicWriteField = (object, name, value) => { object[name] = value; adamicFieldReadiness.get(object)?.delete(name); };
import { createHash as adamicNodeCreateHash } from 'node:crypto';
const adamicCollectionIterator = (collection, part) => { const iterator = collection[part](); return { next: new AdamicClosure(() => iterator.next(), []) }; };
const adamicJSONValue = (value) => {
 if (value instanceof AdamicClosure) return () => undefined;
 if (Array.isArray(value)) return value.map(adamicJSONValue);
 if (value !== null && typeof value === 'object' && !(value instanceof Map) && !(value instanceof Set)) {
  const copy = {};
  for (const key of Object.keys(value)) copy[key] = adamicJSONValue(value[key]);
  return copy;
 }
 return value;
};
const adamicJSONStringify = (value, replacer, space) => JSON.stringify(adamicJSONValue(value), replacer, space);
const adamicCall = (closure, values) => closure.code(closure, values);
const adamicStaticMethods = new WeakMap();
const adamicCallee = (object, name) => { if (Object.hasOwn(object, name)) { const fn = object[name]; return fn.receiver ? { code: (closure, values) => adamicCall(fn, [object, ...values]) } : fn; } const methods = adamicStaticMethods.get(object); const fn = methods && Object.hasOwn(methods, name) ? methods[name] : object[name]; return { code: (closure, values) => fn(object, ...values) }; };
const adamicOptionalCall = (object, name, values) => object === undefined ? undefined : adamicCall(adamicCallee(object, name), values());
const adamicVisit = (array, method, callback) => array[method]((element, index, all) => adamicCall(callback, [element, index, all]));
const adamicMap = (array, callback) => {
	const count = array.length;
	const mapped = [];
	for (let index = 0; index < count; index++) {
		if (index >= array.length) panic('map: the array shrank while it was being mapped');
		mapped.push(adamicCall(callback, [array[index], index, array]));
	}
	return mapped;
};
const adamicFind = (array, method, callback) => {
	const count = array.length;
	const last = method === 'findLast' || method === 'findLastIndex';
	const valueResult = method === 'find' || method === 'findLast';
	for (let step = 0; step < count; step++) {
		const index = last ? count - 1 - step : step;
		if (index >= array.length) panic(`${method}: the array shrank while it was being searched`);
		const element = array[index];
		if (adamicCall(callback, [element, index, array])) return valueResult ? element : index;
	}
	return valueResult ? undefined : -1;
};
const adamicCollectionVisit = (collection, callback) => collection.forEach((value, key, all) => adamicCall(callback, [value, key, all]));
const adamicFrom = (length, callback) => Array.from({ length }, (element, index) => adamicCall(callback, [element, index]));
const adamicDefinedNull = (value, message) => value === null ? panic(message) : value;
const adamicDefined = (value, message) => value === undefined ? panic(message) : value;
const adamicSort = (array, callback) => array.sort((left, right) => adamicCall(callback, [left, right]));
const adamicReduce =(array, callback, initial) => array.reduce((carried, element, index, all) => adamicCall(callback, [carried, element, index, all]), initial);
const adamicSetIndex = (array, index, value) => {
	if (!(Number.isInteger(index) && index >= 0 && index < array.length)) panic(`index ${index} is outside an array of length ${array.length}`);
	array[index] = value;
};
const adamicCast = (object, field, allowed, message) => allowed.includes(object[field]) ? object : panic(message);
const adamicUnready = (name) => { throw new ReferenceError(`Cannot access '${name}' before initialization`); };

const adamicClassIdentities = new WeakMap();
const adamicClass = (value, id) => { const metadata = adamicClasses[id - 1]; if (metadata.literal) { const result = {}; for (const name of metadata.publicKeys) { const descriptor = metadata.accessors[name]; if (descriptor) Object.defineProperty(result, name, {enumerable: true, get: descriptor.get === undefined ? undefined : () => adamicGetAccessor(result, name), set: descriptor.set === undefined ? undefined : (next) => adamicSetAccessor(result, name, next)}); else result[name] = value[name]; } for (const name of metadata.privateFields) Object.defineProperty(result, name, {value: value[name], enumerable: false}); value = result; } else for (const name of metadata.privateFields) Object.defineProperty(value, name, {enumerable: false}); if (metadata.static) { const storage = value; value = function () {}; adamicStaticMethods.set(value, Object.getPrototypeOf(storage)); if (metadata.parent) Object.setPrototypeOf(value, storage[metadata.parent]); for (const name of metadata.privateFields) Object.defineProperty(value, name, {value: storage[name], writable: true, configurable: true}); } adamicClassIdentities.set(value, id); return value; };
const adamicInstanceOf = (value, wanted) => { for (let id = adamicClassIdentities.get(value); id; id = adamicClasses[id - 1].base) { if (id === wanted || (adamicClasses[wanted - 1].definition && adamicClasses[id - 1].definition === adamicClasses[wanted - 1].definition)) return true; } return false; };
const adamicVirtual = (value, slot, ...args) => adamicClasses[adamicClassIdentities.get(value) - 1].methods[slot](value, ...args);
const adamicFindAccessor = (value, name) => { for (let id = adamicClassIdentities.get(value); id; id = adamicClasses[id - 1].base) { const found = adamicClasses[id - 1].accessors[name]; if (found) return found; } };
const adamicGetAccessor = (value, name) => { const get = adamicFindAccessor(value, name).get; return typeof get === 'string' ? adamicCall(value[get], [value]) : get(value); };
const adamicSetAccessor = (value, name, next) => { const set = adamicFindAccessor(value, name).set; return typeof set === 'string' ? adamicCall(value[set], [value, next]) : set(value, next); };
const adamicClasses = [{static: true, parent: "", base: 0, methods: [], definition: 0, privateFields: [], literal: false, publicKeys: [], accessors: {}}, {static: false, parent: "", base: 0, methods: [function_1_DebugTypeMapper_read], definition: 2, privateFields: [], literal: false, publicKeys: [], accessors: {}}];
let local_0_order;
let ready_0 = false;
let local_1_next;
let ready_1 = false;
let local_2_DebugTypeMapper;
let ready_2 = false;
let local_3_DebugTypeMapper_class;
let ready_3 = false;
let local_4_first;
let ready_4 = false;
let local_5_second;
let ready_5 = false;
let local_6_Debug;
let ready_6 = false;

function function_0_DebugTypeMapper_new() {
	let local_8_this = adamicClass(({__proto__: methods_0, "kind": (0)}), 2);
	adamicWriteField(local_8_this, "kind", (ready_1 ? local_1_next : adamicUnready("next")));
	const temporary_1 = ((ready_1 ? local_1_next : adamicUnready("next")) + (1));
	if (!ready_1) adamicUnready("next");
	local_1_next = temporary_1;
	const temporary_2 = ((ready_0 ? local_0_order : adamicUnready("order")) + "construct;");
	if (!ready_0) adamicUnready("order");
	local_0_order = temporary_2;
	return local_8_this;
}

function function_1_DebugTypeMapper_read(local_7_this) {
	return local_7_this["kind"];
}

function function_2_DebugTypeMapper_new_initialize() {
}

function function_3_class_ready_new(local_9_class) {
	return function_0_DebugTypeMapper_new();
}

function function_4_class_ready_new(local_10_class) {
	return function_0_DebugTypeMapper_new();
}

const methods_0 = { __proto__: Object.prototype, "read": function_1_DebugTypeMapper_read };
local_6_Debug = false;
ready_6 = true;
local_0_order = "";
ready_0 = true;
local_1_next = (0);
ready_1 = true;
local_3_DebugTypeMapper_class = adamicClass(({}), 1);
ready_3 = true;
local_2_DebugTypeMapper = local_3_DebugTypeMapper_class;
ready_2 = true;
local_6_Debug = true;
local_4_first = function_3_class_ready_new((ready_2 ? local_2_DebugTypeMapper : adamicUnready("DebugTypeMapper")));
ready_4 = true;
local_5_second = function_4_class_ready_new((ready_2 ? local_2_DebugTypeMapper : adamicUnready("DebugTypeMapper")));
ready_5 = true;
console.log((String(adamicVirtual(local_4_first, 0)) + ":" + String(local_5_second["kind"]) + ":" + String((local_4_first === local_5_second))));
console.log(local_0_order);
