// Generated by adamic from namespace_callable_properties.a. Do not edit.

import { fileStatus, panic, programArguments, readDirectory, readTextFile, utf8At, utf8Length, writeTextFile } from 'adamic';

class AdamicClosure {
	constructor(code, cells, receiver = false) {
		this.code = code;
		this.cells = cells;
		this.receiver = receiver;
	}
}
const adamicCanonical = (identity, code, cells) => { const values = identity.functions ??= new Map(); if (!values.has(code)) values.set(code, new AdamicClosure(code, cells)); return values.get(code); };
const adamicTypeOf = (value) => value instanceof AdamicClosure ? 'function' : typeof value;
const adamicFieldReadiness = new WeakMap();
const adamicFieldRepresentations = new WeakMap();
const adamicRecordFieldTypes = (object, types) => { adamicFieldRepresentations.set(object, {...adamicFieldRepresentations.get(object), ...types}); return object; };
const adamicViewWrite = (object, name, value, type) => { if (!Object.hasOwn(object, name) || adamicFieldRepresentations.get(object)?.[name] !== type && !(adamicFieldRepresentations.get(object)?.[name] === 13 && ([3,4,5,6,8,10].includes(type))) && !(adamicFieldRepresentations.get(object)?.[name] === 10 && type <= 2) && !(adamicFieldRepresentations.get(object)?.[name] === 7 && type === 1)) adamicViewField(object, name, "<write>." + name, type); adamicWriteField(object, name, value); adamicRecordFieldTypes(object, {[name]: adamicFieldRepresentations.get(object)?.[name] === 10 && type <= 2 ? 10 : type}); };
const adamicUninitializedFields = (object, names) => { adamicFieldReadiness.set(object, new Set(names)); return object; };
const adamicReadField = (object, name, expression, optional = false, allowAbsent = false, fieldView = false) => {
    if (optional && (object === undefined || object === null)) return undefined;
    if (object === undefined || object === null) panic(fieldView ? "field read failed: " + expression + " is not initialized; expected " + fieldView + ", found missing" : "read before assignment: field '" + name + "' in " + expression);
    if (!Object.hasOwn(object, name) && typeof object === 'function' && adamicClassIdentities.has(Object.getPrototypeOf(object))) return adamicReadField(Object.getPrototypeOf(object), name, expression, false, allowAbsent, fieldView);
    if (allowAbsent && !Object.hasOwn(object, name)) return undefined;
    if (!Object.hasOwn(object, name) || adamicFieldReadiness.get(object)?.has(name)) panic(fieldView ? "field read failed: " + expression + " is not initialized; expected " + fieldView + ", found " + (!Object.hasOwn(object, name) ? "missing" : "uninitialized") : "read before assignment: field '" + name + "' in " + expression);
    return object[name];
};
const adamicViewTypeNames = Object.freeze({1: "number", 2: "boolean", 3: "string", 4: "object", 5: "array", 6: "Map"});
const adamicViewField = (object, name, expression, type, expected = adamicViewTypeNames[type], allowed = []) => {
    const value = adamicReadField(object, name, expression, false, false, expected);
    const valid = type === 1 ? typeof value === "number" : type === 2 ? typeof value === "boolean" : type === 3 ? typeof value === "string" : type === 4 ? value !== null && typeof value === "object" && !Array.isArray(value) && !(value instanceof Map) : type === 5 ? Array.isArray(value) : type === 6 ? value instanceof Map : false;
    if (!valid) panic("field read failed: " + expression + " is not a " + expected + "; expected " + expected + ", found " + (value === undefined ? "nullish" : value === null ? "nullish" : Array.isArray(value) ? "array" : value instanceof Map ? "Map" : typeof value));
    if (allowed.length && !allowed.includes(value)) panic("field read failed: " + expression + " expected " + expected + ", found " + typeof value + " " + value);
    return value;
};
const adamicCheckedViewCast = (object, field, type, allowed, message) => allowed.includes(adamicViewField(object, field, field, type)) ? object : panic(message);
const adamicDefineField = (object, name, value, enumerable, ready, type) => { if (type !== undefined) adamicRecordFieldTypes(object, {[name]: type}); Object.defineProperty(object, name, {value, writable: true, enumerable, configurable: true}); if (ready) adamicFieldReadiness.get(object)?.delete(name); else { let fields = adamicFieldReadiness.get(object); if (!fields) adamicFieldReadiness.set(object, fields = new Set()); fields.add(name); } };
const adamicSpreadFields = (object, expression) => { const result = {}; if (object !== undefined && object !== null) for (const name of Object.keys(object)) Object.defineProperty(result, name, {value: adamicReadField(object, name, expression), enumerable: true, writable: true, configurable: true}); return adamicRecordFieldTypes(result, adamicFieldRepresentations.get(object) || {}); };
const adamicWriteField = (object, name, value) => { object[name] = value; adamicFieldReadiness.get(object)?.delete(name); };
import { createHash as adamicNodeCreateHash } from 'node:crypto';
const adamicCollectionIterator = (collection, part) => { const iterator = collection[part](); return { next: new AdamicClosure(() => iterator.next(), []) }; };
const adamicJSONValue = (value) => {
 if (value instanceof AdamicClosure) return () => undefined;
 if (Array.isArray(value)) return value.map(adamicJSONValue);
 if (value !== null && typeof value === 'object' && !(value instanceof Map) && !(value instanceof Set)) {
  const copy = {};
  for (const key of Object.keys(value)) copy[key] = adamicJSONValue(value[key]);
  return copy;
 }
 return value;
};
const adamicJSONStringify = (value, replacer, space) => JSON.stringify(adamicJSONValue(value), replacer, space);
const adamicCall = (closure, values) => closure.code(closure, values);
const adamicStaticMethods = new WeakMap();
const adamicCallee = (object, name) => { if (Object.hasOwn(object, name)) { const fn = object[name]; return fn.receiver ? { code: (closure, values) => adamicCall(fn, [object, ...values]) } : fn; } const methods = adamicStaticMethods.get(object); const fn = methods && Object.hasOwn(methods, name) ? methods[name] : object[name]; return { code: (closure, values) => fn(object, ...values) }; };
const adamicOptionalCall = (object, name, values) => object === undefined ? undefined : adamicCall(adamicCallee(object, name), values());
const adamicVisit = (array, method, callback) => array[method]((element, index, all) => adamicCall(callback, [element, index, all]));
const adamicMap = (array, callback) => {
	const count = array.length;
	const mapped = [];
	for (let index = 0; index < count; index++) {
		if (index >= array.length) panic('map: the array shrank while it was being mapped');
		mapped.push(adamicCall(callback, [array[index], index, array]));
	}
	return mapped;
};
const adamicFind = (array, method, callback) => {
	const count = array.length;
	const last = method === 'findLast' || method === 'findLastIndex';
	const valueResult = method === 'find' || method === 'findLast';
	for (let step = 0; step < count; step++) {
		const index = last ? count - 1 - step : step;
		if (index >= array.length) panic(`${method}: the array shrank while it was being searched`);
		const element = array[index];
		if (adamicCall(callback, [element, index, array])) return valueResult ? element : index;
	}
	return valueResult ? undefined : -1;
};
const adamicCollectionVisit = (collection, callback) => collection.forEach((value, key, all) => adamicCall(callback, [value, key, all]));
const adamicFrom = (length, callback) => Array.from({ length }, (element, index) => adamicCall(callback, [element, index]));
const adamicDefinedNull = (value, message) => value === null ? panic(message) : value;
const adamicDefined = (value, message) => value === undefined ? panic(message) : value;
const adamicSort = (array, callback) => array.sort((left, right) => adamicCall(callback, [left, right]));
const adamicReduce =(array, callback, initial) => array.reduce((carried, element, index, all) => adamicCall(callback, [carried, element, index, all]), initial);
const adamicSetIndex = (array, index, value) => {
	if (!(Number.isInteger(index) && index >= 0 && index < array.length)) panic(`index ${index} is outside an array of length ${array.length}`);
	array[index] = value;
};
const adamicCast = (object, field, allowed, message) => allowed.includes(object[field]) ? object : panic(message);
const adamicUnready = (name) => { throw new ReferenceError(`Cannot access '${name}' before initialization`); };

let local_0_level;
let ready_0 = false;
let local_1_level;
let ready_1 = false;
let local_2_detached;
let ready_2 = false;
let local_6_log;
let ready_6 = false;
let local_7_Debug;
let ready_7 = false;
let local_8_print;
let ready_8 = false;
let local_13_error_value;
let ready_13 = false;
let local_20_log_value;
let ready_20 = false;

function function_0_log(local_3_message) {
	console.log(("log:" + local_3_message));
	return;
}

function function_1_error(local_4_message) {
	console.log(("error:" + String((ready_0 ? local_0_level : adamicUnready("level"))) + ":" + local_4_message));
	return;
}

function function_2_print(local_5_message) {
	console.log(("print:" + local_5_message));
	return;
}

function function_3_namespace_ready(local_9_argument) {
	if ((!local_9_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'log')");
	}
	return true;
}

function function_4_namespace_ready(local_10_argument) {
	if ((!local_10_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'error')");
	}
	return true;
}

function function_5_namespace_ready(local_11_argument) {
	if ((!local_11_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'log')");
	}
	return true;
}

function function_6_error_value(self, values) {
	let local_12_message = values[0];
	function_1_error(local_12_message);
}

function function_7_namespace_ready(local_14_argument) {
	if ((!local_14_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'error')");
	}
	return true;
}

function function_8_namespace_ready(local_15_argument) {
	if ((!local_15_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'log')");
	}
	return true;
}

function function_9_namespace_read(local_16_argument, local_17_argument, local_18_argument) {
	return local_18_argument;
}

function function_10_log_value(self, values) {
	let local_19_message = values[0];
	function_0_log(local_19_message);
}

function function_11_namespace_ready(local_21_argument) {
	if ((!local_21_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'log')");
	}
	return true;
}

function function_12_namespace_read(local_22_argument, local_23_argument) {
	return local_23_argument;
}

function function_13_namespace_ready(local_24_argument) {
	if ((!local_24_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'log')");
	}
	return true;
}

function function_14_namespace_read(local_25_argument, local_26_argument) {
	return local_26_argument;
}

function function_15_namespace_ready(local_27_argument) {
	if ((!local_27_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'error')");
	}
	return true;
}

function function_16_namespace_ready(local_28_argument) {
	if ((!local_28_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'log')");
	}
	return true;
}

function function_17_namespace_read(local_29_argument, local_30_argument, local_31_argument) {
	return local_31_argument;
}

function function_18_namespace_ready(local_32_argument) {
	if ((!local_32_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'error')");
	}
	return true;
}

function function_19_namespace_ready(local_33_argument) {
	if ((!local_33_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'log')");
	}
	return true;
}

function function_20_namespace_read(local_34_argument, local_35_argument, local_36_argument) {
	return local_36_argument;
}

function function_21_namespace_ready(local_37_argument) {
	if ((!local_37_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'log')");
	}
	return true;
}

function function_22_namespace_read(local_38_argument, local_39_argument) {
	return local_39_argument;
}

function function_23_namespace_ready(local_40_argument) {
	if ((!local_40_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'error')");
	}
	return true;
}

function function_24_namespace_ready(local_41_argument) {
	if ((!local_41_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'log')");
	}
	return true;
}

function function_25_namespace_read(local_42_argument, local_43_argument, local_44_argument) {
	return local_44_argument;
}

function function_26_namespace_ready(local_45_argument) {
	if ((!local_45_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'log')");
	}
	return true;
}

function function_27_namespace_read(local_46_argument, local_47_argument) {
	return local_47_argument;
}

function function_28_namespace_ready(local_48_argument) {
	if ((!local_48_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'level')");
	}
	return true;
}

function function_29_namespace_ready(local_49_argument) {
	if ((!local_49_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'log')");
	}
	return true;
}

function function_30_namespace_read(local_50_argument, local_51_argument, local_52_argument) {
	return local_52_argument;
}

function function_31_namespace_ready(local_53_argument) {
	if ((!local_53_argument)) {
		panic("TypeError: Cannot read properties of undefined (reading 'level')");
	}
	return true;
}

function function_32_namespace_read(local_54_argument, local_55_argument) {
	return local_55_argument;
}

local_6_log = false;
ready_6 = true;
local_7_Debug = false;
ready_7 = true;
local_8_print = false;
ready_8 = true;
local_13_error_value = new AdamicClosure(function_6_error_value, [], false);
ready_13 = true;
local_20_log_value = new AdamicClosure(function_10_log_value, [], false);
ready_20 = true;
local_0_level = (3);
ready_0 = true;
local_6_log = true;
local_7_Debug = true;
local_1_level = (7);
ready_1 = true;
local_8_print = true;
(() => {
function_3_namespace_ready(local_7_Debug);
function_0_log("first");
return undefined;
})();
(() => {
function_5_namespace_ready(local_7_Debug);
function_4_namespace_ready(local_6_log);
function_1_error("second");
return undefined;
})();
local_2_detached = function_9_namespace_read(function_8_namespace_ready(local_7_Debug), function_7_namespace_ready(local_6_log), local_13_error_value);
ready_2 = true;
adamicCall(local_2_detached, ["third"]);
console.log((String((function_12_namespace_read(function_11_namespace_ready(local_7_Debug), local_20_log_value) === function_14_namespace_read(function_13_namespace_ready(local_7_Debug), local_20_log_value))) + ":" + String((function_17_namespace_read(function_16_namespace_ready(local_7_Debug), function_15_namespace_ready(local_6_log), local_13_error_value) === function_20_namespace_read(function_19_namespace_ready(local_7_Debug), function_18_namespace_ready(local_6_log), local_13_error_value))) + ":" + String((function_22_namespace_read(function_21_namespace_ready(local_7_Debug), local_20_log_value) !== function_25_namespace_read(function_24_namespace_ready(local_7_Debug), function_23_namespace_ready(local_6_log), local_13_error_value))) + ":" + adamicTypeOf(function_27_namespace_read(function_26_namespace_ready(local_7_Debug), local_20_log_value)) + ":" + String(function_30_namespace_read(function_29_namespace_ready(local_7_Debug), function_28_namespace_ready(local_6_log), local_0_level))));
function_2_print("fourth");
console.log((String(function_32_namespace_read(function_31_namespace_ready(local_8_print), local_1_level)) + ":" + String((local_8_print === local_8_print))));
