package regexp

import (
	"reflect"
	"testing"
	"unicode/utf16"
)

// Spec answers are explicit witnesses, not results generated by the matcher.
// The two surrogate answers intentionally differ from our Node-compatible VM.
func TestV8Node2419Recheck(t *testing.T) {
	t.Parallel()
	rows := []struct {
		pattern, flags, input string
		spec, node            [][]int
		refused               bool
	}{
		{`[\q{a}]`, "iv", "A", [][]int{{0, 1}}, nil, true},
		{`[\q{Ss|x}]`, "iv", "X", [][]int{{0, 1}}, nil, true},
		{`(?i:a)[b]`, "v", "aB", nil, [][]int{{0, 2}}, true},
		{`(?-i:a)[b]`, "iv", "aB", [][]int{{0, 2}}, nil, true},
		{`(?i:a)\w`, "u", "aK", nil, [][]int{{0, 2}}, true},
		{`(?i:a)[\w]`, "u", "aK", nil, [][]int{{0, 2}}, true},
		{`(?-i:^)\W`, "iu", "K", nil, [][]int{{0, 1}}, true},
		{`(?i:x|[^a-z])`, "", "B", nil, [][]int{{0, 1}}, true},
		{`(?i:a)|\P{Ll}`, "v", "Σ", [][]int{{0, 1}}, nil, true},
		{`[\q{ab|a|}]`, "iv", "A", [][]int{{0, 1}}, [][]int{{0, 0}}, true},
		{`\B`, "u", "a🌍b", nil, [][]int{{2, 2}}, false},
		{`\B`, "u", "1🌍aac", [][]int{{4, 4}}, [][]int{{2, 2}}, false},
		{`(?!\W)`, "u", "🌍", [][]int{{2, 2}}, [][]int{{1, 1}}, false},
	}
	var cases []executionCase
	for _, row := range rows {
		cases = append(cases, executionCase{Pattern: row.pattern, Flags: row.flags, Input: utf16.Encode([]rune(row.input))})
	}
	answers := nodeResults(t, cases)
	for i, row := range rows {
		if !reflect.DeepEqual(answers[i].Captures, row.node) {
			t.Fatalf("recorded Node 24.19 reproduction changed %s/%s: %+v", row.pattern, row.flags, answers[i])
		}
		p, err := Compile(row.pattern, row.flags)
		if err != nil {
			t.Fatal(err)
		}
		if (p.NativeCompatibility() != nil) != row.refused {
			t.Fatalf("refusal %s/%s: %v", row.pattern, row.flags, p.NativeCompatibility())
		}
		if row.refused {
			r := p.New()
			r.StepLimit = 1000000
			got, err := matcherResult(r, cases[i].Input)
			if err != nil {
				t.Fatal(err)
			}
			if !reflect.DeepEqual(got.Captures, row.spec) {
				t.Fatalf("reference/spec witness %s/%s: got %+v spec %v", row.pattern, row.flags, got, row.spec)
			}
		}
		t.Logf("%s/%s input=%q spec=%v Node24.19=%v refusal=%v", row.pattern, row.flags, row.input, row.spec, answers[i].Captures, row.refused)
	}
}
