import pathlib,json,statistics,shutil
p=pathlib.Path('/tmp/u164');root=pathlib.Path('/workspace/adamic');dest=root/'review/test-audit/stage3-fixtures-runner_guard';dest.mkdir(parents=True,exist_ok=True);base=(p/'base.txt').read_text().strip();records=json.loads((p/'runs.json').read_text());runs={x['id']:x for x in records}
def events(id):
 out=[]
 for s in (p/(id+'.log')).read_text().splitlines():
  try:out.append(json.loads(s))
  except ValueError:pass
 return out
def first(id,needle):return next(e['Output'].strip().splitlines()[0] for e in events(id) if needle in e.get('Output',''))
row_names=['TestFixtures family','TestPrepareFixtureOracleHook','TestFixturePaths','TestFixtureShardManifest','TestTransformedNodeRunnerGuardHook','TestTransformedNodeRunnerGuard','TestFixtureDirectoriesHaveTopLevelTests'];matrix={}
for id in ['W1','W2','W3','S1','S2','S3']:
 status={r:'unknown' for r in row_names}
 for e in events(id):
  name=e.get('Test','')
  if not name or '/' in name or e.get('Action') not in ['pass','fail','skip']:continue
  row='TestFixtures family' if name.startswith('TestFixtures') else name
  if row in status and status[row]!='fail':status[row]=e['Action']
 assert all(v!='unknown' for v in status.values()),(id,status)
 matrix[id]=status
xs=json.loads((p/'timings.json').read_text());med={r:round(statistics.median(x['seconds'] for x in xs if x['test']==r),3) for r in dict.fromkeys(x['test'] for x in xs)}
parent='TestTransformedNodeRunnerGuard';hook=parent+'Hook';setup='TestFixtureDirectoriesHaveTopLevelTests';wfail=first('W2','unexpected runner must fail');sfail=first('S3','must call testFixtureDirectory');pfail=first('P1-hook','open :');registryfail=first('P2','no top-level test')
report=[{'test':hook,'package':'stage3/fixtures','file':'stage3/fixtures/runner_guard_test.go:10','seconds':med[hook],'oracle':'Self-written output text shape assertions. Active helper reads the derived runner; it never executes Node. Default whole-package entry skips unless its parent supplies ADAMIC_RUNNER_GUARD_REPOSITORY.','oracle_kind':'self','kills':[],'unique_kills':[],'last_proven_fail':None,'verdict':'helper','parent':parent,'subsumed_by':[],'mutants_in_matrix':6,'probe_kills':['P1'],'subsumer_seconds':None,'vacuous':False,'bounded':False,'matrix_rows':row_names,'evidence':runs['P1-hook']['command']+' > P1-hook.log 2>&1; '+pfail,'timing_mode':'helper activated with repository environment'},
{'test':parent,'package':'stage3/fixtures','file':'stage3/fixtures/runner_guard_test.go:27','seconds':med[parent],'oracle':'Self-written nine-input accepted/rejected table. Valid inputs require successful child exit. Invalid inputs require failed child exit and the exact shape-guard diagnostic marker, so a later hook failure is rejected. No Node execution.','oracle_kind':'self','kills':[],'unique_kills':[],'witness_kills':['W1','W2'],'last_proven_fail':'W2 '+wfail,'verdict':'witness','subsumed_by':[],'mutants_in_matrix':6,'probe_kills':['P1'],'subsumer_seconds':None,'vacuous':False,'bounded':False,'matrix_rows':row_names,'evidence':runs['W2']['command']+' > W2.log 2>&1; '+wfail,'surviving_weakenings':['W3']},
{'test':setup,'package':'stage3/fixtures','file':'stage3/fixtures/units_test.go:19','seconds':med[setup],'oracle':'Self-written suite-construction rule: every fixture directory has one direct top-level TestFixtures declaration naming its literal directory; actual declarations are parsed and compared to filesystem directories and status rows.','oracle_kind':'self','kills':['S1','S2','S3'],'unique_kills':['S1','S2','S3'],'last_proven_fail':'S3 '+sfail,'verdict':'setup-check','subsumed_by':[],'mutants_in_matrix':6,'probe_kills':['P2'],'subsumer_seconds':None,'vacuous':None,'bounded':False,'matrix_rows':row_names,'evidence':runs['S3']['command']+' > S3.log 2>&1; '+sfail,'probe_note':'P2 empties the static unit declaration registry. This is not a callable-entry probe, so callable-entry vacuity is not assigned.'}]
(p/'report.json').write_text(json.dumps(report,indent=2)+'\n');(p/'matrix.json').write_text(json.dumps({'base':base,'scope':[hook,parent,setup],'matrix_rows':row_names,'family_members':['TestFixturesAssertions','TestFixturesCycles','TestFixturesEnums','TestFixturesHost','TestFixturesNamespaces','TestFixturesNestedFunctions','TestFixturesObjects','TestFixturesPredicates','TestFixturesRecords','TestFixturesRunner','TestFixturesTaste'],'mutant_kinds':{'W1':'weakened witness check','W2':'weakened witness check','W3':'weakened witness check','S1':'construction','S2':'construction','S3':'construction'},'results':matrix},indent=2)+'\n')
(p/'matrix.csv').write_text('row,W1,W2,W3,S1,S2,S3\n'+'\n'.join(r+','+','.join(matrix[m][r] for m in ['W1','W2','W3','S1','S2','S3']) for r in row_names)+'\n')
summary='\n'.join(['u164: three named functions found in their listed files; none moved or vanished.','Base '+base+'; nproc 5; warm setup skipped.','Corrected whole-package baseline passed 17.604s; restored baseline passed 16.798s.','Verdicts: one helper, one witness, one setup-check; W3 is a proven survivor.','Evidence: test-audit/stage3-fixtures-runner_guard under review/test-audit/stage3-fixtures-runner_guard/.'])
meta=[('W1',133,'Disable the complete shape condition with impossible erasable+transformedCalls < 0','TestTransformedNodeRunnerGuard'),('W2',133,'Runtime URL count != 1 becomes > 1','TestTransformedNodeRunnerGuard'),('W3',133,'Total stripTypeScriptTypes prefix count != 1 becomes > 2',''),('S1',148,'Drop TestFixturesAssertions sole call statement','TestFixtureDirectoriesHaveTopLevelTests'),('S2',149,'Change TestFixturesCycles directory constant cycles to enums','TestFixtureDirectoriesHaveTopLevelTests'),('S3',158,'Return early from TestFixturesTaste by replacing its sole call with return','TestFixtureDirectoriesHaveTopLevelTests')]
md=summary+'\n\n```json\n'+json.dumps(report,indent=2)+'\n```\n\n| ID | File:line on origin/main | Change | Failed rows |\n| --- | --- | --- | --- |\n'
for id,line,change,failed in meta:md+=f'| {id} | stage3/fixtures/fixtures_test.go:{line} | {change} | {failed} |\n'
md+='''
Survivor W3: a scratch source containing one recognized transform call, one unknown-mode call and one runtime URL is refused before W3 (helper exit 1 with the shape-guard diagnostic) and accepted after W3 (helper exit 0). The full original package, including the nine-case witness, passes under W3. This demonstrates an uncovered hybrid-call guard weakening; it is not an equivalent candidate. See W3-hybrid-before.log, W3-hybrid-after.log, and hybrid-runner/oracle/node.mjs.

Probes: P1 returns the empty path at transformedNodeRunner entry. Active helper fails with open : no such file or directory; its parent rejects all nine subcases. P2 removes all eleven static fixture unit declarations. The directory checker reports missing units and an empty directory union. Neither probe contributes a mutant kill.

Brief friction, interpretations and practical limits:

1. Starting origin/main is cf735d9fba9e38de6368575e5630e44375a86eaf, newer than the supplied 8de93800f4. All three names remain in their listed files. The complete discovery list is saved.
2. These are harness quality rows. The helper and witness do not run Node, despite their names. Their expected runner text, accepted shapes, exit categories and diagnostic marker are hand-written self oracles. Live Go subprocess execution of our own test binary is not an independent authority.
3. The helper intentionally skips by default. It belongs to TestTransformedNodeRunnerGuard, which activates it in child processes. I activated it against the real repository for all three standalone Good timings and its empty-entry probe. In every whole-package run, only this helper entry skipped. No substantive row was skipped.
4. The parent deliberately supplies broken runner shapes and expects the shape check to reject them. It was judged as a witness by weakening that check. W1 and W2 prove the witness can reject a disabled or loosened check. W3 shows this proof does not cover every guard component: the built-in table lacks a recognized-plus-unknown hybrid call.
5. W2 is caught even though the child still fails its later output-shape assertion. The parent requires the specific guard diagnostic, not just a nonzero exit. That stage requirement is demonstrated by runner_guard_test.go:62 in W2.log.
6. The directory row is a setup check. Its code under test is the eleven direct fixture-unit declarations, not Adamic lowering or its fixtures' recorded Node answers. S1 keeps a discoverable Test name but removes its work; S2 makes two declarations name enums and leaves cycles without a unit; S3 returns without running taste. All three construction failures are caught without changing the checker or any manifest.
7. A runtime mutation switch cannot represent these construction changes cleanly. The checker inspects the actual AST and requires one direct call statement. An inactive switch would already violate that condition. I replayed each standalone diff separately instead of adding a switch to the declarations.
8. The exact callable-entry empty-answer rule does not map to static declarations. P2 supplies an empty construction registry, and the checker fails, but its vacuous field remains null. No standard-library parser or checker assertion was changed to manufacture an empty answer.
9. W mutations use the explicit witness exception for harness edits; S mutations use the setup-check exception for construction edits. No compiler, production port, oracle/node.mjs, recorded behavior, or test assertion was changed. Witness catches are recorded separately from production kills. Setup kills are labeled construction mutations; their uniqueness is over the complete package matrix.
10. The package baseline fit the budget, so all six mutants ran against the complete package. The eleven wrappers that differ only in directory input were grouped into TestFixtures family for matrix counts. This matrix is not bounded to the three scoped rows, and no subsumption verdict is assigned to these special rows.
11. /usr/bin/time was absent. My first npm timing command therefore did not execute npm ci, although the initial package run passed. I corrected this before any mutation: npm ci succeeded in 0.503 seconds, then a replacement whole-package baseline passed. The initial baseline is retained as evidence but is not the qualifying baseline.
12. The scope says three rows, but only two have a check verdict: the helper has its parent instead. I used three guard weakenings and three declaration changes, approximately three mutants per applicable check. No native rebuild is required for these Go harness/construction mutations. Each diff compiled with go vet ./stage3/fixtures/.
13. Guard coverage concerns exact string spellings, not semantic JavaScript equivalence. The source runner is accepted through the known stripTypeScriptTypes spelling and runtime URL spelling. This audit demonstrates the existing string guard and the missing hybrid-input witness, not robustness against every formatting or JavaScript syntax variant.
14. No compiler correctness, fixture semantic coverage, runtime ownership, repo-wide tests or unrelated package audit was attempted. No production mutation was retained. The survivor input is synthetic text for the guard; it is never executed as JavaScript.
'''
md+=f'\nTiming: setup 0s, nproc 5, npm 0.503s. Nine isolated timing runs totaled {sum(x["seconds"] for x in xs):.3f} binary seconds and {sum(x["wall"] for x in xs):.3f} command wall seconds. Six package matrix runs totaled {sum(runs[x]["wall"] for x in ["W1","W2","W3","S1","S2","S3"]):.3f} wall seconds. Per-run compile validation and all command durations are in runs.json. The first exploratory baseline reported oracle-hook preparation 8.39s. Unit work ran approximately 13:47 to 14:03 UTC.\n'
(p/'REPORT.md').write_text(md)
for f in p.iterdir():
 if f.is_file() and f.suffix in ['.log','.json','.txt','.diff','.py','.csv','.md']:shutil.copy2(f,dest/f.name)
shutil.copytree(p/'hybrid-runner',dest/'hybrid-runner',dirs_exist_ok=True)
print(summary);print('files',len(list(dest.rglob('*'))));print('matrix',matrix)
