// Generated by adamic from trees.ts. Do not edit.

#include "adamic.h"

#include <math.h>
#include <stdbool.h>

static adamic_string adamic_string_0 = ADAMIC_STRING("stretch tree of depth ");
static adamic_string adamic_string_1 = ADAMIC_STRING("\011 check: ");
static adamic_string adamic_string_2 = ADAMIC_STRING("\011 trees of depth ");
static adamic_string adamic_string_3 = ADAMIC_STRING("long lived tree of depth ");

static double adamic_global_0_maximumDepth = 0.0;
static bool adamic_ready_0 = false;
static adamic_object * adamic_global_1_stretch = NULL;
static bool adamic_ready_1 = false;
static adamic_object * adamic_global_2_longLived = NULL;
static bool adamic_ready_2 = false;

static adamic_object * adamic_function_0_build(double adamic_local_3_depth);
static adamic_object * adamic_function_0_build_in(adamic_region *region, double adamic_local_3_depth);
static double adamic_function_1_check(adamic_object * adamic_local_4_tree);

static const char *const adamic_shape_0_names[] = {"left", "right"};
static const bool adamic_shape_0_references[] = {true, true};
static const adamic_shape adamic_shape_0 = {2, adamic_shape_0_names, adamic_shape_0_references, NULL};

static adamic_object * adamic_function_0_build(double adamic_local_3_depth) {
	ADAMIC_CHECK_STACK();
	if (adamic_local_3_depth == (0x0p+00)) {
		{
			adamic_object * adamic_temporary_1 = adamic_object_new(&adamic_shape_0);
			adamic_temporary_1->slots[0].reference = NULL;
			adamic_temporary_1->slots[1].reference = NULL;
			adamic_object * adamic_temporary_2 = adamic_temporary_1;
			return adamic_temporary_2;
		}
	}
	adamic_object * adamic_temporary_3 = adamic_function_0_build((adamic_local_3_depth - (0x1p+00)));
	adamic_object * adamic_temporary_4 = adamic_function_0_build((adamic_local_3_depth - (0x1p+00)));
	adamic_object * adamic_temporary_5 = adamic_object_new(&adamic_shape_0);
	adamic_temporary_5->slots[0].reference = adamic_temporary_3;
	adamic_temporary_5->slots[1].reference = adamic_temporary_4;
	adamic_object * adamic_temporary_6 = adamic_temporary_5;
	return adamic_temporary_6;
	adamic_unreachable();
}

static adamic_object * adamic_function_0_build_in(adamic_region *region, double adamic_local_3_depth) {
	ADAMIC_CHECK_STACK();
	if (adamic_local_3_depth == (0x0p+00)) {
		{
			adamic_object *adamic_temporary_7 = adamic_object_new_filled_in(region, &adamic_shape_0);
			adamic_temporary_7->slots[0].reference = NULL;
			adamic_temporary_7->slots[1].reference = NULL;
			adamic_object * adamic_temporary_8 = adamic_temporary_7;
			return adamic_temporary_8;
		}
	}
	adamic_object *adamic_temporary_9 = adamic_function_0_build_in(region, (adamic_local_3_depth - (0x1p+00)));
	adamic_object *adamic_temporary_10 = adamic_function_0_build_in(region, (adamic_local_3_depth - (0x1p+00)));
	adamic_object *adamic_temporary_11 = adamic_object_new_filled_in(region, &adamic_shape_0);
	adamic_temporary_11->slots[0].reference = adamic_temporary_9;
	adamic_temporary_11->slots[1].reference = adamic_temporary_10;
	adamic_object * adamic_temporary_12 = adamic_temporary_11;
	return adamic_temporary_12;
	adamic_unreachable();
}

static double adamic_function_1_check(adamic_object * adamic_local_4_tree) {
	ADAMIC_CHECK_STACK();
	adamic_object * adamic_temporary_13 = ((adamic_object *)(&adamic_local_4_tree->slots[0])->reference);
	bool adamic_temporary_14 = (adamic_temporary_13 == NULL);
	bool adamic_temporary_17 = adamic_temporary_14;
	if (!adamic_temporary_17) {
		adamic_object * adamic_temporary_15 = ((adamic_object *)(&adamic_local_4_tree->slots[1])->reference);
		bool adamic_temporary_16 = (adamic_temporary_15 == NULL);
		adamic_temporary_17 = adamic_temporary_16;
	}
	if (adamic_temporary_17) {
		{
			double adamic_temporary_18 = (0x1p+00);
			return adamic_temporary_18;
		}
	}
	adamic_object * adamic_temporary_19 = ((adamic_object *)(&adamic_local_4_tree->slots[0])->reference);
	if (adamic_temporary_19 == NULL) {
		static const char message[] = "undefined where the checker narrowed it away: a call since the narrowing put it back";
		adamic_panic(message, sizeof message - 1);
	}
	double adamic_temporary_20 = adamic_function_1_check(adamic_temporary_19);
	adamic_object * adamic_temporary_21 = ((adamic_object *)(&adamic_local_4_tree->slots[1])->reference);
	if (adamic_temporary_21 == NULL) {
		static const char message[] = "undefined where the checker narrowed it away: a call since the narrowing put it back";
		adamic_panic(message, sizeof message - 1);
	}
	double adamic_temporary_22 = adamic_function_1_check(adamic_temporary_21);
	double adamic_temporary_23 = (((0x1p+00) + adamic_temporary_20) + adamic_temporary_22);
	return adamic_temporary_23;
	adamic_unreachable();
}

int main(int argc, char **argv) {
	adamic_start(argc, argv);
	adamic_global_0_maximumDepth = (0x1.2p+04);
	adamic_ready_0 = true;
	double adamic_temporary_24 = adamic_global_0_maximumDepth;
	adamic_object * adamic_temporary_25 = adamic_function_0_build((adamic_temporary_24 + (0x1p+00)));
	adamic_object * adamic_temporary_26 = adamic_global_1_stretch;
	adamic_global_1_stretch = adamic_temporary_25;
	adamic_release(adamic_temporary_26);
	adamic_ready_1 = true;
	double adamic_temporary_27 = adamic_global_0_maximumDepth;
	adamic_string * adamic_temporary_28 = adamic_string_from_number((adamic_temporary_27 + (0x1p+00)));
	adamic_object * adamic_temporary_29 = adamic_global_1_stretch;
	double adamic_temporary_30 = adamic_function_1_check(adamic_temporary_29);
	adamic_string * adamic_temporary_31 = adamic_string_from_number(adamic_temporary_30);
	adamic_string * adamic_temporary_32 = adamic_string_concat(4, (adamic_string *const[]){&adamic_string_0, adamic_temporary_28, &adamic_string_1, adamic_temporary_31});
	adamic_write_line(adamic_stdout, adamic_temporary_32);
	adamic_release(adamic_temporary_32);
	adamic_release(adamic_temporary_31);
	adamic_release(adamic_temporary_28);
	double adamic_temporary_33 = adamic_global_0_maximumDepth;
	adamic_object * adamic_temporary_34 = adamic_function_0_build(adamic_temporary_33);
	adamic_object * adamic_temporary_35 = adamic_global_2_longLived;
	adamic_global_2_longLived = adamic_temporary_34;
	adamic_release(adamic_temporary_35);
	adamic_ready_2 = true;
	{
		int64_t adamic_local_5_depth = (int64_t)(0x1p+02);
		for (;;) {
			double adamic_temporary_37 = adamic_global_0_maximumDepth;
			if (!(((double)adamic_local_5_depth) <= adamic_temporary_37)) {
				break;
			}
			{
				{
					double adamic_temporary_39 = adamic_global_0_maximumDepth;
					double adamic_local_6_iterations = adamic_power((0x1p+01), ((adamic_temporary_39 - ((double)adamic_local_5_depth)) + (0x1p+02)));
					double adamic_local_7_total = (0x0p+00);
					{
						double adamic_local_8_index = (0x0p+00);
						for (;;) {
							if (!(adamic_local_8_index < adamic_local_6_iterations)) {
								break;
							}
							{
								{
									adamic_region adamic_temporary_42 = ADAMIC_REGION;
									adamic_object *adamic_temporary_43 = adamic_function_0_build_in(&adamic_temporary_42, ((double)adamic_local_5_depth));
									double adamic_temporary_44 = adamic_function_1_check(adamic_temporary_43);
									adamic_local_7_total = (adamic_local_7_total + adamic_temporary_44);
									adamic_region_end(&adamic_temporary_42);
								}
							}
							adamic_local_8_index = (adamic_local_8_index + (0x1p+00));
						}
					}
					adamic_string * adamic_temporary_45 = adamic_string_from_number(adamic_local_6_iterations);
					adamic_string * adamic_temporary_46 = adamic_string_from_number(((double)adamic_local_5_depth));
					adamic_string * adamic_temporary_47 = adamic_string_from_number(adamic_local_7_total);
					adamic_string * adamic_temporary_48 = adamic_string_concat(5, (adamic_string *const[]){adamic_temporary_45, &adamic_string_2, adamic_temporary_46, &adamic_string_1, adamic_temporary_47});
					adamic_write_line(adamic_stdout, adamic_temporary_48);
					adamic_release(adamic_temporary_48);
					adamic_release(adamic_temporary_47);
					adamic_release(adamic_temporary_46);
					adamic_release(adamic_temporary_45);
				}
			}
			adamic_local_5_depth += (int64_t)((0x1p+01));
		}
	}
	double adamic_temporary_49 = adamic_global_0_maximumDepth;
	adamic_string * adamic_temporary_50 = adamic_string_from_number(adamic_temporary_49);
	adamic_object * adamic_temporary_51 = adamic_global_2_longLived;
	double adamic_temporary_52 = adamic_function_1_check(adamic_temporary_51);
	adamic_string * adamic_temporary_53 = adamic_string_from_number(adamic_temporary_52);
	adamic_string * adamic_temporary_54 = adamic_string_concat(4, (adamic_string *const[]){&adamic_string_3, adamic_temporary_50, &adamic_string_1, adamic_temporary_53});
	adamic_write_line(adamic_stdout, adamic_temporary_54);
	adamic_release(adamic_temporary_54);
	adamic_release(adamic_temporary_53);
	adamic_release(adamic_temporary_50);
	adamic_release(adamic_global_2_longLived);
	adamic_global_2_longLived = NULL;
	adamic_release(adamic_global_1_stretch);
	adamic_global_1_stretch = NULL;
	return 0;
}
