const assert = require('node:assert/strict');
const probe = require('./probe.cjs');
const ts = require(process.argv[2]);
const source = ts.createSourceFile('parent-witness.ts', 'x + y;', ts.ScriptTarget.Latest, true);
const node = source.statements[0].expression;
assert.ok(node.parent);
const clone = ts.getSynthesizedDeepCloneWithReplacements(node, true, () => undefined);
assert.equal(clone.parent, undefined);
assert.ok(node.parent);
const row = probe.snapshot().rows.find(r => r.site === 'parent');
assert.equal(row.violations, 1);
assert.equal(row.outOfTypeReads, 1);
console.log('parent: present on input; undefined on clone; later read = undefined');
