#define ADAMIC_CLOSURE_CONVENTION 1
// Generated by adamic from arguments_length_value_count.a. Do not edit.

#include "adamic.h"

#include <math.h>
#include <stdbool.h>

static adamic_closure * adamic_global_0_selected = NULL;
static bool adamic_ready_0 = false;
static adamic_array * adamic_global_1_source = NULL;
static bool adamic_ready_1 = false;
static adamic_closure * adamic_global_2_restValue = NULL;
static bool adamic_ready_2 = false;
static adamic_closure * adamic_global_5_quiet_value = NULL;
static bool adamic_ready_5 = false;
static adamic_closure * adamic_global_6_reader_value = NULL;
static bool adamic_ready_6 = false;

static double adamic_function_0_reader(double adamic_local_4_argument_count);
static double adamic_function_1_quiet(void);
static double adamic_function_2_invoke(adamic_closure * adamic_local_3_run);
static adamic_code_function adamic_function_3_quiet_value;
static adamic_counted_code_function adamic_function_4_reader_value;

static double adamic_function_0_reader(double adamic_local_4_argument_count) {
	ADAMIC_CHECK_STACK_NAMED("reader");
	(void)adamic_local_4_argument_count;
	double adamic_temporary_1 = adamic_local_4_argument_count;
	return adamic_temporary_1;
	adamic_unreachable();
}

static double adamic_function_1_quiet(void) {
	ADAMIC_CHECK_STACK_NAMED("quiet");
	double adamic_temporary_2 = (0x1.34p+06);
	return adamic_temporary_2;
	adamic_unreachable();
}

static double adamic_function_2_invoke(adamic_closure * adamic_local_3_run) {
	ADAMIC_CHECK_STACK_NAMED("invoke");
	adamic_value adamic_temporary_3 = adamic_closure_call(adamic_local_3_run, (adamic_value[]){{.number = (0x1p+00)}, {.number = (0x1p+01)}}, 2);
	double adamic_temporary_4 = adamic_temporary_3.number;
	double adamic_temporary_5 = adamic_temporary_4;
	return adamic_temporary_5;
	adamic_unreachable();
}

static adamic_value adamic_function_3_quiet_value(adamic_closure *self, adamic_value *arguments) {
	ADAMIC_CHECK_STACK_NAMED("quiet_value");
	(void)self;
	(void)arguments;
	double adamic_temporary_6 = adamic_function_1_quiet();
	double adamic_temporary_7 = adamic_temporary_6;
	return (adamic_value){.number = adamic_temporary_7};
	adamic_unreachable();
}

static adamic_value adamic_function_4_reader_value(adamic_closure *self, adamic_value *arguments, size_t argument_count) {
	ADAMIC_CHECK_STACK_NAMED("reader_value");
	(void)self;
	(void)argument_count;
	(void)arguments;
	double adamic_local_7_argument_count = (double)argument_count;
	(void)adamic_local_7_argument_count;
	double adamic_temporary_8 = adamic_function_0_reader(adamic_local_7_argument_count);
	double adamic_temporary_9 = adamic_temporary_8;
	return (adamic_value){.number = adamic_temporary_9};
	adamic_unreachable();
}

int main(int argc, char **argv) {
	adamic_start(argc, argv);
	adamic_closure * adamic_temporary_10 = adamic_closure_new(adamic_function_3_quiet_value, 0);
	adamic_temporary_10->source_length = 0;
	adamic_closure * adamic_temporary_11 = adamic_global_5_quiet_value;
	adamic_global_5_quiet_value = adamic_temporary_10;
	adamic_release(adamic_temporary_11);
	adamic_ready_5 = true;
	adamic_closure * adamic_temporary_12 = adamic_counted_closure_new(adamic_function_4_reader_value, 0);
	adamic_temporary_12->source_length = 0;
	adamic_closure * adamic_temporary_13 = adamic_global_6_reader_value;
	adamic_global_6_reader_value = adamic_temporary_12;
	adamic_release(adamic_temporary_13);
	adamic_ready_6 = true;
	adamic_closure * adamic_temporary_14 = adamic_retain(adamic_global_5_quiet_value);
	adamic_closure * adamic_temporary_15 = adamic_global_0_selected;
	adamic_global_0_selected = adamic_temporary_14;
	adamic_release(adamic_temporary_15);
	adamic_ready_0 = true;
	adamic_closure * adamic_temporary_16 = adamic_retain(adamic_global_0_selected);
	double adamic_temporary_17 = adamic_function_2_invoke(adamic_temporary_16);
	adamic_string * adamic_temporary_18 = adamic_string_from_number(adamic_temporary_17);
	adamic_string * adamic_temporary_19 = adamic_string_concat(1, (adamic_string *const[]){adamic_temporary_18});
	adamic_write_line(adamic_stdout, adamic_temporary_19);
	adamic_release(adamic_temporary_19);
	adamic_release(adamic_temporary_18);
	adamic_release(adamic_temporary_16);
	adamic_closure * adamic_temporary_20 = adamic_retain(adamic_global_6_reader_value);
	adamic_closure * adamic_temporary_21 = adamic_global_0_selected;
	adamic_global_0_selected = adamic_temporary_20;
	adamic_release(adamic_temporary_21);
	adamic_closure * adamic_temporary_22 = adamic_retain(adamic_global_0_selected);
	double adamic_temporary_23 = adamic_function_2_invoke(adamic_temporary_22);
	adamic_string * adamic_temporary_24 = adamic_string_from_number(adamic_temporary_23);
	adamic_string * adamic_temporary_25 = adamic_string_concat(1, (adamic_string *const[]){adamic_temporary_24});
	adamic_write_line(adamic_stdout, adamic_temporary_25);
	adamic_release(adamic_temporary_25);
	adamic_release(adamic_temporary_24);
	adamic_release(adamic_temporary_22);
	adamic_array * adamic_temporary_26 = adamic_array_new(3, false);
	adamic_temporary_26->element_type = 1;
	adamic_array_push(adamic_temporary_26, (adamic_value){.number = (0x1p+00)});
	adamic_array_push(adamic_temporary_26, (adamic_value){.number = (0x1p+01)});
	adamic_array_push(adamic_temporary_26, (adamic_value){.number = (0x1.8p+01)});
	adamic_array * adamic_temporary_27 = adamic_global_1_source;
	adamic_global_1_source = adamic_temporary_26;
	adamic_release(adamic_temporary_27);
	adamic_ready_1 = true;
	adamic_closure * adamic_temporary_28 = adamic_retain(adamic_global_6_reader_value);
	adamic_closure * adamic_temporary_29 = adamic_global_2_restValue;
	adamic_global_2_restValue = adamic_temporary_28;
	adamic_release(adamic_temporary_29);
	adamic_ready_2 = true;
	adamic_closure * adamic_temporary_30 = adamic_retain(adamic_global_2_restValue);
	adamic_array * adamic_temporary_31 = adamic_array_new(0, false);
	adamic_array * adamic_temporary_32 = adamic_retain(adamic_global_1_source);
	adamic_array * adamic_temporary_33 = adamic_array_slice(adamic_temporary_32, 0, 0, false);
	for (size_t adamic_temporary_34 = 0; adamic_temporary_34 < adamic_temporary_33->length; adamic_temporary_34++) {
		adamic_array_push(adamic_temporary_31, adamic_temporary_33->elements[adamic_temporary_34]);
	}
	adamic_value adamic_temporary_35 = adamic_closure_call(adamic_temporary_30, NULL, adamic_temporary_31->length);
	double adamic_temporary_36 = adamic_temporary_35.number;
	adamic_string * adamic_temporary_37 = adamic_string_from_number(adamic_temporary_36);
	adamic_string * adamic_temporary_38 = adamic_string_concat(1, (adamic_string *const[]){adamic_temporary_37});
	adamic_write_line(adamic_stdout, adamic_temporary_38);
	adamic_release(adamic_temporary_38);
	adamic_release(adamic_temporary_37);
	adamic_release(adamic_temporary_33);
	adamic_release(adamic_temporary_32);
	adamic_release(adamic_temporary_31);
	adamic_release(adamic_temporary_30);
	adamic_release(adamic_global_2_restValue);
	adamic_global_2_restValue = NULL;
	adamic_release(adamic_global_1_source);
	adamic_global_1_source = NULL;
	adamic_release(adamic_global_0_selected);
	adamic_global_0_selected = NULL;
	adamic_release(adamic_global_6_reader_value);
	adamic_global_6_reader_value = NULL;
	adamic_release(adamic_global_5_quiet_value);
	adamic_global_5_quiet_value = NULL;
	return 0;
}
