// Run from the repository root with ADAMIC_TYPESCRIPT pointing to TypeScript 6.0.3.
// Inputs come from the cohere pin recorded below; expected results are never generated.
import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';
import vm from 'node:vm';
import { createHash } from 'node:crypto';
const require = createRequire(import.meta.url);
const ts = require(process.env.ADAMIC_TYPESCRIPT || 'typescript');
if (ts.version !== '6.0.3') throw Error(`requires TypeScript 6.0.3, got ${ts.version}`);
const dir = path.dirname(new URL(import.meta.url).pathname);
const root = path.resolve(dir, '../../../..');
const inputFiles = new Map();
const read = file => { const data = fs.readFileSync(path.join(root, file)); inputFiles.set(file, createHash('sha256').update(data).digest('hex')); return data.toString('utf8'); };
const q = JSON.stringify;
const compiler = 'cohere/TypeScript/tsc/testdata/fixtures/compiler/';
const tools = 'cohere/TypeScript/tools/scripts/tsc/';
const header = '// Generated by generate.mjs from cohere 7945d102a6c18dd36adf9114a758ce646e8b2359.\n// The constructor argument is a parameter: the native runtime compiler must run.\n';
const observe = `function observe(re: RegExp, text: string): void {
    console.log(\`\${re.test(text)}\`);
    re.lastIndex = 0;
    const m = re.exec(text);
    if (m === null) { console.log('none'); }
    else {
        console.log(\`\${m.index}\`);
        for (let i = 0; i < m.length; i++) console.log(m[i] ?? '<undefined>');
    }
    console.log(\`\${re.lastIndex}\`);
}\n`;
const files = new Map();
function fixture(name, body) { files.set(name + '.a', header + body); }
function calls(name, ctor, rows) {
    const patterns = [...new Set(rows.map(r => r[0]))];
    const subjects = [...new Set(rows.map(r => r[1]))];
    // Cross the real inputs rather than emitting thousands of identical call
    // sites. This adds negative pairs and keeps native fixture builds small.
    fixture(name, observe + ctor + '\nconst patterns = ' + q(patterns) + ';\nconst subjects = ' + q(subjects) + ';\nfor (const pattern of patterns) for (const subject of subjects) check(pattern, subject);\n');
}
// The enum definitions select these prefixes and Go files, rather than inventing names.
const enumSource = read(tools + 'generate-enums.ts');
const enumDefs = [...enumSource.matchAll(/goPrefix: "([^"]+)", goFile: "([^"]+)"/g)];
let enumCalls = [];
for (const [, prefix, file] of enumDefs) {
    const go = read('cohere/TypeScript/' + file);
    const full = new RegExp(`^(${prefix}\\w+)\\s+(?:\\S+\\s*)?=\\s*(.+)$`);
    const bare = new RegExp(`^(${prefix}\\w+)$`);
    const lines = go.split('\n').map(s => s.replace(/\/\/.*$/, '').trim());
    const assigned = lines.find(s => full.test(s));
    const continuation = lines.find(s => bare.test(s));
    for (const line of [assigned, continuation, 'OtherNotThisEnum', ...(assigned ? ['x' + assigned] : [])].filter(Boolean)) {
        enumCalls.push(`check(${q(prefix)}, ${q(line)});`);
    }
}
fixture('enums', observe + `function check(prefix: string, line: string): void {
    observe(new RegExp(\`^(\${prefix}\\\\w+)\\\\s+(?:\\\\S+\\\\s*)?=\\\\s*(.+)$\`), line);
    observe(new RegExp(\`^(\${prefix}\\\\w+)$\`), line);
    console.log(line.replace(new RegExp(\`^\${prefix}\`), ''));
}\n` + enumCalls.join('\n') + '\n');
const diagnosticNames = ['maxNodeModuleJsDepth', 'types', 'paths', 'plugins'];
calls('option_errors', `function check(name: string, message: string): void {
    observe(new RegExp(\`Unsupported comparison type for \${name}:\`), message);
}`, diagnosticNames.flatMap(name => [[name, `Unsupported comparison type for ${name}: object`], [name, `Unsupported comparison type for other${name}: object`]]));
const schema = JSON.parse(read('cohere/TypeScript/packages/typescript/schemas/tsconfig.schema.json'));
const schemaRows = [];
function walkSchema(s) {
    if (!s || typeof s !== 'object') return;
    if (s.anyOf) {
        const pattern = s.anyOf.find(x => x.pattern)?.pattern;
        const keys = s.anyOf.find(x => x.enum)?.enum;
        if (pattern && keys) for (const value of keys) {
            for (const text of [value, value.toUpperCase(), value[0].toUpperCase() + value.slice(1), value + '!']) schemaRows.push([pattern, text]);
        }
    }
    Object.values(s).forEach(walkSchema);
}
walkSchema(schema);
if (schemaRows.length === 0) throw Error('schema changed');
calls('schema', `function check(pattern: string, value: string): void { observe(new RegExp(pattern), value); }`, schemaRows);
const errors = [...read('cohere/TypeScript/tsc/testdata/tests/cases/compiler/duplicateLocalVariable1.ts').matchAll(/}, "([^"]+)"\)\)/g)].map(m => m[1]);
calls('error_messages', `function check(pattern: string, message: string): void { observe(new RegExp(pattern), message); }`, errors.flatMap(p => [[p, p === 'Should [also]+ pass' ? 'Should also pass' : p], [p, 'Error: ' + p], [p, 'unrelated error']]));
const mobileSource = read('cohere/TypeScript/tsc/testdata/tests/cases/conformance/fixSignatureCaching.ts');
const mobileRules = vm.runInNewContext('(' + mobileSource.match(/impl\.mobileDetectRules\s*=\s*({[\s\S]*?\n});/)[1] + ')');
const mobileRows = [];
const agents = ['Mozilla/5.0 (iPhone; CPU iPhone OS 10_2_1 like Mac OS X) AppleWebKit/602.4.6 Version/10.0 Mobile/14D27 Safari/602.1',
    'Mozilla/5.0 (Linux; Android 7.0; Nexus 5) AppleWebKit/537.36 Chrome/56.0.2924.87 Mobile Safari/537.36',
    'Mozilla/5.0 (Windows NT 10.0) Chrome/120.0 Safari/537.36', 'rim123', 'not-a-phone'];
for (const [kind, obj] of Object.entries(mobileRules)) {
    if (kind === 'props') {
        for (const values of Object.values(obj)) for (const value of [values].flat()) {
            const pattern = value.replace('[VER]', '([\\w._\\+]+)');
            for (const agent of agents) mobileRows.push([pattern, agent]);
        }
    } else {
        for (const value of Object.values(obj)) if (typeof value === 'string') for (const agent of agents) mobileRows.push([value, agent]);
    }
}
calls('mobile_detect', `function check(pattern: string, ua: string): void { observe(new RegExp(pattern, 'i'), ua); }`, mobileRows);
const widthData = read('stage1/cohere/css/print_width_data.ts');
const emoji = vm.runInNewContext(widthData.match(/export const emojiPatternSource = ([^;]+);/)[1]);
const narrow = vm.runInNewContext(widthData.match(/export const narrowEmojiPatternSource = ([^;]+);/)[1]);
const emojiSubjects = ['plain ASCII', '😀', '©', '©️', '™', '❤️', '👨‍👩‍👧‍👦', '🇺🇸', '👍🏽', '1️⃣', '😀 x © y 👩‍💻', '中', '\ud83d', '\ude00'];
fixture('emoji', `function check(pattern: string, narrowPattern: string, text: string): void {
    let mapped = '';
    for (let i = 0; i < text.length; i++) {
        const c = text.charCodeAt(i);
        mapped += String.fromCodePoint(c >= 0xd800 && c <= 0xdfff ? 0x100000 + c - 0xd800 : c);
    }
    const emojis = new RegExp(pattern, 'gu');
    const narrow = new RegExp(narrowPattern, 'u');
    let match = emojis.exec(mapped);
    while (match !== null) {
        const part = match[0] ?? '';
        console.log(\`\${match.index}:\${part.length}:\${narrow.test(part) ? 1 : 2}:\${emojis.lastIndex}\`);
        match = emojis.exec(mapped);
    }
    console.log(\`\${emojis.lastIndex}\`);
}\n` + `const emojiPattern = ${q(emoji)};\nconst narrowPattern = ${q(narrow)};\n` + emojiSubjects.map(text => `check(emojiPattern, narrowPattern, ${q(text)});`).join('\n') + '\n');
files.set('input_sources.json', JSON.stringify([...inputFiles].map(([file, sha256]) => ({file, sha256})), null, 2) + '\n');
for (const [name, contents] of files) {
    if (process.argv.includes('--check')) {
        if (fs.readFileSync(path.join(dir, name), 'utf8') !== contents) throw Error(`${name} needs regeneration`);
    } else fs.writeFileSync(path.join(dir, name), contents);
}
