// Generated by adamic from stock_decode_entities.ts. Do not edit.

import { fileStatus, panic, programArguments, readDirectory, readTextFile, utf8At, utf8Length, writeTextFile } from 'adamic';

class AdamicClosure {
	constructor(code, cells, receiver = false) {
		this.code = code;
		this.cells = cells;
		this.receiver = receiver;
	}
}
const adamicCanonical = (identity, code, cells) => { const values = identity.functions ??= new Map(); if (!values.has(code)) values.set(code, new AdamicClosure(code, cells)); return values.get(code); };
const adamicTypeOf = (value) => value instanceof AdamicClosure ? 'function' : typeof value;
const adamicFieldReadiness = new WeakMap();
const adamicFieldRepresentations = new WeakMap();
const adamicRecordFieldTypes = (object, types) => { adamicFieldRepresentations.set(object, {...adamicFieldRepresentations.get(object), ...types}); return object; };
const adamicViewWrite = (object, name, value, type) => { if (!Object.hasOwn(object, name) || adamicFieldRepresentations.get(object)?.[name] !== type && !(adamicFieldRepresentations.get(object)?.[name] === 13 && ([3,4,5,6,8,10].includes(type))) && !(adamicFieldRepresentations.get(object)?.[name] === 10 && type <= 2) && !(adamicFieldRepresentations.get(object)?.[name] === 7 && type === 1)) adamicViewField(object, name, "<write>." + name, type); adamicWriteField(object, name, value); adamicRecordFieldTypes(object, {[name]: adamicFieldRepresentations.get(object)?.[name] === 10 && type <= 2 ? 10 : type}); };
const adamicUninitializedFields = (object, names) => { adamicFieldReadiness.set(object, new Set(names)); return object; };
const adamicReadField = (object, name, expression, optional = false, allowAbsent = false, fieldView = false) => {
    if (optional && (object === undefined || object === null)) return undefined;
    if (object === undefined || object === null) panic(fieldView ? "field read failed: " + expression + " is not initialized; expected " + fieldView + ", found missing" : "read before assignment: field '" + name + "' in " + expression);
    if (!Object.hasOwn(object, name) && typeof object === 'function' && adamicClassIdentities.has(Object.getPrototypeOf(object))) return adamicReadField(Object.getPrototypeOf(object), name, expression, false, allowAbsent, fieldView);
    if (allowAbsent && !Object.hasOwn(object, name)) return undefined;
    if (!Object.hasOwn(object, name) || adamicFieldReadiness.get(object)?.has(name)) panic(fieldView ? "field read failed: " + expression + " is not initialized; expected " + fieldView + ", found " + (!Object.hasOwn(object, name) ? "missing" : "uninitialized") : "read before assignment: field '" + name + "' in " + expression);
    return object[name];
};
const adamicViewTypeNames = Object.freeze({1: "number", 2: "boolean", 3: "string", 4: "object", 5: "array", 6: "Map"});
const adamicViewField = (object, name, expression, type, expected = adamicViewTypeNames[type], allowed = []) => {
    const value = adamicReadField(object, name, expression, false, false, expected);
    const valid = type === 1 ? typeof value === "number" : type === 2 ? typeof value === "boolean" : type === 3 ? typeof value === "string" : type === 4 ? value !== null && typeof value === "object" && !Array.isArray(value) && !(value instanceof Map) : type === 5 ? Array.isArray(value) : type === 6 ? value instanceof Map : false;
    if (!valid) panic("field read failed: " + expression + " is not a " + expected + "; expected " + expected + ", found " + (value === undefined ? "nullish" : value === null ? "nullish" : Array.isArray(value) ? "array" : value instanceof Map ? "Map" : typeof value));
    if (allowed.length && !allowed.includes(value)) panic("field read failed: " + expression + " expected " + expected + ", found " + typeof value + " " + value);
    return value;
};
const adamicCheckedViewCast = (object, field, type, allowed, message) => allowed.includes(adamicViewField(object, field, field, type)) ? object : panic(message);
const adamicDefineField = (object, name, value, enumerable, ready, type) => { if (type !== undefined) adamicRecordFieldTypes(object, {[name]: type}); Object.defineProperty(object, name, {value, writable: true, enumerable, configurable: true}); if (ready) adamicFieldReadiness.get(object)?.delete(name); else { let fields = adamicFieldReadiness.get(object); if (!fields) adamicFieldReadiness.set(object, fields = new Set()); fields.add(name); } };
const adamicSpreadFields = (object, expression) => { const result = {}; if (object !== undefined && object !== null) for (const name of Object.keys(object)) Object.defineProperty(result, name, {value: adamicReadField(object, name, expression), enumerable: true, writable: true, configurable: true}); return adamicRecordFieldTypes(result, adamicFieldRepresentations.get(object) || {}); };
const adamicWriteField = (object, name, value) => { object[name] = value; adamicFieldReadiness.get(object)?.delete(name); };
import { createHash as adamicNodeCreateHash } from 'node:crypto';
const adamicCollectionIterator = (collection, part) => { const iterator = collection[part](); return { next: new AdamicClosure(() => iterator.next(), []) }; };
const adamicJSONValue = (value) => {
 if (value instanceof AdamicClosure) return () => undefined;
 if (Array.isArray(value)) return value.map(adamicJSONValue);
 if (value !== null && typeof value === 'object' && !(value instanceof Map) && !(value instanceof Set)) {
  const copy = {};
  for (const key of Object.keys(value)) copy[key] = adamicJSONValue(value[key]);
  return copy;
 }
 return value;
};
const adamicJSONStringify = (value, replacer, space) => JSON.stringify(adamicJSONValue(value), replacer, space);

const adamicCheckJSON = (value, contract, path, terminal = true, depth = 0) => {
 const found = value === null ? 'null' : Array.isArray(value) ? 'array' : adamicTypeOf(value);
 const fail = (actual = found) => { if (terminal) panic('checked any: ' + path + ' needs ' + contract.Name + ', found ' + actual); return false; };
 if (depth > 64) return fail('non-JSON recursion');
 if (contract.Kind === 'ref') return adamicCheckJSON(value,contract.Element,path,terminal,depth);
 if (contract.Kind === 'union') {
  for (const alternative of contract.Alternatives) if (adamicCheckJSON(value, alternative, path, false, depth)) return true;
  if(terminal) {
   const matches=(c,d=0)=>d<=64 && (c.Kind==='ref'?matches(c.Element,d+1):c.Kind==='union'?c.Alternatives.some(a=>matches(a,d+1)):c.Kind.replace('_literal','')===found);
   const candidates=contract.Alternatives.filter(c=>matches(c));
   if(candidates.length===1) return adamicCheckJSON(value,candidates[0],path,true,depth);
  }
  return fail();
 }
 const domain = contract.Kind === 'json';
 if ((domain ? !['number','boolean','string','null','undefined','object','array'].includes(found) : found !== contract.Kind.replace('_literal','')) || depth > 64) return fail(depth > 64 ? 'non-JSON recursion' : found);
 if(contract.Kind.endsWith('_literal') && value !== (found==='number'?contract.LiteralNumber:found==='boolean'?contract.LiteralBoolean:contract.LiteralText)) return fail();
 if (found === 'number' && !Number.isFinite(value)) return fail('non-JSON number');
 if (found === 'object') {
  if (Object.getPrototypeOf(value) !== Object.prototype && Object.getPrototypeOf(value) !== null) return fail('class object');
  if(domain || contract.Element) for(const key of Object.keys(value)) if(!adamicCheckJSON(value[key],domain ? contract : contract.Element,path+'.'+key,terminal,depth+1)) return false;
  for (const field of contract.Fields ?? []) {
   const child = value[field.Name];
   if (field.Optional && child === undefined) continue;
   if (!adamicCheckJSON(child, field.Contract, path + '.' + field.Name, terminal, depth + 1)) return false;
  }
 }
 if (found === 'array' && (contract.Element || domain)) {
  for (let index = 0; index < value.length; index++) if (!adamicCheckJSON(value[index], domain ? contract : contract.Element, path + '[' + index + ']', terminal, depth + 1)) return false;
 }
 return true;
};
const adamicCheckedJSON = (value, contract, path) => { adamicCheckJSON(value, {Kind:'json',Name:'JSON value | undefined'}, path); adamicCheckJSON(value, contract, path); return value; };
const adamicCall = (closure, values) => closure.code(closure, values);
const adamicStaticMethods = new WeakMap();
const adamicCallee = (object, name) => { if (Object.hasOwn(object, name)) { const fn = object[name]; return fn.receiver ? { code: (closure, values) => adamicCall(fn, [object, ...values]) } : fn; } const methods = adamicStaticMethods.get(object); const fn = methods && Object.hasOwn(methods, name) ? methods[name] : object[name]; return { code: (closure, values) => fn(object, ...values) }; };
const adamicOptionalCall = (object, name, values) => object === undefined ? undefined : adamicCall(adamicCallee(object, name), values());
const adamicVisit = (array, method, callback) => array[method]((element, index, all) => adamicCall(callback, [element, index, all]));
const adamicMap = (array, callback) => {
	const count = array.length;
	const mapped = [];
	for (let index = 0; index < count; index++) {
		if (index >= array.length) panic('map: the array shrank while it was being mapped');
		mapped.push(adamicCall(callback, [array[index], index, array]));
	}
	return mapped;
};
const adamicFind = (array, method, callback) => {
	const count = array.length;
	const last = method === 'findLast' || method === 'findLastIndex';
	const valueResult = method === 'find' || method === 'findLast';
	for (let step = 0; step < count; step++) {
		const index = last ? count - 1 - step : step;
		if (index >= array.length) panic(`${method}: the array shrank while it was being searched`);
		const element = array[index];
		if (adamicCall(callback, [element, index, array])) return valueResult ? element : index;
	}
	return valueResult ? undefined : -1;
};
const adamicCollectionVisit = (collection, callback) => collection.forEach((value, key, all) => adamicCall(callback, [value, key, all]));
const adamicFrom = (length, callback) => Array.from({ length }, (element, index) => adamicCall(callback, [element, index]));
const adamicDefinedNull = (value, message) => value === null ? panic(message) : value;
const adamicDefined = (value, message) => value === undefined ? panic(message) : value;
const adamicSort = (array, callback) => array.sort((left, right) => adamicCall(callback, [left, right]));
const adamicReduce =(array, callback, initial) => array.reduce((carried, element, index, all) => adamicCall(callback, [carried, element, index, all]), initial);
const adamicSetIndex = (array, index, value) => {
	if (!(Number.isInteger(index) && index >= 0 && index < array.length)) panic(`index ${index} is outside an array of length ${array.length}`);
	array[index] = value;
};
const adamicCast = (object, field, allowed, message) => allowed.includes(object[field]) ? object : panic(message);
const adamicUnready = (name) => { throw new ReferenceError(`Cannot access '${name}' before initialization`); };

let local_0_entities;
let ready_0 = false;

function function_0_utf16EncodeAsString(local_1_code) {
	return String.fromCodePoint(local_1_code);
}

function function_1_decodeEntities(local_2_text) {
	return ((input, regex, callback) => input.replace(regex, (...values) => { if (!((typeof values[0] === 'string') && (values[1] === undefined || typeof values[1] === 'string' || typeof values[1] === 'number' || (values[1] !== null && typeof values[1] === 'object')) && (values[2] === undefined || typeof values[2] === 'string' || typeof values[2] === 'number' || (values[2] !== null && typeof values[2] === 'object')) && (values[3] === undefined || typeof values[3] === 'string' || typeof values[3] === 'number' || (values[3] !== null && typeof values[3] === 'object')) && (values[4] === undefined || typeof values[4] === 'string' || typeof values[4] === 'number' || (values[4] !== null && typeof values[4] === 'object')) && (values[5] === undefined || typeof values[5] === 'string' || typeof values[5] === 'number' || (values[5] !== null && typeof values[5] === 'object')) && (values[6] === undefined || typeof values[6] === 'string' || typeof values[6] === 'number' || (values[6] !== null && typeof values[6] === 'object')))) panic('RegExp replacement callback argument does not fit its declared type'); return adamicCall(callback, values); }))(local_2_text, new RegExp("&((#((\\d+)|x([\\da-fA-F]+)))|(\\w+));", "g"), new AdamicClosure(function_2_closure, [], false));
}

function function_2_closure(self, values) {
	let local_3_match = values[0];
	let local_4__all = values[1];
	let local_5__number = values[2];
	let local_6__digits = values[3];
	let local_7_decimal = values[4];
	let local_8_hex = values[5];
	let local_9_word = values[6];
	if (Boolean(local_7_decimal)) {
		{
			return function_0_utf16EncodeAsString(Number.parseInt(function_3_checked_any_use(local_7_decimal), (10)));
		}
	} else {
		if (Boolean(local_8_hex)) {
			{
				return function_0_utf16EncodeAsString(Number.parseInt(function_4_checked_any_use(local_8_hex), (16)));
			}
		} else {
			{
				let local_12_ch = (ready_0 ? local_0_entities : adamicUnready("entities")).get(function_5_checked_any_use(local_9_word));
				return (Boolean(local_12_ch) ? function_0_utf16EncodeAsString(adamicDefined(local_12_ch, "undefined where the checker narrowed it away: a call since the narrowing put it back")) : local_3_match);
			}
		}
	}
}

function function_3_checked_any_use(local_10_argument) {
	if ((!(adamicTypeOf(local_10_argument) === "string"))) {
		panic(("checked any: decimal needs string, found " + ((local_10_argument === null) ? "null" : adamicTypeOf(local_10_argument))));
	}
	return local_10_argument;
}

function function_4_checked_any_use(local_11_argument) {
	if ((!(adamicTypeOf(local_11_argument) === "string"))) {
		panic(("checked any: hex needs string, found " + ((local_11_argument === null) ? "null" : adamicTypeOf(local_11_argument))));
	}
	return local_11_argument;
}

function function_5_checked_any_use(local_13_argument) {
	if ((!(adamicTypeOf(local_13_argument) === "string"))) {
		panic(("checked any: word needs string, found " + ((local_13_argument === null) ? "null" : adamicTypeOf(local_13_argument))));
	}
	return local_13_argument;
}

local_0_entities = new Map([]);
ready_0 = true;
local_0_entities.set("nbsp", (160));
console.log(function_1_decodeEntities("&#65; &#x42; &nbsp; &missing;"));
