#define ADAMIC_CLOSURE_RECEIVERS 1
#define ADAMIC_CLOSURE_CONVENTION 1
// Generated by adamic from arguments_length_extended.a. Do not edit.

#include "adamic.h"

#include <math.h>
#include <stdbool.h>

static adamic_string adamic_string_0 = ADAMIC_STRING(":");
static adamic_string adamic_string_1 = ADAMIC_STRING(",");
static adamic_string adamic_string_2 = ADAMIC_STRING(" ");

static adamic_closure * adamic_global_0_initialized = NULL;
static bool adamic_ready_0 = false;
static adamic_closure * adamic_global_1_maybeValue = NULL;
static bool adamic_ready_1 = false;
static adamic_object * adamic_global_2_accessors = NULL;
static bool adamic_ready_2 = false;
static adamic_object * adamic_global_3_literal = NULL;
static bool adamic_ready_3 = false;
static adamic_closure * adamic_global_13_initializer_value = NULL;
static bool adamic_ready_13 = false;
static adamic_closure * adamic_global_15_maybe_value = NULL;
static bool adamic_ready_15 = false;

static adamic_string * adamic_function_0_initializer(adamic_maybe_number adamic_local_5_value, double adamic_local_8_argument_count);
static adamic_closure * adamic_function_1_captured(adamic_maybe_number adamic_local_6_value, double adamic_local_10_argument_count);
static adamic_string * adamic_function_2_maybe(adamic_array * adamic_local_7_items, double adamic_local_11_argument_count);
static adamic_code_function adamic_function_3_closure;
static adamic_counted_code_function adamic_function_4_initializer_value;
static adamic_counted_code_function adamic_function_5_maybe_value;
static adamic_object * adamic_function_6_Constructed_new(adamic_maybe_number adamic_local_20_value, double adamic_local_43_argument_count);
static void adamic_function_7_Constructed_new_initialize(adamic_object * adamic_local_16_this, adamic_maybe_number adamic_local_17_value, double adamic_local_18_argument_count);
static adamic_object * adamic_function_8_Derived_new(adamic_maybe_number adamic_local_24_value, double adamic_local_45_argument_count);
static void adamic_function_9_Derived_new_initialize(adamic_object * adamic_local_21_this, adamic_maybe_number adamic_local_22_value, double adamic_local_44_argument_count);
static adamic_object * adamic_function_10_Accessors_new(void);
static adamic_object * adamic_function_10_Accessors_new_in(adamic_region *region);
static double adamic_function_11_Accessors_getcount(adamic_object * adamic_local_25_this, double adamic_local_29_argument_count);
static void adamic_function_12_Accessors_setcount(adamic_object * adamic_local_26_this, double adamic_local_27_value, double adamic_local_30_argument_count);
static void adamic_function_13_Accessors_new_initialize(void);
static adamic_counted_code_function adamic_function_14_accessor;
static double adamic_function_15_property_getcount(adamic_object * adamic_local_33_object);
static void adamic_function_16_property_setcount(adamic_object * adamic_local_34_object, double adamic_local_35_value);
static double adamic_function_17_property_getliteralCount(adamic_object * adamic_local_36_object);
static void adamic_function_18_property_setcount(adamic_object * adamic_local_37_object, double adamic_local_38_value);
static void adamic_function_19_property_setcount(adamic_object * adamic_local_39_object, double adamic_local_40_value);

static const char *const adamic_shape_0_names[] = {"count"};
static const bool adamic_shape_0_references[] = {false};
static const adamic_shape adamic_shape_0 = {1, adamic_shape_0_names, adamic_shape_0_references, NULL};
static adamic_counted_method_function adamic_method_11;
static adamic_value adamic_method_11(adamic_object *self, adamic_value *arguments, size_t argument_count) {
	(void)arguments;
	return (adamic_value){.number = adamic_function_11_Accessors_getcount(self, (double)argument_count)};
}
static adamic_counted_method_function adamic_method_12;
static adamic_value adamic_method_12(adamic_object *self, adamic_value *arguments, size_t argument_count) {
	(void)arguments;
	adamic_function_12_Accessors_setcount(self, (argument_count > 0 ? arguments[0].number : 0.0), (double)argument_count);
	return (adamic_value){.number = 0};
}
static const char *const adamic_shape_1_method_names[] = {"$get:count", "$set:count"};
static const adamic_method_entry adamic_shape_1_method_code[] = {{.counted = true, .counted_code = adamic_method_11}, {.counted = true, .counted_code = adamic_method_12}};
static const adamic_methods adamic_shape_1_methods = {2, adamic_shape_1_method_names, adamic_shape_1_method_code};
static const adamic_shape adamic_shape_1 = {0, NULL, NULL, &adamic_shape_1_methods};
static adamic_slot_cache adamic_cache_43;
static adamic_slot_cache adamic_cache_44;
static adamic_slot_cache adamic_cache_54;
static adamic_slot_cache adamic_cache_55;
static adamic_slot_cache adamic_cache_58;
static adamic_slot_cache adamic_cache_59;
static const char *const adamic_shape_2_names[] = {"#accessor:14"};
static const bool adamic_shape_2_references[] = {true};
static const adamic_shape adamic_shape_2 = {1, adamic_shape_2_names, adamic_shape_2_references, NULL};
static const adamic_shape adamic_shape_3 = {0, NULL, NULL, NULL};
static const char *const adamic_shape_4_names[] = {"literalCount"};
static const bool adamic_shape_4_references[] = {false};
static const adamic_shape adamic_shape_4 = {1, adamic_shape_4_names, adamic_shape_4_references, NULL};

static const adamic_class adamic_class_1;
static const adamic_class adamic_class_2;
static const adamic_class adamic_class_3;
static const adamic_class adamic_class_4;
static const adamic_class adamic_class_1 = {NULL, 0, 1, NULL, 1, &adamic_shape_0, NULL, 0, false, 0, NULL};
static const adamic_class adamic_class_2 = {&adamic_class_1, 1, 1, NULL, 2, &adamic_shape_0, NULL, 0, false, 0, NULL};
static const size_t adamic_methods_3[] = {11, 12};
static adamic_value adamic_getter_3_0(adamic_object *object) {
	return (adamic_value){.number = adamic_function_11_Accessors_getcount(object, 0)};
}
static void adamic_setter_3_0(adamic_object *object, adamic_value value, int type) {
	(void)type;
	double incoming = (double)(value.number);
	adamic_function_12_Accessors_setcount(object, incoming, 1);
}
static const adamic_accessor adamic_accessors_3[] = {{"count", adamic_getter_3_0, adamic_setter_3_0, 1}};
static const adamic_class adamic_class_3 = {NULL, 0, 0, adamic_methods_3, 3, &adamic_shape_3, adamic_accessors_3, 1, false, 0, NULL};
static adamic_value adamic_getter_4_0(adamic_object *object) {
	adamic_slot_cache cache = {NULL, 0};
	adamic_closure *closure = adamic_object_field(object, "#accessor:14", &cache)->reference;
	return adamic_function_14_accessor(closure, (adamic_value[]){{.reference = object}}, 1);
}
static const adamic_accessor adamic_accessors_4[] = {{"literalCount", adamic_getter_4_0, NULL, 1}};
static const adamic_class adamic_class_4 = {NULL, 0, 1, NULL, 0, &adamic_shape_4, adamic_accessors_4, 1, false, 0, NULL};
static adamic_string * adamic_function_0_initializer(adamic_maybe_number adamic_local_5_value, double adamic_local_8_argument_count) {
	ADAMIC_CHECK_STACK();
	(void)adamic_local_8_argument_count;
	double adamic_temporary_1;
	if (adamic_local_5_value.present) {
		adamic_temporary_1 = adamic_local_5_value.number;
	} else {
		adamic_temporary_1 = adamic_local_8_argument_count;
	}
	double adamic_local_4_value = adamic_temporary_1;
	adamic_string * adamic_temporary_2 = adamic_string_from_number(adamic_local_8_argument_count);
	adamic_string * adamic_temporary_3 = adamic_string_from_number(adamic_local_4_value);
	adamic_string * adamic_temporary_4 = adamic_string_concat(3, (adamic_string *const[]){adamic_temporary_2, &adamic_string_0, adamic_temporary_3});
	adamic_string * adamic_temporary_5 = adamic_temporary_4;
	adamic_release(adamic_temporary_3);
	adamic_release(adamic_temporary_2);
	return adamic_temporary_5;
	adamic_unreachable();
}

static adamic_closure * adamic_function_1_captured(adamic_maybe_number adamic_local_6_value, double adamic_local_10_argument_count) {
	ADAMIC_CHECK_STACK();
	(void)adamic_local_10_argument_count;
	adamic_cell *adamic_local_6_value_cell = adamic_cell_new((adamic_value){.number = adamic_maybe_number_pack(adamic_local_6_value)}, false);
	adamic_cell *adamic_local_9_count_cell = adamic_cell_new((adamic_value){.number = adamic_local_10_argument_count}, false);
	adamic_closure * adamic_temporary_6 = adamic_closure_new(adamic_function_3_closure, 2);
	adamic_temporary_6->source_length = 0;
	adamic_temporary_6->cells[0] = adamic_retain(adamic_local_9_count_cell);
	adamic_temporary_6->cells[1] = adamic_retain(adamic_local_6_value_cell);
	adamic_closure * adamic_temporary_7 = adamic_temporary_6;
	adamic_release(adamic_local_9_count_cell);
	adamic_release(adamic_local_6_value_cell);
	return adamic_temporary_7;
	adamic_unreachable();
}

static adamic_string * adamic_function_2_maybe(adamic_array * adamic_local_7_items, double adamic_local_11_argument_count) {
	ADAMIC_CHECK_STACK();
	(void)adamic_local_11_argument_count;
	adamic_string * adamic_temporary_8 = adamic_string_from_number(adamic_local_11_argument_count);
	adamic_string * adamic_temporary_9 = adamic_array_join(adamic_local_7_items, &adamic_string_1, adamic_join_maybe_numbers);
	adamic_string * adamic_temporary_10 = adamic_string_concat(3, (adamic_string *const[]){adamic_temporary_8, &adamic_string_0, adamic_temporary_9});
	adamic_string * adamic_temporary_11 = adamic_temporary_10;
	adamic_release(adamic_temporary_9);
	adamic_release(adamic_temporary_8);
	return adamic_temporary_11;
	adamic_unreachable();
}

static adamic_value adamic_function_3_closure(adamic_closure *self, adamic_value *arguments) {
	ADAMIC_CHECK_STACK();
	(void)self;
	(void)arguments;
	double adamic_temporary_12 = self->cells[0]->value.number;
	adamic_maybe_number adamic_temporary_13 = adamic_maybe_number_unpack(self->cells[1]->value.number);
	double adamic_temporary_14;
	if (adamic_temporary_13.present) {
		adamic_temporary_14 = adamic_temporary_13.number;
	} else {
		adamic_temporary_14 = (0x0p+00);
	}
	double adamic_temporary_15 = (adamic_temporary_12 + adamic_temporary_14);
	return (adamic_value){.number = adamic_temporary_15};
	adamic_unreachable();
}

static adamic_value adamic_function_4_initializer_value(adamic_closure *self, adamic_value *arguments, size_t argument_count) {
	ADAMIC_CHECK_STACK();
	(void)self;
	(void)argument_count;
	(void)arguments;
	double adamic_local_41_argument_count = (double)argument_count;
	(void)adamic_local_41_argument_count;
	adamic_maybe_number adamic_local_12_value = (argument_count > 0 ? (argument_count > 0 ? adamic_maybe_number_unpack(arguments[0].number) : (adamic_maybe_number){false, 0.0}) : (adamic_maybe_number){false, 0.0});
	adamic_string * adamic_temporary_16 = adamic_function_0_initializer(adamic_local_12_value, adamic_local_41_argument_count);
	adamic_string * adamic_temporary_17 = adamic_temporary_16;
	return (adamic_value){.reference = adamic_temporary_17};
	adamic_unreachable();
}

static adamic_value adamic_function_5_maybe_value(adamic_closure *self, adamic_value *arguments, size_t argument_count) {
	ADAMIC_CHECK_STACK();
	(void)self;
	(void)argument_count;
	(void)arguments;
	double adamic_local_42_argument_count = (double)argument_count;
	(void)adamic_local_42_argument_count;
	adamic_array *adamic_local_14_items = arguments[2].reference;
	adamic_retain(adamic_local_14_items);
	adamic_string * adamic_temporary_18 = adamic_function_2_maybe(adamic_local_14_items, adamic_local_42_argument_count);
	adamic_string * adamic_temporary_19 = adamic_temporary_18;
	adamic_release(adamic_local_14_items);
	return (adamic_value){.reference = adamic_temporary_19};
	adamic_unreachable();
}

static adamic_object * adamic_function_6_Constructed_new(adamic_maybe_number adamic_local_20_value, double adamic_local_43_argument_count) {
	ADAMIC_CHECK_STACK();
	(void)adamic_local_43_argument_count;
	adamic_object * adamic_temporary_20 = adamic_object_new(&adamic_shape_0);
	adamic_temporary_20->class = &adamic_class_1;
	adamic_temporary_20->slots[0].number = (0x0p+00);
	adamic_object * adamic_local_19_this = adamic_temporary_20;
	adamic_function_7_Constructed_new_initialize(adamic_local_19_this, adamic_local_20_value, adamic_local_43_argument_count);
	adamic_object * adamic_temporary_21 = adamic_retain(adamic_local_19_this);
	adamic_release(adamic_local_19_this);
	return adamic_temporary_21;
	adamic_unreachable();
}

static void adamic_function_7_Constructed_new_initialize(adamic_object * adamic_local_16_this, adamic_maybe_number adamic_local_17_value, double adamic_local_18_argument_count) {
	ADAMIC_CHECK_STACK();
	(void)adamic_local_18_argument_count;
	adamic_function_18_property_setcount(adamic_local_16_this, (0x0p+00));
	double adamic_temporary_22;
	if (adamic_local_17_value.present) {
		adamic_temporary_22 = adamic_local_17_value.number;
	} else {
		adamic_temporary_22 = (0x0p+00);
	}
	adamic_function_19_property_setcount(adamic_local_16_this, (adamic_local_18_argument_count + adamic_temporary_22));
}

static adamic_object * adamic_function_8_Derived_new(adamic_maybe_number adamic_local_24_value, double adamic_local_45_argument_count) {
	ADAMIC_CHECK_STACK();
	(void)adamic_local_45_argument_count;
	adamic_object * adamic_temporary_23 = adamic_object_new(&adamic_shape_0);
	adamic_temporary_23->class = &adamic_class_2;
	adamic_temporary_23->slots[0].number = (0x0p+00);
	adamic_object * adamic_local_23_this = adamic_temporary_23;
	adamic_function_9_Derived_new_initialize(adamic_local_23_this, adamic_local_24_value, adamic_local_45_argument_count);
	adamic_object * adamic_temporary_24 = adamic_retain(adamic_local_23_this);
	adamic_release(adamic_local_23_this);
	return adamic_temporary_24;
	adamic_unreachable();
}

static void adamic_function_9_Derived_new_initialize(adamic_object * adamic_local_21_this, adamic_maybe_number adamic_local_22_value, double adamic_local_44_argument_count) {
	ADAMIC_CHECK_STACK();
	(void)adamic_local_44_argument_count;
	adamic_function_7_Constructed_new_initialize(adamic_local_21_this, adamic_local_22_value, adamic_local_44_argument_count);
}

static adamic_object * adamic_function_10_Accessors_new(void) {
	ADAMIC_CHECK_STACK();
	adamic_object * adamic_temporary_25 = adamic_object_new(&adamic_shape_1);
	adamic_temporary_25->class = &adamic_class_3;
	adamic_object * adamic_local_28_this = adamic_temporary_25;
	adamic_object * adamic_temporary_26 = adamic_retain(adamic_local_28_this);
	adamic_release(adamic_local_28_this);
	return adamic_temporary_26;
	adamic_unreachable();
}

static adamic_object * adamic_function_10_Accessors_new_in(adamic_region *region) {
	ADAMIC_CHECK_STACK();
	adamic_object *adamic_temporary_27 = adamic_object_new_in(region, &adamic_shape_1);
	adamic_temporary_27->class = &adamic_class_3;
	adamic_object * adamic_local_28_this = adamic_retain(adamic_temporary_27);
	adamic_object * adamic_temporary_28 = adamic_local_28_this;
	adamic_release(adamic_local_28_this);
	return adamic_temporary_28;
	adamic_unreachable();
}

static double adamic_function_11_Accessors_getcount(adamic_object * adamic_local_25_this, double adamic_local_29_argument_count) {
	ADAMIC_CHECK_STACK();
	(void)adamic_local_29_argument_count;
	double adamic_temporary_29 = adamic_local_29_argument_count;
	return adamic_temporary_29;
	adamic_unreachable();
}

static void adamic_function_12_Accessors_setcount(adamic_object * adamic_local_26_this, double adamic_local_27_value, double adamic_local_30_argument_count) {
	ADAMIC_CHECK_STACK();
	(void)adamic_local_30_argument_count;
	adamic_string * adamic_temporary_30 = adamic_string_from_number(adamic_local_30_argument_count);
	adamic_string * adamic_temporary_31 = adamic_string_from_number(adamic_local_27_value);
	adamic_string * adamic_temporary_32 = adamic_string_concat(3, (adamic_string *const[]){adamic_temporary_30, &adamic_string_0, adamic_temporary_31});
	adamic_write_line(adamic_stdout, adamic_temporary_32);
	adamic_release(adamic_temporary_32);
	adamic_release(adamic_temporary_31);
	adamic_release(adamic_temporary_30);
	return;
}

static void adamic_function_13_Accessors_new_initialize(void) {
	ADAMIC_CHECK_STACK();
}

static adamic_value adamic_function_14_accessor(adamic_closure *self, adamic_value *arguments, size_t argument_count) {
	ADAMIC_CHECK_STACK();
	(void)self;
	(void)argument_count;
	(void)arguments;
	double adamic_local_32_argument_count = (double)argument_count - 1;
	(void)adamic_local_32_argument_count;
	adamic_object * adamic_local_31_this = (argument_count > 0 ? (adamic_object *)(argument_count > 0 ? arguments[0].reference : NULL) : NULL);
	adamic_retain(adamic_local_31_this);
	double adamic_temporary_33 = adamic_local_32_argument_count;
	adamic_release(adamic_local_31_this);
	return (adamic_value){.number = adamic_temporary_33};
	adamic_unreachable();
}

static double adamic_function_15_property_getcount(adamic_object * adamic_local_33_object) {
	ADAMIC_CHECK_STACK();
	bool adamic_temporary_34 = adamic_accessor_find(adamic_local_33_object, "count") != NULL;
	if (adamic_temporary_34) {
		const adamic_accessor *adamic_temporary_35 = adamic_accessor_find(adamic_local_33_object, "count");
		adamic_value adamic_temporary_36 = adamic_accessor_get(adamic_local_33_object, "count");
		double adamic_temporary_37 = (adamic_temporary_35->type == 7 ? (adamic_maybe_number_unpack(adamic_temporary_36.number)).number : adamic_temporary_35->type == 10 ? ((const adamic_number_box *)adamic_temporary_36.reference)->number : adamic_temporary_36.number);
		double adamic_temporary_38 = adamic_temporary_37;
		return adamic_temporary_38;
	}
	double adamic_temporary_39 = (&adamic_local_33_object->slots[0])->number;
	double adamic_temporary_40 = adamic_temporary_39;
	return adamic_temporary_40;
	adamic_unreachable();
}

static void adamic_function_16_property_setcount(adamic_object * adamic_local_34_object, double adamic_local_35_value) {
	ADAMIC_CHECK_STACK();
	bool adamic_temporary_41 = adamic_accessor_find(adamic_local_34_object, "count") != NULL;
	if (adamic_temporary_41) {
		adamic_accessor_set(adamic_local_34_object, "count", (adamic_value){.number = adamic_local_35_value}, 1);
	} else {
		if (adamic_local_34_object == NULL) {
			static const char message[] = "TypeError: Cannot set properties of undefined (setting 'count')";
			adamic_panic(message, sizeof message - 1);
		}
		adamic_object_check_data_write(adamic_local_34_object, "count");
		adamic_value *adamic_temporary_42 = (adamic_local_34_object->shape == &adamic_shape_0 ? (&adamic_local_34_object->slots[0]) : adamic_object_data_field(adamic_local_34_object, "count", &adamic_cache_44));
		adamic_temporary_42->number = adamic_local_35_value;
	}
}

static double adamic_function_17_property_getliteralCount(adamic_object * adamic_local_36_object) {
	ADAMIC_CHECK_STACK();
	bool adamic_temporary_45 = adamic_accessor_find(adamic_local_36_object, "literalCount") != NULL;
	if (adamic_temporary_45) {
		const adamic_accessor *adamic_temporary_46 = adamic_accessor_find(adamic_local_36_object, "literalCount");
		adamic_value adamic_temporary_47 = adamic_accessor_get(adamic_local_36_object, "literalCount");
		double adamic_temporary_48 = (adamic_temporary_46->type == 7 ? (adamic_maybe_number_unpack(adamic_temporary_47.number)).number : adamic_temporary_46->type == 10 ? ((const adamic_number_box *)adamic_temporary_47.reference)->number : adamic_temporary_47.number);
		double adamic_temporary_49 = adamic_temporary_48;
		return adamic_temporary_49;
	}
	double adamic_temporary_50 = (&adamic_local_36_object->slots[0])->number;
	double adamic_temporary_51 = adamic_temporary_50;
	return adamic_temporary_51;
	adamic_unreachable();
}

static void adamic_function_18_property_setcount(adamic_object * adamic_local_37_object, double adamic_local_38_value) {
	ADAMIC_CHECK_STACK();
	bool adamic_temporary_52 = adamic_accessor_find(adamic_local_37_object, "count") != NULL;
	if (adamic_temporary_52) {
		adamic_accessor_set(adamic_local_37_object, "count", (adamic_value){.number = adamic_local_38_value}, 1);
	} else {
		if (adamic_local_37_object == NULL) {
			static const char message[] = "TypeError: Cannot set properties of undefined (setting 'count')";
			adamic_panic(message, sizeof message - 1);
		}
		adamic_object_check_data_write(adamic_local_37_object, "count");
		adamic_value *adamic_temporary_53 = (adamic_local_37_object->shape == &adamic_shape_0 ? (&adamic_local_37_object->slots[0]) : adamic_object_data_field(adamic_local_37_object, "count", &adamic_cache_55));
		adamic_temporary_53->number = adamic_local_38_value;
	}
}

static void adamic_function_19_property_setcount(adamic_object * adamic_local_39_object, double adamic_local_40_value) {
	ADAMIC_CHECK_STACK();
	bool adamic_temporary_56 = adamic_accessor_find(adamic_local_39_object, "count") != NULL;
	if (adamic_temporary_56) {
		adamic_accessor_set(adamic_local_39_object, "count", (adamic_value){.number = adamic_local_40_value}, 1);
	} else {
		if (adamic_local_39_object == NULL) {
			static const char message[] = "TypeError: Cannot set properties of undefined (setting 'count')";
			adamic_panic(message, sizeof message - 1);
		}
		adamic_object_check_data_write(adamic_local_39_object, "count");
		adamic_value *adamic_temporary_57 = (adamic_local_39_object->shape == &adamic_shape_0 ? (&adamic_local_39_object->slots[0]) : adamic_object_data_field(adamic_local_39_object, "count", &adamic_cache_59));
		adamic_temporary_57->number = adamic_local_40_value;
	}
}

int main(int argc, char **argv) {
	adamic_start(argc, argv);
	adamic_closure * adamic_temporary_60 = adamic_counted_closure_new(adamic_function_4_initializer_value, 0);
	adamic_temporary_60->source_length = 0;
	adamic_closure * adamic_temporary_61 = adamic_global_13_initializer_value;
	adamic_global_13_initializer_value = adamic_temporary_60;
	adamic_release(adamic_temporary_61);
	adamic_ready_13 = true;
	adamic_closure * adamic_temporary_62 = adamic_counted_closure_new(adamic_function_5_maybe_value, 0);
	adamic_temporary_62->source_length = 0;
	adamic_closure * adamic_temporary_63 = adamic_global_15_maybe_value;
	adamic_global_15_maybe_value = adamic_temporary_62;
	adamic_release(adamic_temporary_63);
	adamic_ready_15 = true;
	adamic_string * adamic_temporary_64 = adamic_function_0_initializer((adamic_maybe_number){false, 0.0}, 0);
	adamic_write_line(adamic_stdout, adamic_temporary_64);
	adamic_release(adamic_temporary_64);
	adamic_string * adamic_temporary_65 = adamic_function_0_initializer((adamic_maybe_number){false, 0.0}, 1);
	adamic_write_line(adamic_stdout, adamic_temporary_65);
	adamic_release(adamic_temporary_65);
	adamic_string * adamic_temporary_66 = adamic_function_0_initializer(((adamic_maybe_number){true, (0x1.2p+03)}), 1);
	adamic_write_line(adamic_stdout, adamic_temporary_66);
	adamic_release(adamic_temporary_66);
	adamic_closure * adamic_temporary_67 = adamic_retain(adamic_global_13_initializer_value);
	adamic_closure * adamic_temporary_68 = adamic_global_0_initialized;
	adamic_global_0_initialized = adamic_temporary_67;
	adamic_release(adamic_temporary_68);
	adamic_ready_0 = true;
	adamic_closure * adamic_temporary_69 = adamic_retain(adamic_global_0_initialized);
	adamic_array * adamic_temporary_70 = adamic_array_new(0, false);
	for (size_t adamic_temporary_71 = 0; adamic_temporary_71 < 0; adamic_temporary_71++) {
		adamic_array_push(adamic_temporary_70, ((adamic_value *)NULL)[adamic_temporary_71]);
	}
	adamic_value adamic_temporary_72 = adamic_closure_call(adamic_temporary_69, (adamic_value[]){[0] = {.number = adamic_maybe_number_pack((adamic_maybe_number){false, 0.0})}, [2] = {.reference = adamic_temporary_70}}, 0);
	adamic_string * adamic_temporary_73 = (adamic_string *)adamic_temporary_72.reference;
	adamic_write_line(adamic_stdout, adamic_temporary_73);
	adamic_release(adamic_temporary_73);
	adamic_release(adamic_temporary_70);
	adamic_release(adamic_temporary_69);
	adamic_closure * adamic_temporary_74 = adamic_retain(adamic_global_0_initialized);
	adamic_array * adamic_temporary_75 = adamic_array_new(0, false);
	for (size_t adamic_temporary_76 = 0; adamic_temporary_76 < 1; adamic_temporary_76++) {
		adamic_array_push(adamic_temporary_75, (adamic_value[]){{.number = adamic_maybe_number_pack((adamic_maybe_number){false, 0.0})}}[adamic_temporary_76]);
	}
	adamic_value adamic_temporary_77 = adamic_closure_call(adamic_temporary_74, (adamic_value[]){[0] = {.number = adamic_maybe_number_pack((adamic_maybe_number){false, 0.0})}, [2] = {.reference = adamic_temporary_75}}, 1);
	adamic_string * adamic_temporary_78 = (adamic_string *)adamic_temporary_77.reference;
	adamic_write_line(adamic_stdout, adamic_temporary_78);
	adamic_release(adamic_temporary_78);
	adamic_release(adamic_temporary_75);
	adamic_release(adamic_temporary_74);
	adamic_closure * adamic_temporary_79 = adamic_function_1_captured((adamic_maybe_number){false, 0.0}, 0);
	adamic_value adamic_temporary_80 = adamic_temporary_79->code(adamic_temporary_79, NULL);
	double adamic_temporary_81 = adamic_temporary_80.number;
	adamic_string * adamic_temporary_82 = adamic_string_from_number(adamic_temporary_81);
	adamic_closure * adamic_temporary_83 = adamic_function_1_captured((adamic_maybe_number){false, 0.0}, 1);
	adamic_value adamic_temporary_84 = adamic_temporary_83->code(adamic_temporary_83, NULL);
	double adamic_temporary_85 = adamic_temporary_84.number;
	adamic_string * adamic_temporary_86 = adamic_string_from_number(adamic_temporary_85);
	adamic_closure * adamic_temporary_87 = adamic_function_1_captured(((adamic_maybe_number){true, (0x1.cp+02)}), 1);
	adamic_value adamic_temporary_88 = adamic_temporary_87->code(adamic_temporary_87, NULL);
	double adamic_temporary_89 = adamic_temporary_88.number;
	adamic_string * adamic_temporary_90 = adamic_string_from_number(adamic_temporary_89);
	adamic_string * adamic_temporary_91 = adamic_string_concat(5, (adamic_string *const[]){adamic_temporary_82, &adamic_string_2, adamic_temporary_86, &adamic_string_2, adamic_temporary_90});
	adamic_write_line(adamic_stdout, adamic_temporary_91);
	adamic_release(adamic_temporary_91);
	adamic_release(adamic_temporary_90);
	adamic_release(adamic_temporary_87);
	adamic_release(adamic_temporary_86);
	adamic_release(adamic_temporary_83);
	adamic_release(adamic_temporary_82);
	adamic_release(adamic_temporary_79);
	adamic_array * adamic_temporary_92 = adamic_array_new(3, false);
	adamic_temporary_92->element_type = 7;
	adamic_array_push(adamic_temporary_92, (adamic_value){.number = adamic_maybe_number_pack((adamic_maybe_number){false, 0.0})});
	adamic_array_push(adamic_temporary_92, (adamic_value){.number = adamic_maybe_number_pack(((adamic_maybe_number){true, (0x1p+01)}))});
	adamic_array_push(adamic_temporary_92, (adamic_value){.number = adamic_maybe_number_pack((adamic_maybe_number){false, 0.0})});
	adamic_string * adamic_temporary_93 = adamic_function_2_maybe(adamic_temporary_92, (0x1.8p+01));
	adamic_write_line(adamic_stdout, adamic_temporary_93);
	adamic_release(adamic_temporary_93);
	adamic_release(adamic_temporary_92);
	adamic_closure * adamic_temporary_94 = adamic_retain(adamic_global_15_maybe_value);
	adamic_closure * adamic_temporary_95 = adamic_global_1_maybeValue;
	adamic_global_1_maybeValue = adamic_temporary_94;
	adamic_release(adamic_temporary_95);
	adamic_ready_1 = true;
	adamic_closure * adamic_temporary_96 = adamic_retain(adamic_global_1_maybeValue);
	adamic_array * adamic_temporary_97 = adamic_array_new(0, false);
	for (size_t adamic_temporary_98 = 0; adamic_temporary_98 < 3; adamic_temporary_98++) {
		adamic_array_push(adamic_temporary_97, (adamic_value[]){{.number = adamic_maybe_number_pack((adamic_maybe_number){false, 0.0})}, {.number = adamic_maybe_number_pack(((adamic_maybe_number){true, (0x1p+01)}))}, {.number = adamic_maybe_number_pack((adamic_maybe_number){false, 0.0})}}[adamic_temporary_98]);
	}
	adamic_value adamic_temporary_99 = adamic_closure_call(adamic_temporary_96, (adamic_value[]){[0] = {.number = adamic_maybe_number_pack((adamic_maybe_number){false, 0.0})}, [1] = {.number = adamic_maybe_number_pack(((adamic_maybe_number){true, (0x1p+01)}))}, [2] = {.reference = adamic_temporary_97}}, 3);
	adamic_string * adamic_temporary_100 = (adamic_string *)adamic_temporary_99.reference;
	adamic_write_line(adamic_stdout, adamic_temporary_100);
	adamic_release(adamic_temporary_100);
	adamic_release(adamic_temporary_97);
	adamic_release(adamic_temporary_96);
	adamic_object * adamic_temporary_101 = adamic_function_6_Constructed_new((adamic_maybe_number){false, 0.0}, 0);
	double adamic_temporary_102 = adamic_function_15_property_getcount(adamic_temporary_101);
	adamic_string * adamic_temporary_103 = adamic_string_from_number(adamic_temporary_102);
	adamic_object * adamic_temporary_104 = adamic_function_6_Constructed_new((adamic_maybe_number){false, 0.0}, 1);
	double adamic_temporary_105 = adamic_function_15_property_getcount(adamic_temporary_104);
	adamic_string * adamic_temporary_106 = adamic_string_from_number(adamic_temporary_105);
	adamic_object * adamic_temporary_107 = adamic_function_6_Constructed_new(((adamic_maybe_number){true, (0x1.cp+02)}), 1);
	double adamic_temporary_108 = adamic_function_15_property_getcount(adamic_temporary_107);
	adamic_string * adamic_temporary_109 = adamic_string_from_number(adamic_temporary_108);
	adamic_string * adamic_temporary_110 = adamic_string_concat(5, (adamic_string *const[]){adamic_temporary_103, &adamic_string_2, adamic_temporary_106, &adamic_string_2, adamic_temporary_109});
	adamic_write_line(adamic_stdout, adamic_temporary_110);
	adamic_release(adamic_temporary_110);
	adamic_release(adamic_temporary_109);
	adamic_release(adamic_temporary_107);
	adamic_release(adamic_temporary_106);
	adamic_release(adamic_temporary_104);
	adamic_release(adamic_temporary_103);
	adamic_release(adamic_temporary_101);
	adamic_object * adamic_temporary_111 = adamic_function_8_Derived_new((adamic_maybe_number){false, 0.0}, 0);
	double adamic_temporary_112 = adamic_function_15_property_getcount(adamic_temporary_111);
	adamic_string * adamic_temporary_113 = adamic_string_from_number(adamic_temporary_112);
	adamic_object * adamic_temporary_114 = adamic_function_8_Derived_new((adamic_maybe_number){false, 0.0}, 1);
	double adamic_temporary_115 = adamic_function_15_property_getcount(adamic_temporary_114);
	adamic_string * adamic_temporary_116 = adamic_string_from_number(adamic_temporary_115);
	adamic_object * adamic_temporary_117 = adamic_function_8_Derived_new(((adamic_maybe_number){true, (0x1.cp+02)}), 1);
	double adamic_temporary_118 = adamic_function_15_property_getcount(adamic_temporary_117);
	adamic_string * adamic_temporary_119 = adamic_string_from_number(adamic_temporary_118);
	adamic_string * adamic_temporary_120 = adamic_string_concat(5, (adamic_string *const[]){adamic_temporary_113, &adamic_string_2, adamic_temporary_116, &adamic_string_2, adamic_temporary_119});
	adamic_write_line(adamic_stdout, adamic_temporary_120);
	adamic_release(adamic_temporary_120);
	adamic_release(adamic_temporary_119);
	adamic_release(adamic_temporary_117);
	adamic_release(adamic_temporary_116);
	adamic_release(adamic_temporary_114);
	adamic_release(adamic_temporary_113);
	adamic_release(adamic_temporary_111);
	adamic_object * adamic_temporary_121 = adamic_function_10_Accessors_new();
	adamic_object * adamic_temporary_122 = adamic_global_2_accessors;
	adamic_global_2_accessors = adamic_temporary_121;
	adamic_release(adamic_temporary_122);
	adamic_ready_2 = true;
	adamic_object * adamic_temporary_123 = adamic_global_2_accessors;
	double adamic_temporary_124 = adamic_function_15_property_getcount(adamic_temporary_123);
	adamic_string * adamic_temporary_125 = adamic_string_from_number(adamic_temporary_124);
	adamic_string * adamic_temporary_126 = adamic_string_concat(1, (adamic_string *const[]){adamic_temporary_125});
	adamic_write_line(adamic_stdout, adamic_temporary_126);
	adamic_release(adamic_temporary_126);
	adamic_release(adamic_temporary_125);
	adamic_object * adamic_temporary_127 = adamic_global_2_accessors;
	adamic_function_16_property_setcount(adamic_temporary_127, (0x1.2p+03));
	adamic_closure * adamic_temporary_128 = adamic_counted_closure_new(adamic_function_14_accessor, 0);
	adamic_temporary_128->source_length = 0;
	adamic_temporary_128->receiver = true;
	adamic_object * adamic_temporary_129 = adamic_object_new(&adamic_shape_2);
	adamic_temporary_129->class = &adamic_class_4;
	adamic_temporary_129->slots[0].reference = adamic_temporary_128;
	adamic_object * adamic_temporary_130 = adamic_global_3_literal;
	adamic_global_3_literal = adamic_temporary_129;
	adamic_release(adamic_temporary_130);
	adamic_ready_3 = true;
	adamic_object * adamic_temporary_131 = adamic_global_3_literal;
	double adamic_temporary_132 = adamic_function_17_property_getliteralCount(adamic_temporary_131);
	adamic_string * adamic_temporary_133 = adamic_string_from_number(adamic_temporary_132);
	adamic_string * adamic_temporary_134 = adamic_string_concat(1, (adamic_string *const[]){adamic_temporary_133});
	adamic_write_line(adamic_stdout, adamic_temporary_134);
	adamic_release(adamic_temporary_134);
	adamic_release(adamic_temporary_133);
	adamic_release(adamic_global_3_literal);
	adamic_global_3_literal = NULL;
	adamic_release(adamic_global_2_accessors);
	adamic_global_2_accessors = NULL;
	adamic_release(adamic_global_1_maybeValue);
	adamic_global_1_maybeValue = NULL;
	adamic_release(adamic_global_0_initialized);
	adamic_global_0_initialized = NULL;
	adamic_release(adamic_global_15_maybe_value);
	adamic_global_15_maybe_value = NULL;
	adamic_release(adamic_global_13_initializer_value);
	adamic_global_13_initializer_value = NULL;
	return 0;
}
