from pathlib import Path
import json,statistics,shlex,shutil
p=Path('/tmp/u162/evidence');runs=json.loads((p/'runs.json').read_text());plan=json.loads((p/'plan.json').read_text());name='TestMissingStatementFailsWithMethodName';pkg='stage3/census/latent/statementrewrite';matrix=[]
def es(id):return [json.loads(s) for s in (p/(id+'.log')).read_text().splitlines()]
seconds=statistics.median([next(x['Elapsed'] for x in reversed(es('timing-'+str(i))) if x['Action']=='pass' and not x.get('Test')) for i in range(1,4)])
for id in ['M1','M2','M3','P1']:
 events=es(id);fail=[x['Test'] for x in events if x['Action']=='fail' and x.get('Test')];line=next((x['Output'].strip() for x in events if x.get('OutputType')=='error'),None);matrix.append(dict(id=id,failed_rows=fail,failing_line=line,command=next(x['command'] for x in runs if x['id']==id),environment={'ADAMIC_MUTANT':id,'ADAMIC_BUILD_CACHE_DIR':'/tmp/u162/cache/'+id}))
(p/'matrix.json').write_text(json.dumps(matrix,indent=2));line=matrix[1]['failing_line'];command='ADAMIC_MUTANT=M2 ADAMIC_BUILD_CACHE_DIR=/tmp/u162/cache/M2 '+shlex.join(matrix[1]['command'])+' > M2.log 2>&1';row=dict(test=name,package=pkg,file=pkg+'/main_test.go',seconds=seconds,oracle='Self-written CLI contract: nonzero exit must contain lowering.statement: expected exactly one function, found 0; output file must not exist. M2 demonstrates that an unrelated failure is rejected.',oracle_kind='self',kills=['M1','M2'],unique_kills=['M1','M2'],last_proven_fail='M2: '+line,verdict='setup-check',subsumed_by=[],mutants_in_matrix=3,probe_kills=['P1'],subsumer_seconds=None,vacuous=False,bounded=False,matrix_rows=[name],evidence=command+'; '+line)
(p/'rows.json').write_text(json.dumps([row],indent=2));summary=['Unit u162: one top-level test at origin/main cf735d9fba9e38de6368575e5630e44375a86eaf.','Clean whole-package baseline and three individual count=1 runs passed; no skips.','Verdict: setup-check; M1 and M2 are unique catches within this package.','M3 survives and demonstrably removes comments; P1 empty-entry probe is caught.','Evidence branch: test-audit/stage3-census-latent-statementrewrite; production source restored.'];text='\n'.join(summary)+'\n\n```json\n'+json.dumps([row],indent=2)+'\n```\n\n| ID | Origin file:line | Change | Failed rows |\n|---|---|---|---|\n'
for x in plan:text+='| '+x['id']+' | '+x['file']+':'+str(x['line'])+' | '+x['old'].replace('\n',' ')+' -> '+x['new'].replace('\n',' ')+' | '+(', '.join(next(m['failed_rows'] for m in matrix if m['id']==x['id'])) or 'none')+' |\n'
text+='\nSurvivor M3: parsing with mode 0 instead of parser.ParseComments drops // package note and // statement comment from the rewritten valid-method output. Both clean and mutant exit 0. See M3-witness.diff and the three survivor source/output files. This is observed changed behavior unguarded by this package, not an equivalent candidate. The witness commands are recorded in runs.json, with ADAMIC_MUTANT=M0 and M3 respectively.\n\n'
text+='CODE UNDER TEST: the Go statementrewrite CLI that constructs census instrumentation by locating lowering.statement, renaming it latentStatementRaw, retaining its body and adding the wrapper. ORACLE: the hand-written expected diagnostic substring, nonzero exit and absence of output file in main_test.go. No outside authority is claimed.\n\n'
text+='Scope and instruction issues\n\nThe requested package contains exactly one Test and no families, helpers, opt-in rows or witnesses. No names moved or vanished. The error assertion uses the word mutant, but the test itself checks the rewriter refusal directly; it does not witness another agreement comparator. Because the code builds census instrumentation, the suite-construction category applies and the verdict is setup-check. M1 and M2 are construction mutations in code under test, not edits to its oracle. Their unique catches do not establish repository-wide uniqueness.\n\n'
text+='The function reached by the missing-method fixture is main. printed is declared in the same package but the short-circuit method-name condition prevents the fixture calling it. The valid-method survivor witness does reach printed. The inventory lists both facts rather than treating package membership as coverage. Three mutants were fixed from main before any mutated run: one diagnostic constant, one count condition, one parser option. All matrix commands run the whole package.\n\n'
text+='The count mutant panics in a go-run subprocess; it does not abort the Go test binary. The actual test records and rejects that unrelated index panic because it lacks the required method-name diagnostic. Thus this oracle checks more than an exit code, although it checks only a substring, not exact stderr or an exact exit status. The test does not exercise successful rewriting, comment retention, signature validation or wrapper correctness. M3 demonstrates the comment-retention gap concretely.\n\n'
text+='Warm tools do not remove the required npm ci step. stage3/api dependencies were refreshed even though this package uses only Go and loads no node_modules. No tools setup script was needed, no opt-ins were required and no test skipped. No step exceeded 90 seconds, and no narrowing was needed. Compiler code and native products were not mutated, so no compiler cache isolation or clang rebuild was needed. The switched CLI is compiled once and inherited ADAMIC_MUTANT selects the child go-run behavior; each standalone diff has no switch and passes go vet for the package.\n\n'
text+='The initial pure probe used an unconditional return and go vet rejected the following unreachable code. It was replaced by if true { return }, which passes vet and has the same empty-entry behavior as the runtime probe. That correction caused a second, entirely green clean measurement round and replay of all matrices; the saved logs and timings are from the final round. Tests and their expected values were never modified. Production source is restored, and the final whole-package run passes.\n\n'
prep=json.loads((p/'preparation.json').read_text());build=sum(x['wall_seconds'] for x in runs if 'vet' in x['id'] or x['id']=='switch-build');testing=sum(x['wall_seconds'] for x in runs if x['id'].startswith('timing-') or x['id'] in ['M0','M1','M2','M3','P1','restored']);text+='Timing and uncovered work\n\nWarm setup: 0 seconds for setup.sh; nproc=5. npm ci: '+str(round(prep['npm-ci']['seconds'],3))+' seconds. Initial baseline shell wall: '+str(round(prep['baseline']['seconds'],3))+' seconds. Individual binary times: 0.038, 0.040, 0.041 seconds, median '+str(seconds)+' seconds. Final-round Go build/vet shell wall: '+str(round(build,3))+' seconds. Final-round measurement, matrix and restored-test shell wall: '+str(round(testing,3))+' seconds. Raw commands and wall times are in preparation.json and runs.json. Total session work was approximately four minutes, including reading, script correction, evidence preparation and push.\n\nOther packages were not run. The full repository gate, exact diagnostic text authority, successful-rewrite correctness beyond the comment witness, and repository-wide uniqueness remain uncovered. No test was changed or deleted, main was not pushed, and no pull request was opened.\n';(p/'REPORT.md').write_text(text)
for name in ['audit.py','report.py']:shutil.copy('/tmp/u162/'+name,p/name)
print(json.dumps([row],indent=2))
