const fs=require('fs'),path=require('path'),ts=require('/tmp/lane5-c-original/lib/typescript.js');
const home=path.resolve(__dirname,'..'),e=require('../original-members.json'),c=require('/tmp/lane5-c-carrier-declarations.json');
const ranks=[56,161,326,704,707,884,1235,1238,1250,1307,2798],rows=[];
const parse=s=>ts.createSourceFile('declaration.a',s,ts.ScriptTarget.Latest,true);
for(const rank of ranks){const m=e.members.find(x=>x.rank===rank),defs=new Map();
function visit(t){if(ts.isTypeReferenceNode(t)){const n=t.typeName.getText(),d=c[n];if(!d)throw Error('unknown '+n);if(!defs.has(n)){if(d.kind==='TypeAliasDeclaration'){const a=parse(d.text).statements[0];if(a.typeParameters?.length)throw Error('generic alias '+n);defs.set(n,d.text);visit(a.type);}else if(d.kind==='InterfaceDeclaration')defs.set(n,'interface '+n+' {readonly value:number;'+(d.kindValue===undefined?'':'readonly kind:'+d.kindValue+';')+'}');else throw Error('carrier '+n);}return;}ts.forEachChild(t,x=>{if(ts.isTypeNode(x))visit(x);});}
function concrete(t){if(ts.isParenthesizedTypeNode(t))return concrete(t.type);if(ts.isUnionTypeNode(t))return concrete(t.types.find(x=>x.kind!==ts.SyntaxKind.UndefinedKeyword));if(ts.isTypeReferenceNode(t)&&c[t.typeName.getText()]?.kind==='TypeAliasDeclaration')return concrete(parse(c[t.typeName.getText()].text).statements[0].type);return t.getText();}
function value(t){if(ts.isParenthesizedTypeNode(t))return value(t.type);if(ts.isUnionTypeNode(t))return value(t.types.find(x=>x.kind!==ts.SyntaxKind.UndefinedKeyword));if(ts.isTypeReferenceNode(t)){const d=c[t.typeName.getText()];return d.kind==='TypeAliasDeclaration'?value(parse(d.text).statements[0].type):'{value:1'+(d.kindValue===undefined?'':',kind:'+d.kindValue)+'}';}if(ts.isTypeLiteralNode(t))return '{'+t.members.map(x=>x.name.getText()+':1').join(',')+'}';if(t.kind===ts.SyntaxKind.NumberKeyword)return '3';throw Error('value '+t.getText());}
try{const element=parse('type Element='+m.type+';').statements[0].type.elementType;visit(element);const good=value(element),bad=rank===56?'[1]':'['+good.replace(/value:1/,'value:"bad"').replace(/nodePos:1/,'nodePos:"bad"')+']';const parts=m.read.split('.');parts.pop();let owner='(value as Target).items';for(let i=parts.length-1;i>0;i--)owner='{'+parts[i]+':'+owner+'}';const prefix='// Original Array member and receiver; adjacent payload carriers reduced.\n'+[...defs.values()].join('\n')+'\ninterface OriginalMember<T> {'+m.declarations[0].text+'}\ninterface Base {readonly items:unknown;}\ninterface Target {readonly items:'+m.type+';}\nfunction probe(value:Base):void {const '+parts[0]+'='+owner+';const incoming:'+concrete(element)+'='+good+';const witnessResult='+m.read+'(incoming);console.log(String(witnessResult));}\n';const dir=path.join(home,'families','rank-'+rank);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'good.a'),(prefix+'const seed:'+concrete(element)+'='+good+';probe({items:[seed]});\n').replace(/\r\n/g,'\n'));fs.writeFileSync(path.join(dir,'wrong-element.a'),(prefix+(rank===56?'const restricted:1[]=[1];probe({items:restricted});':'probe({items:'+bad+'});')+'\n').replace(/\r\n/g,'\n'));rows.push({rank,reads:m.reads,type:m.type,read:m.read,declaration:m.declarations[0].text,diagnostic:'UNPINNED'});}catch(err){console.log(rank+': '+err.message);}}
fs.writeFileSync(path.join(__dirname,'push-candidates.json'),JSON.stringify(rows,null,2)+'\n');console.log('Prepared '+rows.length+' push families.');
