import pathlib,json,difflib,subprocess
root=pathlib.Path('/workspace/adamic');out=root/'review/test-defend/stage1-cohere-markdownblocks-structure_layout_shards';base='stage1/cohere/markdownblocks/'
mutants=[dict(id='D1',file=base+'width.ts',old='code <= 0x36f',new='code <= 0x36e',menu='off-by-one bound',aim='UnicodeWidths enumerates U+036F; the common layout corpus contains U+0301 but not the upper combining bound.'),dict(id='D2',file=base+'structure.ts',old="arena.node(child.doc).kind !== 't'",new="arena.node(child.doc).kind === 't'",menu='flip condition',aim='Sentence whitespace boundaries, checked by structure-specific built-in witnesses, but also supplied to the table family by the same corpus.'),dict(id='D3',file=base+'structure.ts',old='while(stack.length > 0)',new='while(stack.length > 1)',menu='off-by-one bound',aim='Paragraph flattening tail, a structure-specific claimed behavior not separately targeted in the original audit.'),dict(id='D4',file=base+'tables.ts',old="const first = align === 'center' || align === 'left' ? ':' : '-';",new="const first = align === 'center' || align === 'right' ? ':' : '-';",menu='change constant',aim='Table delimiter alignment, targeted by table-specific assertions but shared through the identical common program/corpus.')]
for m in mutants:
 s=(root/m['file']).read_text();assert s.count(m['old'])==1;m['line']=s[:s.index(m['old'])].count('\n')+1
 (out/(m['id']+'.diff')).write_text(''.join(difflib.unified_diff(s.splitlines(True),s.replace(m['old'],m['new']).splitlines(True),fromfile='a/'+m['file'],tofile='b/'+m['file'])))
(out/'planned-mutants.json').write_text(json.dumps(mutants,indent=2));(out/'code-and-oracle.md').write_text('CODE UNDER TEST: Markdown TypeScript structure, table and Unicode-width ports, compiled by Adamic. ORACLE: live Go cohere output and the pinned Prettier fork run through Node; widths also compare installed emoji-regex 10.6.0, get-east-asian-width 1.6.0 and narrow-emojis 0.0.3. No oracle, harness or test mutation.\n\nFamilies both execute list_probe.ts on blockCorpus(whitespace), under source Node, JavaScript backend, sanitized native and release native. They differ in shard partition and built-in mutants. These are not distinct Node/native executor twins. Semantic comparison offers no exclusive ordinary input; D2-D4 try the separately named construction behavior and record whether common corpus checks also fail.\n\nD1 targets the boundary excluded from the common corpus but enumerated as an individual Unicode scalar by Widths. Go profiles include compiler packages; V8 profiles supplement coverage of port sources. Product cache effects are not intrinsic code exclusivity.\n')
ref='origin/test-audit/stage1-cohere-markdownblocks-structure_layout_shards';path='review/test-audit/stage1-cohere-markdownblocks-structure_layout_shards/'
for n in ['README.md','results.json','scope.json','code-inventory.txt','planning.md','planned-mutants.json','mutants.json']:
 r=subprocess.run(['git','show',ref+':'+path+n],capture_output=True)
 if r.returncode==0:(out/('audit-'+n)).write_bytes(r.stdout)
print(json.dumps(mutants,indent=2))
