import pathlib,json,re,csv,subprocess
root=pathlib.Path('/workspace/adamic');p=root/'review/test-defend/internal-lower-enum_flags';plan=json.loads((p/'defense-plan.json').read_text());prior=json.loads((p/'prior-audit.json').read_text());names=['TestFlagEnumsOpen','TestFlagEnumsDomain','TestEnumNeverDefault','TestFlagEnumLiteralSpellings','TestFlagEnumMemberAliases','TestEnumNameEnumeration','TestFlagEnumInlineIteration','TestFlagEnumAliasBoundaries','TestEnumInitializationGraphMemo','TestEnumNamespaceSharedCycle','TestStringEnumsStayClosed','TestNumericEnumLiteralPromises'];comparisons={x['test']:x for x in json.loads((p/'coverage-comparisons.json').read_text())};matrix={};details={}
for m in plan:
 ident=m['id'];es=[json.loads(s) for s in (p/(ident+'.log')).read_text().splitlines() if s.startswith('{')]
 assert any(e['Action'] in ['pass','fail'] and 'Test'not in e for e in es),ident
 failed=[e['Test'] for e in es if e['Action']=='fail' and 'Test'in e and '/'not in e['Test']];passed=[e['Test'] for e in es if e['Action']=='pass' and 'Test'in e and '/'not in e['Test']];skipped=[e['Test'] for e in es if e['Action']=='skip'];matrix[ident]={'failed':failed,'passed':passed,'skipped':skipped,'binary_seconds':next(e['Elapsed'] for e in reversed(es) if e['Action'] in ['pass','fail'] and 'Test'not in e)};details[ident]={n:''.join(e.get('Output','') for e in es if e.get('Test','').split('/')[0]==n) for n in failed}
(p/'matrix.json').write_text(json.dumps(matrix,indent=2))
listed=re.findall(r'^Test\w+',(p/'list.log').read_text(),re.M)
with (p/'matrix.csv').open('w') as f:
 w=csv.writer(f);w.writerow(['row',*[m['id'] for m in plan]])
 for n in listed:w.writerow([n,*['fail' if n in matrix[m['id']]['failed'] else 'pass' if n in matrix[m['id']]['passed'] else 'skip or unknown' for m in plan]])
notes={
'TestFlagEnumsOpen':('enumRefusal, enumAssignable, assignment, enumConstant and enumFields','Node source versus lowered JavaScript output for positive cases; self-written Refused type for member promises','Assignment coverage exclusive to literal-promises subsumer; flag-shaped compound shift update is a semantic distinction. The unused reason column still is not asserted.'),
'TestFlagEnumsDomain':('flagDomainSeen, assignment/combine, enumFields and container lowering','Node source versus lowered JavaScript output','Runtime bitwise/container effects are checked. The row does not assert the internal flagDomain classification; TestEnumFlagProofsWithoutObservableLoweringEffect does. Its domain name should not be taken as a direct proof-algorithm assertion.'),
'TestEnumNeverDefault':('enumDefaultUnreachable, enumNeverCheck and switch lowering','Node source versus lowered JavaScript output','Calls only declared Red/Green/Blue cases. It neither executes an out-of-enum default nor asserts an inserted never guard, despite the default-focused name.'),
'TestFlagEnumLiteralSpellings':('enumConstant and enumFields','Node source versus lowered JavaScript output','Shared enumConstant lines with subsumer, but hexadecimal direct initializers distinguish the input. Output values and reverse names now checked.'),
'TestFlagEnumMemberAliases':('enumConstant and enumFields','Node source versus lowered JavaScript output','Qualified same-enum aliases distinguish the input from foreign aliases and ordinary bitwise members. Alias values, reverse names and keys are checked.'),
'TestEnumNameEnumeration':('plainEnumerableObject and forIn; enumFields','Node source versus lowered JavaScript output','Enum for-in origin differs from subsumer for-of iteration. Enumerated names now observed.'),
'TestFlagEnumInlineIteration':('forOf, libraryArrayForOf, flagDomainSeen and contextual object lowering','Node source versus lowered JavaScript output','The inline loop observes 0 then 3 and a reverse name. It does not directly assert a flag-domain classification; its observable iteration promise is checked.'),
'TestFlagEnumAliasBoundaries':('enumAssignable, flagMemberWidened, castProof and forOf','Node agreement for positive alias/iterable cases; self-written Refused type for two negative cases','Positive boundary outputs now checked. Negative member-slot and Mutable<T> cases accept any Refused, so an unrelated refusal can satisfy them.'),
'TestEnumInitializationGraphMemo':('namespaceCallGraph.reach/discover cache and transitive propagation','Self-written reach count and exact body expansion counts','One exclusive block at namespaces_call_graph.go:135-136. Completed single-target cache queries differ on shared cache-hit lines. Counts genuinely assert work, not elapsed time.'),
'TestEnumNamespaceSharedCycle':('namespaceCallGraph.reach/discover Tarjan components and reach sharing','Self-written two declaration identities and exact expansion count','Exclusive active-edge handling at 42-46 and namespace read at 103-104. Two-node component differs from three-node namespace cycle.'),
'TestStringEnumsStayClosed':('castProof, enumAssignable and refuseWidening','Self-written Refused type and enum-members/no-unchecked-cast diagnostic alternatives','No exclusive block. Primitive-to-string-enum inputs distinguish shared cast proof. D6 proves the diagnostic assertion can fail, not that rejection can be bypassed.'),
'TestNumericEnumLiteralPromises':('enumAssignable, enumRefusal, enumStoredType and enumMemberOrigin','Self-written Refused type','The named promises are refused, but the row does not require an enum-literal diagnostic. An unrelated Refused can satisfy it. Coverage includes indexed stored-type and open-tag differences.'),
}
results=[]
for n in names:
 old=next(x for x in prior if x['test']==n);aimed=[m for m in plan if m['target']==n];unique=[m for m in plan if matrix[m['id']]['failed']==[n]];attempts=[]
 for m in aimed:attempts.append({'mutant':m['id'],'file_line':m['file']+':'+str(m['line']),'change':m['menu'],'rows_failed':matrix[m['id']]['failed']})
 cut,oracle,finding=notes[n];chosen=unique[0] if unique else None
 if chosen:
  ident=chosen['id'];fail=next(s.strip() for s in details[ident][n].splitlines() if '.go:'in s and not 'function body expansions'in s)
  # Log lines giving the substantive assertion are preferred over t.Log.
  command='ADAMIC_BUILD_CACHE_DIR=/tmp/enum-defend/cache/'+('D3-source-spelling' if ident=='D3' else ident)+' timeout 120 go test -json -count=1 -timeout 90s ./internal/lower/ -run . > '+ident+'.log 2>&1'
  evidence=command+'; '+fail
 else:evidence='go test -json -count=1 -timeout 90s -coverpkg=github.com/system-inc/adamic/internal/lower -coverprofile='+n+'.cover ./internal/lower/ -run ^'+n+'$; '+str(comparisons[n]['exclusive_blocks'])+' exclusive blocks versus '+comparisons[n]['compared_with']+'. No aimed mutant allocated within the seven final-mutant cap; no three-attempt negative verdict claimed.'
 result={'test':n,'package':'internal/lower','prior_verdict':old['verdict'],'subsumed_by':old['subsumed_by'],'defense':'defended' if chosen else 'cannot-judge','unique_mutant':chosen['id']+' '+chosen['file']+':'+str(chosen['line']) if chosen else None,'attempts':attempts,'evidence':evidence,'code_under_test':cut,'oracle':oracle,'coverage_exclusive_blocks':comparisons[n]['exclusive_blocks'],'finding':finding}
 if chosen:result['rows_passed_file']=chosen['id']+'-passed-rows.json';(p/result['rows_passed_file']).write_text(json.dumps(matrix[chosen['id']]['passed'],indent=2))
 results.append(result)
(p/'rows.json').write_text(json.dumps(results,indent=2))
changes=json.loads((p/'scope-changes.json').read_text());runs=json.loads((p/'matrix-runs.json').read_text());initial=json.loads((p/'initial.json').read_text());costs={'setup_seconds':0,'npm_seconds':initial['npm']['seconds'],'baseline_wall_seconds':initial['baseline']['seconds'],'baseline_binary_seconds':38.863,'coverage_wall_seconds':sum(x['seconds'] for x in json.loads((p/'coverage-runs.json').read_text()).values()),'final_matrix_wall_seconds':sum(runs[m['id']]['wall_seconds'] for m in plan),'inactive_spelling_attempt_seconds':runs['D3-inactive']['wall_seconds'],'note':'Wide cache attempt was interrupted and excluded. Every final matrix has its own build-cache directory; D3 corrected spelling uses D3-source-spelling.'};(p/'costs.json').write_text(json.dumps(costs,indent=2))
report='Seven rows defended by unique production catches; five remain cannot-judge under the seven final-mutant cap.\nBaseline passed; every requested row still exists; '+str(len(changes['new']))+' additional current top-level rows were included.\nSource and tests restored unchanged; evidence prepared for test-defend/internal-lower-enum_flags.\n\nStarting origin/main: '+subprocess.check_output(['git','rev-parse','HEAD'],cwd=root,text=True).strip()+'\n\n```json\n'+json.dumps(results,indent=2)+'\n```\n\n'
report+='The matrix ran the whole package for each final mutant. Each D*-passed-rows.json lists exactly the observed passing top-level rows. matrix.json lists failures and skips. No test, oracle, or preparation helper was mutated. The diagnostic mutant D6 alters a production repair string, not its expected test text. All final diffs apply against the starting commit and passed go vet ./internal/lower/.\n\n'
report+='Coverage: each requested row and its named subsumer ran independently with -coverpkg on internal/lower. The untrue string row was compared with a whole-package run excluding it. Profiles, per-row exclusive block positions and coverage-comparisons.json preserve the comparison. Source line spans in Go coverage blocks are leads, not proof of exclusive semantics.\n\n'
report+='Brief ambiguities and time costs:\n- The three-honest-attempt negative rule conflicts with a seven-mutant ceiling for twelve rows. Final matrices cost roughly fifty seconds, so seven meaningful final mutants were prioritized. Five unallocated rows remain cannot-judge; no deletion is justified by that result.\n- The prior audit was based on 8171b317, rather than the brief\'s older file reference. Main is now later and '+str(len(changes['new']))+' rows were added with none removed. Most positive enum assertions now run Node comparisons. The previous acceptance-only limitations are not current evidence.\n- Initial wide D1 cache disabling expanded diamond paths exponentially. It was interrupted; its partial log supports no verdict. Narrowed D1 disables only the first completed single-target cache entry and completes normally.\n- Initial D3 selected normalized AST numeric text, so hexadecimal spelling was invisible and the package passed. Corrected sourceExpression reads source spelling. The inactive diff/log are retained and excluded from final defenses.\n- D6 establishes unique diagnostic sensitivity. It leaves rejection enabled and does not prove a missing soundness barrier. The broad StringEnumsStayClosed name covers only the two cast cases actually asserted.\n- Default package runs skip TestOriginalCycleLedger, TestOptionalWideningCensus and one TestMixedUnionContractGraph subcase. Their opt-in scenarios remain unknown. Defended means unique among the observed full default-package run; those skips and repo-wide uniqueness are not established.\n\n'
report+='For every cannot-judge row, rows.json records its name/assertion limits. Domain and inline iteration observe runtime output, not classification internals; never-default does not execute the default; negative alias/literal rows check Refused type without requiring the particular promised reason. Graph performance names are backed by exact expansion counts, a valid work assertion.\n\nTiming: '+json.dumps(costs)+'. No other package tests ran. The broad aborted attempt and inactive selector consumed extra time but neither is used as a proven catch.\n'
(p/'report.md').write_text(report)
print([(x['test'],x['defense'],x['unique_mutant']) for x in results]);print(costs)
