// Generated by adamic from throw_keeps_old_value.a. Do not edit.

#include "adamic.h"

#include <math.h>
#include <stdbool.h>

static adamic_string adamic_string_0 = ADAMIC_STRING("");
static adamic_string adamic_string_1 = ADAMIC_STRING("failed");
static adamic_string adamic_string_2 = ADAMIC_STRING("zero");
static adamic_string adamic_string_3 = ADAMIC_STRING("local");
static adamic_string adamic_string_4 = ADAMIC_STRING("spread caught: ");
static adamic_string adamic_string_5 = ADAMIC_STRING(" ");
static adamic_string adamic_string_6 = ADAMIC_STRING("moved");
static adamic_string adamic_string_7 = ADAMIC_STRING("move caught: ");

static adamic_object * adamic_function_0_fail(bool adamic_local_0_when);
static adamic_object * adamic_function_0_fail_in(adamic_region *region, bool adamic_local_0_when);
static adamic_string * adamic_function_1_spreadThenAssign(void);
static adamic_object * adamic_function_2_consume(adamic_object * adamic_local_1_node);
static adamic_string * adamic_function_3_moveThenAssign(void);

static const char *const adamic_shape_0_names[] = {"value", "label"};
static const bool adamic_shape_0_references[] = {false, true};
static const adamic_shape adamic_shape_0 = {2, adamic_shape_0_names, adamic_shape_0_references, NULL};
static adamic_slot_cache adamic_cache_22;
static adamic_slot_cache adamic_cache_25;
static adamic_slot_cache adamic_cache_31;
static adamic_slot_cache adamic_cache_39;
static adamic_slot_cache adamic_cache_42;
static adamic_slot_cache adamic_cache_52;
static adamic_slot_cache adamic_cache_58;

static adamic_object * adamic_function_0_fail(bool adamic_local_0_when) {
	ADAMIC_CHECK_STACK();
	if (adamic_local_0_when) {
		{
			adamic_string * adamic_temporary_1 = adamic_string_from_number((0x1p+00));
			adamic_string * adamic_temporary_2 = adamic_string_concat(2, (adamic_string *const[]){&adamic_string_1, adamic_temporary_1});
			adamic_object * adamic_temporary_3 = adamic_error_new(adamic_temporary_2);
			adamic_thrown = adamic_retain(adamic_temporary_3);
			adamic_release(adamic_temporary_3);
			adamic_release(adamic_temporary_2);
			adamic_release(adamic_temporary_1);
			return NULL;
		}
	}
	adamic_string * adamic_temporary_4 = adamic_string_from_number((0x0p+00));
	adamic_string * adamic_temporary_5 = adamic_string_concat(2, (adamic_string *const[]){&adamic_string_2, adamic_temporary_4});
	adamic_object * adamic_temporary_6 = adamic_object_new(&adamic_shape_0);
	adamic_temporary_6->slots[0].number = (0x0p+00);
	adamic_temporary_6->slots[1].reference = adamic_temporary_5;
	adamic_object * adamic_temporary_7 = adamic_temporary_6;
	adamic_release(adamic_temporary_4);
	return adamic_temporary_7;
	adamic_unreachable();
}

static adamic_object * adamic_function_0_fail_in(adamic_region *region, bool adamic_local_0_when) {
	ADAMIC_CHECK_STACK();
	if (adamic_local_0_when) {
		{
			adamic_string * adamic_temporary_8 = adamic_string_from_number((0x1p+00));
			adamic_string * adamic_temporary_9 = adamic_string_concat(2, (adamic_string *const[]){&adamic_string_1, adamic_temporary_8});
			adamic_object * adamic_temporary_10 = adamic_error_new(adamic_temporary_9);
			adamic_thrown = adamic_retain(adamic_temporary_10);
			adamic_release(adamic_temporary_10);
			adamic_release(adamic_temporary_9);
			adamic_release(adamic_temporary_8);
			return NULL;
		}
	}
	adamic_string * adamic_temporary_11 = adamic_string_from_number((0x0p+00));
	adamic_string * adamic_temporary_12 = adamic_string_concat(2, (adamic_string *const[]){&adamic_string_2, adamic_temporary_11});
	adamic_object *adamic_temporary_13 = adamic_object_new_in(region, &adamic_shape_0);
	adamic_temporary_13->slots[0].number = (0x0p+00);
	adamic_temporary_13->slots[1].reference = adamic_temporary_12;
	adamic_object * adamic_temporary_14 = adamic_temporary_13;
	adamic_release(adamic_temporary_11);
	return adamic_temporary_14;
	adamic_unreachable();
}

static adamic_string * adamic_function_1_spreadThenAssign(void) {
	ADAMIC_CHECK_STACK();
	adamic_string * adamic_temporary_15 = adamic_string_from_number((0x1.4p+02));
	adamic_string * adamic_temporary_16 = adamic_string_concat(2, (adamic_string *const[]){&adamic_string_3, adamic_temporary_15});
	adamic_object * adamic_temporary_17 = adamic_object_new(&adamic_shape_0);
	adamic_temporary_17->slots[0].number = (0x1.4p+02);
	adamic_temporary_17->slots[1].reference = adamic_temporary_16;
	adamic_object * adamic_local_2_local = adamic_temporary_17;
	adamic_release(adamic_temporary_15);
	{
		bool adamic_temporary_19 = ((adamic_local_2_local->heap.references == 1 && !adamic_weak_held(adamic_local_2_local)) && !adamic_local_2_local->frozen);
		adamic_object * adamic_temporary_20 = (adamic_temporary_19 ? adamic_retain(adamic_local_2_local) : adamic_object_copy(adamic_local_2_local));
		adamic_value *adamic_temporary_21 = adamic_object_field(adamic_temporary_20, "value", &adamic_cache_22);
		adamic_temporary_21->number = (0x1.8p+02);
		adamic_temporary_20->class = NULL;
		adamic_temporary_20->tuple = false;
		adamic_object * adamic_local_3_other = adamic_temporary_20;
		adamic_object * adamic_temporary_23 = adamic_function_0_fail(true);
		if (adamic_thrown != NULL) {
			adamic_release(adamic_temporary_23);
			adamic_release(adamic_local_3_other);
			goto adamic_landing_18;
		}
		adamic_object * adamic_temporary_24 = adamic_local_2_local;
		adamic_local_2_local = adamic_temporary_23;
		adamic_release(adamic_temporary_24);
		double adamic_temporary_26 = adamic_object_data_field(adamic_local_3_other, "value", &adamic_cache_25)->number;
		adamic_string * adamic_temporary_27 = adamic_string_from_number(adamic_temporary_26);
		adamic_string * adamic_temporary_28 = adamic_string_concat(1, (adamic_string *const[]){adamic_temporary_27});
		adamic_string * adamic_temporary_29 = adamic_temporary_28;
		adamic_release(adamic_temporary_27);
		adamic_release(adamic_local_3_other);
		adamic_release(adamic_local_2_local);
		return adamic_temporary_29;
		adamic_release(adamic_local_3_other);
	}
	goto adamic_done_18;
	adamic_landing_18:;
	{
		adamic_object *adamic_temporary_30 = adamic_thrown;
		adamic_thrown = NULL;
		adamic_object * adamic_local_4_error = adamic_temporary_30;
		double adamic_temporary_32 = adamic_object_data_field(adamic_local_2_local, "value", &adamic_cache_31)->number;
		adamic_string * adamic_temporary_33 = adamic_string_from_number(adamic_temporary_32);
		adamic_string * adamic_temporary_34 = ((adamic_string *)(&adamic_local_2_local->slots[1])->reference);
		adamic_string * adamic_temporary_35 = adamic_string_concat(4, (adamic_string *const[]){&adamic_string_4, adamic_temporary_33, &adamic_string_5, adamic_temporary_34});
		adamic_string * adamic_temporary_36 = adamic_temporary_35;
		adamic_release(adamic_temporary_33);
		adamic_release(adamic_local_4_error);
		adamic_release(adamic_local_2_local);
		return adamic_temporary_36;
		adamic_release(adamic_local_4_error);
	}
	goto adamic_done_18;
	adamic_done_18:;
	adamic_unreachable();
}

static adamic_object * adamic_function_2_consume(adamic_object * adamic_local_1_node) {
	ADAMIC_CHECK_STACK();
	bool adamic_temporary_37 = ((adamic_local_1_node->heap.references == 1 && !adamic_weak_held(adamic_local_1_node)) && !adamic_local_1_node->frozen);
	adamic_object * adamic_temporary_38 = (adamic_temporary_37 ? adamic_retain(adamic_local_1_node) : adamic_object_copy(adamic_local_1_node));
	double adamic_temporary_40 = adamic_object_data_field(adamic_local_1_node, "value", &adamic_cache_39)->number;
	adamic_value *adamic_temporary_41 = adamic_object_field(adamic_temporary_38, "value", &adamic_cache_42);
	adamic_temporary_41->number = (adamic_temporary_40 + (0x1.9p+06));
	adamic_temporary_38->class = NULL;
	adamic_temporary_38->tuple = false;
	adamic_object * adamic_temporary_43 = adamic_temporary_38;
	adamic_release(adamic_local_1_node);
	return adamic_temporary_43;
	adamic_unreachable();
}

static adamic_string * adamic_function_3_moveThenAssign(void) {
	ADAMIC_CHECK_STACK();
	adamic_string * adamic_temporary_44 = adamic_string_from_number((0x1.cp+02));
	adamic_string * adamic_temporary_45 = adamic_string_concat(2, (adamic_string *const[]){&adamic_string_6, adamic_temporary_44});
	adamic_object * adamic_temporary_46 = adamic_object_new(&adamic_shape_0);
	adamic_temporary_46->slots[0].number = (0x1.cp+02);
	adamic_temporary_46->slots[1].reference = adamic_temporary_45;
	adamic_object * adamic_local_5_local = adamic_temporary_46;
	adamic_release(adamic_temporary_44);
	{
		adamic_object * adamic_temporary_48 = adamic_local_5_local;
		adamic_local_5_local = NULL;
		adamic_object * adamic_temporary_49 = adamic_function_2_consume(adamic_temporary_48);
		adamic_object * adamic_local_6_other = adamic_temporary_49;
		adamic_object * adamic_temporary_50 = adamic_function_0_fail(true);
		if (adamic_thrown != NULL) {
			adamic_release(adamic_temporary_50);
			adamic_release(adamic_local_6_other);
			goto adamic_landing_47;
		}
		adamic_object * adamic_temporary_51 = adamic_local_5_local;
		adamic_local_5_local = adamic_temporary_50;
		adamic_release(adamic_temporary_51);
		double adamic_temporary_53 = adamic_object_data_field(adamic_local_6_other, "value", &adamic_cache_52)->number;
		adamic_string * adamic_temporary_54 = adamic_string_from_number(adamic_temporary_53);
		adamic_string * adamic_temporary_55 = adamic_string_concat(1, (adamic_string *const[]){adamic_temporary_54});
		adamic_string * adamic_temporary_56 = adamic_temporary_55;
		adamic_release(adamic_temporary_54);
		adamic_release(adamic_local_6_other);
		adamic_release(adamic_local_5_local);
		return adamic_temporary_56;
		adamic_release(adamic_local_6_other);
	}
	goto adamic_done_47;
	adamic_landing_47:;
	{
		adamic_object *adamic_temporary_57 = adamic_thrown;
		adamic_thrown = NULL;
		adamic_object * adamic_local_7_error = adamic_temporary_57;
		double adamic_temporary_59 = adamic_object_data_field(adamic_local_5_local, "value", &adamic_cache_58)->number;
		adamic_string * adamic_temporary_60 = adamic_string_from_number(adamic_temporary_59);
		adamic_string * adamic_temporary_61 = ((adamic_string *)(&adamic_local_5_local->slots[1])->reference);
		adamic_string * adamic_temporary_62 = adamic_string_concat(4, (adamic_string *const[]){&adamic_string_7, adamic_temporary_60, &adamic_string_5, adamic_temporary_61});
		adamic_string * adamic_temporary_63 = adamic_temporary_62;
		adamic_release(adamic_temporary_60);
		adamic_release(adamic_local_7_error);
		adamic_release(adamic_local_5_local);
		return adamic_temporary_63;
		adamic_release(adamic_local_7_error);
	}
	goto adamic_done_47;
	adamic_done_47:;
	adamic_unreachable();
}

int main(int argc, char **argv) {
	adamic_start(argc, argv);
	adamic_string * adamic_temporary_64 = adamic_function_1_spreadThenAssign();
	adamic_write_line(adamic_stdout, adamic_temporary_64);
	adamic_release(adamic_temporary_64);
	adamic_string * adamic_temporary_65 = adamic_function_3_moveThenAssign();
	adamic_write_line(adamic_stdout, adamic_temporary_65);
	adamic_release(adamic_temporary_65);
	return 0;
}
