import pathlib,json,statistics
p=pathlib.Path('/workspace/adamic/review/test-audit/stage1-cohere-values');run=json.loads((p/'runs.json').read_text()); by={r['name']:r for r in run};plan=json.loads((p/'plan.json').read_text());names=['TestThePortParsesAsGoCohereDoes','TestEachGapStandsWhereGapsMdSaysItDoes']
def events(name):
 a=[]
 for l in (p/(name+'.log')).read_text().splitlines():
  try:a.append(json.loads(l))
  except:pass
 return a
def failed(name):return sorted({e['Test'].split('/')[0] for e in events(name) if e.get('Action')=='fail' and e.get('Test')})
def evidence(id,row):
 for e in events(id):
  o=e.get('Output','').strip()
  if e.get('Test','').startswith(row+'/') and (('and Go cohere differ:' in o and 'native and' in o) or 'natively: exit' in o or 'this gap lowers now' in o):return o
 return next((e.get('Output','').strip() for e in events(id) if e.get('Test','').startswith(row) and '.go:' in e.get('Output','')),'No observed assertion')
matrix={m['id']:failed(m['id']) for m in plan['mutants']};rows=[]
for name in names:
 kills=[m for m,f in matrix.items() if name in f];unique=[m for m in kills if len(matrix[m])==1]; probe='P1' if name==names[0] else 'P2'; last=kills[-1] if kills else None
 rows.append(dict(test=name,package='stage1/cohere/values',file='stage1/cohere/values/'+('values_test.go' if name==names[0] else 'gaps_test.go'),seconds=statistics.median(by[name+'-'+str(i)]['elapsed'] for i in range(1,4)),oracle='Go cohere and postcss-values-parser 2.0.1 run on Node; full serialized trees and refusal text, plus sanitizer/leak success' if name==names[0] else 'Node executes all five fixtures and validates handwritten stdout; native output matches that stdout; one exact NotYet.What label is self-written',oracle_kind='external-run' if name==names[0] else ['external-run','self'],kills=kills,unique_kills=unique,last_proven_fail=(last+': '+evidence(last,name)) if last else None,verdict='sacred' if unique else 'cannot-judge',subsumed_by=[],mutants_in_matrix=4,probe_kills=[probe] if name in failed(probe) else [],subsumer_seconds=None,vacuous=name not in failed(probe),bounded=False,matrix_rows=[],evidence='ADAMIC_VALUES_LIBRARY=/tmp/u148-library ADAMIC_BUILD_CACHE_DIR=/tmp/u148/cache/replay-'+last+' '+by[last]['command']+' > '+last+'.log 2>&1; '+evidence(last,name) if last else None))
(p/'rows.json').write_text(json.dumps(rows,indent=2));(p/'matrix.json').write_text(json.dumps(matrix,indent=2))
(p/'probe-matrix.json').write_text(json.dumps({'P1':failed('P1'),'P2':failed('P2'),'W1':failed('W1')},indent=2))
timings=dict(nproc=int((p/'nproc.txt').read_text()),setup='warm env, cloud/setup.sh skipped',npm=json.loads((p/'npm-timing.json').read_text()),builds={r['name']:r['wall'] for r in run if r['name'].endswith('-build')},run_wall=sum(r['wall'] for r in run if r['elapsed'] is not None),all_recorded_wall=sum(r['wall'] for r in run))
(p/'timings.json').write_text(json.dumps(timings,indent=2))
text='Unit u148 at '+plan['base']+'.\nTwo listed top-level rows, no moved or missing tests.\nFour frozen production mutants; '+str(sum(not f for f in matrix.values()))+' survivors.\nTwo empty-answer probes and one weakened-comparison witness.\nEvidence branch test-audit/stage1-cohere-values; source restored.\n\n```json\n'+json.dumps(rows,indent=2)+'\n```\n\n'
text+='| ID | origin/main location | Change | Failed rows |\n|---|---|---|---|\n'
for m in plan['mutants']:text+='| '+m['id']+' | '+m['file']+':'+str(m['line'])+' | `'+m['change']+'` | '+', '.join(matrix[m['id']])+' |\n'
text+='\nSurvivors: '+('none' if all(matrix.values()) else 'see matrix.json')+'.\n\n'
text+='Code and oracle were named before mutants; plan.json freezes the code-derived menu. functions-static.txt inventories declarations, port-reached.json records actual V8 reach, coverage-functions.log records measured compiler/native function coverage from the gap row. Static declarations are not claimed as proof of reach. Count-only driver functions are outside the tested entry mode.\n\n'
text+='Witness: W1 replaces firstDifference with an empty answer. It is a harness-only exception, excluded from production kills. The port row combines positive agreement and 18 built-in mutation witness subcases; W1.log gives exact outcomes. No separate top-level witness verdict is assigned to that mixed row.\n\n'
text+='Probes: P1 returns an empty parsed tree via new Parser(loose, []).parse(), the valid empty-input answer. P2 makes Lower return an empty ir.Program and removes the now-unused imports. Only P1 judges port vacuity and P2 judges gap vacuity. P2 effects on preparation for the port do not count as port probe kills. Neither probe supports sacred.\n\n'
text+='Brief problems and time costs:\n\n- P1 returns an empty tree, yet all 18 built-in witness subcases pass because empty answers already disagree with Go cohere. The positive subcase fails, so the whole row is not vacuous. W1 separately demonstrates the weakened comparison is detected.\n- Stage1 rebuild exception caps mutants at four, overriding the approximate three per row target; three port changes plus one compiler change were tested. Each TS diff has an actual sanitized native build; M4 passes go vet and its generated native products compile during the matrix.\n- The unit checks two different products: a port and the compiler. Mutating only the port cannot assess the gap row. M4 targets native stringCall instead of changing fixtures or oracle code.\n- The port top-level row combines a positive agreement check and mutation witnesses. A single verdict cannot describe both roles; its sacred verdict rests only on production answer differences, while W1 separately demonstrates the witness check.\n- Valid typed empty values need representation rather than nil pointers. P1 is an empty tree and P2 is an empty IR program; neither is a production mutant.\n- Audit execution error: /usr/bin/time does not exist. The first wrapped npm ci did not run. npm ci was corrected using Python timing and passed. The restored clean package baseline then passed; qualifying timings and production matrices were repeated after it. Initial logs are retained separately and do not decide verdicts.\n- One read tool call lost its exec-server transport and was retried. No code or test result was obtained from that failed call.\n- Full serialized outputs provide stronger evidence than exit codes; the gap refusal subcase additionally requires a specific error type and exact self-written label. It does not derive that label from Node.\n- The gap fixture comments still describe closed features as refused; GAPS.md and the actual gap table mark their current status. Scope came from go test -list, not those comments.\n\n'
text+='Timing: '+json.dumps(timings)+'. Raw runs.json records every measured command; test binary seconds, rather than command wall time, decide row medians. Initial baseline binary seconds were 31.355.\n\n'
text+='Not covered: other packages and repo-wide uniqueness, real CSS corpora, other random seeds, count-only driver mode, key insertion order, non-UTF-8 inputs and lone surrogates, alternate operating systems, every compiler path. Four mutations are bounded evidence, not a proof that every possible break is caught. Standalone diffs apply to the pinned starting commit; replay validation logs are preserved. No product source changes remain.\n'
(p/'REPORT.md').write_text(text)
print(json.dumps(rows,indent=2));print(json.dumps(timings,indent=2));print(matrix)
