// Package worker generates a runnable Cloudflare Worker from a checked Adamic handler.
package worker

import (
	"context"
	_ "embed"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/microsoft/TypeScript/tsc/shim/ast"
	"github.com/microsoft/TypeScript/tsc/shim/checker"
	"github.com/system-inc/adamic/internal/javascript"
	"github.com/system-inc/adamic/internal/load"
	"github.com/system-inc/adamic/internal/lower"
)

//go:embed utf8.mjs
var utf8Runtime string

//go:embed json_decode.mjs
var jsonDecodeRuntime string

//go:embed json_encode.mjs
var jsonEncodeRuntime string

//go:embed runtime.mjs
var workerRuntime string

// CheckSignature requires the prelude's actual types, not structurally compatible lookalikes.
// The bridge is generated only after this check, before any output directory is touched.
func CheckSignature(ctx context.Context, program *load.Program) error {
	entry := program.Files()[0]
	types, release := program.Checker(ctx, entry)
	defer release()
	var exported *ast.Symbol
	for _, symbol := range types.GetExportsOfModule(entry.AsNode().Symbol()) {
		if symbol.Name == "handle" && types.GetTypeOnlyAliasDeclaration(symbol) == nil {
			exported = symbol
			break
		}
	}
	found := "no exported handle"
	refuse := func() error {
		return fmt.Errorf("%s: refused: worker handle must be (request: HttpRequest) => HttpResponse from 'adamic/http'; found %s\n  fix: import type { HttpRequest, HttpResponse } from 'adamic/http'; export function handle(request: HttpRequest): HttpResponse { ... }", program.FileName(entry), found)
	}
	if exported == nil {
		return refuse()
	}
	target := exported
	if target.Flags&ast.SymbolFlagsAlias != 0 {
		target = types.GetAliasedSymbol(target)
	}
	functionType := types.GetTypeOfSymbolAtLocation(target, entry.AsNode())
	found = "handle: " + types.TypeToString(functionType)
	signatures := types.GetSignaturesOfType(functionType, checker.SignatureKindCall)
	if len(signatures) != 1 || len(target.Declarations) != 1 {
		return refuse()
	}
	declaration := target.Declarations[0]
	if declaration.Kind != ast.KindFunctionDeclaration || len(declaration.TypeParameters()) != 0 || len(declaration.Parameters()) != 1 {
		return refuse()
	}
	parameter := declaration.Parameters()[0].AsParameterDeclaration()
	if parameter.QuestionToken != nil || parameter.DotDotDotToken != nil || parameter.Initializer != nil {
		return refuse()
	}
	runtime := types.TryFindAmbientModule("adamic/http")
	if runtime == nil {
		return fmt.Errorf("worker: missing adamic/http prelude module")
	}
	var requestType, responseType *checker.Type
	for _, symbol := range types.GetExportsOfModule(runtime) {
		switch symbol.Name {
		case "HttpRequest":
			requestType = types.GetDeclaredTypeOfSymbol(symbol)
		case "HttpResponse":
			responseType = types.GetDeclaredTypeOfSymbol(symbol)
		}
	}
	if requestType == nil || responseType == nil {
		return fmt.Errorf("worker: missing HttpRequest or HttpResponse in the adamic prelude")
	}
	signature := signatures[0]
	if len(signature.Parameters()) != 1 || types.GetTypeOfSymbolAtLocation(signature.Parameters()[0], declaration) != requestType || types.GetReturnTypeOfSignature(signature) != responseType {
		return refuse()
	}
	return nil
}

// Bridge imports a handler module; both the compiled handler and stripped source use this code.
// Its fixed request and response layout follows the signature validated by CheckSignature.
func Bridge(handlerImport string) string {
	return `// Generated by adamic worker. Do not edit.
import { handle } from ` + strconv.Quote(handlerImport) + `;
import { AdamicPanic } from './adamic.mjs';

export default {
	async fetch(request, env, context) {
		const url = new URL(request.url);
		const input = {
			method: request.method,
			url: request.url,
			path: url.pathname,
			query: Array.from(url.searchParams, ([name, value]) => ({ name, value })),
			headers: Array.from(request.headers, ([name, value]) => ({ name, value })),
			body: await request.text(),
		};
		let output;
		try {
			output = handle(input);
		} catch (error) {
			if (!(error instanceof AdamicPanic)) throw error;
			console.error(error.message);
			return new Response('internal error', { status: 500 });
		}
		const headers = new Headers();
		for (const field of output.headers) headers.append(field.name, field.value);
		return new Response(output.body, { status: output.status, headers });
	},
};
`
}

// Build checks and lowers before writing anything, including on a signature refusal.
func Build(entry, output string) error {
	return BuildWith(entry, output, Options{})
}

func BuildWith(entry, output string, options Options) error {
	program, err := load.Load([]string{entry})
	if err != nil {
		return err
	}
	if err := CheckSignature(context.Background(), program); err != nil {
		return err
	}
	types, release := program.Checker(context.Background(), program.Files()[0])
	for _, exported := range types.GetExportsOfModule(program.Files()[0].AsNode().Symbol()) {
		if types.GetTypeOnlyAliasDeclaration(exported) != nil {
			continue
		}
		target := exported
		if target.Flags&ast.SymbolFlagsAlias != 0 {
			target = types.GetAliasedSymbol(target)
		}
		for _, declaration := range target.Declarations {
			if declaration.Kind == ast.KindFunctionDeclaration && len(declaration.TypeParameters()) != 0 {
				release()
				return fmt.Errorf("worker: exported generic function %s is not yet supported; fix: export a concrete function", exported.Name)
			}
		}
	}
	release()
	lowered, err := lower.Lower(context.Background(), program)
	if err != nil {
		return err
	}
	hasHandle := false
	for _, exported := range lowered.Exports {
		if exported.Name == "handle" {
			hasHandle = true
		}
	}
	if !hasHandle {
		return fmt.Errorf("worker: checked handle was lost during lowering")
	}
	backend := javascript.Options{ModuleExports: true, RuntimeImport: "./adamic.mjs"}
	var wasm []workerFile
	var imports string
	bridge := Bridge("./handler.mjs")
	if len(options.Wasm) != 0 {
		backend.ExternalFunctions, imports, wasm, err = wasmFiles(entry, program, lowered, options)
		if err != nil {
			return err
		}
		bridge = wasmBridge("./handler.mjs")
	}
	handler := imports + javascript.JavaScriptWith(lowered, backend)
	name := strings.TrimSuffix(filepath.Base(entry), filepath.Ext(entry))
	configuration := fmt.Sprintf("name = %s\nmain = \"worker.mjs\"\ncompatibility_date = \"2026-10-07\"\n", strconv.Quote(name))
	if len(options.Wasm) != 0 {
		configuration += "\n[[rules]]\ntype = \"CompiledWasm\"\nglobs = [\"**/*.wasm\"]\nfallthrough = false\n"
	}
	runtime := strings.Replace(workerRuntime, "/* UTF8_RUNTIME */", strings.Replace(utf8Runtime, "export function createUtf8", "function createUtf8", 1), 1)
	const decoderStub = "// The JavaScript backend imports decodeJson. Its Workers implementation is a separate unit, so until it\n// lands a call panics, loudly, rather than decoding with code the oracle also runs.\nexport function decodeJson() { panic('decodeJson: not yet available on Workers'); }"
	if strings.Count(runtime, decoderStub) != 1 {
		return fmt.Errorf("worker: decodeJson runtime assembly marker missing")
	}
	runtime = strings.Replace(runtime, decoderStub, jsonDecodeRuntime, 1)
	const encoderStub = "// Keep the backend's encoder import linkable until the Workers JSON runtime unit lands.\nexport function encodeJson() { panic('encodeJson: not yet available on Workers'); }"
	if strings.Count(runtime, encoderStub) != 1 {
		return fmt.Errorf("worker: encodeJson runtime assembly marker missing")
	}
	runtime = strings.Replace(runtime, encoderStub, jsonEncodeRuntime, 1)
	files := []workerFile{
		{"handler.mjs", handler},
		{"adamic.mjs", runtime},
		{"worker.mjs", bridge},
		{"wrangler.toml", configuration},
	}
	files = append(files, wasm...)
	if err := os.MkdirAll(output, 0755); err != nil {
		return err
	}
	for _, file := range files {
		if err := os.WriteFile(filepath.Join(output, file.name), []byte(file.text), 0644); err != nil {
			return err
		}
	}
	return nil
}
