#!/usr/bin/env python3
"""Generate directly selectable tests for the original program globs."""
import glob
import hashlib
import json
import os
from pathlib import Path
import re

root = Path(__file__).resolve().parents[2]
patterns = ['dedication/dedication.a', 'internal/load/testdata/0.1/compile/*.ts',
            'internal/load/testdata/0.1/compile/07_modules/main.ts', 'internal/oracle/testdata/*.a',
            'internal/oracle/testdata/modules/main.a', 'internal/flow/testdata/*.a']
excluded = {'killed_after_output.a', 'size_class_churn.a', 'bitwise_sweep.a',
            'typed_arrays_primes_large.a', 'normalize_coverage_long.a'}
families = [('SingleAssignment', 'checkSingleAssignmentProgram'), ('MutationRanges', 'checkMutationRangesProgram'), ('GraphPaths', 'checkGraphPathsProgram'), ('Liveness', 'checkLivenessProgram')]
manifest = []
for package in ['flow', 'fresh']:
    paths = []
    for pattern in patterns:
        for path in sorted(glob.glob(str(root / pattern))):
            source = Path(path)
            if package == 'flow' and source.name in excluded:
                continue
            relative = Path(os.path.relpath(source, root / 'internal' / package)).as_posix()
            paths.append(relative)
    assert len(paths) == len(set(paths))
    kinds = families if package == 'flow' else [('Writes', 'checkFreshProgram')]
    rows = []
    for kind, helper in kinds:
        group = []
        for relative in paths:
            label = re.sub('[^A-Za-z0-9]', '_', relative)
            digest = hashlib.sha256(relative.encode()).hexdigest()[:12]
            name = 'Test' + package.title() + kind + '_' + label + '_' + digest
            if package == 'flow' and relative != '../oracle/testdata/timsort.a':
                name = 'TestFlowProgram_' + label + '_' + digest
            group.append((relative, name, helper))
            source = (root / 'internal' / package / relative).resolve()
            manifest.append({'package':package,'family':kind,'test':name,'program':str(source.relative_to(root)),
                             'path':relative,'sha256':hashlib.sha256(source.read_bytes()).hexdigest()})
        rows.append(group)
    text = '// Code generated by review/test-split-flow/generate.py; DO NOT EDIT.\n'
    text += 'package ' + ('flow' if package == 'flow' else 'fresh_test') + '\n\nimport "testing"\n\n'
    text += 'var ' + package + 'CorpusPaths = []string{\n'
    text += ''.join('\t' + json.dumps(path) + ',\n' for path in paths) + '}\n\n'
    text += 'var ' + package + 'CorpusTests = [][]func(*testing.T){\n'
    for group in rows:
        text += '\t{\n' + ''.join('\t\t' + name + ',\n' for _,name,_ in group) + '\t},\n'
    text += '}\n\n'
    for group in rows:
        for index, (relative,name,helper) in enumerate(group):
            if package == "flow" and relative != "../oracle/testdata/timsort.a":
                name = "TestFlowProgram_" + re.sub("[^A-Za-z0-9]", "_", relative) + "_" + hashlib.sha256(relative.encode()).hexdigest()[:12]
                if group != rows[0]:
                    continue
                helper = "checkAllFlowProgram"
            text += 'func ' + name + '(t *testing.T) {\n\tt.Parallel()\n\tbegin' + package.title() + 'Unit(t)\n\t' + helper + '(t, ' + package + 'CorpusPaths[' + str(index) + '])\n}\n\n'
    (root / 'internal' / package / 'corpus_units_test.go').write_text(text)
(root/'review/test-split-flow/units.json').write_text(json.dumps(manifest,indent=2)+'\n')
print('Generated', len(manifest), 'program units')
