//go:build ignore

// Generate the JavaScript literal from the same Go table used by fmt's %q.
// Run from this directory with: go run generate_printable.go > printable.a
package main

import (
	"fmt"
	"strconv"
	"unicode"
)

func main() {
	fmt.Printf("// Generated by generate_printable.go using Go Unicode %s; do not edit.\n", unicode.Version)
	fmt.Print("export const printable = /^[")
	for point := rune(0); point <= unicode.MaxRune; point++ {
		if !strconv.IsPrint(point) {
			continue
		}
		first := point
		for point < unicode.MaxRune && strconv.IsPrint(point+1) {
			point++
		}
		fmt.Printf(`\u{%x}`, first)
		if point != first {
			fmt.Printf(`-\u{%x}`, point)
		}
	}
	fmt.Println("]$/u;")
}
