import pathlib,json,re,collections,datetime
p=pathlib.Path(__file__).parent; results=json.loads((p/'results.json').read_text());matrix=json.loads((p/'matrix.json').read_text());menu=json.loads((p/'menu.json').read_text());timings=json.loads((p/'timings.json').read_text());follow=json.loads((p/'followup-timings.json').read_text());families=json.loads((p/'families.json').read_text())
changes={'M01':'Negate checker identity comparison','M02':'Drop type representative registration statement','M03':'Drop whole class-key argument loop','M04':'Negate receiver-overrides condition','M05':'Flip fresh literal condition','M06':'Flip private-identifier exclusion','M07':'Union member bound !=2 to <2','M08':'Index-signature condition !=0 to <0','M09':'Call-signature condition !=0 to <0','M10':'SUPPLEMENTAL: remove guard terms before GetTypeArguments','M11':'Drop readiness pass call','M12':'Flip variable exclamation-token condition','M13':'Drop property readiness-origin assignment','M14':'Flip property-declaration permission in useOfThis','M15':'Negate array-type condition','M16':'Drop implied empty-literal target context append','M17':'Negate enumeration binding-written condition','M18':'Written detection true to false','M19':'Return negated record-written flag','M20':'Change indexed-write diagnostic reason constant'}
table='| ID | Origin/main file:line | Change | Observed failed rows | Unknown rows |\n|---|---|---|---|---|\n'
for m in menu:
 mid=m['id']
 if mid not in matrix:continue
 states=matrix[mid];table+=f"| [{mid}]({mid}.diff) | {m['file']}:{m['line']} | {changes[mid]} | "+', '.join(r for r,s in states.items() if s=='fail')+f" | {sum(s=='unknown' for s in states.values())} |\n"
(p/'mutants.md').write_text(table)
counts=collections.Counter(r['verdict'] for r in results)
summary='''u030: all 14 assigned names exist in their original files; none moved or vanished.
Base: origin/main 8171b3173bdbfce1f7982d3c4f731279307ece37.
Clean enabled baseline: PASS, 32.623 test-binary seconds; nproc=5.
Verdicts: 7 sacred, 5 subsumed, 1 overlapping, 1 cannot-judge; five vacuous rows.
Evidence: test-audit/internal-lower-class_instance_key, review/test-audit/internal-lower-class_instance_key/.
'''
friction='''Brief interpretation, mistakes, and costs:
- The reference commit 8de93800f4 was older than fetched origin/main. All 14 names were checked against the actual starting test list and remained in their named files.
- env.sh worked, but listing the lower package required a cold build, approximately 47.18 seconds. No cloud/setup.sh was run.
- The default package baseline skips two unrelated inventories. Both were enabled by fetching pristine TypeScript v6.0.3, verifying the pin, and generating diagnostics with upstream's script. Source cloning took about 9.27 seconds. Tests load no extra Node dependency directory for this setup; the generator uses Node builtins.
- The enabled baseline still skips TestMixedUnionContractGraph/interface_Node_{readonly_ready:boolean}_type_Target=Node|readonly_Node[];, whose body explicitly awaits compiler/views-v3. No installable tool enables that implementation gap.
- There are 239 top-level test functions and 237 package rows after grouping the three assertOverrideParameterRefusal wrappers. Their bodies call one identical checker with different fixture inputs. Families and members are in families.json. The 14 assigned functions retain separate rows because they have distinct test bodies/assertions rather than input-only checker wrappers. Shared lowerSource prepares and invokes lowering; using that helper alone does not establish an input-only wrapper family.
- The unconditional entry return probes failed go vet as unreachable code. Tautological pointer guards preserve an unconditional empty answer while passing vet. The initial failure is saved in probe-first-vet.log. This added one failed validation and a resume.
- M10 removes condition terms, which does not literally match the supplied menu. It is supplemental and excluded from kills, unique kills, subsumption, and worthy verdicts. The branded row can fail on M10, but the admissible menu did not meaningfully attack its guard, so its verdict is cannot-judge. The matrix preserves the supplemental column and matrix-kinds.json labels it. There are 19 admissible production mutants, one supplemental mutation, and two probes, not 22 production mutants.
- Actual Go binary panics happened for M05, M10, and M12. All 14 assigned rows were rerun alone for each. Outside unfinished rows remain unknown: M05 87, M10 153, M12 33 grouped rows. A failed child establishes row failure even when a panic prevents the parent completion event.
- The original detector incorrectly treated quoted native stderr containing panic: as a Go test binary panic on M11. That run completed normally with every row resolved; 14 unnecessary reruns cost about 25 seconds. The saved runner's detector is corrected to match an actual panic output line. M11 is not an aborted matrix.
- bounded=true indicates an assigned row's results include an aborted package run or the supplemental aborted guard run. matrix_rows lists the isolated replay set of all 14 assigned rows. Completed outside-row failures from the original run are retained in the full matrix and disqualify uniqueness; unknowns are never treated as passes. The seven sacred rows each have an admissible unique kill from a completed whole-package run.
- Direct negative signature proofs correctly decline their inputs even with no implementation. Their own P2 entry probe passes, so both are vacuous under the prescribed definition. Acceptance-only Lower rows also pass P1. These are findings independent of their verdicts.
- Shapes admits its positive nested-readonly-fields subcase on P1 and fails its negative subcases. The iterator row fails its first negative case on P1 before its positive controls execute; no claim is made that those unexecuted controls passed.
- Whole-package tests include TestUndecidedCycleReadsUseReadyChecks, which emits C, builds sanitized native products, and runs Node. Every mutant received its own ADAMIC_BUILD_CACHE_DIR. Assigned rows themselves do not build native products. Individual native rebuild durations were not instrumented; package binary times bound their cost. The brief's four-mutant fallback for native rebuilds and twenty-mutant Go switch menu are ambiguous for these incidental whole-package builds: this run used twenty switched Go changes and reports that limit rather than claiming four native rebuilds.
- Reciprocal subsumption names the other assigned row for PrivateRepair and SoundNeighbors, each resting on M14 alone. KeysRepair rests on two admissible kills; UsesReadiness on two; GenericReturn on one. These are finite-matrix hints, not deletion recommendations. Outside subsumers were timed three times after restoration. No claim is made that the chosen subsumer is globally fastest among every candidate.
- The audit took approximately 34 minutes, beyond the requested approximate 20-minute target. All individual test binaries fit their 90-second budget; no cooked run required coverage narrowing. Whole-package repetitions and panic reruns account for most of the cost.
'''
def cost(prefix,condition):return round(sum(v['wall'] for k,v in timings.items() if condition(k)),3)
costs=f'''Setup/build/run costs:
Warm tool verification: under one second, Go 1.27.1, nproc=5. npm ci reported 326 ms. Initial list/build wall about 47.18 s. Default baseline 30.261 s and enabled baseline 32.623 s in the test binary; Node diagnostics generation under one second. Reach coverage command 8.746 s wall, listing 422 reached functions.
All 42 assigned isolated timing commands: {cost('',lambda k:k.startswith('Test'))} s wall. Median binary samples are in results.json and raw logs. Production/probe vet commands: {cost('',lambda k:'-vet' in k)} s wall, plus the initial rejected P1 validation (0.491 s). The switched Go binary built once in {timings['switch-build']['wall']} s.
Twenty matrix commands (including supplemental M10): {cost('',lambda k:k.startswith('M') and '-' not in k)} s wall. Isolated mutation reruns: {cost('',lambda k:k.startswith('M') and '-Test' in k)} s wall, including the unnecessary M11 reruns. Fourteen entry-probe commands: {cost('',lambda k:k.startswith('P') and '-Test' in k)} s wall. Survivor witnesses and outside-subsumer timings: {round(sum(v['wall'] for v in follow.values()),3)} s wall. Detailed timings preserve every command and exit.
No other Go packages were tested, no repo-wide uniqueness was claimed, no PR was opened, and main was not pushed. The whole-package native cycle tests ran, but their individual rebuild times were not separately measured. Supplemental observation tests are not mutation kills and were removed. All production sources and submodule state are restored. Every standalone diff applies to the starting base and passed go vet ./internal/lower/; selector scaffolding is saved separately as selector.txt.
'''
survivors='''Survivors:
- M06: privateStaticMember(#secret) changes present=true to false; public field changes present=false to true. Actual function-output witness in survivor-original.log and survivor-M06.log. Unguarded member classification; downstream runtime consequences were not evaluated.
- M13: IR property n readiness changes from "new Box().n" to "n". Actual Lower-output witness in survivor-original.log and survivor-M13.log. Unguarded diagnostic-origin metadata change; checked-read counts remain unchanged.
Both witnesses used `timeout 120 go test -v -count=1 -timeout 90s ./internal/lower/ -run ^TestAuditU030SurvivorWitness$` before and after applying the standalone diff. No equivalent candidate among the observed survivors.
'''
probes='''P1 at lower.go:20 returns nil,nil at Lower entry. P2 at clock_generic_returns_t_01.go:14 returns 0,false at the direct signature-proof entry. Their standalone diffs use tautological pointer guards solely to avoid vet's unreachable-code rejection. Results are recorded per assigned entry, not across unrelated entries. Probe failures are excluded from production kills.
'''
report=summary+'\n```json\n'+json.dumps(results,indent=2)+'\n```\n\n'+table+'\n'+probes+'\n'+survivors+'\n'+friction+'\n'+costs
(p/'REPORT.md').write_text(report)
print(summary);print(counts)
