import json,pathlib,subprocess,datetime
p=pathlib.Path('/workspace/adamic/review/test-defend/stage1-typescript-parser-jsx_rejection');r=json.loads((p/'results.json').read_text());runs=json.loads((p/'runs.json').read_text());plan=json.loads((p/'plan.json').read_text());matrix=json.loads((p/'matrix.json').read_text())
assert len([x for x in runs if x['id']=='D6'])>0
assert subprocess.check_output(['git','diff','--name-only']).decode()==''
for m in plan:subprocess.run(['git','apply','--check',str(p/'diffs'/(m['id']+'.diff'))],check=True)
# Native direct row has built and executed every production variant.
for m in plan:
 cells=[x for x in matrix if x['id']==m['id']];assert any('TestJsxNative' in x['passed'] or ('TestJsxNative' in x['failed'] and 'TestJsxNative' not in x['anchor_failures']+x['possible_build_failures']) for x in cells),m['id']
start='76c59c81e8617cea1892a01841494895927a712c'
issues=['Whole-package baseline timed out at 90.017 seconds, with no assertion failure. The three defender coverage runs and all selected boundary/scanner/product/shard clean controls passed. Aggregate mutation matrices also cooked; all unfinished defender rows were rerun alone. Unknown leaves remain explicitly unknown.', 'Go coverage cannot instrument the TypeScript port or child native executables. Requested Go profiles cover actual load/lower/native compilation; Node V8 profiles and clean-HEAD source maps supplement port coverage. Exact native-versus-Node TypeScript line exclusivity is unmeasured.', 'The audit sampled only a few rows. Current listing has 100 tests, exactly the same names as the audit list. The defense matrix expands to all 36 JSX caller/product names, including previously omitted witnesses and preparation wrappers.', 'The Node/native rows share every source input through jsxManifest. Their different backends and sanitized/release native modes remain distinct coverage obligations. Source-mutant overlap does not establish that either backend check can be removed.', 'The member row combines original refusal with a permissive built-in source variant. D2 and D3 fail during that positive variant. These are observed test failures, not demonstrations that its original refusal check caught a regression.', 'D3 preserves the original rejection marker but moves its diagnostic from token position 21 to 14; the row proceeds and fails later on its permissive variant. It compares Go diagnostic class and Node/native stderr equality, not Go diagnostic position.', 'The member row logs that its check catches the built-in mutant exit zero, but never feeds that mutant through the refusal assertion. It only checks that permissive output contains custom-element. The refusal name itself is supported by its original assertions; the logged witness claim is stronger than demonstrated.', 'Built-in mutant recipes are exact source-string matches. D6 changes an anchor used by a namespace mutant; any such construction failure is retained separately and excluded from behavioral catches.', 'Six fixed-menu mutants were used, three per subject question with Node/native sharing three attempts. No oracle, harness or test was mutated. Compiler/runtime backend-specific semantic mutations beyond this port-source set were not explored.', 'Results are bounded. No row was deleted or rewritten, and no absence-of-uniqueness result is a deletion recommendation. Full-package and repository-wide uniqueness outside the listed matrix remains unknown.']
text='Defended none of the three rows with these six production attempts.\nEach row has three attempted differences caught by another observed row.\nTests remain unchanged; source restored; all diffs apply to origin/main '+start+'.\n\n'+json.dumps(r,indent=2)+'\n\nCODE UNDER TEST: TypeScript parser/scanner port and native compilation. ORACLE: unchanged Go TypeScript parser; Node executes the port. Full details are in method.md.\n\nMutants, origin/main sites:\n\n| ID | Site | Change |\n|---|---|---|\n'
for m in plan:text+='| '+m['id']+' | '+m['file']+':'+str(m['line'])+' | '+(m['old']+' -> '+m['new']).replace('\n',' ').replace('|','\\|')+' |\n'
text+='\nCoverage: coverage-diffs.json retains all exclusive Go blocks. Member versus Node: 4420 exclusive compiler blocks, 8 shared. Node versus Native: no exclusive compiler blocks, 8 shared. Native versus Node: 4421 exclusive compiler blocks, 8 shared. This reflects compilation, not port answer semantics. mapped-v8-coverage.json identifies member-only original-port mappings jsx.ts:33 and main.ts:64-66 versus Node. Boundary private-member input reaches the same invalid-name guard; Node/native use the same manifest corpus.\n\nUnclear instructions and time costs:\n\n'+'\n'.join('- '+s for s in issues)+'\n\nTiming: warm setup skipped (0 seconds), npm reports 606 milliseconds, nproc 5. Sum of completed matrix/control command walls: '+str(round(sum(x['wall'] for x in runs),3))+' seconds; coverage command walls: '+str(round(sum(x['wall'] for x in json.loads((p/'coverage-runs.json').read_text())),3))+' seconds. The whole-package baseline binary took 90.017 seconds and timed out. Cold native rebuilds are included in command and row times, not separately phase-timed. No other package tests were run.\n'
(p/'REPORT.md').write_text(text);(p/'validation.json').write_text(json.dumps(dict(starting_commit=start,source_restored=True,standalone_apply_checks=[m['id'] for m in plan],native_built_and_executed=[m['id'] for m in plan],tests_changed=False),indent=2))
print([(x['test'],x['defense']) for x in r])
