import pathlib,json,subprocess,shutil
R=pathlib.Path('/workspace/adamic');E=pathlib.Path('/tmp/d159/evidence');P='stage1/typescript/parser';base=subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip();runs=json.loads((E/'runs.json').read_text())
def events(id):return [json.loads(l) for l in (E/(id+'.log')).read_text().splitlines() if l.startswith('{')]
def failing(id,test):
 outs=[e['Output'].strip() for e in events(id) if e['Action']=='output' and e.get('Test')==test]
 return next((l for l in outs if any(k in l for k in ['warm-up count','sanitized build unavailable','native: %!w','no such file or directory'])),next((l for l in outs if '--- FAIL:' in l),None))
mat={m['id']:{n:next((e['Action'] for e in reversed(events(m['id'])) if e.get('Test')==n and e['Action'] in ['pass','fail']), 'unknown') for n in m['rows']} for m in runs};assert all(v!='unknown' for mm in mat.values() for v in mm.values())
(E/'matrix.json').write_text(json.dumps(mat,indent=2));out=[]
for test,prior,sub,ids in [('TestCompilerExpressionsAgree_Setup','untrue',[],['D3','D4','D5']),('TestPerformance','subsumed',['TestWholePerformance'],['D1']),('TestWholePerformance','subsumed',['TestPerformance'],['D2'])]:
 attempts=[]
 for id in ids:
  m=next(m for m in runs if m['id']==id);attempts.append(dict(mutant=id,file_line=m['path']+':'+str(m['line']),change=m['new'].replace(m['old'],'').strip() if m['old'] in m['new'] else m['old'].strip()+' -> '+m['new'].strip(),rows_failed=[n for n,status in mat[id].items() if status=='fail']))
 id=ids[0];m=next(m for m in runs if m['id']==id);success=test!='TestCompilerExpressionsAgree_Setup'
 obj=dict(test=test,package=P,prior_verdict=prior,subsumed_by=sub,defense='defended' if success else 'not defended',unique_mutant=(id+' '+m['path']+':'+str(m['line'])) if success else None,attempts=attempts,evidence=' '.join(m['command'])+' > '+id+'.log 2>&1; '+str(failing(id,test)),bounded=True,matrix_rows=m['rows'],rows_passed=[n for n,status in mat[id].items() if status=='pass'])
 if not success:obj['production_verdict']='subsumed';obj['current_subsumed_by']=['TestProduct_CompilerExpressionsNative']
 out.append(obj)
(E/'rows.json').write_text(json.dumps(out,indent=2))
summary='Two benchmark rows defended by distinct semantic count mutants in the complete count-caller matrix.\nSetup not uniquely defended; real production build faults refute its prior untrue classification, but are shared catches.\nOrigin/main '+base+'; 100 current tests, no names added or removed since the audit.\n'
text='''CODE UNDER TEST: TestPerformance and TestWholePerformance exercise the TypeScript port main.run/countTree in stage1/typescript/parser/main.ts and nodes.ts, compiled natively and executed on Node. Setup exercises successful construction through production native.Build, including options and file writes. No oracle, test or harness source was edited.

ORACLE: The two benchmarks compare external TypeScript-Go recursive counts; Whole also compares full AST bytes before timing. Setup relies on successful construction without errors, a self-written construction criterion. It never executes or checks the returned product path.

Reach and baseline: The full enabled baseline timed out at 90.021 seconds during native preparation, without an ordinary assertion failure. The current count-caller matrix then passed in 82.520 seconds, and the setup/shared-caller matrix in 22.215 seconds. The three individual coverage runs also passed. No mutation run cooked. The count matrix runs TestPerformance, TestWholePerformance, TestNodeCountCheckCatchesMutant and TestWholeCountCheckCatchesMutant. Static caller search finds --count only in those four top-level tests. All other current rows construct products or run non-count output; D1's new return is guarded by countOnly and D2 changes only countTree, which the non-count path never calls. Thus the bounded count matrix includes every affected execution route. Other 96 rows were not replayed per counter mutant and are not claimed to have passed.

For the broad native-builder mutations, the bounded matrix runs Setup, TestProduct_CompilerExpressionsNative and all sixteen TestCompilerExpressionsAgree_NNN shards. Other native-build consumers remain unmeasured. These shared catches already defeat exclusivity, so wider execution cannot improve Setup's defense. All eighteen selected clean rows passed before mutation.

Coverage: Each requested row ran with -coverpkg=./internal/native,./internal/lower,./internal/load and a separate -coverprofile. The Setup comparison ran TestProduct_CompilerExpressionsNative with the same coverage options. Each comparison shares 4428 covered Go blocks and has no exclusive Go production block. Those profiles cover compiler preparation, not TypeScript or generated C subprocess execution. Node V8 coverage supplements them with actual port execution. TestPerformance has no exclusive port lines against Whole; Whole alone covers driver byte-position/printing paths. Function counts show countTree called 3342060 times in Performance and 5326818 times in Whole, with printTree called zero versus 887803 times. Shared lines still receive different roots and modes.

An independent observation of the unchanged parser over the pinned corpus found 77 files, 72 with more than three expression roots, a maximum of 23955 roots, and 789 interface declarations. The expression count witness has three roots; the whole count witness uses a const declaration and a type alias, with no interface declaration. D1 returns early only for count-only expression mode when root count exceeds three. D2 returns early only at interface nodes in countTree. Both preserve full AST printing and the built-in mutant replacement sites.

D1: TestPerformance fails with Node count 17 versus Go 557010. WholePerformance and both count witnesses pass. D2: WholePerformance fails with Node count 847479 versus Go 887803. Performance and both count witnesses pass. These are semantic omissions in large expression counting and declaration subtree counting, not speed changes. Standalone diffs compile through native Build in the real matrix, including sanitized count-witness products.

Setup attempts: D3 makes native.Build report unavailable sanitized compilation. Setup, its product wrapper and all sixteen compiler shards fail. D4 flips the source-write error condition, so a successful write is reported as an error; the same eighteen rows fail. These are production builder faults, not malformed generated C caught by -Werror. D5 returns success without constructing an executable. Setup and its product wrapper pass, but all sixteen downstream shards fail with missing executable errors. D5 is an empty-success construction probe and contributes no positive uniqueness claim. Three attempts find no Setup-only catch. D3/D4 nevertheless prove Setup can fail under real production mutations, so untrue is too strong: its observed production status is subsumed by TestProduct_CompilerExpressionsNative.

Findings about names: Neither performance row asserts a timing threshold, ratio bound or regression tolerance. They establish different counting contracts and report timing. The Whole name also promises a full-tree preflight, which its assertions do check. Setup does initialize compiler products and detects reported build failures, but successful initialization does not establish artifact existence. D5 directly demonstrates that limitation. No test was deleted, rewritten or weakened.

Friction and unclear instructions:
1. The full parser package exceeds the 90-second binary budget before reaching many parallel rows. I narrowed by current count-only callers and by Setup's shared build callers. All scopes and unknown results outside them are explicit.
2. Go -coverprofile cannot cover a TypeScript port or generated C executing in subprocesses. Go compiler/builder coverage plus Node V8 port coverage avoids presenting harness coverage as parser execution coverage. Native instruction-level coverage was not collected.
3. The setup row's requested comparison is the rest of the package. One other row covers every production block it covers; therefore its set of exclusive Go blocks against the whole rest is also empty. I measured that sufficient subset rather than replaying the entire rest with coverage, which already exceeded budget.
4. Exclusive lines were not enough: the benchmark counter visits shared code over different graph roots. Whole's exclusive print preflight is already covered elsewhere, so I aimed at declaration counting rather than treating those lines as uniqueness proof.
5. The verdict instructions say an untrue row with a shared production catch becomes subsumed, but the final defense enum excludes subsumed. rows.json uses defense=not defended for Setup and production_verdict=subsumed with the observed catcher. This preserves both meanings.
6. Setup's prior audit weakened construction in a harness helper. That showed a missing-artifact blind spot, but did not establish that no production mutation can fail Setup. The two production error mutants correct that inference.
7. Aiming at inputs is permitted, but named test/path selectors would not provide a semantic defense. D1 uses expression-mode root-list size, and D2 uses a declaration kind. Neither checks a test name, corpus filename or audit environment selector.
8. Every count-mode route was included, including the newer whole-count witness in the current package. Scope comparison actually found no added or removed test names; no update was inferred merely from the newer origin/main commit.
9. Early-return guards preserve TypeScript flow narrowing and built-in mutation-site strings. A whole-body return or replacement could have created preparation failures rather than semantic counter evidence.
10. The repository ignores .log files, so evidence logs must be explicitly force-added. Source restoration was verified before packaging.

Costs and limits: Warm setup skipped, npm ci reported 350 ms, nproc 5. Five mutations were run, below the seven-mutant ceiling; both count matrices took about 73 command-wall seconds and stayed below 90 binary seconds. Builder matrices took about 17 wall seconds each. Native rebuilds are included in real matrix runtime. Every Go builder diff passed go vet ./internal/native/. All standalone diffs apply independently to the starting origin/main commit. No other packages, broad builder consumers, exhaustive native coverage or repo-wide uniqueness were tested. Source edits are restored. Full report, profiles, coverage differences, caller searches, input-shape observation and raw JSON logs are retained.
'''
(E/'REPORT.md').write_text(summary+'\n'+json.dumps(out,indent=2)+'\n\n'+text)
(E/'caller-search.txt').write_text(subprocess.check_output(['rg','-n','--','--count|countTree|countOnly','stage1/typescript/parser'],cwd=R,text=True))
for p in (E/'diffs').glob('*.diff'):subprocess.run(['git','apply','--check',str(p)],cwd=R,check=True)
(E/'diff-validation.log').write_text('All five independent diffs apply to '+base+'. D1/D2 compile in native count matrices; D3/D4/D5 pass go vet ./internal/native/.\n')
print(summary)
