"""Exhaustive integer rune canonicalization against the production Go regexp helper."""
import pathlib,json,subprocess,time,hashlib
root=pathlib.Path(__file__).resolve().parent;repo=root.parents[4]
work=pathlib.Path('/workspace/wave-09-case');work.mkdir(exist_ok=True)
def write(name,text):p=work/name;p.write_text(text);return p
def run(name,args,cwd=repo):
 start=time.monotonic()
 with (work/(name+'.stdout')).open('wb') as out,(work/(name+'.stderr')).open('wb') as err:r=subprocess.run(list(map(str,args)),cwd=cwd,stdout=out,stderr=err,timeout=120)
 elapsed=time.monotonic()-start;print(name,r.returncode,round(elapsed,6),flush=True)
 assert r.returncode==0,(name,(work/(name+'.stderr')).read_text()[:2000])
 return (work/(name+'.stdout')).read_bytes(),elapsed
virtual=repo/'cohere/wave09_case_oracle.go';overlay=write('overlay.json',json.dumps({'Replace':{str(virtual):str(root/'testdata/case_oracle.go')}}))
go=work/'go';run('go-build',['go','build','-overlay',overlay,'-o',go,virtual],repo/'cohere')
tables,_=run('tables',[go,'--tables']);data=json.loads(tables)
expected='// Unicode '+data['Version']+' primitive ToUpper and SimpleFold mappings, generated by the owned Go oracle.\nexport const unicodeVersion = '+json.dumps(data['Version'])+';\nexport const uppercasePairs:readonly number[] = '+json.dumps(data['Upper'])+';\nexport const foldPairs:readonly number[] = '+json.dumps(data['Fold'])+';\n'
assert (root/'unicode_case_data.a').read_text()==expected,'Unicode data drift'
truth,go_time=run('go',[go])
source='import {canonicalize} from '+json.dumps(str(root/'canonicalize.a'))+';\nfor(let value=-1;value<=1114112;value++){console.log(`${canonicalize(value,false)}\\t${canonicalize(value,true)}`);}\n'
path=write('main.a',source);measurements={'runes':1114114,'answers':2228228,'bytes':len(truth),'unicode_version':data['Version'],'go_seconds':go_time,'sha256':hashlib.sha256(truth).hexdigest()}
for mode in ['normal','sanitized','ascii-mutant','fold-mutant']:
 current=path
 if mode.endswith('mutant'):
  text=(root/'canonicalize.a').read_text().replace("'./unicode_case_data.a'",json.dumps(str(root/'unicode_case_data.a')))
  anchor='value>=128&&upper<128' if mode=='ascii-mutant' else 'folded<least'
  replacement='value>=1114113&&upper<128' if mode=='ascii-mutant' else 'folded>least'
  assert text.count(anchor)==1
  mutated=write(mode+'.a',text.replace(anchor,replacement));current=write(mode+'-main.a',source.replace(str(root/'canonicalize.a'),str(mutated)))
 binary=work/mode;args=['/workspace/wave-09-core/adamic','build',current,'-o',binary]
 if mode=='sanitized':args.append('--sanitize')
 run(mode+'-build',args);actual,elapsed=run(mode,[binary]);assert not (work/(mode+'.stderr')).read_bytes()
 if mode.endswith('mutant'):
  assert actual!=truth;measurements[mode+'_difference']=next(i for i,(a,b) in enumerate(zip(actual,truth)) if a!=b)
  print(mode,'caught at byte',measurements[mode+'_difference'],flush=True)
 else:
  if actual!=truth:
   diff=next((i for i,(a,b) in enumerate(zip(actual,truth)) if a!=b),min(len(actual),len(truth)));raise AssertionError((mode,diff,actual[max(0,diff-80):diff+100],truth[max(0,diff-80):diff+100]))
  measurements[mode+'_seconds']=elapsed;print(mode,'identical bytes',len(truth),flush=True)
emitted,_=run('js-build',['/workspace/wave-09-core/adamic','js',path]);js=write('main.mjs',emitted.decode())
for name,p in [('source',path),('emitted',js)]:
 actual,elapsed=run(name,['node','--disable-warning=ExperimentalWarning',repo/'oracle/node.mjs',p]);assert actual==truth;measurements[name+'_seconds']=elapsed
write('results.json',json.dumps(measurements,indent=2)+'\n')
print('PASS exhaustive ECMAScript case canonicalization, production Go, native, sanitizers, both Node modes and two semantic mutants; no native regex compiler is exercised',flush=True)
