#!/usr/bin/env python3
"""Generate ECMA-262 Canonicalize tables from Unicode 17.0.0 (Node 24)."""
import hashlib
import pathlib
import urllib.request
root = pathlib.Path(__file__).resolve().parents[1]
base = 'https://www.unicode.org/Public/17.0.0/ucd/'
data = {}
for name in ['CaseFolding.txt', 'UnicodeData.txt', 'SpecialCasing.txt', 'PropertyValueAliases.txt']:
    data[name] = urllib.request.urlopen(base + name).read()
fold, upper, expand = {}, {}, set()
for line in data['CaseFolding.txt'].decode().splitlines():
    line = line.split('#')[0].strip()
    if not line:
        continue
    code, status, mapping, *_ = [s.strip() for s in line.split(';')]
    if status in ('C','S'):
        fold[int(code,16)] = int(mapping,16)
for line in data['UnicodeData.txt'].decode().splitlines():
    fields = line.split(';')
    if fields[12]:
        upper[int(fields[0],16)] = int(fields[12],16)
for line in data['SpecialCasing.txt'].decode().splitlines():
    line = line.split('#')[0].strip()
    if not line:
        continue
    code, lower, title, mapping, condition, *_ = [s.strip() for s in line.split(';')]
    if not condition:
        values = [int(s,16) for s in mapping.split()]
        if len(values) != 1:
            expand.add(int(code,16))
        else:
            upper[int(code,16)] = values[0]
for code in expand:
    upper.pop(code,None)
upper = {code: value for code,value in upper.items() if code!=value and not(code>=128 and value<128)}
lines = ['// Code generated by testdata/generate-canonicalize.py; DO NOT EDIT.',
         '// Unicode 17.0.0, matching Node 24. Unicode data license:',
         '// https://www.unicode.org/license.txt']
for name, contents in data.items():
    lines.append('// '+name+' SHA256 '+hashlib.sha256(contents).hexdigest())
lines += ['package regexp', '', 'import "sort"', '',
          'func canonicalize(c rune, f Flags) rune {',
          '\tif !f.IgnoreCase { return c }',
          '\ttable := legacyUppercase[:]',
          '\tif unicodeMode(f) { table = simpleCaseFold[:] }',
          '\ti := sort.Search(len(table), func(i int) bool { return table[i][0] >= c })',
          '\tif i < len(table) && table[i][0] == c { return table[i][1] }',
          '\treturn c', '}', '']
for name, table in [('simpleCaseFold',fold),('legacyUppercase',upper)]:
    lines.append('var '+name+' = [...][2]rune{')
    lines += [f'\t{{0x{code:X}, 0x{value:X}}},' for code,value in sorted(table.items())]
    lines += ['}', '']
(root/'canonicalize.go').write_text('\n'.join(lines))
print(f'Unicode 17.0.0: {len(fold)} simple folds, {len(upper)} legacy uppercase mappings, {len(expand)} full expansions excluded')

aliases = {}
for line in data['PropertyValueAliases.txt'].decode().splitlines():
    line = line.split('#')[0].strip()
    if not line:
        continue
    fields = [s.strip() for s in line.split(';')]
    if fields[0]=='sc':
        for alias in fields[1:]:
            aliases[alias]=fields[2]
(root/'script_aliases.go').write_text('// Code generated by testdata/generate-canonicalize.py; DO NOT EDIT.\n// Unicode 17.0.0 Script aliases. Unicode data license: https://www.unicode.org/license.txt\npackage regexp\n\nvar scriptAliases = map[string]string{\n'+''.join(f'\t"{key}": "{value}",\n' for key,value in sorted(aliases.items()))+'}\n')
(root/'testdata/unicode-license.txt').write_bytes(urllib.request.urlopen('https://www.unicode.org/license.txt').read())
print(f'Unicode 17.0.0: {len(aliases)} exact Script aliases')
