#!/usr/bin/env python3
"""Run real table mutants in isolated copies; never change repository sources."""
from pathlib import Path
import tempfile,shutil,subprocess,json,os
root=Path(__file__).resolve().parents[3];proof=Path('/tmp/regex-runtime-postmerge-table-mutants');proof.mkdir(exist_ok=True)
base=json.loads(Path(os.environ['ADAMIC_REGEX_TEST_OVERLAY']).read_text()) if os.environ.get('ADAMIC_REGEX_TEST_OVERLAY') else {'Replace':{}}
cases=[('range-entry','TestRegExpRuntimePropertyIdentity','property identity failed'),('invalid-alias','TestRegExpRuntimePropertyIdentity','property identity failed'),('wasm-property','TestRegExpRuntimePropertiesWASI','WASI identity:'),('stale-generation','TestRegExpRuntimePropertiesGenerated','runtime property tables are stale'),('unconditional-link','TestRegExpRuntimeCompilerNotLinked','linked compiler symbols or tables')]
for name,test,witness in cases:
 with tempfile.TemporaryDirectory(prefix='regex-table-mutant-') as scratch:
  scratch=Path(scratch);runtime=scratch/'runtime';shutil.copytree(root/'internal/native/runtime',runtime)
  c=runtime/'regexp_compile_properties.c';data=c.read_text();table=runtime/'regexp_compile_tables.h'
  if name=='range-entry':
   data2=table.read_text();assert data2.count('{0x0000,0x007F},')>=1;table.write_text(data2.replace('{0x0000,0x007F},','{0x0000,0x007E},',1))
  if name=='invalid-alias':data=data.replace('#include "regexp_compile.h"','#include "regexp_compile.h"\n#include <string.h>').replace('    size_t low = 0,','    if(length==5 && memcmp(expression,"ascii",5)==0) return &regex_compile_property_0;\n    size_t low = 0,',1)
  if name=='wasm-property':data=data.replace('    size_t low = 0,','#ifdef ADAMIC_TARGET_WASI\n    return NULL;\n#endif\n    size_t low = 0,',1)
  if name=='unconditional-link':data=data.replace('#ifdef ADAMIC_REGEXP_RUNTIME_COMPILER','#if 1',1)
  if name=='stale-generation':table.write_text(table.read_text().replace('Generated by','Mutated by',1))
  c.write_text(data)
  testfile=scratch/'regexp_compile_test.go';source=(root/'internal/native/regexp_compile_test.go').read_text().replace('filepath.Abs("runtime")','filepath.Abs('+json.dumps(str(runtime))+')').replace('os.ReadFile("runtime/regexp_compile_tables.h")','os.ReadFile('+json.dumps(str(table))+')');testfile.write_text(source)
  overlay=json.loads(json.dumps(base));overlay['Replace'][str(root/'internal/native/regexp_compile_test.go')]=str(testfile)
  if name=='unconditional-link':
   helper=scratch/'library_regexp_compile.go';helper.write_text((root/'internal/native/library_regexp_compile.go').read_text().replace('return RuntimeLibraryForSource("", source, options)','return RuntimeLibraryForSource('+json.dumps(str(runtime))+', source, options)',1));overlay['Replace'][str(root/'internal/native/library_regexp_compile.go')]=str(helper)
  overlayfile=scratch/'overlay.json';overlayfile.write_text(json.dumps(overlay));log=proof/(name+'.log')
  with log.open('w') as out:result=subprocess.run(['go','test','-overlay='+str(overlayfile),'./internal/native','-run','^'+test+'$','-count=1','-v'],cwd=root,stdout=out,stderr=subprocess.STDOUT)
  text=log.read_text();assert result.returncode!=0 and witness in text and 'build failed' not in text and 'compile:' not in text,(name,text)
  print(name+': caught at '+witness,flush=True)
