// Generated by adamic from stack_forever.a. Do not edit.

#include "adamic.h"

#include <math.h>
#include <stdbool.h>

static adamic_string adamic_string_0 = ADAMIC_STRING("start");

static double adamic_function_0_loop(double adamic_local_0_n);

static double adamic_function_0_loop(double adamic_local_0_n) {
	#ifdef ADAMIC_TARGET_WASI
	volatile unsigned char adamic_stack_frame[32];
	adamic_stack_frame[0] = 0;
	adamic_stack_frame[31] = 0;
	if ((uintptr_t)adamic_stack_frame < adamic_stack_limit) adamic_stack_overflow();
	#endif
	ADAMIC_CHECK_STACK();
	double adamic_temporary_1 = adamic_function_0_loop((adamic_local_0_n + (0x1p+00)));
	double adamic_temporary_2 = adamic_temporary_1;
	return adamic_temporary_2;
	adamic_unreachable();
}

int main(int argc, char **argv) {
	adamic_start(argc, argv);
	adamic_write_line(adamic_stdout, &adamic_string_0);
	double adamic_temporary_3 = adamic_function_0_loop((0x0p+00));
	adamic_string * adamic_temporary_4 = adamic_string_from_number(adamic_temporary_3);
	adamic_string * adamic_temporary_5 = adamic_string_concat(1, (adamic_string *const[]){adamic_temporary_4});
	adamic_write_line(adamic_stdout, adamic_temporary_5);
	adamic_release(adamic_temporary_5);
	adamic_release(adamic_temporary_4);
	return 0;
}
