// Capture cohere's pinned named character references as native string data.
package main

import (
	"bytes"
	"crypto/sha256"
	"encoding/json"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
)

func main() {
	source := flag.String("source", "cohere/internal/format/markdown/micromark/entities_generated.go", "pinned Go entities")
	output := flag.String("output", "stage1/cohere/markdownblocks", "native data directory")
	formatter := flag.String("formatter", "/tmp/cssstrings-cohere", "cohere formatter executable")
	check := flag.Bool("check", false, "compare generated bytes")
	flag.Parse()
	raw, e := os.ReadFile(*source)
	must(e)
	tree, e := parser.ParseFile(token.NewFileSet(), *source, raw, 0)
	must(e)
	entities := map[string]string{}
	ast.Inspect(tree, func(n ast.Node) bool {
		v, ok := n.(*ast.ValueSpec)
		if !ok {
			return true
		}
		if len(v.Names) != 1 || v.Names[0].Name != "characterEntities" || len(v.Values) != 1 {
			panic("unexpected entity declaration")
		}
		value := v.Values[0].(*ast.CompositeLit)
		for _, element := range value.Elts {
			pair := element.(*ast.KeyValueExpr)
			key, e := strconv.Unquote(pair.Key.(*ast.BasicLit).Value)
			must(e)
			text, e := strconv.Unquote(pair.Value.(*ast.BasicLit).Value)
			must(e)
			if _, exists := entities[key]; exists {
				panic("duplicate entity")
			}
			entities[key] = text
		}
		return false
	})
	if len(entities) != 2125 {
		panic("expected pinned 2125 entities")
	}
	names := make([]string, 0, len(entities))
	for name := range entities {
		names = append(names, name)
	}
	sort.Strings(names)
	// Reference names are case-sensitive. Uppercase/lowercase keys and values are
	// separate data concerns, and callers import each table's home directly.
	for _, upper := range []bool{true, false} {
		prefix := "lower"
		if upper {
			prefix = "upper"
		}
		for _, kind := range []string{"Names", "Values"} {
			var b bytes.Buffer
			fmt.Fprintf(&b, "// Pinned cohere named entities, source SHA256 %x.\n// Regenerate: go run ./stage1/cohere/markdownblocks/tools/generate_entities\n", sha256.Sum256(raw))
			field := prefix + "Entity" + kind
			fmt.Fprintf(&b, "export const %s: readonly string[] = [\n", field)
			for _, name := range names {
				if (name[0] >= 'A' && name[0] <= 'Z') != upper {
					continue
				}
				text := name
				if kind == "Values" {
					text = entities[name]
				}
				encoded, e := json.Marshal(text)
				must(e)
				fmt.Fprintf(&b, "    %s,\n", encoded)
			}
			fmt.Fprintln(&b, "];")
			formatData(*formatter, filepath.Join(*output, field+".ts"), b.Bytes(), *check)
		}
	}
}
func must(e error) {
	if e != nil {
		panic(e)
	}
}

func formatData(formatter, output string, data []byte, check bool) {
	tmp, e := os.CreateTemp("", "adamic-entities-*.ts")
	must(e)
	defer os.Remove(tmp.Name())
	_, e = tmp.Write(data)
	must(e)
	must(tmp.Close())
	out, e := exec.Command(formatter, "--no-cache", "--fix", tmp.Name()).CombinedOutput()
	if e != nil {
		panic(fmt.Sprintf("cohere: %v %s", e, out))
	}
	result, e := os.ReadFile(tmp.Name())
	must(e)
	if check {
		actual, e := os.ReadFile(output)
		must(e)
		if !bytes.Equal(actual, result) {
			panic("generated entities changed")
		}
	} else {
		must(os.WriteFile(output, result, 0644))
	}
}
