"""Read source blobs only: all root configs and two nested configs per held pin."""
import concurrent.futures
import hashlib
import json
import pathlib
import subprocess

root = pathlib.Path(__file__).resolve().parent
names = {'CohereSettings.json', 'NexusCohereSettings.json', 'package.yaml', '.prettierrc', '.prettierrc.json', '.prettierrc.yaml', '.prettierrc.yml', '.prettierrc.json5', '.prettierrc.js', 'prettier.config.js', '.prettierrc.ts', 'prettier.config.ts', '.prettierrc.mjs', 'prettier.config.mjs', '.prettierrc.mts', 'prettier.config.mts', '.prettierrc.cjs', 'prettier.config.cjs', '.prettierrc.cts', 'prettier.config.cts', '.prettierrc.toml'}

def collect(pin):
    repo, sha = pin['repo'], pin['commit']
    cache = pathlib.Path('/tmp/scout42-public') / (repo.replace('/', '__') + '-' + sha[:8])
    def git(*args):
        return subprocess.check_output(['git', '-C', str(cache), *args], stderr=subprocess.PIPE, timeout=180)
    paths = git('ls-tree', '-r', '--name-only', sha).decode().splitlines()
    matched = [p for p in paths if pathlib.PurePosixPath(p).name in names]
    selected = [p for p in matched if '/' not in p] + [p for p in matched if '/' in p][:2]
    files = []
    for path in selected:
        data = git('show', sha + ':' + path)
        destination = 'settings-corpus/' + repo.replace('/', '__') + '-' + sha[:8] + '/' + path
        target = root / destination
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        files.append(dict(source=path, fixture=destination, sha256=hashlib.sha256(data).hexdigest()))
    return dict(repo=repo, commit=sha, discovered=matched, files=files)

with concurrent.futures.ThreadPoolExecutor(max_workers=4) as pool:
    records = list(pool.map(collect, json.loads((root / 'corpus.json').read_text())))
(root / 'settings-corpus.json').write_text(json.dumps(records, indent=2) + '\n')
print('pins', len(records), 'configs', sum(len(row['files']) for row in records), 'all config paths', sum(len(row['discovered']) for row in records))

repository = root.parents[3]
sets = repository / 'cohere/internal/lint/configuration/sets'
lines = ['// Exact embedded settings at the cohere pin; generated by testdata/settings_sources.py.', "import type { ReadResult } from './host.a';", 'export function embedded(source: string): ReadResult {', '    switch(source) {']
setnames = []
for file in sorted(sets.rglob('*.json')):
    name = 'cohere:' + str(file.relative_to(sets))[:-5]
    setnames.append(name)
    lines.append('        case ' + json.dumps(name) + ": return { kind: 'Ok', text: " + json.dumps(file.read_text(), ensure_ascii=True) + ' };')
lines += ["        default: return { kind: 'Error', message: source + " + json.dumps(' is not a rule set cohere carries; the sets are ' + ', '.join(setnames)) + ' };', '    }', '}']
(root.parent / 'settings/sets.a').write_text('\n'.join(lines) + '\n')
