//go:build ignore

// Run from the markdowninline package directory, or through go generate.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strconv"
)

const preamble = `// Code generated by testdata/generate_shard_units.go; DO NOT EDIT.
//go:generate go run testdata/generate_shard_units.go

package markdowninline

import (
 "flag"
 "fmt"
 "regexp"
 "strings"
	"os"
	"sync"
	"testing"
	"time"
)

var inlineSharedOnce sync.Once
var inlineSharedRun func(*testing.T, int)
var inlineSharedOverlayDir string

// Shared temporary products live through m.Run, including every parallel unit.
// Not parallel: m.Run and process-wide cleanup of the shared overlay directory.
func TestMain(m *testing.M) {
 flag.Parse()
 includeInlineSetup()
 code := m.Run()
	if inlineSharedOverlayDir != "" {
		os.RemoveAll(inlineSharedOverlayDir)
	}
	os.Exit(code)
}
func sharedInlineShards(t *testing.T) func(*testing.T, int) {
	t.Helper()
	inlineSharedOnce.Do(func() {
		start := time.Now()
		data := collectInlineCorpus(t)
		inlineSharedRun = prepareInlineShards(t, data.paths, data.texts, data.files, data.generatedEnd, data.selected)
		t.Logf("shared setup: %.6fs", time.Since(start).Seconds())
	})
	if inlineSharedRun == nil {
		t.Fatal("shared setup failed")
	}
	return inlineSharedRun
}

// A selected shard still needs its separately timed setup unit. Selecting no
// Markdown inline shards leaves other package tests' selection unchanged.
func includeInlineSetup() {
 run := flag.Lookup("test.run").Value.String()
 if run == "" { return } // The default selection already includes setup.
 selector, err := regexp.Compile(strings.Split(run, "/")[0])
 if err != nil { return } // testing reports invalid selection patterns.
 if selector.MatchString("TestMarkdownInline_Setup") { return }
 for ordinal := 0; ordinal < testMarkdownInlineShards; ordinal++ {
  if selector.MatchString(fmt.Sprintf("TestMarkdownInline_%04d", ordinal)) {
   if err := flag.Set("test.run", "^TestMarkdownInline_Setup$|(?:"+run+")"); err != nil { panic(err) }
   return
  }
 }
}

// A cooked unit exits at 90 seconds rather than leaving a slow test running.
func inlineUnitBudget(t *testing.T) func() {
 name := t.Name()
 timer := time.AfterFunc(90*time.Second, func() {
  fmt.Fprintf(os.Stderr, "cooked: %s exceeded its 90-second deadline\n", name)
  os.Exit(124)
 })
 return func() { timer.Stop() }
}

// Not parallel: shared builds must finish before any parallel shard resumes.
func TestMarkdownInline_Setup(t *testing.T) {
 stop := inlineUnitBudget(t)
 defer stop()
 sharedInlineShards(t)
}

// ADAMIC_TEST_SHARD=i/n selects ordinal % n == i (zero-based); unset runs all.
// Gate selectors use ^TestMarkdownInline_NNNN$, visible through go test -list.
func runInlineUnit(t *testing.T, ordinal int) {
 if inlineSharedRun == nil { t.Fatal("shared setup was not selected") }
 // Shared setup has completed before this leaf's 90-second budget begins.
 stop := inlineUnitBudget(t)
 defer stop()
 inlineSharedRun(t, ordinal)
}

`

func main() {
	source, err := os.ReadFile("shards_test.go")
	if err != nil {
		panic(err)
	}
	match := regexp.MustCompile(`(?m)^const testMarkdownInlineShards = ([0-9]+)$`).FindSubmatch(source)
	if match == nil {
		panic("missing literal testMarkdownInlineShards")
	}
	count, err := strconv.Atoi(string(match[1]))
	if err != nil {
		panic(err)
	}
	var output bytes.Buffer
	output.WriteString(preamble)
	for ordinal := 0; ordinal < count; ordinal++ {
		fmt.Fprintf(&output, "func TestMarkdownInline_%04d(t *testing.T) {\n t.Parallel()\n runInlineUnit(t, %d)\n}\n", ordinal, ordinal)
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("shard_units_test.go", formatted, 0644); err != nil {
		panic(err)
	}
}
