//go:build ignore

// Run from the markdowninline package directory, or through go generate.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"regexp"
	"strconv"
)

const preamble = `// Code generated by testdata/generate_shard_units.go; DO NOT EDIT.
//go:generate go run testdata/generate_shard_units.go

package markdowninline

import (
	"os"
	"sync"
	"testing"
	"time"
)

var inlineSharedOnce sync.Once
var inlineSharedRun func(*testing.T, int)
var inlineSharedOverlayDir string

// Shared temporary products live through m.Run, including every parallel unit.
// Not parallel: owns process exit and shared-product cleanup after all tests.
func TestMain(m *testing.M) {
	code := m.Run()
	if inlineSharedOverlayDir != "" {
		os.RemoveAll(inlineSharedOverlayDir)
	}
	os.Exit(code)
}
func sharedInlineShards(t *testing.T) func(*testing.T, int) {
	t.Helper()
	inlineSharedOnce.Do(func() {
		start := time.Now()
		data := collectInlineCorpus(t)
		inlineSharedRun = prepareInlineShards(t, data.paths, data.texts, data.files, data.generatedEnd, data.selected)
		t.Logf("shared setup: %.6fs", time.Since(start).Seconds())
	})
	if inlineSharedRun == nil {
		t.Fatal("shared setup failed")
	}
	return inlineSharedRun
}

// Setup is a separately discoverable unit. A selected shard also initializes
// setup once when run alone; cache products are shared and read-only.
// Not parallel: shared build initialization completes before parallel shard execution.
func TestMarkdownInlineSetup(t *testing.T) { sharedInlineShards(t) }

// ADAMIC_TEST_SHARD=i/n selects ordinal % n == i (zero-based); unset runs all.
// Gate selectors use ^TestMarkdownInline_NNNN$, visible through go test -list.
func runInlineUnit(t *testing.T, ordinal int) {
	sharedInlineShards(t)(t, ordinal)
}

`

func main() {
	source, err := os.ReadFile("shards_test.go")
	if err != nil {
		panic(err)
	}
	match := regexp.MustCompile(`(?m)^const testMarkdownInlineShards = ([0-9]+)$`).FindSubmatch(source)
	if match == nil {
		panic("missing literal testMarkdownInlineShards")
	}
	count, err := strconv.Atoi(string(match[1]))
	if err != nil {
		panic(err)
	}
	var output bytes.Buffer
	output.WriteString(preamble)
	for ordinal := 0; ordinal < count; ordinal++ {
		fmt.Fprintf(&output, "func TestMarkdownInline_%04d(t *testing.T) {\n t.Parallel()\n runInlineUnit(t, %d)\n}\n", ordinal, ordinal)
	}
	formatted, err := format.Source(output.Bytes())
	if err != nil {
		panic(err)
	}
	if err := os.WriteFile("shard_units_test.go", formatted, 0644); err != nil {
		panic(err)
	}
}
