import pathlib,json,collections,statistics
p=pathlib.Path('/workspace/adamic/review/test-audit/internal-native-arguments_length');rows=json.loads((p/'rows.json').read_text());matrix=json.loads((p/'matrix.json').read_text());plans=json.loads((p/'plan.json').read_text());runs=json.loads((p/'runs.json').read_text());valid=json.loads((p/'final-validation.json').read_text());mapping={r['test']:r['row_id'] for r in rows}
summary=['u045: base e8cb7ac7478d52c3cc847a1163518b5849f7cc87; nproc 5.','All 14 requested functions exist in their named files; no family grouping was needed.','Whole-package baseline cooked at 90.023s; clean scoped baseline passed in 18.635s.','Bounded verdicts: 10 sacred, 4 witness; no package-wide uniqueness is claimed.','20 production mutants, 2 weakened checks, 10 entry probes; production restored.']
s='\n'.join(summary)+'\n\n```json\n'+json.dumps(rows,indent=2)+'\n```\n\n'
s+='All production matrices ran the 14 names in names.json. Beyond that bounded set, catches are unknown. Static caller evidence is in static-test-callers.log, reached Go functions in reached-functions.txt (187), and the C entry/call graph in runtime-functions.txt.\n\n'
s+='Code under test: native C emission and calling conventions, borrow/region/reuse analysis, runtime feature selection, native build flags, the C case runtime and its production version metadata. Oracles: actual Node mappings/version/output, handwritten plan/C marker/numeric expectations, and clang rejection plus handwritten diagnostic labels for witnesses. No oracle, harness or original test was mutated for production results. The two tagged witness diffs are the explicitly allowed weakened-check exception.\n\n'
s+='Witnesses: W_BUILD ignores clang failures in the Build adapter. DropCount, RuntimeDropCount and WrongOrder all fail. W_NODE makes the planted missing-thunk comparison always report agreement; OptionalMethodThunksMatchNode fails. Production-mutant failures of these four witnesses are recorded as precondition failures, never production kills.\n\n'
s+='| ID | Base file:line | Change | Eligible failed rows | Witness precondition failures, excluded |\n|---|---|---|---|---|\n'
for m in plans:
 text=m['old'].replace('\n',' ')+' -> '+(m['new'].replace('\n',' ') or '(drop statement)')
 if len(text)>200:text={'M05':'Pass-through exclusions return true instead of false','M06':'pureKind default returns true instead of false'}.get(m['id'],text)
 s+='| '+m['id']+' | '+m['file']+':'+str(m['line'])+' | '+text.replace('|','\\|')+' | '+', '.join(mapping[n] for n in matrix[m['id']]['eligible_failed'])+' | '+', '.join(mapping[n] for n in matrix[m['id']]['witness_precondition_failures'])+' |\n'
s+='\nSurvivors in the eligible bounded production matrix:\n\n- M03: observed featureFlags("// ADAMIC_NODE_HOST\\n") changes [] to [-DADAMIC_NODE_HOST=1]. This comment selects a runtime feature.\n- M06: observed consumes(ir.Call{}) changes false to true. The table-based test does not cover this unknown-operation default.\n- M13: controlled object-parameter summaries change safe/storing/mixed from false/true/true to true/false/true. Mixed-target truth remains the same, exposing the weakness of the mixed-summary assertion.\n- M16: emitted method-thunk text changes its outer argument_count > 0 to >= 0; an inner > 0 guard remains. No native execution difference was established. Treat it as an execution-equivalent candidate, not a demonstrated semantic bug.\n- M17: counted closure signature loses its size_t argument_count parameter. No eligible regular row catches it, but DropCount and WrongOrder fail their valid-build precondition. This is not an all-tests survivor; those catches are excluded by the witness rule.\n\n'
s+='Empty-answer observations:\n\n- P_C: NoReader fails its counted cases; closure_convention_plain.a passes. ParserHasNoUnusedOptionalMethodThunks and RuntimeFeaturesIgnoreLiterals both pass empty C.\n- P_BORROW: BorrowChainDeclarations fails its positive walk expectations; InheritanceMemoryPlans passes an empty borrow plan.\n- P_CHAIN and P_CONSUMES: their rows fail their positive expectations.\n- P_REGIONS and P_REUSE: InheritanceMemoryPlans fails an empty region or reuse plan.\n- P_LIBRARY: RuntimeFeaturesIgnoreLiterals fails when no library path is returned.\n- P_BUILD: ArithmeticIsNeverFused fails when Build returns success without producing a binary.\n- P_CASE_LOWER and P_CASE_UPPER: CaseMappingMatchesNode fails when either runtime entry returns NULL.\n- Unicode version metadata has no callable production entry to short-circuit; it was not probed, and its vacuous value is null. Witness vacuity is also null.\n- For a composite row, vacuous=true denotes a passing empty probe on at least one direct entry. vacuous_entries names that entry; it does not erase the row\'s checks on other entries.\n\n'
s+='Brief ambiguities, limits and costs:\n\n- Fresh origin/main is e8cb7ac7, not the historical 8de93800f4. Fresh main governed; no requested name moved or vanished.\n- Three mutants per 14 rows would be 42; the cap of 20 governed. Four rows are witnesses and were judged by the two weakened checks instead.\n- The whole package cannot fit the 90-second budget. The bounded matrix includes all requested rows, and caller searches show other package tests reach the mutated functions. Sacred and unique_kills are bounded findings only; central replay must settle package and repo uniqueness.\n- Wrapper grouping was checked against actual bodies. The closure witnesses assert different properties and remain separate. The points/contexts sweeps are already subtests of one top-level row.\n- M10 initially left a chain binding unused. Before any matrix ran, its condition was changed to element || false && chain, preserving the deliberate disabled-chain behavior and a compilable binding. M17\'s standalone diff was later cleaned of blank-line trailing whitespace without changing behavior.\n- Runtime C can read the selector; production header metadata cannot. M20 required its own embedded-source rebuild. Its command wall and binary durations are logged rather than conflated with a timed standalone rebuild.\n- The Flags mutation changes compiler options, which rebuilds runtime variants. Native Build writes fresh fixture executables; runtime libraries are keyed by source/header bytes, compiler and flags. Every matrix also received ADAMIC_BUILD_CACHE_DIR=/tmp/u045/cache/ID.\n- Three vacuity findings concern one entry of a composite check. The entry names are reported explicitly. No safe callable empty-entry probe was added for embedded Unicode metadata.\n- The optional-method row combines positive Node comparisons and a planted failure. Under the brief\'s witness rule, only W_NODE decides its verdict; production precondition failures do not count.\n- No production matrix cooked or panicked. The whole-package baseline timed out, rather than producing a red assertion baseline; the narrowed clean baseline passed.\n- 86 default baseline skips were observed, listed individually in skipped-baseline.json. They include the WASI families without a configured SDK and opt-in measurement/archive rows. These outside-scope integrations were not provisioned or enabled after narrowing. Installable benchmark opt-ins were left uncovered because the 610-measurement and other inventory runs exceed this unit\'s budget. No scoped function skipped.\n- M16 has a generated-C textual difference but no demonstrated runtime difference; it is not labeled an unguarded semantic failure. M17 has observed witness precondition catches; it is not labeled globally unguarded.\n- No other package tests ran. Independent replay diffs all apply to the starting sources and compile. Production sources and original tests are restored; no PR or main push was made.\n\n'
binary=0;static=[]
for run in runs:
 for l in (p/(run['id']+'.log')).read_text().splitlines():
  try:d=json.loads(l)
  except:continue
  if d.get('Action') in ['pass','fail'] and not d.get('Test'):
   binary+=d.get('Elapsed',0)
   if run['id']=='M20':static.append({'wall':run['wall'],'binary_seconds':d.get('Elapsed'),'overhead_including_embedded_rebuild':run['wall']-d.get('Elapsed',0)})
(p/'timing-summary.json').write_text(json.dumps({'whole_baseline_seconds':90.023,'scope_baseline_seconds':18.635,'scope_baseline_wall':25.448207105,'isolated_three_run_wall':146.763058101,'switched_go_build':json.loads((p/'build.json').read_text()),'matrix_command_walls':sum(r['wall'] for r in runs),'matrix_binary_seconds':binary,'standalone_compile_validation_wall':sum(v['wall'] for v in valid),'metadata_rebuild_observation':static},indent=2))
s+=f'Timing: warm toolchain worked, setup skipped (0 seconds); nproc 5. npm ci reported 0.394s. Whole baseline: 90.023s cooked. Scoped baseline: 18.635s binary, 25.448s command wall including coverage build. All three isolated measurements: 146.763s command wall. Switched Go test build: 6.669s. Matrices, weakened checks and probes: {sum(r["wall"] for r in runs):.3f}s command wall, {binary:.3f}s binary elapsed. Independent final diff validation: {sum(v["wall"] for v in valid):.3f}s. M20 command/binary/rebuild-overhead observation: {static}. Total session approximately 25 minutes, including source review, preparation and survivor observations.\n'
(p/'REPORT.md').write_text(s);print('report written; matrices',len(runs),'binary',binary,'wall',sum(r['wall'] for r in runs))
