//go:build ignore

// Freeze the toolchain's Unicode predicates as JavaScript RegExp literals.
// This avoids substituting a different Unicode version from the JS runtime.
package main

import (
	"fmt"
	"strings"
	"unicode"
)

func character(value rune) string { return fmt.Sprintf(`\u{%x}`, value) }
func pattern(test func(rune) bool) string {
	var out strings.Builder
	out.WriteString("/^[")
	for first := rune(0); first <= unicode.MaxRune; first++ {
		if !test(first) {
			continue
		}
		last := first
		for last < unicode.MaxRune && test(last+1) {
			last++
		}
		out.WriteString(character(first))
		if last > first {
			out.WriteString("-")
			out.WriteString(character(last))
		}
		first = last
	}
	out.WriteString("]/u")
	return out.String()
}
func main() {
	fmt.Printf("// Generated by unicode_tables.go; Go Unicode %s.\n", unicode.Version)
	fmt.Printf("export function upper(name: string): boolean { return %s.test(name); }\n", pattern(unicode.IsUpper))
	fmt.Printf("export function printable(character: string): boolean { return %s.test(character); }\n", pattern(unicode.IsPrint))
}
