import pathlib,json,shlex,subprocess
p=pathlib.Path('review/test-defend/stage1-cohere-css-composition_shards');r=json.loads((p/'results.json').read_text())
for ident in ['clean','D1']:
 batches=[x for x in r if x['mutant']==ident and x['group'].startswith('parser-batch-')]
 assert len(batches)==4 and all(x['exit']==0 for x in batches)
 assert len(set(t for x in batches for t in x['passed']))==388
runs=[x for x in r if x['mutant']=='D1' and x['group']!='parser-family']
passed=sorted({t for x in runs for t in x['passed']});failed=sorted({t for x in runs for t in x['failed']});skipped=sorted({t for x in runs for t in x['skipped']});assert failed==['TestCSSThroughput'];assert len(passed)==416
scope=json.loads((p/'scope.json').read_text());unknown=sorted(set(scope['current'])-set(passed)-set(failed)-set(skipped))
(p/'passed-rows.json').write_text(json.dumps(dict(mutant='D1',passed=passed,failed=failed,skipped=skipped,not_replayed=unknown),indent=2)+'\n')
hit=next(x for x in r if x['mutant']=='D1' and x['group']=='throughput');line=next(x for x in hit['outputs'] if 'checksum' in x);evidence='env ADAMIC_CSS_BENCH=1 ADAMIC_CSS_LIBRARY=/tmp/defend-css/library ADAMIC_CSS_FIXTURES=/tmp/defend-css/fixtures ADAMIC_BUILD_CACHE_DIR=/tmp/defend-css/cache/D1 '+shlex.join(hit['command'])+'; '+line
row=dict(test='TestCSSThroughput',package='stage1/cohere/css',prior_verdict='subsumed',subsumed_by=['TestCompositionMatchesGo family'],defense='defended',unique_mutant='D1 stage1/cohere/css/main.ts:59',attempts=[dict(mutant='C1',file_line='stage1/cohere/css/input.ts:63',change='Replace binary-search midpoint with low+1, preserving answers and increasing lookup work.',rows_failed=[]),dict(mutant='D1',file_line='stage1/cohere/css/main.ts:59',change='Off by one: repeat nine rounds instead of ten.',rows_failed=failed)],evidence=evidence,bounded=True,matrix_rows=sorted(set(passed+failed+skipped)),unknown_outside_matrix=unknown,performance_finding='Logs speed without a threshold or ratio assertion; C1 passes. Independent PostCSS enables the repeat-count kill.')
(p/'rows.json').write_text(json.dumps([row],indent=2)+'\n')
report=(p/'REPORT-draft.md').read_text();report='Defended in the complete reached-main replay: D1 fails only TestCSSThroughput.\nAll 388 parser shards and 16 former-subsumer composition shards pass, plus related builders and witnesses.\nKeep for repeat-count consistency; speed is logged, not asserted.\n\n'+report
report+='\n## Completed result\n\nD1: 416 top-level functions passed, one failed, one Darwin-only product skipped. The 388 parser shards were fully replayed clean and mutated in four batches. '+str(len(unknown))+' other top-level functions were not replayed and are not claimed as experimentally passed. The reached-entry narrowing is documented by main-callers.txt. This is a bounded defense, not repo-wide uniqueness.\n\nExact failure: '+line+'\n\nBoth standalone diffs were git apply --check validated against unchanged starting main. No production source or test diff remains.\n\nTotal controller command wall seconds (clean reached runs and mutant runs, including cooked and stopped attempts): '+str(round(sum(x['wall'] for x in r),3))+'. Clean instrumented coverage binary time 111.814s and whole baseline 90.017s are additional. API npm ci reported 651ms and independent library install 1s. Warm setup skipped. Native rebuild and execution are combined in the recorded per-run wall times.\n'
(p/'REPORT.md').write_text(report);(p/'REPORT-draft.md').unlink()
print('Final:',len(passed),'passed;',len(failed),'failed;',len(skipped),'skipped;',len(unknown),'outside bounded replay')
