import pathlib,json,difflib,subprocess,time,os,re
root=pathlib.Path('/workspace/adamic'); ev=root/'review/test-audit/stage1-cohere-lint-shards'; path=root/'stage1/cohere/lint/shards/shards.go'; original=path.read_text(); (ev/'original.go.txt').write_text(original)
menu=[('C1','var casePrefix = []byte("case ")','var casePrefix = []byte("CASE ")','change prefix constant'),('C2','blocks[number] = output[start:end]','blocks[number+1] = output[start:end]','off-by-one block key'),('C3','if _, seen := blocks[number]; seen {','if _, seen := blocks[number]; seen && false {','flip duplicate condition'),('C4','&& isCaseLine(output[search:])','','drop whole-line condition'),('C5','return digits > 0 &&','return digits >= 0 &&','off-by-one digit bound'),('C6',"rest[digits] <= '9'","rest[digits] <= '8'",'change digit upper bound'),('C7','blocks[number] = output[start:end]','blocks[number] = output[start:end-1]','off-by-one block slice'),('C8','if len(blocks) != rows {','if false {','flip case-count condition'),('C9',"rest[digits] == '\\n'","rest[digits] != '\\n'",'flip line terminator condition')]
records=[]
for mid,old,new,kind in menu:
 assert original.count(old)==1
 changed=original.replace(old,new); line=original[:original.index(old)].count('\n')+1; records.append(dict(id=mid,line=line,old=old,new=new,menu=kind))
 (ev/(mid+'.diff')).write_text(''.join(difflib.unified_diff(original.splitlines(True),changed.splitlines(True),fromfile='a/stage1/cohere/lint/shards/shards.go',tofile='b/stage1/cohere/lint/shards/shards.go')))
start=original.index('func Merge('); end=original.index('\n// isCaseLine',start); old=original[start:end]; new=old[:old.index('{')+1]+'\n return nil, nil\n}\n'; records.append(dict(id='P1',line=85,old=old,new=new,menu='empty Merge body'))
(ev/'P1.diff').write_text(''.join(difflib.unified_diff(original.splitlines(True),original.replace(old,new).splitlines(True),fromfile='a/stage1/cohere/lint/shards/shards.go',tofile='b/stage1/cohere/lint/shards/shards.go')))
(ev/'menu.json').write_text(json.dumps(records,indent=2)); (ev/'functions.txt').write_text('Reached package functions: Merge and isCaseLine. Run is not reached by any test. Three separate rows assert reordering, preservation of non-case lines, and missing/repeated/malformed/extra input rejection. Nine construction mutations fixed before observing results; no port, oracle or test edits.\n')
