"use strict";
const fs=require("node:fs"),path=require("node:path"),assert=require("node:assert/strict"),vm=require("node:vm"),ts=require("typescript");
const [tree,builtModule,output]=process.argv.slice(2),runtime=require(path.resolve(builtModule));
const source=file=>ts.createSourceFile(file,fs.readFileSync(path.join(tree,"src/compiler",file),"utf8"),ts.ScriptTarget.Latest,true);
const functions=(s,names)=>names.map(name=>{const matches=s.statements.filter(n=>ts.isFunctionDeclaration(n)&&n.name?.text===name);assert.equal(matches.length,1,name);return matches[0].getText(s).replace(/^export /,"");}).join("\n");
const config=source("commandLineParser.ts");
const predicate=vm.runInNewContext(ts.transpileModule(functions(config,["isNullOrUndefined","isCompilerOptionsValue"])+"\nisCompilerOptionsValue;",{compilerOptions:{target:ts.ScriptTarget.ESNext}}).outputText,{...runtime});
assert.equal(predicate({type:"list",element:{type:"string"}},[{}]),true,"existing option predicate does not check list elements");
assert.equal(runtime.readJson("package.json",{readFile:()=>"7"}),7,"declared object reader returns scalar JSON");
assert.equal(runtime.convertToObject(runtime.parseJsonText("input.json","7"),[]),7,"public converter returns scalar");
const utility=source("utilities.ts"),constructors=vm.runInNewContext(ts.transpileModule(functions(utility,["Node","Token","Identifier","Type"])+"\n({Node,Token,Identifier,Type});",{compilerOptions:{target:ts.ScriptTarget.ESNext}}).outputText,{...runtime});
const node=new constructors.Node(0,0,0),token=new constructors.Token(0,0,0),identifier=new constructors.Identifier(0,0,0),type=new constructors.Type(0);
assert.equal(node.parent,undefined);assert.equal(token.parent,undefined);assert(!Object.hasOwn(token,"modifierFlagsCache"));assert(!Object.hasOwn(identifier,"escapedText"));assert(!Object.hasOwn(type,"symbol"));assert(!Object.hasOwn(type,"id"));
const input=runtime.createSourceFile("x.ts","let x = 1",runtime.ScriptTarget.Latest),extra=new Date(1);input.pluginField=extra;const cloned=runtime.factory.cloneNode(input);assert.strictEqual(cloned.pluginField,extra,"actual SourceFile copy preserves an external enumerable extension");
const compile=text=>vm.runInNewContext(ts.transpileModule(text,{compilerOptions:{target:ts.ScriptTarget.ESNext}}).outputText,{...runtime});
const mutants=[];
const predicateText=functions(config,["isNullOrUndefined","isCompilerOptionsValue"]);assert(predicateText.includes("return isArray(value);"));
assert.throws(()=>assert.equal(compile(predicateText.replace("return isArray(value);","return false;")+"\nisCompilerOptionsValue;")({type:"list"},[{}]),true),assert.AssertionError);mutants.push({change:"actual list predicate returns false",caughtBy:"existing acceptance counterexample"});
const readText=functions(utility,["readJsonOrUndefined","readJson","tryParseJson"]);assert(readText.includes("return JSON.parse(text);"));
assert.throws(()=>assert.equal(compile(readText.replace("return JSON.parse(text);","return {};")+"\nreadJson;")("package.json",{readFile:()=>"7"}),7),assert.AssertionError);mutants.push({change:"actual strict JSON parser substitutes an empty object",caughtBy:"primitive reader counterexample"});
const nodeText=functions(utility,["Node"]);assert(nodeText.includes("this.parent = undefined!;"));
assert.throws(()=>assert.equal(new (compile(nodeText.replace("this.parent = undefined!;","this.parent = {} as Node;")+"\nNode;"))(0,0,0).parent,undefined),assert.AssertionError);mutants.push({change:"actual header initializes a parent object",caughtBy:"absent parent observation"});
const typeText=functions(utility,["Type"]);assert(typeText.includes("this.flags = flags;"));
assert.throws(()=>assert(!Object.hasOwn(new (compile(typeText.replace("this.flags = flags;","this.flags = flags; this.symbol = {};")+"\nType;"))(0),"symbol")),assert.AssertionError);mutants.push({change:"actual Type header initializes symbol",caughtBy:"missing symbol observation"});
const evidence={mutants,observations:{optionListOfObjectsAccepted:true,objectReaderReturnsNumber:7,publicConverterReturnsNumber:7,nodeParent: "undefined",tokenModifierCache:"absent",identifierEscapedText:"absent",typeSymbol:"absent",typeId:"absent",sourceFileExternalEnumerableExtensionPreserved:true},interpretation:"JSON has a recursive static union. Public API sanctions, staged owner contracts and unvalidated option predicates require decisions; these observations do not establish impossibility."};fs.writeFileSync(output,JSON.stringify(evidence,null,2)+"\n");console.log(JSON.stringify(evidence));
