// TypeScript 6.0.3 source evidence. Unknown effects remain unknown, never complete.
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const ts = require(process.env.TYPESCRIPT_API || '/workspace/cache/tsc-census/npm/node_modules/typescript');
const root = path.resolve(process.argv[2]);
const out = path.resolve(process.argv[3]);
const config = ts.readConfigFile(path.join(root, 'src/compiler/tsconfig.json'), ts.sys.readFile);
if (config.error) throw Error(ts.flattenDiagnosticMessageText(config.error.messageText, '\n'));
const parsed = ts.parseJsonConfigFileContent(config.config, ts.sys, path.join(root, 'src/compiler'), undefined, path.join(root, 'src/compiler/tsconfig.json'));
let host;
if(process.env.SCOUT_SELFTEST){host=ts.createCompilerHost(parsed.options);const get=host.getSourceFile;host.getSourceFile=(name,...rest)=>{if(name.endsWith('/factory/proofs.ts'))return ts.createSourceFile(name,fs.readFileSync(process.env.SCOUT_SELFTEST,'utf8'),ts.ScriptTarget.Latest,true,ts.ScriptKind.TS);return get(name,...rest);};}
const program = ts.createProgram(parsed.fileNames, parsed.options,host);
const checker = program.getTypeChecker();
const files = program.getSourceFiles().filter(s => s.fileName.includes('/src/compiler/factory/') || s.fileName.endsWith('/src/compiler/parser.ts'));
const utilities = program.getSourceFile(path.join(root, 'src/compiler/utilities.ts'));
function where(n) { const s=n.getSourceFile(), p=s.getLineAndCharacterOfPosition(n.getStart(s)); return {file:path.relative(root,s.fileName),line:p.line+1,column:p.character+1}; }
function walk(n, fn) { fn(n); ts.forEachChild(n, c=>walk(c,fn)); }
function unwrap(n) { while(n && (ts.isAsExpression(n)||ts.isTypeAssertionExpression(n)||ts.isParenthesizedExpression(n)||ts.isNonNullExpression(n)||ts.isSatisfiesExpression(n))) n=n.expression; return n; }
function symbol(n) { return n && checker.getSymbolAtLocation(n); }
function constrained(t) { return checker.getBaseConstraintOfType(t)||t; }
function isNode(t) { if(!t) return false; t=constrained(t); if(t.isUnion())return t.types.some(isNode); const p=checker.getPropertiesOfType(t).map(s=>s.name);return ['kind','pos','end'].every(k=>p.includes(k)); }
function functionName(n) { if(n.name)return n.name.getText(); if(ts.isVariableDeclaration(n.parent)) return n.parent.name.getText(); if(ts.isPropertyAssignment(n.parent))return n.parent.name.getText(); return '<anonymous@'+where(n).line+':'+where(n).column+'>'; }
function members(t) { t=constrained(t); const parts=t.isUnion()?t.types.filter(isNode):[t]; const result=new Map(); for(const part of parts){for(const p of checker.getPropertiesOfType(constrained(part))){ if(p.flags&ts.SymbolFlags.Optional)continue; const d=p.valueDeclaration||p.declarations?.[0]; if(!d)continue; const pt=checker.getTypeOfSymbolAtLocation(p,d); const key=p.name; if(!result.has(key))result.set(key,{name:key,type:checker.typeToString(pt),declaration:where(d),phantom:/^_.*Brand$/.test(key),allowsUndefined:!!(pt.flags&ts.TypeFlags.Undefined)||(pt.isUnion()&&pt.types.some(x=>x.flags&ts.TypeFlags.Undefined)),unionMembers:[]});result.get(key).unionMembers.push(checker.typeToString(part)); }}return [...result.values()].sort((a,b)=>a.name.localeCompare(b.name)); }
const functions=[], byDeclaration=new Map(), byName=new Map();
for(const sf of files){walk(sf,n=>{if(!ts.isFunctionLike(n)||!n.body)return;const sig=checker.getSignatureFromDeclaration(n);if(!sig)return;const rt=checker.getReturnTypeOfSignature(sig), name=functionName(n);const f={n,name,rt,nodeResult:isNode(rt),id:path.relative(root,sf.fileName)+':'+where(n).line+':'+where(n).column,location:where(n),parser:sf.fileName.endsWith('/parser.ts')};functions.push(f);byDeclaration.set(n,f);if(!byName.has(name))byName.set(name,[]);byName.get(name).push(f);});}
const selected = functions.filter(f => f.nodeResult || f.n.parameters.some(p=>isNode(checker.getTypeAtLocation(p))) || /^create|^update/.test(f.name) && !f.parser || /^createBase|^finishNode$/.test(f.name));
const baseWrites={};
walk(utilities,n=>{if(ts.isFunctionDeclaration(n)&&['Node','Token','Identifier'].includes(n.name?.text)){const writes=[];walk(n.body,x=>{if(ts.isBinaryExpression(x)&&x.operatorToken.kind===ts.SyntaxKind.EqualsToken&&ts.isPropertyAccessExpression(unwrap(x.left))&&unwrap(unwrap(x.left).expression).kind===ts.SyntaxKind.ThisKeyword){writes.push({field:unwrap(x.left).name.text,undefined:unwrap(x.right)?.kind===ts.SyntaxKind.Identifier&&unwrap(x.right).text==='undefined',location:where(x),expression:x.right.getText()});}});baseWrites[n.name.text]=writes;}});
const summaries=new Map(), analyses=new Map();
function resolveCall(n) { const sig=checker.getResolvedSignature(n);let f=sig&&byDeclaration.get(sig.declaration);if(f)return f;const e=unwrap(n.expression),name=ts.isPropertyAccessExpression(e)?e.name.text:ts.isIdentifier(e)?e.text:'';const candidates=(byName.get(name)||[]).filter(x=>x.nodeResult&&!x.parser); if(candidates.length===1)return candidates[0];return undefined; }
function clone(s) {return {env:new Map([...s.env].map(([k,v])=>[k,new Set(v)])),heap:new Map([...s.heap].map(([k,v])=>[k,{...v,written:new Set(v.written),undefined:new Set(v.undefined)}]))};}
function merge(a,b) { if(!a)return b;if(!b)return a;const s=clone(a);for(const [k,v]of b.env)s.env.set(k,new Set([...(s.env.get(k)||[]),...v]));for(const[k,v]of b.heap){const u=s.heap.get(k);if(!u){s.heap.set(k,{...v,written:new Set(v.written),undefined:new Set(v.undefined)});continue;}u.written=new Set([...u.written].filter(x=>v.written.has(x)));u.undefined=new Set([...u.undefined,...v.undefined]);u.escaped||=v.escaped;}return s;}
function analyze(f, detailed=false){
 let state={env:new Map(),heap:new Map()},sequence=0;
 const writes=[],escapes=[],returns=[],gaps=[],creations=[];
 function make(n,s,fields=[],undefinedFields=[],origin='unknown') {const id=f.id+'#'+n.pos; if(!s.heap.has(id)){s.heap.set(id,{written:new Set(fields),undefined:new Set(undefinedFields),escaped:false,origin,location:where(n)});creations.push({id,origin,location:where(n),type:checker.typeToString(checker.getTypeAtLocation(n))});}return new Set([id]);}
 for(const p of f.n.parameters){if(isNode(checker.getTypeAtLocation(p))){const v=make(p,state,[],[],'parameter');state.env.set(symbol(p.name),v);for(const id of v)state.heap.get(id).escaped=true;}}
 function escape(ids,n,kind,s){for(const id of ids){const o=s.heap.get(id);if(!o)continue;escapes.push({object:id,kind,location:where(n),first:!o.escaped,written:[...o.written].sort(),undefined:[...o.undefined].sort(),sequence:sequence++});o.escaped=true;}}
 function expr(n,s){n=unwrap(n);if(!n)return new Set();if(ts.isIdentifier(n))return new Set(s.env.get(symbol(n))||[]);
  if(ts.isPropertyAccessExpression(n)||ts.isElementAccessExpression(n)){expr(n.expression,s);if(ts.isElementAccessExpression(n))expr(n.argumentExpression,s);return new Set();}
  if(ts.isConditionalExpression(n)){expr(n.condition,s);const a=clone(s),b=clone(s),av=expr(n.whenTrue,a),bv=expr(n.whenFalse,b),m=merge(a,b);s.env=m.env;s.heap=m.heap;return new Set([...av,...bv]);}
  if(ts.isBinaryExpression(n)){
   const op=n.operatorToken.kind;
   if(op>=ts.SyntaxKind.FirstAssignment&&op<=ts.SyntaxKind.LastAssignment){const left=unwrap(n.left);if(ts.isPropertyAccessExpression(left)||ts.isElementAccessExpression(left)){const ids=expr(left.expression,s),rhs=expr(n.right,s),field=ts.isPropertyAccessExpression(left)?left.name.text:ts.isStringLiteral(left.argumentExpression)?left.argumentExpression.text:'<computed>';for(const id of ids){const o=s.heap.get(id);const plain=op===ts.SyntaxKind.EqualsToken;writes.push({object:id,field,location:where(n),afterEscape:o.escaped,definiteAssignment:plain,expression:n.right.getText(),sequence:sequence++});if(plain){o.written.add(field);if(unwrap(n.right)?.kind===ts.SyntaxKind.Identifier&&unwrap(n.right).text==='undefined')o.undefined.add(field);else o.undefined.delete(field);}}escape(rhs,n,'store',s);return rhs;}const rhs=expr(n.right,s);if(ts.isIdentifier(left)){const sym=symbol(left);if(s.env.has(sym)||sym?.declarations?.some(d=>d.pos>=f.n.pos&&d.end<=f.n.end))s.env.set(sym,rhs);else escape(rhs,n,'store',s);}return rhs;}
   const a=expr(n.left,s);if([ts.SyntaxKind.AmpersandAmpersandToken,ts.SyntaxKind.BarBarToken,ts.SyntaxKind.QuestionQuestionToken].includes(op)){const skipped=clone(s),b=expr(n.right,s),m=merge(skipped,s);s.env=m.env;s.heap=m.heap;return new Set([...a,...b]);}const b=expr(n.right,s);return op===ts.SyntaxKind.CommaToken?b:new Set();
  }
  if(ts.isCallExpression(n)||ts.isNewExpression(n)){
   expr(n.expression,s);const args=(n.arguments||[]).map(a=>expr(a,s));for(const a of args)escape(a,n,'passed',s);
   if(ts.isCallExpression(n)&&/^(setTextRangePosEnd|setTextRangePosWidth|setTextRangePos|setTextRangeEnd)$/.test(n.expression.getText())){const names=n.expression.getText()==='setTextRangePos'?['pos']:n.expression.getText()==='setTextRangeEnd'?['end']:['pos','end'];for(const id of args[0]||[]){const o=s.heap.get(id);for(const field of names){o.written.add(field);o.undefined.delete(field);writes.push({object:id,field,location:where(n),afterEscape:o.escaped,definiteAssignment:true,expression:'audited '+n.expression.getText()+' helper',sequence:sequence++});}}return args[0]||new Set();}
   const callee=ts.isCallExpression(n)&&resolveCall(n),summary=callee&&summaries.get(callee.id);
   const name=n.expression.getText();
   // A summary certifies only return writes. Passing an existing node remains an escape.
   if(summary&&isNode(checker.getTypeAtLocation(n)))return make(n,s,summary.written,summary.undefined,'call:'+callee.id);
   if(ts.isNewExpression(n)&&isNode(checker.getTypeAtLocation(n))){const ctor=/TokenConstructor/.test(name)?'Token':/IdentifierConstructor/.test(name)&&!name.includes('Private')?'Identifier':'Node';const ws=baseWrites[ctor]||[];return make(n,s,ws.map(w=>w.field),ws.filter(w=>w.undefined).map(w=>w.field),'default-allocator:'+ctor);}
   // Supplied BaseNodeFactory is virtual. The default profile is explicitly conditional on the stock allocator.
   if(ts.isCallExpression(n)&&/\.createBase(SourceFileNode|IdentifierNode|PrivateIdentifierNode|TokenNode|Node)$/.test(name)){const ctor=/TokenNode$/.test(name)?'Token':/IdentifierNode$/.test(name)&&!name.includes('Private')?'Identifier':'Node',ws=baseWrites[ctor];return make(n,s,ws.map(w=>w.field),ws.filter(w=>w.undefined).map(w=>w.field),'default-base-factory:'+ctor);}
   if(isNode(checker.getTypeAtLocation(n))){gaps.push({kind:'unknown-node-call',location:where(n),expression:n.getText()});return make(n,s,[],[],'unknown-call');}return new Set();
  }
  if(ts.isObjectLiteralExpression(n)){const fields=[],undef=[];for(const p of n.properties){if(ts.isPropertyAssignment(p)||ts.isShorthandPropertyAssignment(p)){const e=ts.isPropertyAssignment(p)?p.initializer:p.name;const ids=expr(e,s);escape(ids,p,'stored-in-object',s);fields.push(p.name.getText().replace(/^['"]|['"]$/g,''));if(unwrap(e)?.getText()==='undefined')undef.push(fields.at(-1));}else if(ts.isSpreadAssignment(p))escape(expr(p.expression,s),p,'spread',s);}return isNode(checker.getTypeAtLocation(n))?make(n,s,fields,undef,'literal'):new Set();}
  if(ts.isArrayLiteralExpression(n)){for(const e of n.elements)escape(expr(e,s),e,'stored-in-array',s);return new Set();}
  if(ts.isFunctionExpression(n)||ts.isArrowFunction(n)){const captured=new Set();walk(n.body,x=>{if(ts.isIdentifier(x))for(const id of s.env.get(symbol(x))||[])captured.add(id);});escape(captured,n,'captured-by-closure',s);return new Set();}
  ts.forEachChild(n,c=>{expr(c,s);});return new Set();
 }
 function block(stmts,s){for(const n of stmts){if(!s)break;s=stmt(n,s);}return s;}
 function stmt(n,s){if(ts.isBlock(n))return block(n.statements,s);
  if(ts.isVariableStatement(n)){for(const d of n.declarationList.declarations){const ids=expr(d.initializer,s);if(ts.isIdentifier(d.name))s.env.set(symbol(d.name),ids);else{escape(ids,d,'destructured-unknown',s);gaps.push({kind:'destructuring',location:where(d)});}}return s;}
  if(ts.isExpressionStatement(n)){expr(n.expression,s);return s;}
  if(ts.isReturnStatement(n)){const ids=expr(n.expression,s);for(const id of ids){const o=s.heap.get(id);returns.push({object:id,location:where(n),written:[...o.written].sort(),undefined:[...o.undefined].sort(),origin:o.origin});}if(!ids.size&&isNode(f.rt)){gaps.push({kind:'untracked-return',location:where(n),expression:n.expression?.getText()});returns.push({object:null,location:where(n),written:[],undefined:[],origin:'unknown'});}escape(ids,n,'returned',s);return null;}
  if(ts.isIfStatement(n)){expr(n.expression,s);return merge(stmt(n.thenStatement,clone(s)),n.elseStatement?stmt(n.elseStatement,clone(s)):clone(s));}
  if(ts.isSwitchStatement(n)){expr(n.expression,s);let joined=n.caseBlock.clauses.some(ts.isDefaultClause)?null:clone(s);for(const c of n.caseBlock.clauses){const b=clone(s);if(c.expression)expr(c.expression,b);joined=merge(joined,block(c.statements,b));}return joined;}
  if(ts.isForStatement(n)||ts.isForOfStatement(n)||ts.isForInStatement(n)||ts.isWhileStatement(n)||ts.isDoStatement(n)){gaps.push({kind:'loop-not-proven',location:where(n)});if(n.initializer)expr(n.initializer,s);if(n.expression)expr(n.expression,s);if(n.condition)expr(n.condition,s);const b=stmt(n.statement,clone(s));if(b&&n.incrementor)expr(n.incrementor,b);return merge(s,b);}
  if(ts.isThrowStatement(n)){escape(expr(n.expression,s),n,'thrown',s);return null;}
  if(ts.isFunctionDeclaration(n))return s;
  if(ts.isBreakStatement(n)||ts.isContinueStatement(n)){gaps.push({kind:'abrupt-control-not-proven',location:where(n)});return s;}
  if(ts.isTryStatement(n)){gaps.push({kind:'try-not-proven',location:where(n)});let m=merge(stmt(n.tryBlock,clone(s)),n.catchClause?stmt(n.catchClause.block,clone(s)):clone(s));return m&&n.finallyBlock?stmt(n.finallyBlock,m):m;}
  expr(n,s);return s;
 }
 if(ts.isBlock(f.n.body))block(f.n.body.statements,state);else{const ids=expr(f.n.body,state);for(const id of ids){const o=state.heap.get(id);returns.push({object:id,location:where(f.n.body),written:[...o.written],undefined:[...o.undefined],origin:o.origin});}escape(ids,f.n.body,'returned',state);}
 const guaranteed=returns.length?returns.reduce((a,r)=>a.filter(x=>r.written.includes(x)),returns[0].written):[];
 const undefinedFields=[...new Set(returns.flatMap(r=>r.undefined))];
 // Any unsupported control form disables propagation and completeness claims.
 const unsupported=gaps.some(g=>g.kind!=='unknown-node-call'&&g.kind!=='untracked-return');
 const summary={written:unsupported?[]:guaranteed.sort(),undefined:undefinedFields.sort()};
 if(detailed)return {summary,writes,escapes,returns,gaps,creations};return summary;
}
let rounds=0;for(;rounds<24;rounds++){let changed=false;for(const f of functions.filter(f=>f.nodeResult)){const next=analyze(f),prior=summaries.get(f.id);if(JSON.stringify(next)!==JSON.stringify(prior)){summaries.set(f.id,next);changed=true;}}if(!changed)break;}if(rounds===24)throw Error('summary fixed point did not settle');
const ledger=[];
for(const f of selected){const a=analyze(f,true);analyses.set(f.id,a);const required=f.nodeResult?members(f.rt):[...new Map(f.n.parameters.filter(p=>isNode(checker.getTypeAtLocation(p))).flatMap(p=>members(checker.getTypeAtLocation(p))).map(p=>[p.name,p])).values()];const first=a.escapes.filter(e=>e.first);const returned=new Set(a.returns.map(r=>r.object).filter(Boolean));const resultEscapes=first.filter(e=>returned.has(e.object));const unsupported=a.gaps.some(g=>!['unknown-node-call','untracked-return'].includes(g.kind));
 const fields=required.map(p=>{const ws=a.writes.filter(w=>w.field===p.name),before=resultEscapes.length>0&&resultEscapes.every(e=>e.written.includes(p.name)),atReturn=a.returns.length>0&&a.returns.every(r=>r.written.includes(p.name));const undefinedBefore=resultEscapes.some(e=>e.undefined.includes(p.name))&&!p.allowsUndefined;return {...p,status:p.phantom?'phantom-type-brand':unsupported?'unresolved-control':before&&!undefinedBefore?'definitely-written-before-escape':before&&undefinedBefore?'written-undefined-before-escape':atReturn?'written-by-return-after-earlier-escape':ws.length?'conditional-or-path-incomplete-write':'no-proven-write',writes:ws.map(w=>({location:w.location,afterEscape:w.afterEscape,definiteAssignment:w.definiteAssignment,expression:w.expression})),allocatorEvidence:Object.values(baseWrites).flat().filter(w=>w.field===p.name),calleeEvidence:a.creations.filter(c=>c.origin.startsWith('call:')).map(c=>({callee:c.origin.slice(5),location:c.location,guaranteed:(summaries.get(c.origin.slice(5))?.written||[]).includes(p.name)})).filter(c=>c.guaranteed),returnEvidence:a.returns.filter(r=>r.written.includes(p.name)).map(r=>r.location)};});
 const runtime=fields.filter(p=>!p.phantom), withoutParent=runtime.filter(p=>p.name!=='parent');
 const complete=list=>f.nodeResult&&list.length>0&&list.every(p=>p.status==='definitely-written-before-escape');
 ledger.push({id:f.id,name:f.name,location:f.location,endLine:where(f.n.body).line+f.n.body.getText().split('\n').length-1,parser:f.parser,nodeResult:f.nodeResult,nodeType:checker.typeToString(f.rt),factoryName:/^create|^update/.test(f.name),classification:!f.nodeResult?'non-node-builder':a.creations.some(c=>c.origin==='literal'||c.origin.startsWith('default-'))?'allocating':a.creations.some(c=>c.origin.startsWith('call:'))?'composed-or-forwarding':'input-or-unresolved',completeBeforeEscape:complete(runtime),completeApartFromParent:complete(withoutParent),requiredFields:fields,...a});}
const parserPaths=[];const parser=files.find(s=>s.fileName.endsWith('/parser.ts'));
walk(parser,n=>{if(ts.isCallExpression(n)){const name=ts.isPropertyAccessExpression(n.expression)?n.expression.name.text:ts.isIdentifier(n.expression)?n.expression.text:'';if(name==='finishNode'||name.startsWith('createBase')){const t=checker.getTypeAtLocation(n);parserPaths.push({operation:name,location:where(n),nodeType:checker.typeToString(t),expression:n.getText(),requiredFields:isNode(t)?members(t):[],callee:resolveCall(n)?.id||null});}}});
const phaseWrites=[];
for(const sf of program.getSourceFiles().filter(s=>s.fileName.startsWith(path.join(root,'src/compiler')+'/'))){walk(sf,n=>{if(!ts.isBinaryExpression(n)||n.operatorToken.kind<ts.SyntaxKind.FirstAssignment||n.operatorToken.kind>ts.SyntaxKind.LastAssignment)return;const lhs=unwrap(n.left);if(!ts.isPropertyAccessExpression(lhs)||!isNode(checker.getTypeAtLocation(lhs.expression)))return;const ps=checker.getSymbolAtLocation(lhs.name);if(!ps||ps.flags&ts.SymbolFlags.Optional)return;phaseWrites.push({field:lhs.name.text,location:where(n),receiverType:checker.typeToString(checker.getTypeAtLocation(lhs.expression)),expression:n.getText(),undefined:unwrap(n.right)?.getText()==='undefined',plainAssignment:n.operatorToken.kind===ts.SyntaxKind.EqualsToken});});}
const allFunctions=functions.map(f=>({id:f.id,name:f.name,location:f.location,nodeResult:f.nodeResult,nodeType:checker.typeToString(f.rt),included:selected.includes(f)}));
const factoryNodes=ledger.filter(f=>!f.parser&&f.nodeResult&&f.factoryName);
const afterWrites=ledger.flatMap(f=>f.writes.filter(w=>w.afterEscape).map(w=>({function:f.id,...w,required:f.requiredFields.some(p=>!p.phantom&&p.name===w.field)})));
const uniqueAfter=new Map(afterWrites.map(w=>[w.location.file+':'+w.location.line+':'+w.location.column+':'+w.field,w]));
const manifest=files.concat([utilities,program.getSourceFile(path.join(root,'src/compiler/types.ts'))]).map(sf=>({file:path.relative(root,sf.fileName),bytes:Buffer.byteLength(sf.text),sha256:crypto.createHash('sha256').update(sf.text).digest('hex'),lines:sf.text.split('\n').length}));
const deferredFields=factoryNodes.flatMap(f=>f.requiredFields.filter(p=>!p.phantom&&p.status==='written-undefined-before-escape').map(p=>({factory:f.id,field:p.name,declaration:p.declaration,writes:p.writes})));
const counts={deferredRequiredFactoryFieldPairs:deferredFields.length,distinctDeferredRequiredFieldNames:new Set(deferredFields.map(p=>p.field)).size,apiVersion:ts.version,fixedPointRounds:rounds,files:files.length,allCallableBodies:functions.length,factoryNodeBuilders:factoryNodes.length,factoryCompleteBeforeEscape:factoryNodes.filter(f=>f.completeBeforeEscape).length,factoryCompleteApartFromParent:factoryNodes.filter(f=>f.completeApartFromParent).length,factoryAllRequiredSlotsWrittenBeforeEscape:factoryNodes.filter(f=>f.requiredFields.filter(p=>!p.phantom).every(p=>['definitely-written-before-escape','written-undefined-before-escape'].includes(p.status))).length,allNodeProducingBodies:ledger.filter(f=>f.nodeResult).length,parserNodeProducingBodies:ledger.filter(f=>f.nodeResult&&f.parser).length,parserBaseAndFinishCalls:parserPaths.length,parserFinishCalls:parserPaths.filter(p=>p.operation==='finishNode').length,afterEscapeWriteSites:uniqueAfter.size,requiredAfterEscapeWriteSites:[...uniqueAfter.values()].filter(w=>w.required).length,conditionalRequiredFields:factoryNodes.reduce((n,f)=>n+f.requiredFields.filter(p=>p.status==='conditional-or-path-incomplete-write').length,0),upstreamDiagnostics:ts.getPreEmitDiagnostics(program).map(d=>({code:d.code,location:d.file?{file:path.relative(root,d.file.fileName),line:d.file.getLineAndCharacterOfPosition(d.start).line+1}:null,message:ts.flattenDiagnosticMessageText(d.messageText,'\n')}))};
fs.mkdirSync(out,{recursive:true});for(const [name,value]of Object.entries({factories:ledger,functions:allFunctions,parser_paths:parserPaths,after_escape:[...uniqueAfter.values()],source_manifest:manifest,allocator_writes:baseWrites,phase_writes:phaseWrites,deferred_fields:deferredFields,counts}))fs.writeFileSync(path.join(out,name+'.json'),JSON.stringify(value,null,2)+'\n');
console.log(JSON.stringify(counts,null,2));
