package oracle

import (
	"flag"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"syscall"
	"testing"

	"github.com/system-inc/adamic/internal/native"
)

// updateCounts rewrites counts.md with what was measured: go test ./internal/oracle -run TestCounts -args -update-counts
var updateCounts = flag.Bool("update-counts", false, "rewrite counts.md with the counts this run measured")

// countsPath is the checked-in table of every fixture's counts.
const countsPath = "counts.md"

const countsHeader = `# Counts

Every oracle fixture, input fixtures included, built counted (` + "`adamic build --count`" + `, runtime/count.h) and run once. Counts are deterministic, so a
change to how Adamic counts references shows here as a change of numbers, in review. Allocations and frees are heap values (strings,
objects, arrays, maps, cells, closures); retains and releases are calls to adamic_retain and adamic_release; peak is the most heap
values live at once; in regions is the values let go of with their region (runtime/region.c) rather than freed one at a time, so a
finished program's allocations are its frees and its values in regions. A fixture that panics is counted where it stopped; an input
fixture runs as TestInputAgreesWithNode runs it, a directory of its own to write in included, and must finish. Every run has an
8 MiB stack (ulimit -s 8192), so a fixture's counts never depend on the stack of whoever runs it. This is the baseline borrow
inference and reuse in place are measured against (docs/memory.md).

Not counted, though the oracle runs it as it runs every fixture: internal/oracle/testdata/stack_overflow.a, which recurses until
the stack runs out, so its allocations measure how deep it got, and every change to a frame's size moves them.

Generated by TestCountsAreRecorded; after a change that moves them, run
` + "`go test ./internal/oracle -run TestCountsAreRecorded -args -update-counts`" + ` and commit the diff.

| Fixture | Allocations | Frees | Retains | Releases | Peak live | In regions |
|---|---:|---:|---:|---:|---:|---:|
`

// countsLine is the line a counted build writes last to stderr (runtime/count.c).
var countsLine = regexp.MustCompile(`(?m)^adamic: counts: allocations (\d+) frees (\d+) retains (\d+) releases (\d+) peak (\d+) regions (\d+)\n\z`)

// pinnedStack is a command run with an 8 MiB stack, whatever the stack of whoever runs the test: a
// fixture that recurses until the stack runs out is counted at the depth it reached, which moves with
// the stack's size (ulimit -s), and the table has to be the same on every machine. The shell's ulimit
// is POSIX's, on Linux and macOS alike; where the hard limit won't allow 8 MiB, it fails out loud.
func pinnedStack(name string, arguments ...string) (string, []string) {
	return "/bin/sh", append([]string{"-c", `ulimit -s 8192 && exec "$0" "$@"`, name}, arguments...)
}

// uncounted is the fixtures the table leaves out, each for the reason the table's header gives: a
// count that measures something other than counting.
var uncounted = map[string]bool{
	"internal/oracle/testdata/stack_overflow.a": true,
}

// counted builds a lowered fixture counted, runs it, and returns its row of the table. An input
// fixture runs as TestInputAgreesWithNode runs it: from its own directory, with its arguments, a
// directory of its own to write in when it writes, and as nobody when the test is root. It must
// finish, as it must there, so its row counts the whole program and not where it stopped.
func counted(t *testing.T, path string, input bool, arguments []string, unreadable bool, writes bool) string {
	t.Helper()
	absolute, err := filepath.Abs(filepath.Join(repository, path))
	if err != nil {
		t.Fatal(err)
	}
	program, err := lowered(t, absolute)
	if err != nil {
		t.Fatalf("Lower: %v", err)
	}
	given := identity(t)
	context := cacheKey(given.context, path, fmt.Sprint(input, unreadable, writes), cacheKey(arguments...))
	if input {
		context = cacheKey(context, inputIdentity(t))
	}
	key := nativeResultKey(native.C(program), given.libraries[2], given.nodeVersion, context)
	executeCounted := func() recordedRun {
		var result run
		if input {
			shared := sharedDirectory(t)
			how := inputRun{directory: filepath.Dir(absolute), arguments: arguments}
			if os.Geteuid() == 0 {
				how.credential = &syscall.Credential{Uid: 65534, Gid: 65534}
			}
			if unreadable {
				path := filepath.Join(shared, "unreadable.txt")
				if err := os.WriteFile(path, []byte("secret\n"), 0o000); err != nil {
					t.Fatal(err)
				}
				how.arguments = append(append([]string{}, how.arguments...), path)
			}
			if writes {
				how.arguments = append([]string{writable(t, shared, "counted")}, how.arguments...)
			}
			if strings.HasPrefix(path, "internal/oracle/testdata/node_fs_file_") {
				how = fsFilePrepare(t, shared, "counted")
			}
			binary := filepath.Join(shared, "program")
			if err := native.Build(native.C(program), binary, native.Options{Count: true}); err != nil {
				t.Fatal(err)
			}
			name, pinned := pinnedStack(binary, how.arguments...)
			result = executeInput(t, how, nil, name, pinned...)
			if result.exitCode != 0 {
				t.Fatalf("want an input fixture's counted run to finish, as TestInputAgreesWithNode wants it to on Node: exit %d, stderr %q", result.exitCode, result.stderr)
			}
		} else {
			binary := filepath.Join(t.TempDir(), "program")
			if err := native.Build(native.C(program), binary, native.Options{Count: true}); err != nil {
				t.Fatal(err)
			}
			name, pinned := pinnedStack(binary)
			result = execute(t, name, pinned...)
		}
		return record(result)
	}
	var result run
	if *updateCounts {
		result = executeCounted().run()
	} else {
		result = cachedResult(t, given.cache, nativeResults, key, executeCounted).run()
	}
	match := countsLine.FindSubmatch(result.stderr)
	if match == nil {
		t.Fatalf("no counts at the end of stderr (exit %d): %q", result.exitCode, result.stderr)
	}
	return fmt.Sprintf("| %s | %s | %s | %s | %s | %s | %s |", path, match[1], match[2], match[3], match[4], match[5], match[6])
}

type countCase struct {
	path                                                  string
	input, unreadable, writes, defaultCompiler, predicate bool
	arguments                                             []string
}

// countCases is the complete old sweep, including the helpers formerly run in the parent.
func countCases() ([]countCase, error) {
	var cases []countCase
	for _, fixture := range fixtures {
		if fixture.lowers && !uncounted[fixture.path] {
			cases = append(cases, countCase{path: fixture.path})
		}
	}
	for _, fixture := range inputFixtures {
		cases = append(cases, countCase{path: fixture.path, input: true, arguments: fixture.arguments, unreadable: fixture.unreadable, writes: fixture.writes})
	}
	for _, fixture := range fsFileFixtures {
		cases = append(cases, countCase{path: "internal/oracle/testdata/node_fs_file_" + fixture + ".a", input: true})
	}
	for _, path := range []string{"stage3/interface-downcasts/visitor.a", "stage3/interface-downcasts/wrong-kind.a"} {
		cases = append(cases, countCase{path: path, defaultCompiler: true})
	}
	for _, name := range []string{"default-staged", "default-wrong-type", "default-wrong-boolean", "default-literal", "default-boxed-string", "default-boxed-write", "default-destructure", "default-read-before-set", "readiness-identifier", "readiness-identifier-uninitialized", "readiness-number", "readiness-number-uninitialized"} {
		cases = append(cases, countCase{path: interfaceSource(name)})
	}
	paths, err := filepath.Glob(filepath.Join(repository, "internal/lower/testdata/predicates/overload_*.a"))
	if err != nil || len(paths) == 0 {
		return nil, fmt.Errorf("predicate fixtures: %v", err)
	}
	typescript, err := filepath.Glob(filepath.Join(repository, "internal/lower/testdata/predicates/overload_*.ts"))
	if err != nil {
		return nil, err
	}
	paths = append(paths, typescript...)
	sort.Strings(paths)
	for _, path := range paths {
		relative, err := filepath.Rel(repository, path)
		if err != nil {
			return nil, err
		}
		cases = append(cases, countCase{path: filepath.ToSlash(relative), predicate: true})
	}
	return cases, nil
}

// Each fixture owns its comparison, so sharding and failures use the same unit.
func TestCountsAreRecorded(t *testing.T) {
	t.Parallel()
	identity(t) // sync.Once shares the runtime builds across all fixtures.
	cases, err := countCases()
	if err != nil {
		t.Fatal(err)
	}
	recorded, err := os.ReadFile(countsPath)
	if err != nil && !*updateCounts {
		t.Fatalf("%v: record the counts with -update-counts", err)
	}
	recordedRows := map[string]string{}
	for _, line := range strings.Split(string(recorded), "\n") {
		fields := strings.Split(line, " | ")
		if len(fields) == 7 || len(fields) == 5 {
			recordedRows[strings.TrimPrefix(fields[0], "| ")] = line
		}
	}
	// Validate the complete shape even when only a subset of leaves is selected.
	table := func(rows []string) string {
		var table strings.Builder
		table.WriteString(countsHeader)
		predicate := false
		for index, each := range cases {
			if each.predicate && !predicate {
				table.WriteString(predicateCountsHeader)
				predicate = true
			}
			table.WriteString(rows[index])
			table.WriteString("\n")
		}
		return table.String()
	}
	wanted := make([]string, len(cases))
	for index, each := range cases {
		wanted[index] = recordedRows[each.path]
	}
	if !*updateCounts && table(wanted) != string(recorded) {
		t.Error("counts.md header, fixture inventory, or order changed; record with -update-counts")
	}
	rows := make([]string, len(cases))
	if *updateCounts {
		t.Cleanup(func() {
			if t.Failed() {
				return
			}
			if err := os.WriteFile(countsPath, []byte(table(rows)), 0o644); err != nil {
				t.Fatal(err)
			}
		})
	}
	// The two default-compiler fixtures share one CLI build, rather than go run per case.
	var compilerOnce sync.Once
	compiler := filepath.Join(t.TempDir(), "adamic")
	var compilerError error
	for index, each := range cases {
		t.Run(each.path, func(t *testing.T) {
			t.Parallel()
			var row string
			switch {
			case each.predicate:
				row = predicateCountsRow(t, filepath.Join(repository, each.path))
			case each.defaultCompiler:
				compilerOnce.Do(func() {
					command := exec.Command("go", "build", "-o", compiler, "./cmd/adamic")
					command.Dir = repository
					if output, err := command.CombinedOutput(); err != nil {
						compilerError = fmt.Errorf("build default compiler: %w: %s", err, output)
					}
				})
				if compilerError != nil {
					t.Fatal(compilerError)
				}
				row = defaultInterfaceCount(t, each.path, compiler)
			default:
				row = counted(t, each.path, each.input, each.arguments, each.unreadable, each.writes)
			}
			rows[index] = row // Each leaf owns one slot; cleanup runs after all children finish.
			if !*updateCounts && recordedRows[each.path] != row {
				t.Errorf("the counts changed and %s wasn't updated (go test ./internal/oracle -run TestCountsAreRecorded -args -update-counts):\nrecorded: %s\nmeasured: %s", countsPath, recordedRows[each.path], row)
			}
		})
	}
}
