package oracle

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strings"
	"sync"
	"syscall"
	"testing"

	"github.com/system-inc/adamic/internal/native"
)

// updateCounts rewrites counts.md with what was measured: go test ./internal/oracle -run TestCounts -args -update-counts
var updateCounts = flag.Bool("update-counts", false, "rewrite counts.md with the counts this run measured")

// countsPath is the checked-in table of every fixture's counts.
const countsPath = "counts.md"

// Extra counters register source witnesses that need an explicit frontend adapter.
var additionalFixtureCounts []func(*testing.T) []string

const countsHeader = `# Counts

Every oracle fixture, input fixtures included, built counted (` + "`adamic build --count`" + `, runtime/count.h) and run once. Counts are deterministic, so a
change to how Adamic counts references shows here as a change of numbers, in review. Allocations and frees are heap values (strings,
objects, arrays, maps, cells, closures); retains and releases are calls to adamic_retain and adamic_release; peak is the most heap
values live at once; in regions is the values let go of with their region (runtime/region.c) rather than freed one at a time, so a
finished program's allocations are its frees and its values in regions. A fixture that panics is counted where it stopped; an input
fixture runs as TestInputAgreesWithNode runs it, a directory of its own to write in included, and must finish. Every run has an
8 MiB stack (ulimit -s 8192), so a fixture's counts never depend on the stack of whoever runs it. This is the baseline borrow
inference and reuse in place are measured against (docs/memory.md). Parallel fixtures run with ADAMIC_THREADS=1;
parallel peak liveness and work after an exception otherwise depend on scheduling.

Not counted, though the oracle runs it as it runs every fixture: internal/oracle/testdata/stack_overflow.a, which recurses until
the stack runs out, so its allocations measure how deep it got, and every change to a frame's size moves them.

Generated by TestCountsAreRecorded; after a change that moves them, run
` + "`go test ./internal/oracle -run TestCountsAreRecorded -args -update-counts`" + ` and commit the diff.

| Fixture | Allocations | Frees | Retains | Releases | Peak live | In regions |
|---|---:|---:|---:|---:|---:|---:|
`

// countsLine is the line a counted build writes last to stderr (runtime/count.c).
var countsLine = regexp.MustCompile(`(?m)^adamic: counts: allocations (\d+) frees (\d+) retains (\d+) releases (\d+) peak (\d+) regions (\d+)\n\z`)

// pinnedStack is a command run with an 8 MiB stack, whatever the stack of whoever runs the test: a
// fixture that recurses until the stack runs out is counted at the depth it reached, which moves with
// the stack's size (ulimit -s), and the table has to be the same on every machine. The shell's ulimit
// is POSIX's, on Linux and macOS alike; where the hard limit won't allow 8 MiB, it fails out loud.
func pinnedStack(name string, arguments ...string) (string, []string) {
	return "/bin/sh", append([]string{"-c", `ulimit -s 8192 && exec "$0" "$@"`, name}, arguments...)
}

// uncounted is the fixtures the table leaves out, each for the reason the table's header gives: a
// count that measures something other than counting.
var uncounted = map[string]bool{
	"internal/oracle/testdata/stack_overflow.a": true,
}

// counted builds a lowered fixture counted, runs it, and returns its row of the table. An input
// fixture runs as TestInputAgreesWithNode runs it: from its own directory, with its arguments, a
// directory of its own to write in when it writes, and as nobody when the test is root. It must
// finish, as it must there, so its row counts the whole program and not where it stopped.
func counted(t *testing.T, path string, input bool, arguments []string, unreadable bool, writes bool) string {
	t.Helper()
	absolute, err := filepath.Abs(filepath.Join(repository, path))
	if err != nil {
		t.Fatal(err)
	}
	program, err := lowered(t, absolute)
	if err != nil {
		t.Fatalf("Lower: %v", err)
	}
	given := identity(t)
	context := cacheKey(given.context, path, fmt.Sprint(input, unreadable, writes), cacheKey(arguments...))
	if usesParallelMap(program) {
		context = cacheKey(context, "parallel-threads-1")
	}
	if input {
		context = cacheKey(context, inputIdentity(t))
	}
	key := nativeResultKey(native.C(program), given.libraries[countedBuild], given.nodeVersion, context)
	executeCounted := func() recordedRun {
		var result run
		if input {
			shared := sharedDirectory(t)
			how := inputRun{directory: filepath.Dir(absolute), arguments: arguments}
			if os.Geteuid() == 0 {
				how.credential = &syscall.Credential{Uid: 65534, Gid: 65534}
			}
			if unreadable {
				path := filepath.Join(shared, "unreadable.txt")
				if err := os.WriteFile(path, []byte("secret\n"), 0o000); err != nil {
					t.Fatal(err)
				}
				how.arguments = append(append([]string{}, how.arguments...), path)
			}
			if writes {
				how.arguments = append([]string{writable(t, shared, "counted")}, how.arguments...)
			}
			if strings.HasPrefix(path, "internal/oracle/testdata/node_fs_file_") {
				how = fsFilePrepare(t, shared, "counted")
			}
			binary := filepath.Join(shared, "program")
			if err := native.Build(native.C(program), binary, native.Options{Count: true}); err != nil {
				t.Fatal(err)
			}
			name, pinned := pinnedStack(binary, how.arguments...)
			result = executeInput(t, how, nil, name, pinned...)
			if result.exitCode != 0 {
				t.Fatalf("want an input fixture's counted run to finish, as TestInputAgreesWithNode wants it to on Node: exit %d, stderr %q", result.exitCode, result.stderr)
			}
		} else {
			binary := filepath.Join(t.TempDir(), "program")
			if err := native.Build(native.C(program), binary, native.Options{Count: true}); err != nil {
				t.Fatal(err)
			}
			name, pinned := pinnedStack(binary)
			if path == "internal/oracle/testdata/process_observations.a" {
				// Environment observations are tested across values separately; counting must use
				// fixed inputs rather than depend on whoever runs the gate's color preferences.
				result = executeWith(t, []string{"NO_COLOR=1", "FORCE_COLOR=0", "ADAMIC_PROCESS_TEST=value", "ADAMIC_PROCESS_TEST_MISSING=missing", "ADAMIC_PROCESS_�=surrogate"}, name, pinned...)
			} else if usesParallelMap(program) {
				result = executeWith(t, []string{"ADAMIC_THREADS=1"}, name, pinned...)
			} else if path == slowRegExpFixtures[0].path {
				// The long backtracking fixture has the same three-minute bound in
				// its counted run as in its dedicated behavior and leak oracle.
				result = longRegExpRun(t, nil, name, pinned...)
			} else {
				result = execute(t, name, pinned...)
			}
		}
		return record(result)
	}
	var result run
	if *updateCounts {
		result = executeCounted().run()
	} else {
		result = cachedResult(t, given.cache, nativeResults, key, executeCounted).run()
	}
	match := countsLine.FindSubmatch(result.stderr)
	if match == nil {
		t.Fatalf("no counts at the end of stderr (exit %d): %q", result.exitCode, result.stderr)
	}
	return fmt.Sprintf("| %s | %s | %s | %s | %s | %s | %s |", path, match[1], match[2], match[3], match[4], match[5], match[6])
}

// Every fixture's counts are recorded, and a change to them fails until the table is updated with it.
func TestCountsAreRecorded(t *testing.T) {
	t.Parallel()
	fixtures := append(slices.Clone(fixtures), slowRegExpFixtures...)
	rows := make([]string, len(fixtures)+len(inputFixtures)+len(fsFileFixtures))
	var lock sync.Mutex
	t.Run("fixtures", func(t *testing.T) {
		for index, fixture := range fixtures {
			if !fixture.lowers || uncounted[fixture.path] || refusedAdamicNonNullFixture(fixture.path) {
				continue
			}
			t.Run(fixture.path, func(t *testing.T) {
				t.Parallel()
				row := counted(t, fixture.path, false, nil, false, false)
				lock.Lock()
				rows[index] = row
				lock.Unlock()
			})
		}
		for index, fixture := range inputFixtures {
			t.Run(fixture.path, func(t *testing.T) {
				t.Parallel()
				row := counted(t, fixture.path, true, fixture.arguments, fixture.unreadable, fixture.writes)
				lock.Lock()
				rows[len(fixtures)+index] = row
				lock.Unlock()
			})
		}
		for index, fixture := range fsFileFixtures {
			path := "internal/oracle/testdata/node_fs_file_" + fixture + ".a"
			t.Run(path, func(t *testing.T) {
				t.Parallel()
				row := counted(t, path, true, nil, false, false)
				lock.Lock()
				rows[len(fixtures)+len(inputFixtures)+index] = row
				lock.Unlock()
			})
		}
	})
	if t.Failed() {
		return
	}
	rows = append(rows, interfaceCastCounts(t)...)
	for _, count := range additionalFixtureCounts {
		rows = append(rows, count(t)...)
	}
	var table strings.Builder
	table.WriteString(countsHeader)
	for _, row := range rows {
		if row != "" {
			table.WriteString(row)
			table.WriteString("\n")
		}
	}
	table.WriteString(predicateCountsTable(t))
	if *updateCounts {
		if err := os.WriteFile(countsPath, []byte(table.String()), 0o644); err != nil {
			t.Fatal(err)
		}
		return
	}
	recorded, err := os.ReadFile(countsPath)
	if err != nil {
		t.Fatalf("%v: record the counts with -update-counts", err)
	}
	if string(recorded) == table.String() {
		return
	}
	// Say which rows moved, so the failure reads as the review diff will.
	recordedRows := map[string]string{}
	for _, line := range strings.Split(string(recorded), "\n") {
		if fields := strings.Split(line, " | "); len(fields) == 7 {
			recordedRows[strings.TrimPrefix(fields[0], "| ")] = line
		}
	}
	moved := []string{}
	for _, row := range rows {
		if row == "" {
			continue
		}
		fixture := strings.TrimPrefix(strings.Split(row, " | ")[0], "| ")
		if recordedRows[fixture] != row {
			moved = append(moved, fmt.Sprintf("recorded: %s\nmeasured: %s", recordedRows[fixture], row))
		}
	}
	t.Errorf("the counts changed and %s wasn't updated with them (go test ./internal/oracle -run TestCountsAreRecorded -args -update-counts):\n%s",
		countsPath, strings.Join(moved, "\n"))
}
