package oracle

// Keep incoming integration registrations outside the shared oracle harness.
func init() {
	for _, incoming := range []struct {
		path            string
		lowers, checked bool
	}{
		{"internal/oracle/testdata/non_null.a", true, false},
		{"internal/oracle/testdata/non_null_map.a", true, true},
		{"internal/oracle/testdata/non_null_catch.a", true, true},
		{"internal/oracle/testdata/non_null_field.a", true, true},
		{"internal/oracle/testdata/non_null_capture.a", true, true},
		{"internal/oracle/testdata/non_null_array.a", true, true},
		{"internal/oracle/testdata/non_null_union.a", true, true},
		{"internal/oracle/testdata/non_null_boolean.a", true, true},
		{"internal/oracle/testdata/non_null_null.a", true, true},
		{"internal/oracle/testdata/process_exit_code.a", true, false},
		{"internal/oracle/testdata/process_exit.a", true, false},
		{"internal/oracle/testdata/process_exit_default.a", true, false},
		{"internal/oracle/testdata/process_exit_uncaught.a", true, false},
		{"internal/oracle/testdata/process_bad_code.a", true, false},
		{"internal/oracle/testdata/process_observations.a", true, false},
		{"internal/oracle/testdata/process_shadow.a", true, false},
		{"internal/oracle/testdata/graph_regions/classification_return.a", true, false},
		{"internal/oracle/testdata/graph_regions/classification_conditional.a", true, false},
		{"internal/oracle/testdata/graph_regions/classification_mixed.a", true, false},
		{"internal/oracle/testdata/graph_regions/classification_override.a", true, false},
		{"internal/oracle/testdata/graph_regions_weak_mixed.a", true, false},
		{"internal/oracle/testdata/graph_regions_structural_literal.a", true, false},
		{"internal/oracle/testdata/graph_regions_counted_container.a", true, false},
		{"internal/oracle/testdata/weak_region_review.a", true, false},
		{"internal/oracle/testdata/graph_regions_throw.a", true, false},
		{"internal/oracle/testdata/graph_regions_static_private.a", true, false},
		{"internal/oracle/testdata/graph_regions_generic_capture.a", true, false},
		{"internal/oracle/testdata/graph_regions_nested_self.a", true, false},
		{"internal/oracle/testdata/graph_regions_nested_disjoint.a", true, false},
		{"internal/oracle/testdata/graph_regions_entries.a", true, false},
		{"internal/oracle/testdata/graph_regions/million.a", true, false},
		{"internal/oracle/testdata/graph_regions_accessor.a", true, false},
		{"internal/oracle/testdata/graph_regions_literal_method.a", true, false},
		{"internal/oracle/testdata/graph_regions_regression_01.a", true, false},
		{"internal/oracle/testdata/graph_regions_regression_02.a", true, false},
		{"internal/oracle/testdata/graph_regions_regression_03.a", true, false},
		{"internal/oracle/testdata/graph_regions_regression_04.a", true, false},
		{"internal/oracle/testdata/graph_regions_regression_05.a", true, false},
		{"internal/oracle/testdata/graph_regions_regression_06.a", true, false},
		{"internal/oracle/testdata/graph_regions_regression_07.a", true, false},
		{"internal/oracle/testdata/graph_regions_regression_08.a", true, false},
		{"internal/oracle/testdata/graph_regions_regression_09.a", true, false},
		{"internal/oracle/testdata/graph_regions_regression_10.a", true, false},
		{"internal/oracle/testdata/graph_regions_regression_11.a", true, false},
		{"internal/oracle/testdata/graph_regions_regression_12.a", true, false},
		{"internal/oracle/testdata/graph_regions_regression_13.a", true, false},
		{"internal/oracle/testdata/graph_regions_regression_14.a", true, false},
		{"internal/oracle/testdata/graph_regions_regression_15.a", true, false},
		{"internal/oracle/testdata/graph_regions_static.a", true, false},
		{"internal/oracle/testdata/graph_regions_static_interface.a", true, false},
		{"internal/oracle/testdata/graph_regions_static_parent.a", true, false},
		{"internal/oracle/testdata/graph_regions_anchor.a", true, false},
		{"internal/oracle/testdata/graph_regions_cache.a", true, false},
		{"internal/oracle/testdata/graph_regions_closure.a", true, false},
		{"internal/oracle/testdata/graph_regions_escape.a", true, false},
		{"internal/oracle/testdata/graph_regions_flow.a", true, false},
		{"internal/oracle/testdata/graph_regions_list.a", true, false},
		{"internal/oracle/testdata/graph_regions_literals.a", true, false},
		{"internal/oracle/testdata/graph_regions_parse.a", true, false},
		{"internal/oracle/testdata/graph_regions_symbols.a", true, false},
	} {
		fixtures = append(fixtures, incoming)
	}
}
