import pathlib,json,re,subprocess,shutil
r=pathlib.Path('/workspace/adamic');p=r/'review/test-audit/stage1-cohere-tsprinter-class_interface_gap';pkg='stage1/cohere/tsprinter';plans=json.loads((p/'plan.json').read_text());med=json.loads((p/'timing-medians.json').read_text());runs=json.loads((p/'runs.json').read_text())+json.loads((p/'finish-runs.json').read_text())
def events(id):
 out=[]
 for s in (p/(id+'.log')).read_text().splitlines():
  try:out.append(json.loads(s))
  except:pass
 return out
core=list(med);family='TestExpressionsAgainstGoAndPrettier family';mutfamily='TestMutants family'
def failing(id,test):
 es=events(id);errors=[e.get('Output','').strip() for e in es if e.get('Test')==test and e.get('OutputType')=='error'];errors+= [e.get('Output','').strip() for e in es if e.get('Test')==test and '.go:' in e.get('Output','') and not e.get('OutputType')];return errors[0] if errors else next((e.get('Output','').strip() for e in es if e.get('Test')==test and '--- FAIL:' in e.get('Output','')),'no observed failure')
def cmd(id):return ' '.join(next(x['command'] for x in runs if x['id']==id))+' > '+id+'.log 2>&1'
matrix={}
for id in ['M1','M2','M3','M4','M5','M6']:
 es=events(id);matrix[id]={t:next((e['Action'] for e in reversed(es) if e.get('Test')==t and e.get('Action') in ['pass','fail','skip']),'unknown') for t in core}
matrix['M1'][family]='fail';(p/'matrix.json').write_text(json.dumps(matrix,indent=2))
rows=[]
def row(test,file,oracle,kind,kills,unique,verdict,last=None,subs=None,probe=None):
 t=test
 d=dict(test=t,package=pkg,file=pkg+'/'+file,seconds=med.get(t,{}).get('seconds'),oracle=oracle,oracle_kind=kind,kills=kills,unique_kills=unique,last_proven_fail=None,verdict=verdict,subsumed_by=subs or [],mutants_in_matrix=6 if t in core else 1,probe_kills=probe or [],subsumer_seconds=10.782 if subs else None,vacuous=False if probe else None,bounded=True,matrix_rows=core+[family],evidence='')
 if last:
  id,actual=last;line=failing(id,actual);d['last_proven_fail']=id+': '+line;d['evidence']=cmd(id)+'; '+line
 if verdict in ['setup-check','witness']:d['mutants_in_matrix']=1
 rows.append(d);return d
row('TestClassInterfaceMethodGap','class_interface_gap_test.go:16','Node executes the refused source and the callback workaround; exact NotYet type, location and wording are handwritten.','external-run',['M3'],['M3'],'sacred',('M3','TestClassInterfaceMethodGap'),probe=['P-Lower'])
row('TestClosedOptionalBooleanFunctionGap','class_interface_gap_test.go:70','Node, sanitized native and JavaScript backend must print the handwritten absent string; leak check also runs.','external-run',['M6'],['M6'],'sacred',('M6','TestClosedOptionalBooleanFunctionGap'),probe=['P-Lower'])
row('TestTrackedCorpusRoots','corpus_test.go:68','Handwritten tracked-file and missing/empty-root invariants; Git supplies the fixture index.','self',['S1'],[],'setup-check',('S1','TestTrackedCorpusRoots'))
row('TestDocumentsAgainstGoAndPrettier','doc_test.go:33','5072 exact output cases from executing Go cohere and Prettier 3.9.6, compared with Node port, native and JavaScript backend; sanitizers and leaks checked.','external-run',['M1','M2','M4','M5'],['M2','M5'],'sacred',('M2','TestDocumentsAgainstGoAndPrettier'),probe=['P-Documents'])
row('TestTSPrinterCachedMetadataRelocation','expression_products_test.go:172','Handwritten relocation, Source/Want preservation and immutable shared-product invariants.','self',['S2'],[],'setup-check',('S2','TestTSPrinterCachedMetadataRelocation'))
row('TestExpressionUnitBoxSelection','expression_units_test.go:49','Handwritten exactly-once selection, invalid-selector and unset-selector invariants.','self',['S3'],[],'setup-check',('S3','TestExpressionUnitBoxSelection'))
row('TestExpressionUnitPlantedDisagreement','expression_units_test.go:240','Node emits a handwritten planted string; self-written requirement of exactly one correctly labelled rejection.','self',['W1'],[],'witness',('W1','TestExpressionUnitPlantedDisagreement'))
d=row('TestExpressionUnitUnionRejectsMissingAndRepeated','expression_units_test.go:273','Handwritten missing/repeated union rejection.','self',['W2'],[],'witness',('W2','TestExpressionUnitUnionRejectsMissingAndRepeated'));d['failure_origin']='expression_units_test.go:278; scratch log line 251 after the checker body was removed'
d=row(family,'expression_top_level_test.go:5','Executing Go cohere, Prettier 3.9.6 and embedded Prettier; exact text plus independently pinned allowance records. Narrow member 000 covers 2644 cases.','external-run',['M1'],[],'subsumed',('M1-family-member','TestExpressionsAgainstGoAndPrettier_000'),subs=['TestDocumentsAgainstGoAndPrettier']);d['members']=['TestExpressionsAgainstGoAndPrettier_%03d'%i for i in range(65)]+['TestExpressionsAgainstGoAndPrettierUnion'];d['matrix_members']=['TestExpressionsAgainstGoAndPrettier_000'];d['unknown_mutants']=['M2','M3','M4','M5','M6'];d['timing_limitation']='Whole family exceeded 90 seconds; no three-run median. Subsumption rests on one observed mutant, not a deletion recommendation.'
d=row('TestCompilerGaps','gaps_test.go:13','Node prints im; handwritten substring names the default-sort refusal. This checks diagnostic text, not the Refused type.','external-run',[],[],'cannot-judge',probe=['P-Lower']);d['evidence']='No planned production mutant altered arraySort; sorting quality remains unjudged within the budget. P-Lower-TestCompilerGaps.log: gaps_test.go:34: expected recorded gap "Adamic 0.1 refuses sort without a comparator", got <nil>'
row('TestClosedPrefixUpdateValueGap','gaps_test.go:45','Node, native and JavaScript backend must print handwritten 2; leak check runs.','external-run',['M4'],[],'subsumed',('M4','TestClosedPrefixUpdateValueGap'),subs=['TestDocumentsAgainstGoAndPrettier'],probe=['P-Lower'])
d=row('TestNumberConstructor','gaps_test.go:63','Node, native and backend check only Number(\'17\') prints 17. It passes M5 even though the native Number(\'17x\') witness changes NaN to 17; the input cannot distinguish convert from parseFloat.','external-run',[],[],'untrue',probe=['P-Lower']);d['evidence']=cmd('M5')+'; --- PASS: TestNumberConstructor; separate number-witness.ts outputs baseline NaN, M5 17';d['relevant_mutants']=1
row(mutfamily,'mutant_grain_shards_test.go:11','Builtin port mutants must finish normally and disagree with executing Go cohere. Weakened shared comparison tested through member 000.','external-run',['W3'],[],'witness',('W3','TestMutants_000'))['members']=['TestMutants_%03d'%i for i in range(29)]+['TestMutantsUnion'];rows[-1]['matrix_members']=['TestMutants_000'];rows[-1]['timing_limitation']='Whole family exceeded 90 seconds; no three-run median. Other members not independently checked with W3.'
(p/'results.json').write_text(json.dumps(rows,indent=2))
shutil.copy('/workspace/u140-audit.py',p/'audit.py');shutil.copy('/workspace/u140-finish.py',p/'finish.py');shutil.copy('/workspace/u140-report.py',p/'report.py')
feedback='''Brief feedback and limits:
1. The supplied commit/file list is stale. Starting at 60f24a6ef736a6016edeca63df075678186bba8d, mutant_shards_test.go moved to mutant_grain_shards_test.go. TestExpressionsAgainstGoAndPrettier vanished as a function and became 65 numbered leaves plus a union. The requested slice now contains 107 functions grouped into 13 rows.
2. The package name does not identify the code under test. Gap rows lower independent fixtures and test internal/lower, while documents and expression rows test the TypeScript port. Mutating only the port would miss the compiler rows. Other rows test construction or shared checks.
3. The brief omits the install locations and pin needed by opt-in corpora. Prettier 3.9.6 and TypeScript commit 050880ce59e30b356b686bd3144efe24f875ebc8 were installed. npm ci took 1.969s, Prettier install 4.210s, TypeScript clone 38.635s, pin fetch/checkout 33.191s. Setup itself was skipped because the warm env.sh worked. nproc=5.
4. Source changes are inputs to native product caches. A selector requires distinct compiler cache directories even with one compiled switch. Port mutants were rebuilt separately, respecting the fallback cap (two port mutants). Explicit sanitized docMain rebuilds took M1 16.242s and M2 8.583s, including Go CLI overhead. The document empty-answer probe built in 6.699s. Go mutation diffs each passed go vet; all witness/construction Go diffs and P-Lower also passed go vet.
5. Whole package binary timed out at 90 seconds (94.995s command wall). Both complete families timed out at 90 seconds too. That rule conflicts with a mandatory three-run family median; seconds is null for those families. Eleven smaller rows have three independent binary-reported timing samples. Narrow family members then passed together in 14.636s binary time, 17.165s command wall. No assertion-red clean baseline was audited.
6. A grouped family can contain output checks and a construction-only union. This report keeps one row, tests the common output comparison through member 000, and leaves the union fault-injection and other members unknown.
7. A kill matrix narrowed to slices has varying observation sets. M1 includes an additional expression member; M2 through M6 do not. Unique kills mean unique only within each observed matrix. There is no package-wide or repo-wide uniqueness claim. S and W edits are setup/witness evidence, not production mutants or sacred evidence.
8. Empty-answer probes are relevant only to the actual code-under-test entry. Lower is preparation for the document row, so its P-Lower failure is excluded there; P-Documents decides its vacuity. Construction and witness entries were not probed, and have vacuous=null. Neither full expression entry nor all family members were empty-probed.
9. Failure line numbers can shift after replacing a checker body. W2's raw log says expression_units_test.go:251; that unchanged assertion is at origin/main line 278. Mutant source coordinates in plan.json and this report all use the starting commit. t.Helper also attributes W3's failure to its original shard callsite, line 49.
10. The count of desired mutants conflicts with the native rebuild fallback and the time budget. Six production mutants were planned from source before running any of them: two port mutants and four compiler mutants. Three construction and three witness edits are separately labelled. No production mutant targeted arraySort, so TestCompilerGaps is cannot-judge, not untrue. Number conversion received one relevant mutant; its untrue finding is limited to that observed set.
11. The audit runner initially treated any text containing panic: as a test-binary abort. M4's child-program panic caused unnecessary standalone reruns. This was an avoidable runner cost, not a test timeout or additional kill evidence. The real P-Lower binary abort required standalone reruns.
12. No external-authority oracle was assigned. Handwritten diagnostic contracts remain self components even when the row also executes Node. NumberConstructor's single decimal input is a demonstrated oracle-strength limit.

Survivors: none among the six production mutants in the observed matrices. Untested rows or members are unknown, not survivors. Separate Number-conversion witness: baseline Number('17x') prints NaN; M5 prints 17; TestNumberConstructor still passes.

Evidence: plan.json was written before mutations; reached-functions.txt contains 407 dynamically reached compiler functions plus the document-port call inventory; lower.cover is the clean coverage profile. matrix.json, results.json, runs.json, finish-runs.json and raw logs preserve commands and observations. Six production diffs, three construction diffs, three witness diffs and two empty-answer probe diffs apply to the starting commit. audit.py and finish.py show instrumentation and restore logic; they require the documented warm tools/oracle paths and workspace temp directory. Never execute them blindly in a dirty worktree.

Timing: baseline and dependency times above are wall times; row medians in results.json use each isolated test binary's ok line, never parent --- PASS durations for parallel tests. Audit runner command wall total was 331.306s (including builds, vet, tests and reruns); go vet subset 10.279s. Native/build preparation occurs inside several test binaries, so an exact aggregate split between native building and execution is not measurable from existing logs. All commands' measured durations are retained rather than inventing that split. No other package test suite was run. Compiler packages were vetted only. No corpus/oracle/test fixtures were altered. Production source is restored; only evidence is committed.
'''
(p/'README.txt').write_text(feedback)
print('report generated',len(rows))
