from pathlib import Path
import subprocess,json,os
root=Path(__file__).resolve().parents[2]; scratch=Path('/workspace/adamic-scratch/group1-ruled-overlay'); scratch.mkdir(exist_ok=True)
def check(name,relative,before,after,package,pattern,evidence):
 p=root/relative; original=p.read_text(); assert original.count(before)==1,(name,original.count(before)); q=scratch/(name+'.go');q.write_text(original.replace(before,after,1)); overlay=scratch/(name+'.json');overlay.write_text(json.dumps({'Replace':{str(p):str(q)}})); log=Path('/tmp/area-stack-group1-mutant-'+name+'.log')
 with log.open('w') as out:r=subprocess.run(['go','test','-overlay',str(overlay),package,'-run',pattern,'-count=1','-v'],cwd=root,stdout=out,stderr=subprocess.STDOUT,env=dict(os.environ,ADAMIC_GATE_UNCACHED='1'))
 s=log.read_text();assert r.returncode!=0 and evidence in s and 'build failed' not in s,(name,s);print(name+': caught by '+evidence,flush=True)
graph='internal/lower/namespaces_call_graph.go'
check('namespace-reaching','internal/lower/namespaces.go','case ast.KindFunctionDeclaration:\n\t\t\tif declaration.Body() != nil {\n\t\t\t\treturn declaration\n\t\t\t}','case ast.KindFunctionDeclaration:\n\t\t\treturn nil','./internal/lower','^TestNamespaceInitializationReachability$','reaching call lost its initialization refusal')
check('namespace-memo',graph,'if cached := g.functions[function]; cached != nil {','if cached := g.functions[function]; cached != nil && cached.active {','./internal/lower','^TestNamespaceCallGraphLinearWork$/12$','nonlinear function walks: got 8191, want 13')
check('namespace-cycle',graph,'member.reaches = reaches','member.reaches = member.reads','./internal/lower','^TestNamespaceCallGraphCycleUnion$','partial cycle reach')
check('enum-reaching',graph,'\t\t\tif declaration := g.lowering.namespaceRuntimeEnum(node); declaration != nil {\n\t\t\t\tentry.reads[declaration] = node\n\t\t\t}\n','','./internal/lower','^TestEnumInitializationReach/reaching-','pending enum read on line 2 must stay refused')
check('enum-memo',graph,'if cached := g.functions[function]; cached != nil {','if cached := g.functions[function]; cached != nil && cached.active {','./internal/lower','^TestEnumInitializationGraphMemo/12$','nonlinear enum function walks: got 8191, want 13')
check('enum-readiness','internal/lower/locals.go','Checked: l.result.Locals[local].NamespaceState || l.checkedModuleRead(node, local)','Checked: (l.result.Locals[local].NamespaceState || l.checkedModuleRead(node, local)) && l.namespaceRuntimeEnum(node) == nil','./internal/oracle','^TestEnumInitializationUnknownPinned$','--- FAIL: TestEnumInitializationUnknownPinned')
check('literal-callable','internal/lower/literal_callable_branch.go','case ast.KindTrueKeyword:\n\t\treturn expression.WhenTrue','case ast.KindTrueKeyword:\n\t\treturn expression.WhenFalse','./internal/oracle','^TestEnumInitializationNode/callable-selection$','stdout differs')
p=root/'internal/lower/namespaces.go';s=p.read_text();a=s.index('func (l *lowering) namespaceReadyReads('); b=s.index('func (l *lowering) namespaceReadyValue(',a);old=s[a:b];new=old[:old.index('{')+1]+'\nreturn nil\n}\n\n'
check('namespace-readiness','internal/lower/namespaces.go',old,new,'./internal/oracle','^TestNativeAgreesWithNode$/internal/oracle/testdata/namespaces_unknown_function_before.a$','exit codes differ')
check('ambient-host','internal/lower/namespaces.go','if declaration.Flags&ast.NodeFlagsAmbient != 0 || ast.HasSyntacticModifier(declaration, ast.ModifierFlagsAmbient) || ast.GetSourceFileOfNode(declaration).IsDeclarationFile {','if false {','./internal/lower','^TestNamespaceAmbient','ambient')
check('parameter-property','internal/lower/class_inheritance.go','(member.Kind == ast.KindPropertyDeclaration || parameterProperty(member))','member.Kind == ast.KindPropertyDeclaration','./internal/lower','^TestParameterPropertiesSoundness$','--- FAIL: TestParameterPropertiesSoundness')
