package typeaware

import (
	"bytes"
	"encoding/json"
	"fmt"
	goast "go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// Export the unmodified upstream fixture builders as data. Test cases remain
// separate directory trees so their module-resolution graphs cannot collide.
func wave21BlockingFixtures(h *harness) []string {
	fset := token.NewFileSet()
	read := func(stem string) *goast.File {
		tree, e := parser.ParseFile(fset, filepath.Join(h.repository, "cohere/internal/lint/rules/nexus", stem+"_test.go"), nil, 0)
		if e != nil {
			h.t.Fatal(e)
		}
		return tree
	}
	blocking := read("correctness_require_blocking_standard_streams")
	output := read("correctness_no_process_exit_after_output")
	var generated bytes.Buffer
	generated.WriteString("package main\nimport (\"encoding/json\";\"os\";\"strings\")\n")
	write := func(n goast.Node) {
		if e := printer.Fprint(&generated, fset, n); e != nil {
			h.t.Fatal(e)
		}
		generated.WriteString("\n")
	}
	for _, tree := range []*goast.File{output, read("correctness_no_uncleared_race_timeout")} {
		for _, decl := range tree.Decls {
			switch d := decl.(type) {
			case *goast.GenDecl:
				if d.Tok != token.IMPORT {
					write(d)
				}
			case *goast.FuncDecl:
				if !strings.HasPrefix(d.Name.Name, "Test") && !strings.Contains(d.Name.Name, "Run") && !strings.Contains(d.Name.Name, "Expect") {
					write(d)
				}
			}
		}
	}
	var fires, silent *goast.FuncDecl
	for _, decl := range blocking.Decls {
		switch d := decl.(type) {
		case *goast.GenDecl:
			if d.Tok != token.IMPORT {
				write(d)
			}
		case *goast.FuncDecl:
			name := d.Name.Name
			if name == "TestCorrectnessRequireBlockingStandardStreamsFires" {
				fires = d
				continue
			}
			if name == "TestCorrectnessRequireBlockingStandardStreamsStaysSilent" {
				silent = d
				continue
			}
			if d.Recv != nil || (!strings.HasPrefix(name, "Test") && name != "correctnessRequireBlockingStandardStreamsRun" && name != "correctnessRequireBlockingStandardStreamsExpect") {
				write(d)
			}
		}
	}
	generated.WriteString("func main(){var all []map[string]string\n")
	for _, name := range []string{"Statement", "Sync", "CardBalances", "Godword"} {
		fmt.Fprintf(&generated, "all=append(all,map[string]string{correctnessNoProcessExitAfterOutputFile:correctnessNoProcessExitAfterOutput%s(false)},map[string]string{correctnessNoProcessExitAfterOutputFile:correctnessNoProcessExitAfterOutput%s(true)})\n", name, name)
	}
	generated.WriteString("all=append(all,map[string]string{correctnessNoUnclearedRaceTimeoutFile:correctnessNoUnclearedRaceTimeoutPhiSocial(false)},map[string]string{correctnessNoUnclearedRaceTimeoutFile:correctnessNoUnclearedRaceTimeoutPhiSocial(true)})\n")
	for _, name := range []string{"Facets", "ShardWorker", "PhiSocialUpload", "LintEngineParity", "NewMigration", "Structure"} {
		fmt.Fprintf(&generated, "all=append(all,correctnessRequireBlockingStandardStreams%s(false).files(),correctnessRequireBlockingStandardStreams%s(true).files())\n", name, name)
	}
	for _, fn := range []*goast.FuncDecl{fires, silent} {
		if fn == nil {
			h.t.Fatal("fixture test missing")
		}
		generated.WriteString("{\n")
		for _, statement := range fn.Body.List {
			if a, ok := statement.(*goast.AssignStmt); ok {
				for _, lhs := range a.Lhs {
					if id, ok := lhs.(*goast.Ident); ok && (id.Name == "library" || id.Name == "cases") {
						write(a)
						break
					}
				}
			}
		}
		if fn == fires {
			generated.WriteString("for _,c:=range cases {all=append(all,c.testCase.files())}\n")
		} else {
			generated.WriteString("for _,c:=range cases {all=append(all,c.files())}\n")
		}
		generated.WriteString("}\n")
	}
	generated.WriteString("if e:=json.NewEncoder(os.Stdout).Encode(all);e!=nil {panic(e)}}\n")
	exporter := h.write("blocking_fixtures.go", generated.String())
	result := h.must("blocking-fixture-export", exec.Command("go", "run", exporter))
	var cases []map[string]string
	if e := json.Unmarshal(result.stdout, &cases); e != nil {
		h.t.Fatal(e)
	}
	var paths []string
	for i, files := range cases {
		for name, text := range files {
			// Shared globals are already supplied by process fixtures. Keep only the
			// blocking prelude once; a separate .d.ts per case would redeclare globals.
			if strings.HasSuffix(name, ".d.ts") {
				if strings.HasSuffix(name, "prelude.d.ts") {
					h.write("blocking-prelude.d.ts", text)
				}
				continue
			}
			target := filepath.Join(h.directory, fmt.Sprintf("blocking-%03d", i), strings.TrimPrefix(name, "/"))
			if e := os.MkdirAll(filepath.Dir(target), 0755); e != nil {
				h.t.Fatal(e)
			}
			if e := os.WriteFile(target, []byte(text), 0644); e != nil {
				h.t.Fatal(e)
			}
			paths = append(paths, target)
		}
	}
	// Map iteration is deliberately sorted for reproducible finding serialization.
	sortStrings(paths)
	h.t.Logf("blocking streams: %d upstream programs, %d source files", len(cases), len(paths))
	return paths
}
func sortStrings(paths []string) {
	for i := 1; i < len(paths); i++ {
		for j := i; j > 0 && paths[j] < paths[j-1]; j-- {
			paths[j], paths[j-1] = paths[j-1], paths[j]
		}
	}
}
