// Read the scout JSON made by 6945a8a4 and the pinned typed string-index census.
// node rank.cjs <TypeScript checkout> <scout JSON> <output JSON>
const fs=require('fs'),path=require('path'),ts=require(process.env.CENSUS_TYPESCRIPT || 'typescript');
const root=path.resolve(process.argv[2], 'src/compiler');let files=[];
function walk(d){for(const e of fs.readdirSync(d,{withFileTypes:true})){const p=path.join(d,e.name);if(e.isDirectory())walk(p);else if(e.name.endsWith('.ts')&&!e.name.endsWith('.d.ts'))files.push(p)}}walk(root);
const parsed=new Map(),calls={};for(const file of files){const f=ts.createSourceFile(file,fs.readFileSync(file,'utf8'),ts.ScriptTarget.Latest,true);parsed.set(path.relative(root,file),f);function visit(n){if(ts.isCallExpression(n)){const x=n.expression;const name=ts.isIdentifier(x)?x.text:ts.isPropertyAccessExpression(x)?x.name.text:null;if(name)calls[name]=(calls[name]||0)+1;}ts.forEachChild(n,visit)}visit(f)}
const lookups=JSON.parse(fs.readFileSync(path.join(__dirname, '../../census/data/string_lookups.json'))).filter(s=>/MapLike<|Record<string,/.test(s.receiver_type)).map(s=>({...s,file:s.file.replace('src/compiler/',''),kind:'string index',column:s.column}));
const scout=JSON.parse(fs.readFileSync(process.argv[3])).sites.filter(s=>(s.arguments||[]).some(a=>/MapLike<|Record<string,/.test(a))||/MapLike<|Record<string,/.test(s.receiver||''));
const sites=[...lookups,...scout];for(const s of sites){const f=parsed.get(s.file),offset=f.getPositionOfLineAndCharacter(s.line-1,s.column-1);let node=f;function find(n){if(n.getStart(f)<=offset&&n.end>offset){node=n;ts.forEachChild(n,find)}}find(f);let fn=node;while(fn&&!(ts.isFunctionDeclaration(fn)&&fn.name)){fn=fn.parent} s.function=fn?fn.name.text:'top level';s.calls=calls[s.function]||0;s.context=fn?fn.getText(f):f.text.slice(Math.max(0,offset-500),offset+1000);s.source_sha256=require('crypto').createHash('sha256').update(f.text).digest('hex');}
sites.sort((a,b)=>b.calls-a.calls||a.file.localeCompare(b.file)||a.line-b.line||a.column-b.column);sites.forEach((s,i)=>{s.rank=i+1;s.batch=Math.floor(i/10)+1});fs.writeFileSync(process.argv[4],JSON.stringify(sites,null,2)+'\n');for(const s of sites)console.log(s.rank,s.calls,s.function,s.file+':'+s.line+':'+s.column,s.kind);
