import pathlib,json,re,difflib
r=pathlib.Path('/workspace/adamic');p=r/'review/test-audit/stage1-cohere-css-composition_shards'
menu=[dict(id='M1',file='stage1/cohere/css/parser.ts',old='        parser.parse();\n',new='',kind='drop statement',change='drop parser.parse invocation; constructor root still returned',entry='compose_main.ts',rows=['TestCompositionMatchesGo family','TestCSSThroughput','TestCSSPrinterOptimizedMatchesGo']),dict(id='M2',file='stage1/cohere/css/compose.ts',old="node.setBoolean('import', true);",new="node.setBoolean('import', false);",kind='change constant',change='clear composed import marker',entry='compose_main.ts',rows=['TestCompositionMatchesGo family','TestCSSPrinterOptimizedMatchesGo']),dict(id='M3',file='stage1/cohere/css/tree.ts',old='return quote(node.literalValue);',new="return quote('');",kind='change constant',change='render literal tree nodes as empty strings',entry='compose_main.ts',rows=['TestCompositionMatchesGo family']),dict(id='M4',file='stage1/cohere/css/print_doc.ts',old="n.kind === 'indent' ? 1 : -1",new="n.kind === 'indent' ? 0 : -1",kind='change constant',change='drop document indentation increment',entry='print_main.ts',rows=['TestCSSPrinterOptimizedMatchesGo'])]
for m in menu:
 base=(r/m['file']).read_text();assert base.count(m['old'])==1;m['line']=base[:base.index(m['old'])].count('\n')+1;mutated=base.replace(m['old'],m['new'],1);(p/(m['id']+'.diff')).write_text(''.join(difflib.unified_diff(base.splitlines(True),mutated.splitlines(True),fromfile='a/'+m['file'],tofile='b/'+m['file'])))
(p/'menu.json').write_text(json.dumps(menu,indent=2))
(p/'CODE-AND-ORACLE.md').write_text('''CODE UNDER TEST: the stage1 TypeScript CSS port, compiled natively, including raw parser, composition, canonical rendering and document printing. source-functions.json lists a conservative CSS declaration inventory; it is not dynamic coverage. compose_main.ts calls compose/renderTree, main.ts calls parse/render and print_main.ts calls format. The three tiny closed-gap snippets and the open-gap refusal row instead check Adamic compiler/dependency-port boundaries.
ORACLE: independent Go cohere parser/composition/printer outputs, PostCSS and Prettier. Node running the same port is an additional execution of the implementation, not an independent algorithm. TestCSSParserOptimizedMatchesNode specifically uses that port source as its expected oracle, so port-source mutant results are inadmissible for that row; it needs a compiler mutant. Production diffs never modify Go cohere or external npm libraries.
Fixed production menu, selected after reading the code and recording the inventory, before mutant failures: drop parser.parse invocation, clear import marker, empty literal-rendering constant, zero indentation increment. All four have standalone native build checks. M1 returns a structured constructor root and prints nonempty results; it is a dropped internal call, not the separate empty-main probe.
Families: 16 composition agreement shards form one family; its union contains distinct planted comparisons and is a witness row. The two composition setup wrappers form a setup family. 64 printer wrappers run one checker and form one mixed agreement/mutant family, judged as a witness. Its union asserts shard construction and remains separate. This yields 16 rows rather than the brief's claimed 14. Exact 95 names and memberships are recorded, none moved or vanished.
The declared matrix bounds use source imports and entry callers. M1 reaches composition, count throughput and printer; M2 composition and printer; M3 canonical composition rendering; M4 printer documents. Witness rows are judged only by weakened guards. Unreached/compiler rows and the coupled Node-oracle row receive no production verdict from these mutations.
''')
print([(m['id'],m['file'],m['line']) for m in menu])
