import { execFileSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { registerHooks, stripTypeScriptTypes } from 'node:module';
import { resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const root = fileURLToPath(new URL('../', import.meta.url));
registerHooks({
	resolve(specifier, context, nextResolve) {
		if (specifier === 'adamic') return { url: new URL('../oracle/adamic.mjs', import.meta.url).href, shortCircuit: true };
		return nextResolve(specifier, context);
	},
	load(url, context, nextLoad) {
		if (url.endsWith('.ts') || url.endsWith('.a')) {
			let source = readFileSync(fileURLToPath(url), 'utf8');
			// The landing branch's oracle supplies descriptors from types, never lowered code.
			if (/\bdecodeJson\s*(?:<|\()/.test(source)) {
				const sources = JSON.parse(execFileSync('go', ['run', './oracle/json_types.go', fileURLToPath(url)], { cwd: root, encoding: 'utf8' }));
				source = sources[fileURLToPath(url)];
			}
			return { format: 'module', source: stripTypeScriptTypes(source), shortCircuit: true };
		}
		return nextLoad(url, context);
	},
});

export function firstDifference(expected, actual) {
	if (expected.status !== actual.status) return 'status';
	if (expected.headers.length !== actual.headers.length) return 'headers.length';
	for (let index = 0; index < expected.headers.length; index += 1) {
		for (let field = 0; field < 2; field += 1) {
			if (expected.headers[index][field] !== actual.headers[index][field]) return `headers[${index}][${field}]`;
		}
	}
	if (expected.body !== actual.body) return 'body';
	return undefined;
}
function lines(path) {
	const source = readFileSync(path, 'utf8');
	const rows = source.split('\n');
	if (rows.at(-1) === '') rows.pop();
	return rows.map((row, index) => {
		try { return JSON.parse(row); } catch { throw new Error(`${path}: invalid JSON on line ${index + 1}`); }
	});
}

export async function replay(workerPath, requestsPath, mode, responsesPath) {
	const module = await import(pathToFileURL(resolve(workerPath)).href);
	const requests = lines(requestsPath);
	const expected = mode === '--compare' ? lines(responsesPath) : undefined;
	const recorded = [];
	for (let index = 0; index < requests.length; index += 1) {
		const row = requests[index];
		const request = new Request(row.url, { method: row.method, headers: row.headers, ...(row.body === null ? {} : { body: row.body }) });
		let response;
		if (typeof module.default?.fetch === 'function') response = await module.default.fetch(request);
		else if (typeof module.handle === 'function') {
			// Generic source-oracle adapter for the next pure .a handler. Production bridges
			// are generated by the compiler; this adapter only runs outside the Worker.
			const url = new URL(request.url);
			const fields = (pairs) => [...pairs].map(([name, value]) => ({ name, value }));
			const result = module.handle({ method: request.method, url: request.url, path: url.pathname,
				query: fields(url.searchParams), headers: fields(request.headers), body: await request.text() });
			response = new Response(result.body, { status: result.status, headers: result.headers.map(({ name, value }) => [name, value]) });
		} else throw new Error(`${workerPath} exports neither default.fetch nor handle`);
		const bytes = Buffer.from(await response.arrayBuffer());
		const actual = { status: response.status, headers: [...response.headers], body: bytes.toString('utf8') };
		if (mode === '--record' && !Buffer.from(actual.body, 'utf8').equals(bytes)) throw new Error(`request ${index}: response body is not UTF-8`);
		const difference = expected === undefined ? undefined : expected[index] === undefined ? 'response missing'
			: firstDifference(expected[index], actual) ?? (Buffer.from(expected[index].body, 'utf8').equals(bytes) ? undefined : 'body.bytes');
		if (difference !== undefined) {
			console.error(JSON.stringify({ index, request: row, field: difference, expected: expected[index], actual }));
			return false;
		}
		recorded.push(actual);
	}
	if (expected !== undefined && expected.length !== requests.length) {
		console.error(JSON.stringify({ index: requests.length, request: null, field: 'responses.length', expected: expected.length, actual: requests.length }));
		return false;
	}
	if (mode === '--record') writeFileSync(responsesPath, recorded.map((row) => JSON.stringify(row)).join('\n') + '\n');
	console.log(`${workerPath}: ${requests.length} requests ${mode === '--record' ? 'recorded' : mode === '--compare' ? 'matched' : 'replayed'}`);
	return true;
}
if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
	const [worker, requests, mode, responses, ...extra] = process.argv.slice(2);
	if (!worker || !requests || extra.length || (mode !== undefined && !['--record', '--compare'].includes(mode)) || ((mode === undefined) !== (responses === undefined))) {
		console.error('usage: node workers/replay.mjs <worker.mjs|worker.ts|handler.a> <requests.jsonl> [--record <responses.jsonl> | --compare <responses.jsonl>]');
		process.exitCode = 2;
	} else if (!await replay(worker, requests, mode, responses)) process.exitCode = 1;
}
